---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/guidelines-for-upgrading-controllers-with-arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: Ermitteln Sie, ob Sie ARL verwenden können, um das alte System-Chassis und die alten Festplatten für Ihre Upgrade-Konfiguration zu behalten. 
---
= Richtlinien für Controller Upgrades
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ob Sie die Aggregatverschiebung (ARL, Aggregate Relocation) und die alten System-Chassis- und -Festplatten beibehalten können, hängt von der System-Upgrade-Konfiguration und der ONTAP-Version ab.



[[supported-upgrades-for-arl]]
== Unterstützte Upgrades für ARL

Für bestimmte Systemkonfigurationen werden Controller-Upgrades unterstützt. Siehe die link:decide-to-use-the-aggregate-relocation-guide.html#supported-systems["unterstützte System-Upgrade-Kombinationen"] für eine Liste der unterstützten Systeme und der minimalen ONTAP Version.

Wenn Sie ein neues AFF A30, AFF A50, AFF A70, AFF A90, AFF A150, AFF A900, AFF C30, AFF C60, AFF C80, FAS2820 oder FAS9500 als komplettes System einschließlich eines neuen Gehäuses erhalten haben, lesen Sie link:other-references.html["Quellen"], um zu _Verwenden Sie die Befehle "system controller replace", um die Controller-Hardware unter ONTAP 9.8 oder höher zu aktualisieren_.

Das Controller-Upgrade mit ARL wird auf Systemen unterstützt, die mit SnapLock Enterprise und SnapLock Compliance Volumes konfiguriert sind.



[[two-node-switchless-clusters]]
== 2-Node-Cluster ohne Switches

Wenn Sie Nodes in einem 2-Node-Cluster ohne Switches aktualisieren, können Sie die Nodes im Cluster ohne Switches während des Upgrades belassen. Sie müssen sie nicht in einen Switch-Cluster konvertieren.



[[switch-attached-clusters]]
== Switch Attached-Cluster

Wenn Sie Nodes in einem Cluster aktualisieren, das mit einem Cluster-Switch verbunden ist, müssen Sie überprüfen, ob die auf dem Switch ausgeführte Version von Make, Model, Firmware, RCF und ONTAP mit denen identisch ist, die nach dem Upgrade auf dem Ersatz-Controller ausgeführt werden. Falls erforderlich, müssen Sie das Switch-Upgrade vor dem Upgrade der Controller mithilfe von ARL durchführen.

Weitere Informationen finden Sie unter link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["Stellen Sie eine Verbindung zu einem Switch-Attached-Cluster her"].



[[troubleshoot]]
== Fehlerbehebung

Möglicherweise ist beim Upgrade des Node-Paars ein Fehler auftritt. Der Node kann abstürzen, Aggregate werden möglicherweise nicht verschoben oder LIFs werden nicht migriert. Die Ursache des Fehlers und seiner Lösung hängt davon ab, wann der Fehler während des Aktualisierungsvorgangs aufgetreten ist.

Sollten Probleme auftreten, lesen Sie den Abschnitt link:aggregate-relocation-failures.html["Fehlerbehebung"] am Ende der Verfahrensanleitung für weitere Informationen und mögliche Lösungen. Informationen über die Fehler, die auftreten können, sind nach Phase des Verfahrens im link:overview-of-the-arl-upgrade.html["ARL-Upgradesequenz"] aufgeführt.

Wenn Sie keine Lösung für das aufgetretene Problem finden, wenden Sie sich an den technischen Support.

.Was kommt als Nächstes?
Nach Durchsicht der Richtlinien für die Aufrüstung von Controllern, link:overview-of-the-arl-upgrade.html["Erfahren Sie mehr über die ARL-Upgrade-Sequenz"].
