---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/guidelines-for-upgrading-controllers-with-arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: Ermitteln Sie, ob Sie ARL verwenden können, um das alte System-Chassis und die alten Festplatten für Ihre Upgrade-Konfiguration zu behalten. 
---
= Richtlinien für Controller Upgrades
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ob Sie die Aggregatverschiebung (ARL, Aggregate Relocation) und die alten System-Chassis- und -Festplatten beibehalten können, hängt von der System-Upgrade-Konfiguration und der ONTAP-Version ab.



== Unterstützte Upgrades für ARL

Controller Upgrades werden für bestimmte Systemkonfigurationen unterstützt. Weitere Informationen finden Sie im link:decide_to_use_the_aggregate_relocation_guide.html#supported-systems["unterstützte System-Upgrade-Kombinationen"] für eine Liste der unterstützten Systeme und der Mindestversion von ONTAP.

Wenn Sie ein neues AFF A30, AFF A50, AFF A70, AFF A90, AFF A150, AFF A900, AFF C30, AFF C60, AFF C80, FAS2820 oder FAS9500 als komplettes System mit einem neuen Gehäuse erhalten haben, finden Sie unter link:other_references.html["Quellen"]den Link „ Verwenden Sie Befehle zum Ersetzen des Systemcontrollers“ für das Upgrade der Controller-Hardware mit ONTAP 9.8 oder höher_.

Das Controller-Upgrade mit ARL wird auf Systemen unterstützt, die mit SnapLock Enterprise und SnapLock Compliance Volumes konfiguriert sind.



== 2-Node-Cluster ohne Switches

Wenn Sie Nodes in einem 2-Node-Cluster ohne Switches aktualisieren, können Sie die Nodes im Cluster ohne Switches während des Upgrades belassen. Sie müssen sie nicht in einen Switch-Cluster konvertieren.



== Switch Attached-Cluster

Wenn Sie Nodes in einem Cluster aktualisieren, das mit einem Cluster-Switch verbunden ist, müssen Sie überprüfen, ob die auf dem Switch ausgeführte Version von Make, Model, Firmware, RCF und ONTAP mit denen identisch ist, die nach dem Upgrade auf dem Ersatz-Controller ausgeführt werden. Falls erforderlich, müssen Sie das Switch-Upgrade vor dem Upgrade der Controller mithilfe von ARL durchführen.

Weitere Informationen finden Sie unter link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["Stellen Sie eine Verbindung zu einem Switch-Attached-Cluster her"].



== Fehlerbehebung

Möglicherweise ist beim Upgrade des Node-Paars ein Fehler auftritt. Der Node kann abstürzen, Aggregate werden möglicherweise nicht verschoben oder LIFs werden nicht migriert. Die Ursache des Fehlers und seiner Lösung hängt davon ab, wann der Fehler während des Aktualisierungsvorgangs aufgetreten ist.

Sollten Probleme auftreten, lesen Sie bitte die link:aggregate_relocation_failures.html["Fehlerbehebung"] Weitere Informationen und mögliche Lösungen finden Sie im Abschnitt am Ende des Verfahrens. Informationen zu den möglichen Fehlern finden Sie in der nach Phasen des Verfahrens sortierten Liste im link:overview_of_the_arl_upgrade.html["ARL-Upgradesequenz"] .

Wenn Sie keine Lösung für das aufgetretene Problem finden, wenden Sie sich an den technischen Support.
