---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/install-asa150-affa150-fas2820-on-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: Installieren Sie die Ersatzsystemmodule in node2 während eines ARL-Upgrades von Controller-Modellen im selben Chassis. 
---
= Installieren Sie das ASA A150, AFF A150 oder FAS2820 Controller-Modul in node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Installieren Sie das ASA A150, AFF A150 oder FAS2820 Controllermodul, das Sie für das Upgrade erhalten haben, in node2. Node2 ist Controller B und befindet sich auf der rechten Seite des Gehäuses, wenn Sie von der Rückseite des Systems auf die Controller blicken.

.Bevor Sie beginnen
* Wenn du nicht bereits geerdet bist, beground dich richtig.
* Trennen Sie alle Kabel, einschließlich Konsole, Management, SAS Storage und Datennetzwerkkabel, vom entfernten Controller.


.Schritte
. Richten Sie das Ende des Controller-Moduls an Schacht B im Chassis aus, und drücken Sie dann vorsichtig das Controller-Modul zur Hälfte in das System.
+

TIP: Schacht B befindet sich auf der rechten Seite des Gehäuses.

+

WARNING: Setzen Sie das Controller-Modul erst dann vollständig in das Gehäuse ein, wenn Sie dazu später im Verfahren aufgefordert werden.

. Verkabeln Sie die Management- und Konsolen-Ports mit dem node2-Controller-Modul.
+

NOTE: Da das Chassis bereits eingeschaltet ist, beginnt Node2 zu booten, sobald er vollständig eingesetzt ist.  Um zu verhindern, dass Node2 hochfährt, schließen Sie die Konsolen- und Managementkabel an, bevor Sie das Controller-Modul vollständig einsetzen.

. Drücken Sie das Controller-Modul fest in das Gehäuse, bis es auf die Mittelebene trifft und vollständig sitzt.
+
Die Verriegelung steigt, wenn das Controller-Modul voll eingesetzt ist.

+

NOTE: Um eine Beschädigung der Anschlüsse zu vermeiden, sollten Sie beim Einschieben des Controller-Moduls in das Gehäuse keine übermäßige Kraft anwenden.

. Schließen Sie die serielle Konsole an, sobald das Modul sitzt, und seien Sie bereit, den AUTOBOOT von Knoten2 zu unterbrechen.
. Nachdem Sie DEN AUTOBOOT unterbrochen haben, wird node2 an der LOADER-Eingabeaufforderung angehalten. Wenn Sie das AUTOBOOT nicht rechtzeitig unterbrechen und node2 startet den Boot-Vorgang, warten Sie auf die Eingabeaufforderung und drücken Sie Strg-C, um zum Boot-Menü zu gelangen. Nachdem der Node im Boot-Menü angehalten wurde, verwenden Sie Option `8` , um den Node neu zu booten und DAS AUTOBOOT während des Neubootens zu unterbrechen.

