---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-nas-lifs-node1-from-node2-to-upgraded-node1.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Vergewissern Sie sich, dass die node1 NAS-Daten-LIFs auf Node 2 von Node 2 auf Node 1 verschoben werden, wenn Sie zum Upgrade von Controller-Modellen im selben Chassis ARL verwenden. 
---
= Verschieben Sie node1-Aggregate und NAS-Daten-LIFs nicht-Root von node2 auf den aktualisierten node1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die Netzwerkkonfiguration auf Knoten 1 überprüft haben, müssen Sie die zu Knoten 1 gehörenden NAS-Daten-LIFs von Knoten 2 auf Knoten 1 verschieben und bestätigen, dass die SAN-LIFs auf Knoten 1 vorhanden sind.

.Über diese Aufgabe
Remote LIFs verarbeiten den Datenverkehr zu SAN LUNs während des Upgrade-Vorgangs. Das Verschieben von SAN LIFs ist für die Integrität des Clusters oder der Dienste während des Upgrades nicht erforderlich. SAN LIFs werden nur dann verschoben, wenn sie neuen Ports zugeordnet werden müssen.

Sie überprüfen, ob die LIFs intakt sind und sich an den richtigen Ports befinden, nachdem Sie Knoten 1 online geschaltet haben.

.Schritte
. Wiederaufnahme des Betriebs der Versetzung:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt die folgenden Aufgaben aus:

+
--
** Cluster-Quorum-Prüfung
** System-ID-Prüfung
** Prüfung der Bildversion
** Überprüfung der Zielplattform
** Prüfung der Netzwerkanachabilität


--
+
Das System unterbricht den Vorgang an dieser Stelle während der Netzwerkerreichbarkeitsprüfung.

. Durchführen einer Prüfung der Netzwerkfähigkeit:
+
[source, cli]
----
network port reachability show -node node1
----
+
Vergewissern Sie sich, dass alle verbundenen Ports, einschließlich der Schnittstellengruppe und VLAN-Ports, ihren Status als anzeigen `OK`.

. Bei den folgenden Upgrades müssen Sie die FCP SAN LIFs neu zuweisen.
+
[cols="35,65"]
|===
| Vorhandenes System | Austauschsystem 


| AFF A250 | AFF A30, AFF A50 


| AFF C250 | AFF C30, AFF C60 


| AFF A800 | AFF A70, AFF A90 


| AFF C800 | AFF C80 
|===
+
Bei allen anderen System-Upgrades fahren Sie mit <<resume_relocation_step4,Schritt 4>>fort.

+
.. Neuzuweisung von FCP-SAN-LIFs für FCP- oder FC-NVMe-Datenzugriff an die korrekten Home Ports:
+
[source, cli]
----
network interface show -vserver <vserver_hosting_fcp_lifs>
----
.. Bei LIFs, deren aktueller Node als aktualisierter node1 angegeben wird und der aktuelle Port den Status „oper“ als „-“ meldet (da der Port auf dem AFF A800 Node vorhanden war, jedoch nicht auf dem AFF A90 Node vorhanden ist), ändern Sie den aktuellen Port, bevor er online geschaltet werden kann.
+
Überprüfen Sie, ob die physische Konnektivität zum FC-Zielport hergestellt ist, an den die FC-LIF verschoben werden muss:

+
--
... Legen Sie den LIF-Status auf „down“ fest:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name>  -status-admin down
----
... Ändern Sie den Home Port des LIF:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> - home-node <node1> -home-port <FC_target_port>
----
... Legen Sie den LIF-Status auf „up“ fest:
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <lif_name>  -status-admin up
----


--
+
Wiederholen Sie die Teilschritte a und b für jede FC-SAN-LIF, die sich als Home in Knoten 1 befindet.



. [[resume_Relocation_step4]]Umzugsvorgang fortsetzen:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt folgende Prüfungen durch:

+
--
** Cluster-Zustandsprüfung
** LIF-Statusüberprüfung für Cluster


--
+
Nach Durchführung dieser Prüfungen verschiebt das System die nicht-Root-Aggregate und NAS-Daten-LIFs, die sich im Besitz von node1 befinden, in die neue Knoten1.

+
Der Controller-Ersatzvorgang hält nach Abschluss der Ressourcenverschiebung die Pause ein.

. Überprüfen Sie den Status der Aggregatverschiebung und der LIF-Verschiebung von NAS-Daten:
+
[source, cli]
----
system controller replace show-details
----
+
Wenn der Austausch des Controllers unterbrochen wird, prüfen und korrigieren Sie den Fehler, falls zutreffend, und führen Sie das Problem anschließend aus `resume` Um den Vorgang fortzusetzen.

. Falls erforderlich, stellen Sie verschobene LIFs wieder her und setzen Sie sie zurück oder migrieren und modifizieren Sie die node1 LIFs manuell, die nicht automatisch auf node1 verschoben wurden.
+
[role="tabbed-block"]
====
.Versetzte LIFs wiederherstellen und zurücksetzen
--
.. Liste aller verschobenen LIFs:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Wenn LIFs verschoben werden, stellen Sie den Home-Node wieder in node1 wieder her:
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node1_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Manuelle Migration und Modifizierung von LIFs
--
.. Migrieren Sie die LIFs, die nicht automatisch auf Knoten 1 verschoben wurden:
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node1_nodename> -destination-port <port_on_node1>
----
.. Ändern Sie den Home-Knoten und den Home-Port für die migrierten LIFs:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node1_nodename> -home-port <home_port>
----


--
====
. Setzen Sie den Vorgang fort, um das System zur Durchführung der erforderlichen Nachprüfungen zu auffordern:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt die folgenden Nachprüfungen durch:

+
** Cluster-Quorum-Prüfung
** Cluster-Zustandsprüfung
** Aggregatrekonstruktion
** Aggregatstatus-Prüfung
** Überprüfung des Festplattenstatus
** LIF-Statusüberprüfung für Cluster
** Lautstärkerprüfung



