---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Vergewissern Sie sich, dass die NAS-Daten-LIFs auf Node 1 von Node 1 auf Node 2 verschoben werden, wenn Sie zum Upgrade von Controller-Modellen im selben Chassis ARL verwenden. 
---
= Verschieben Sie Aggregate und NAS-Daten-LIFs zurück auf node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die Netzwerkkonfiguration auf Knoten 2 überprüft haben, müssen Sie die zu Knoten 2 gehörenden NAS-Daten-LIFs von Knoten 1 auf Knoten 2 verschieben und bestätigen, dass die SAN-LIFs auf Knoten 2 vorhanden sind.

.Über diese Aufgabe
Remote LIFs verarbeiten den Datenverkehr zu SAN LUNs während des Upgrade-Vorgangs. Das Verschieben von SAN LIFs ist für die Integrität des Clusters oder der Dienste während des Upgrades nicht erforderlich. SAN LIFs werden nur dann verschoben, wenn sie neuen Ports zugeordnet werden müssen.

Sie überprüfen, ob die LIFs intakt sind und sich an den richtigen Ports befinden, nachdem Sie Knoten 2 online geschaltet haben.

.Schritte
. Wiederaufnahme des Betriebs der Versetzung:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt die folgenden Aufgaben aus:

+
--
** Cluster-Quorum-Prüfung
** System-ID-Prüfung
** Prüfung der Bildversion
** Überprüfung der Zielplattform
** Prüfung der Netzwerkanachabilität


--
+
Das System unterbricht den Vorgang an dieser Stelle während der Netzwerkerreichbarkeitsprüfung.

. Wiederaufnahme des Betriebs der Versetzung:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt folgende Prüfungen durch:

+
--
** Cluster-Zustandsprüfung
** LIF-Statusüberprüfung für Cluster


--
+
Nach Durchführung dieser Überprüfungen verlagert das System die nicht-Root-Aggregate und NAS-Daten-LIFs zurück auf node2, das jetzt auf dem Ersatz-Controller ausgeführt wird.

+
Der Controller-Ersatzvorgang hält nach Abschluss der Ressourcenverschiebung die Pause ein.

. Überprüfen Sie den Status der Aggregatverschiebung und der LIF-Verschiebung von NAS-Daten:
+
[source, cli]
----
system controller replace show-details
----
+
Wenn der Austausch des Controllers unterbrochen wird, prüfen und korrigieren Sie den Fehler, falls zutreffend, und führen Sie das Problem anschließend aus `resume` Um den Vorgang fortzusetzen.

. Falls erforderlich, stellen Sie verschobene LIFs wieder her und setzen Sie sie zurück oder migrieren und modifizieren Sie die node2 LIFs manuell, die nicht automatisch auf node2 verschoben wurden.
+
[role="tabbed-block"]
====
.Versetzte LIFs wiederherstellen und zurücksetzen
--
.. Liste aller verschobenen LIFs:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Wenn LIFs verschoben werden, stellen Sie den Home-Node wieder in node2 wieder her:
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node2_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Manuelle Migration und Modifizierung von LIFs
--
.. Migrieren Sie die LIFs, die nicht automatisch auf Knoten 2 verschoben wurden:
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node2_nodename> -destination-port <port_on_node2>
----
.. Ändern Sie den Home-Knoten und den Home-Port für die migrierten LIFs:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node2_nodename> -home-port <home_port>
----


--
====
. Setzen Sie den Vorgang fort, um das System zur Durchführung der erforderlichen Nachprüfungen zu auffordern:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt die folgenden Nachprüfungen durch:

+
** Cluster-Quorum-Prüfung
** Cluster-Zustandsprüfung
** Aggregatrekonstruktion
** Aggregatstatus-Prüfung
** Überprüfung des Festplattenstatus
** LIF-Statusüberprüfung für Cluster
** Lautstärkerprüfung



