---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/overview-of-the-arl-upgrade.html 
keywords: overview, arl, upgrade, owner, controller, hardware, old, system, chassis, disk, disks 
summary: Informieren Sie sich, wie das Upgrade von Controller-Modellen im selben Chassis durch ARL erfolgt. 
---
= Erfahren Sie mehr über die ARL-Upgradesequenz
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bevor Sie die Nodes mit ARL aktualisieren, sollten Sie unbedingt verstehen, wie das Verfahren funktioniert. In diesem Inhalt wird das Verfahren in mehrere Phasen unterteilt.



== Aktualisieren Sie das Node-Paar

Zum Upgrade des Node-Paars müssen Sie die ursprünglichen Nodes vorbereiten und dann für die ursprünglichen und die neuen Nodes eine Reihe von Schritten ausführen. Anschließend können Sie die ursprünglichen Knoten außer Betrieb nehmen.



== Übersicht über die ARL-Upgrade-Sequenz

Während des Verfahrens aktualisieren Sie die ursprüngliche Controller Hardware mit der Ersatz-Controller-Hardware, einem Controller gleichzeitig. Nutzen Sie die HA-Paar-Konfiguration, um das Eigentum von Aggregaten ohne Root-Berechtigungen zu verschieben. Alle Aggregate außerhalb der Root-Ebene müssen zwei Umlagerungen durchlaufen, um das endgültige Ziel zu erreichen, nämlich den korrekten aktualisierten Node.

Jedes Aggregat hat einen Hausbesitzer und aktuellen Eigentümer. Der Hausbesitzer ist der eigentliche Eigentümer des Aggregats, und der aktuelle Eigentümer ist der temporäre Eigentümer.

Die folgende Tabelle beschreibt die grundlegenden Aufgaben, die Sie in den einzelnen Phasen ausführen, und den Zustand der Aggregateigentümer am Ende der Phase. Detaillierte Schritte sind im weiteren Verlauf des Verfahrens aufgeführt:

[cols="35,65"]
|===
| Stufe | Schritte 


| link:verify_upgrade_hardware.html["Phase 1: Upgrade vorbereiten"]  a| 
In Phase 1 überprüfen Sie, ob Sie über die richtige Hardware für Ihr Upgrade verfügen, führen Vorabprüfungen durch und korrigieren bei Bedarf die Eigentümerschaft für Aggregate. Sie müssen bestimmte Informationen aufzeichnen, wenn Sie Storage Encryption mit dem Onboard Key Manager managen und die SnapMirror Beziehungen stilllegen möchten.

Gesamteigentum am Ende von Phase 1:

* Node1 ist der Hausbesitzer und der aktuelle Besitzer der node1 Aggregate
* Node2 ist der Hausbesitzer und der aktuelle Besitzer der node2 Aggregate




| link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["Phase 2: Ressourcen verlagern und Knoten in den Ruhestand zurücknehmen 1"]  a| 
In Phase 2 verschieben Sie Node1-nicht-Root-Aggregate und NAS-Daten-LIFs von Node1 zu Node2. Dieser Prozess ist weitgehend automatisiert; der Vorgang hält an, damit Sie seinen Status überprüfen können. Sie müssen den Vorgang manuell fortsetzen. Bei Bedarf verschieben Sie fehlerhafte oder Vetos Aggregate. Sie erfassen Node1-Informationen für die spätere Verwendung im Verfahren vor dem Ausscheiden von node1. Sie können sich auch später beim Verfahren auf den Netzboot node1 vorbereiten.

Gesamteigentum am Ende von Phase 2:

* Node2 ist der aktuelle Besitzer von node1 Aggregaten
* Node2 ist der Hausbesitzer und der aktuelle Besitzer von node2 Aggregaten




| link:cable-node1-for-shared-cluster-HA-storage.html["Stufe 3: Starten Sie Node1 mit den Ersatz-Systemmodulen"]  a| 
In Phase 3 starten Sie node1 mit aktualisierten Systemmodulen und überprüfen die aktualisierte node1-Installation. Wenn Sie NetApp Volume Encryption (NVE) verwenden, stellen Sie die Konfiguration des Schlüsselmanagers wieder her. Außerdem werden node1 Aggregate und NAS-Daten-LIFs von node2 auf die aktualisierte Node1 verschoben und Sie überprüfen, ob die SAN-LIFs auf node1 vorhanden sind.

Gesamteigentum am Ende von Stufe 3:

* Aktualisierter node1 ist der Haupteigentümer und aktueller Besitzer von node1-Aggregaten
* Node2 ist der Hausbesitzer und der aktuelle Besitzer von node2 Aggregaten




| link:relocate_non_root_aggr_nas_lifs_from_node2_to_node1.html["Phase 4: Ressourcen verlagern und Knoten zurücknehmen 2"]  a| 
Während Phase 4 verschieben Sie Aggregate und NAS-Daten-LIFs von Knoten 2 auf die aktualisierte Knoten 1 und Mustern Knoten 2 aus.

Gesamteigentum am Ende von Stufe 4:

* Der aktualisierte Knoten 1 ist der Hausbesitzer und der aktuelle Besitzer von Aggregaten, die ursprünglich zu node1 gehörten
* Der aktualisierte Knoten 1 ist der aktuelle Besitzer von node2 Aggregaten




| link:install-aff-a30-a50-c30-c50-node2.html["Stufe 5: Installieren Sie die Ersatz-Systemmodule auf Knoten 2"]  a| 
In Phase 5 installieren Sie die neuen Systemmodule, die Sie für den aktualisierten Knoten 2 erhalten haben, und dann Netboot Knoten 2.

Gesamteigentum am Ende von Stufe 5:

* Der aktualisierte Node1 ist der Hausbesitzer und der aktuelle Besitzer der Aggregate, die ursprünglich zu node1 gehörten.
* Upgrade node2 ist der Hausbesitzer und der aktuelle Besitzer von Aggregaten, die ursprünglich zu node2 gehörten.




| link:boot_node2_with_a900_controller_and_nvs.html["Stufe 6: Starten Sie Node2 mit den Ersatz-Systemmodulen"]  a| 
In Phase 6 booten Sie Knoten2 mit aktualisierten Systemmodulen und überprüfen die aktualisierte Knoten2-Installation. Wenn Sie NVE verwenden, stellen Sie die Schlüsselmanagerkonfiguration wieder her. Bei Upgrades von Switch-verbundenen Clustern müssen Sie überprüfen, ob die Cluster-Switch-Referenzkonfigurationsdatei (RCF) die gemeinsam genutzten Cluster-/HA-Ports unterstützt. Sie verschieben außerdem Nicht-Root-Aggregate und NAS-Daten-LIFs von Knoten1 von Knoten1 auf den aktualisierten Knoten2 und überprüfen, ob die SAN-LIFs auf Knoten2 vorhanden sind.



| link:manage-authentication-using-kmip-servers.html["Phase 7: Das Upgrade abschließen"]  a| 
In Phase 7 bestätigen Sie, dass die neuen Nodes korrekt eingerichtet wurden. Und wenn die neuen Nodes verschlüsselt sind, konfigurieren und einrichten Sie Storage Encryption oder NVE. Zudem sollten die alten Nodes außer Betrieb gesetzt und der SnapMirror Betrieb fortgesetzt werden.

|===