---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/prepare-nodes-for-upgrade.html 
keywords: preparing, prepare, nodes, upgrade, stage 1, prechecks, old, system, chassis, disk, disks 
summary: Wenn Sie mit ARL Controller-Modelle im selben Chassis aktualisieren, bereiten Sie die Nodes vor und führen eine Reihe von Vorabprüfungen durch. 
---
= Bereiten Sie die Knoten für ein Upgrade vor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Der Prozess des Controller-Austauschs beginnt mit einer Reihe von Vorabprüfungen. Sie sammeln auch Informationen über die ursprünglichen Nodes, die Sie später verwenden können. Falls erforderlich, ermitteln Sie den Typ der verwendeten Self-Encrypting Drives.



== Schritt 1: Die Knoten vorbereiten

Starten Sie den Controller-Austausch und führen Sie Vorabprüfungen durch. Ermitteln Sie gegebenenfalls den Typ der verwendeten selbstverschlüsselnden Laufwerke.

.Schritte
. Listen Sie die Firmware-Version des Service-Prozessors (SP) oder des Baseboard Management Controller (BMC) auf, die auf dem alten Controller ausgeführt wird:
+
`service-processor show`

+
Vergewissern Sie sich, dass Sie über eine unterstützte SP- oder BMC-Firmware-Version verfügen:

+
[cols="30,35,35"]
|===
| Alter Controller | SP oder BMC | Mindestversion der Firmware 


| AFF A800 | BMC | 10.9 


| AFF A220 | BMC | 11,9P1 


| AFF A200 | SP | 5.11P1 


| AFF C 190 | BMC | 11,9P1 


| FAS2620 | SP | 5.11P1 


| FAS2720 | BMC | 11,9P1 
|===
. Starten Sie den Controller-Ersatzprozess, indem Sie den folgenden Befehl im erweiterten Berechtigungsmodus der ONTAP-Befehlszeile eingeben:
+
`set -privilege advanced`

+
`system controller replace start -nodes _node_names_`

+
Die Ausgabe sieht ähnlich aus wie im folgenden Beispiel. Die Ausgabe zeigt die auf Ihrem Cluster ausgeführte ONTAP-Version an:

+
....
Warning:
1. Current ONTAP version is 9.15.1

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM  batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

4. Note: This is not a MetroCluster configuration. Controller replacement supports only ARL based procedures.

Do you want to continue? {y|n}: y
....
. Wählen Sie  `y`. Sie sehen die folgende Ausgabe:
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
In der Vorabprüfungen-Phase führt das System die folgende Liste der Überprüfungen im Hintergrund aus.

+
[cols="35,65"]
|===
| Pre-Check | Beschreibung 


| Cluster-Integritätsprüfung | Überprüft alle Nodes im Cluster, um sicherzustellen, dass sie sich in einem ordnungsgemäßen Zustand befinden. 


| Statusprüfung Der Aggregatverschiebung | Überprüft, ob eine Aggregatverschiebung bereits erfolgt. Wenn eine weitere Aggregatverschiebung erfolgt, schlägt die Prüfung fehl. 


| Modellname Prüfen | Überprüft, ob die Controller-Modelle bei diesem Verfahren unterstützt werden. Wenn die Modelle nicht unterstützt werden, schlägt die Aufgabe fehl. 


| Cluster-Quorum-Prüfung | Überprüft, ob die zu ersetzenden Nodes sich in Quorum befinden. Wenn sich die Knoten nicht im Quorum befinden, schlägt die Aufgabe fehl. 


| Überprüfung Der Bildversion | Es wird geprüft, ob auf den zu ersetzenden Knoten dieselbe Version von ONTAP ausgeführt wird. Wenn die ONTAP-Image-Versionen unterschiedlich sind, schlägt die Aufgabe fehl. Auf den neuen Knoten muss dieselbe Version von ONTAP 9.x installiert sein, die auch auf den ursprünglichen Knoten installiert ist. Wenn auf den neuen Knoten eine andere Version von ONTAP installiert ist, müssen Sie die neuen Controller nach der Installation per Netzwerkstart starten. Anweisungen zum Aktualisieren von ONTAP finden Sie unter link:other-references.html["Quellen"] zum Link _Upgrade ONTAP_. 


| HA-Statusüberprüfung | Überprüft, ob beide Nodes, die ersetzt werden, in einer HA-Paar-Konfiguration mit Hochverfügbarkeit vorhanden sind. Wenn das Speicher-Failover für die Controller nicht aktiviert ist, schlägt die Aufgabe fehl. 


| Aggregatstatus-Prüfung | Wenn die Nodes ersetzt werden, eigene Aggregate, für die sie nicht der Home-Inhaber sind, schlägt die Aufgabe fehl. Die Nodes sollten nicht im Besitz von nicht lokalen Aggregaten sein. 


| Überprüfung Des Festplattenstatus | Falls bei einem der zu ersetzenden Knoten Festplatten fehlen oder ausgefallen sind, schlägt der Vorgang fehl. Falls Festplatten fehlen, lesen Sie link:other-references.html["Quellen"], um auf _Festplatten- und Aggregatverwaltung mit der CLI_, _Logische Speicherverwaltung mit der CLI_ und _HA-Paarverwaltung_ zu verweisen, um den Speicher für das HA-Paar zu konfigurieren. 


| LIF-Statusüberprüfung von Daten | Überprüft, ob für einen der zu ersetzenden Nodes keine lokalen Daten-LIFs vorhanden sind. Die Nodes sollten keine Daten-LIFs enthalten, für die sie nicht der Home-Inhaber sind. Wenn einer der Nodes nicht-lokale Daten-LIFs enthält, schlägt die Aufgabe fehl. 


| LIF-Status des Clusters | Überprüft, ob die Cluster-LIFs für beide Nodes aktiv sind. Wenn die Cluster-LIFs ausgefallen sind, schlägt die Aufgabe fehl. 


| ASUP-Statusprüfung | Wenn AutoSupport-Benachrichtigungen nicht konfiguriert sind, schlägt die Aufgabe fehl. Bevor Sie mit dem Austausch des Controllers beginnen, müssen Sie AutoSupport aktivieren. 


| CPU-Auslastungs-Prüfung | Überprüft, ob die CPU-Auslastung bei allen zu ersetzenden Nodes mehr als 50 % beträgt. Wenn die CPU-Nutzung über einen erheblichen Zeitraum mehr als 50 % beträgt, schlägt die Aufgabe fehl. 


| Aggregatrekonstruktion | Überprüft, ob bei beliebigen Datenaggregaten eine Rekonstruktion durchgeführt wird. Wenn die Aggregatrekonstruktion ausgeführt wird, schlägt die Aufgabe fehl. 


| Knoten Affinität Job Überprüfung | Überprüft, ob Jobs mit Knotenorientierung ausgeführt werden. Wenn Knotenaffinitätsjobs ausgeführt werden, schlägt die Prüfung fehl. 
|===
. Wenn der Controller-Ersatzvorgang gestartet und die Vorabprüfungen abgeschlossen sind, wird der Vorgang angehalten. In diesem Fall können Sie die Ausgabedaten sammeln, die Sie zu einem späteren Zeitpunkt im Controller-Upgrade-Prozess benötigen könnten.
. Führen Sie den folgenden Befehlssatz aus, wie durch das Verfahren zum Austausch des Controllers auf der Systemkonsole gesteuert.
+
Führen Sie die Befehle an dem seriellen Port aus, der mit den einzelnen Nodes verbunden ist, und speichern Sie die Ausgabe der Befehle einzeln:

+
** `vserver services name-service dns show`
** `network interface show -curr-node _local_ -role cluster,intercluster,node-mgmt,cluster-mgmt,data`
** `network port show -node _local_ -type physical`
** `service-processor show -node _local_ -instance`
** `network fcp adapter show -node _local_`
** `network port ifgrp show -node _local_`
** `system node show -instance -node _local_`
** `run -node _local_ sysconfig`
** `run -node local sysconfig -ac`
** `run -node local aggr status -r`
** `vol show -fields type`
** `run local aggr options _data_aggregate_name_`
** `vol show -fields type , space-guarantee`
** `storage aggregate show -node _local_`
** `volume show -node _local_`
** `storage array config show -switch _switch_name_`
** `system license show -owner _local_`
** `storage encryption disk show`
** `security key-manager onboard show-backup`
** `security key-manager external show`
** `security key-manager external show-status`
** `network port reachability show -detail -node _local_`
+

NOTE: Wenn NetApp Volume Encryption (NVE) oder NetApp Aggregate Encryption (NAE) den Onboard Key Manager verwendet, halten Sie die Schlüsselmanager-Passphrase bereit, um später im Verfahren die Neusynchronisierung des Schlüsselmanagers abzuschließen.



. Wenn Ihr System Self-Encrypting Drives verwendet, lesen Sie den Artikel der Knowledge Base https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Wie erkennen Sie, ob ein Laufwerk FIPS-zertifiziert ist"^] Ermitteln der Art der Self-Encrypting Drives, die auf dem HA-Paar verwendet werden, das Sie aktualisieren. ONTAP unterstützt zwei Arten von Self-Encrypting Drives:
+
--
** FIPS-zertifizierte NetApp Storage Encryption (NSE) SAS- oder NVMe-Laufwerke
** Self-Encrypting-NVMe-Laufwerke (SED) ohne FIPS


[NOTE]
====
FIPS-Laufwerke können nicht mit anderen Laufwerkstypen auf demselben Node oder HA-Paar kombiniert werden.

SEDs können mit Laufwerken ohne Verschlüsselung auf demselben Node oder HA-Paar kombiniert werden.

====
https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["Weitere Informationen zu unterstützten Self-Encrypting Drives"^].

--




== Schritt 2: Korrigieren Sie den Aggregatbesitz, falls eine ARL-Vorprüfung fehlschlägt

Wenn die aggregierte Statusprüfung fehlschlägt, müssen Sie Aggregate des Partner-Node an den Node „Home-Owner“ zurückgeben und den Vorabprüfvorgang erneut initiieren.

.Schritte
. Gibt die Aggregate zurück, die derzeit dem Partner-Node gehören, an den Home-Owner-Node:
+
`storage aggregate relocation start -node _source_node_ -destination _destination-node_ -aggregate-list *`

. Überprüfen Sie, dass weder node1 noch node2 noch Eigentümer von Aggregaten ist, für die es der aktuelle Eigentümer ist (aber nicht der Hausbesitzer):
+
`storage aggregate show -nodes _node_name_ -is-home false -fields owner-name, home-name, state`

+
Das folgende Beispiel zeigt die Ausgabe des Befehls, wenn ein Node sowohl der aktuelle Eigentümer als auch der Home-Inhaber von Aggregaten ist:

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----
. Starten Sie den Controller-Austauschprozess neu:


`system controller replace start -nodes _node_names_`

.Was kommt als Nächstes?
Nach der Vorbereitung der Knoten, link:complete-preparation-for-upgrade.html["Die Vorbereitungen für das Upgrade abschließen"].
