---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/relocate-failed-or-vetoed-aggr-node2.html 
keywords: relocate, failed, vetoed, aggregates, relocation, operation 
summary: Verschieben Sie fehlgeschlagene oder abgelehnte Aggregate auf Knoten 2, wenn Sie ARL zum Aktualisieren von Controllermodellen im selben Gehäuse verwenden. 
---
= Verschieben Sie fehlgeschlagene oder abgelehnte Aggregate auf Knoten2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn die Verlagerung von Aggregaten fehlschlägt oder ein Veto eingelegt wird, müssen Sie die Aggregate manuell auf Knoten 2 verlagern oder bei Bedarf entweder die Vetos oder Zielprüfungen außer Kraft setzen.

.Über diese Aufgabe
Das System unterbricht den Umzugsvorgang aufgrund des Fehlers.

.Schritte
. Überprüfen Sie die EMS-Protokolle (Event Management System), um festzustellen, warum das Aggregat nicht verschoben oder gegen ein Vetos eingesetzt wurde.
. Verschiebung ausgefallener oder Vetos von Aggregaten:
+
`storage aggregate relocation start -node <node1> -destination <node2> -aggregate-list <aggregate_name> -ndo-controller-upgrade true`

. Geben Sie bei der entsprechenden Aufforderung ein `y`.
. Sie können die Verschiebung mit einer der folgenden Methoden erzwingen:
+
[cols="35,65"]
|===
| Option | Beschreibung 


| Veto-Prüfungen werden überschrieben | Verwenden Sie den folgenden Befehl:
`storage aggregate relocation start -node node1 -destination node2 -aggregate-list <aggregate_list> -ndo-controller-upgrade true -override-vetoes true` 


| Zielprüfungen überschreiben | Verwenden Sie den folgenden Befehl:
`storage aggregate relocation start -node node1 -destination node2 -aggregate-list <aggregate_list> -ndo-controller-upgrade true -override-vetoes true -override-destination-checks true` 
|===

