---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/retire-node2.html 
keywords: retire, node2, retiring, node 
summary: Fahren Sie node2 herunter und entfernen Sie es aus dem Rack oder Chassis, wenn Sie mit ARL ein Upgrade der Controller-Modelle im selben Chassis durchführen. 
---
= Node2 ausmustern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um Knoten2 außer Betrieb zu nehmen, fahren Sie Knoten2 ordnungsgemäß herunter und entfernen ihn dann aus dem Rack oder Gehäuse.

.Schritte
. Vorgang fortsetzen:
+
`system controller replace resume`

+
Der Knoten wird automatisch angehalten.



.Was kommt als Nächstes?
Nach der Außerbetriebnahme von node2 wählen Sie je nach Ihrer Upgrade-Konfiguration eines der folgenden Verfahren zum Austausch des Controllers aus:

* link:replace-node2-affa250-affc250.html["Ersetzen Sie das Controller-Modul AFF A250 oder AFF C250 von node2"]
* link:replace-node2-affa800-affc800.html["Ersetzen Sie das Controller-Modul AFF A800 oder AFF C800 von node2"]
* link:replace-node2-affa220-affa200-affc190-fas2620-fas2720.html["Ersetzen Sie das Controller-Modul von node2 AFF A220, AFF A200, AFF C190, FAS2620 oder FAS2720"]
* link:replace-node2-aff700-fas900.html["Ersetzen Sie die node2 AFF A700 oder FAS9000 Controller und NVRAM Module"]

