---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/verify-rcf-configuration.html 
keywords: aggregate, relocation, cluster, switch, rcf, shared 
summary: Überprüfen Sie, ob der RCF des Cluster-Switches die gemeinsam genutzten Cluster-/HA-Ports für die neuen Controller für Upgrades von Switch-verbundenen Clustern unterstützt. 
---
= Überprüfen der RCF-Konfiguration auf Cluster-Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In dieser Phase des Upgrade-Vorgangs sollten sich alle Datenaggregate auf Knoten1 befinden.  Wenn Sie eine Konfiguration mit Switch-verbundenen Clustern aktualisieren, müssen Sie überprüfen, ob die Cluster-Switch-Referenzkonfigurationsdatei (RCF) die gemeinsam genutzten Cluster-/HA-Ports für die neuen Controller unterstützt.

Wenn Sie auf eine Zwei-Knoten Cluster ohne Switches-Konfiguration upgraden, können Sie diesen Abschnitt überspringen und zu link:move-non-root-aggr-and-nas-data-lifs-back-to-node2.html["Verschieben Sie Aggregate und NAS-Daten-LIFs zurück auf node2"] gehen.

.Schritte
. Wechseln in den erweiterten Berechtigungsmodus:
+
`set advanced`

. Überprüfen Sie den Status von „IC RDMA“:
+
`ha interconnect status show`

+
In der Ausgabe sollte die "IC RDMA Connection" den Status haben `Up` .

+
[cols="50,50"]
|===
| Wenn der Status „IC RDMA-Verbindung“ ... ist. | Dann… 


| `Up` | Gehe zu link:move-non-root-aggr-and-nas-data-lifs-back-to-node2.html["Verschieben Sie Aggregate und NAS-Daten-LIFs zurück auf node2"]. 


| `Down` | Gehe zu<<verify-rcf-step3,Schritt 3>> . 
|===
. [[verify-rcf-step3]]Überprüfen Sie die Cluster-Ports und den Switch-RCF.
+
Weitere Informationen finden Sie unter link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["Stellen Sie eine Verbindung zu einem Switch-Attached-Cluster her"].

. Überprüfen Sie, ob der Status „IC RDMA-Verbindung“ geändert wurde in `Up` :
+
`ha interconnect status show`



.Was kommt als Nächstes?
Nach Überprüfung der RCF-Konfiguration link:move-non-root-aggr-and-nas-data-lifs-back-to-node2.html["Nicht-Root-Aggregate und NAS-Daten-LIFs zurück zu node2 verschieben"].
