---
settings:
  name: Upgrade controllers
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: AFF und FAS System-Upgrade-Dokumentation
    url: "/index.html"
  - title: Wählen Sie das Upgrade Ihrer Controller-Hardware aus
    url: "/choose_controller_upgrade_procedure.html"
  - section: upgrade-arl
  - section: upgrade
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: AFF and FAS Systems
  repo: ontap-systems-family
