---
permalink: upgrade/migrate-fas2820-aggregates-epsilon-lifs.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node1, node4, migrate, aggregates, lifs 
summary: 'Migrieren Sie die Datenaggregate, Epsilon und logischen Schnittstellen (LIFs) auf Knoten1 zu Knoten4.' 
---
= Migrieren Sie Datenaggregate, Epsilon und LIFs auf FAS2820 Knoten1 nach Knoten4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Migrieren Sie die Datenaggregate, Epsilon und logischen Schnittstellen (LIFs) auf dem FAS2820 Knoten1 zu Knoten4.

.Über diese Aufgabe
Führen Sie die folgenden Schritte auf Knoten4 aus.

.Schritte
. Legen Sie an der LOADER-Eingabeaufforderung für Knoten4 die Partnersystem-ID fest:
+
[source, cli]
----
setenv partner-sysid <system_ID_of_node1>
----
. Überprüfen Sie die Partnersystem-ID:
+
[source, cli]
----
printenv partner-sysid
----
. Speichern Sie die Änderungen:
+
[source, cli]
----
saveenv
----
. Starten Sie den Knoten im Startmenü:
+
[source, cli]
----
boot_ontap menu
----
. Wählen Sie im Startmenü die Option `6 Update flash from backup config` um das /var-Dateisystem auf Knoten4 wiederherzustellen.
+
Dadurch wird die gesamte Flash-basierte Konfiguration durch das letzte Backup auf Festplatten ersetzt.

. Eingabe `y` Um fortzufahren.
+
[NOTE]
====
Der Knoten startet automatisch neu, um die neue Kopie des Dateisystems /var zu laden.

Der Knoten meldet eine Warnung bei Nichtübereinstimmung der System-ID. Eingabe `y` Um die System-ID zu überschreiben.

====
. Migration der Cluster-LIFs:
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
network port show
----
+
[NOTE]
====
Wenn die Systemcluster-Ports beim Upgrade eines FAS2820 auf einen Ersatzcontroller nicht identisch sind, müssen Sie die Schnittstellen auf Knoten 4 möglicherweise vorübergehend in Cluster-Ports ändern:

[source, cli]
----
network port modify -node <node4> -port <port_name> -mtu 9000 -ipspace Cluster
----
====
+
[source, cli]
----
network interface migrate -vserver Cluster -lif <cluster_LIF>  -destination-node <node4> -destination-port <port_name>
----
. Warten Sie, bis der Cluster das Quorum erreicht hat, und überprüfen Sie dann, ob die Clusterknoten fehlerfrei sind:
+
[source, cli]
----
– cluster show
----
+

NOTE: Das HA-Paar und der Storage Failover bleiben im aktuellen Zustand deaktiviert.

. Verschieben Sie die Cluster-LIFs auf die temporären 25-Gbit-Cluster-Ports auf node 4:
+
[source, cli]
----
network interface modify -vserver Cluster -lif <cluster_LIF> -home-node <node4> -home-port <port_name>
----
. Führen Sie diesen Schritt nur aus, wenn auf dem FAS2820 Cluster, den Sie aktualisieren, Schnittstellengruppen und Daten-VLANs verwendet werden. Andernfalls gehen Sie zu<<migrate_node1_nod4,Schritt 11>> .
+
Die physischen Netzwerkportnamen auf dem Ersatzcontroller unterscheiden sich von denen auf dem FAS2820.  Dies kann zu verschobenen VLANs und falsch konfigurierten Schnittstellengruppen auf Knoten 4 führen.

+
.. Zeigen Sie die verschobenen VLANs an:
+
[source, cli]
----
cluster controller-replacement network displaced-vlans show
----
.. Stellen Sie die verschobenen VLANs wieder her:
+
[source, cli]
----
cluster controller-replacement network displaced-vlans restore
----
.. Korrigieren Sie die falsch konfigurierten Schnittstellengruppen.  Die Portnamen zwischen dem FAS2820 und den Controllern, die Sie aktualisieren, können unterschiedlich sein.  Aktualisieren Sie die Schnittstellengruppen mit den richtigen Mitgliedsports:
+
[source, cli]
----
ifgrp remove-port -node <node2> -ifgrp <ifgrp_name> -port <port_name>
----
+
[source, cli]
----
ifgrp add-port -node <node2> -ifgrp <ifgrp_name> -port <port_name>
----




[[migrate_node1_nod4]]
. Migrieren Sie die Datenaggregate auf Node 1 zu node 4:
+
[source, cli]
----
storage aggregate relocation start -aggregate-list <aggregate_list_name> -node <node1> -destination <node4> -ndo-controller-upgrade true -override-destination-checks true
----
. Datenaggregatstatus anzeigen:
+
[source, cli]
----
storage aggregate show
----
. Migrieren Sie das Epsilon, indem Sie es von Knoten1 entfernen und zu Knoten4 verschieben.
+
.. Epsilon aus Knoten 1 entfernen:
+
[source, cli]
----
cluster modify -epsilon false -node <node1>
----
.. Epsilon auf node4 verschieben:
+
[source, cli]
----
cluster modify -epsilon true -node <node4>
----


. Zeigen Sie den Clusterstatus an, um die Epsilon-Änderung zu überprüfen:
+
[source, cli]
----
cluster show
----
. Alle Datennetzwerk-LIFs anzeigen:
+
[source, cli]
----
network interface show -role data
----
. Migrieren Sie alle Daten-LIFs auf node4:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node4> -destination-port <port_name>
----
. Status aller Daten-LIFs im Cluster anzeigen:
+
[source, cli]
----
network interface show -role data
----
. Wenn LIFs ausgefallen sind, setzen Sie ihren Verwaltungsstatus auf `up` indem Sie für jedes LIF einmal den folgenden Befehl eingeben:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin up
----
. Migration der Cluster-Management-LIF:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <cluster_mgmt_lif> -destination-node <node4> -destination-port <port_name>
----
. Status der Cluster-Management-LIF anzeigen:
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. Stopp-Nr. 1:
+
[source, cli]
----
halt -node <node1> -inhibit-takeover true -ignore-quorum-warnings true
----


.Was kommt als Nächstes?
link:convert-fas2820-node1-drive-shelf.html["Konvertieren Sie Knoten 1 in ein Laufwerk-Shelf und verbinden Sie es mit Knoten 3"]
