---
permalink: upgrade/reassign-fas2820-node2-drives.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node2, node4, reassign, drives 
summary: Nachdem Sie FAS2820 Knoten2 in ein DS212C-Laufwerksregal konvertiert und eine Verbindung mit Knoten4 hergestellt haben, weisen Sie die Laufwerke, die zuvor zu Knoten2 gehörten, Knoten4 neu zu. 
---
= Laufwerke von FAS2820 -Knoten2 zu Knoten4 neu zuweisen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Weisen Sie die Laufwerke, die zuvor zu FAS2820 Knoten2 gehörten, Knoten4 neu zu.

.Bevor Sie beginnen
Vergewissern Sie sich, dass sich an der LOADER-Eingabeaufforderung sowohl Knoten 3 als auch knoten 4 im Standby-Modus befinden.

.Über diese Aufgabe
Führen Sie die folgenden Schritte auf Knoten4 aus.

.Schritte
. Booten sie node 4 an der LOADER-Eingabeaufforderung im Wartungsmodus:
+
[source, cli]
----
boot_ontap maint
----
+
Die Eingabeaufforderung „Wartungsmodus“ wird angezeigt.

. Alle angeschlossenen Laufwerke anzeigen:
+
[source, cli]
----
disk show -v
----
. Notieren Sie den lokalen System-ID-Wert; dies ist die System-ID von node4. Notieren Sie auch die System-IDs von node1 und node2 aus der Spalte „EIGENTÜMER“.
. Weisen Sie alle Laufwerke von Knoten2 zu Knoten4 neu zu.
+
[role="tabbed-block"]
====
.Wenn Sie ganze Festplatten verwenden
--
Führen Sie den folgenden Befehl aus:

[source, cli]
----
disk reassign -s <node2_system_ID> -d <node4_system_ID>
----
--
.Wenn Sie partitionierte Festplatten verwenden
--
Führen Sie den folgenden Befehl aus:

[source, cli]
----
disk reassign -s <node2_system_ID> -d <node4_system_ID> -p <node1_system_ID>
----
--
====
. Überprüfen Sie, ob alle neu zugewiesenen Laufwerke der neuen System-ID angezeigt werden:
+
[source, cli]
----
disk show -s <node4_System_ID>
----
+

CAUTION: Wenn die Laufwerke nicht angezeigt werden können, *stoppen* Sie und wenden Sie sich an den technischen Support, um Hilfe zu erhalten.

. Überprüfen Sie, ob das Root-Aggregat von node2 in der Ausgabe gemeldet wird und das Aggregat online ist:
+
[source, cli]
----
aggr status
----
. Beenden des Wartungsmodus:
+
[source, cli]
----
halt
----


.Was kommt als Nächstes?
link:migrate-fas2820-aggregates-epsilon-lifs.html["Migrieren Sie Datenaggregate, Epsilon und LIFs auf Node 1 nach node 4"]
