---
permalink: upgrade/reassign-node2-drives.html 
sidebar: sidebar 
keywords: fas2820, aff a150, aff a220, ndu, nondisruptive, upgrade, node2, node4, reassign, drives 
summary: Nachdem Sie node2 in ein Laufwerksgehäuse umgewandelt und mit node4 verbunden haben, weisen Sie die Laufwerke, die zuvor zu node2 gehörten, node4 neu zu. 
---
= Weisen Sie Laufwerke von Knoten 2 zu knoten 4 neu zu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Weisen Sie die Laufwerke, die zuvor zu node2 gehörten, node4 zu.

.Bevor Sie beginnen
Vergewissern Sie sich, dass sich an der LOADER-Eingabeaufforderung sowohl Knoten 3 als auch knoten 4 im Standby-Modus befinden.

.Schritte
Führen Sie diese Schritte auf node4 durch.

. Booten sie node 4 an der LOADER-Eingabeaufforderung im Wartungsmodus:
+
[source, cli]
----
boot_ontap maint
----
+
Die Eingabeaufforderung „Wartungsmodus“ wird angezeigt.

. Alle angeschlossenen Laufwerke anzeigen:
+
[source, cli]
----
disk show -v
----
. Notieren Sie den lokalen System-ID-Wert; dies ist die System-ID von node4. Notieren Sie auch die System-IDs von node1 und node2 aus der Spalte „EIGENTÜMER“.
. Weisen Sie alle Laufwerke von Knoten2 zu Knoten4 neu zu.
+
[role="tabbed-block"]
====
.Wenn Sie ganze Festplatten verwenden
--
Führen Sie den folgenden Befehl aus:

[source, cli]
----
disk reassign -s <node2_system_ID> -d <node4_system_ID>
----
--
.Wenn Sie partitionierte Festplatten verwenden
--
Führen Sie den folgenden Befehl aus:

[source, cli]
----
disk reassign -s <node2_system_ID> -d <node4_system_ID> -p <node1_system_ID>
----
--
====
. Überprüfen Sie, ob alle neu zugewiesenen Laufwerke der neuen System-ID angezeigt werden:
+
[source, cli]
----
disk show -s <node4_System_ID>
----
+

CAUTION: Wenn die Laufwerke nicht angezeigt werden können, *stoppen* Sie und wenden Sie sich an den technischen Support, um Hilfe zu erhalten.

. Überprüfen Sie, ob das Root-Aggregat von node2 in der Ausgabe gemeldet wird und das Aggregat online ist:
+
[source, cli]
----
aggr status
----
. Beenden des Wartungsmodus:
+
[source, cli]
----
halt
----


.Was kommt als Nächstes?
link:migrate-aggregates-epsilon-lifs.html["Migrieren Sie Datenaggregate, Epsilon und LIFs auf Node 1 nach node 4"]
