---
permalink: upgrade/reassign-node1-drives.html 
sidebar: sidebar 
keywords: fas2820, aff a150, aff a220, ndu, nondisruptive, upgrade, node3, node1, reassign, drives 
summary: Nachdem Sie node1 in ein Laufwerksgehäuse umgewandelt und mit node3 verbunden haben, weisen Sie die Laufwerke, die zuvor zu node1 gehörten, node3 neu zu. 
---
= Neuzuweisung von Laufwerken von Knoten 1 zu Knoten 3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Weisen Sie die zuvor node1 zugewiesenen Laufwerke node3 zu.

.Schritte
Führen Sie diese Schritte auf node3 durch.

. Booten Sie an der EINGABEAUFFORDERUNG DES LOADERS Node 3 im Wartungsmodus:
+
[source, cli]
----
boot_ontap maint
----
+
Die Eingabeaufforderung „Wartungsmodus“ wird angezeigt.

. Alle angeschlossenen Laufwerke anzeigen:
+
[source, cli]
----
disk show -v
----
. Notieren Sie den Wert der lokalen System-ID. Dies ist die System-ID von Knoten3.  Notieren Sie sich außerdem die System-IDs von Knoten1 und Knoten4 aus der Spalte „EIGENTÜMER“.
. Neuzuweisung aller Laufwerke von Knoten 1 zu Knoten 3:
+
[role="tabbed-block"]
====
.Wenn Sie ganze Festplatten verwenden
--
Führen Sie den folgenden Befehl aus:

[source, cli]
----
disk reassign -s <node1_system_ID> -d <node3_system_ID>
----
--
.Wenn Sie partitionierte Festplatten verwenden
--
Führen Sie den folgenden Befehl aus:

[source, cli]
----
disk reassign -s <node1_system_ID> -d <node3_system_ID> -p <node4_system_ID>
----
--
====
. Überprüfen Sie, ob alle neu zugewiesenen Laufwerke der neuen System-ID angezeigt werden:
+
[source, cli]
----
disk show -s <node3_system_ID>
----
+

CAUTION: Wenn die Laufwerke nicht angezeigt werden können, *stoppen* Sie und wenden Sie sich an den technischen Support, um Hilfe zu erhalten.

. Wartungsmodus Beenden:
+
[source, cli]
----
halt
----


.Was kommt als Nächstes?
link:migrate-node4-lifs-aggregates.html["Migrieren Sie LIFs und Datenaggregate auf node 4 auf Node 3"]
