---
permalink: upgrade/upgrade_reassign_drives_node1_to_node3.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node3, node1, reassign, drives 
summary: Verbinden Sie Knoten 1 physisch mit Knoten 3, bevor Sie Laufwerke von Knoten 1 zu Knoten 3 neu zuweisen 
---
= Neuzuweisung von Laufwerken von Knoten 1 zu Knoten 3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Konvertierung von AFF A250 node1 in ein NS224 Laufwerk-Shelf und der Verbindung zu AFF A400 node3 müssen Sie die Laufwerke, die zuvor zu node1 gehörte, zu node3 neu zuweisen.

.Schritte
. Booten Sie an der EINGABEAUFFORDERUNG DES LOADERS Node 3 im Wartungsmodus:
+
`boot_ontap maint`

. Zeigen Sie den Status der 100-GbE-Schnittstellen an:
+
`storage port show`

. Legen Sie 100-GbE-Schnittstellen auf Storage-Ports fest:
+
`storage port modify -p e0c -m storage`

+
`storage port modify -p e0d -m storage`

. Überprüfen Sie die Modusänderungen an den 100-GbE-Schnittstellen:
+
`storage port show`

+
Die Ausgabe wie im folgenden Beispiel sollte angezeigt werden:

+
[listing]
----
*> storage port modify -p e0c -m storage
Nov 10 16:27:23 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0c to storage mode.

Nov 10 16:27:29 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8885.

*> storage port modify -p e0d -m storage
Nov 10 16:27:34 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0d to storage mode.

Nov 10 16:27:38 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8886.

*> storage port show
Port Type Mode    Speed(Gb/s) State    Status  VLAN ID
---- ---- ------- ----------- -------- ------- -------
e0c  ENET storage 100 Gb/s    enabled  online  30
e0d  ENET storage 100 Gb/s    enabled  offline 30
----
. Alle angeschlossenen Laufwerke anzeigen:
+
`disk show -v`

. Notieren Sie den lokalen System-ID-Wert; dies ist die System-ID von node3. Notieren Sie auch die System-IDs von node1 und node2 aus der Spalte „EIGENTÜMER“.
. Neuzuweisung aller Laufwerke von Knoten 1 zu Knoten 3:
+
`disk reassign -s _node1_system_ID_ -d _node3_system_ID_ -p _node4_system_ID_`

. Überprüfen Sie, ob alle neu zugewiesenen Laufwerke der neuen System-ID angezeigt werden:
+
`disk show -s _node3_system_ID_`

+

NOTE: Wenn Laufwerke nicht sichtbar sind, *STOP* und wenden Sie sich an den technischen Support, um Hilfe zu erhalten.

. Wartungsmodus Beenden:
+
`halt`



.Was kommt als Nächstes?
link:upgrade_migrate_lIFs_aggregates_node4_node3.html["Migrieren Sie LIFs und Datenaggregate auf node 4 auf Node 3"]
