---
permalink: upgrade/upgrade-remove-original-nodes.html 
sidebar: sidebar 
keywords: volume, move, node, remove, original, cluster, configuration, disk, initialize, remove the original nodes from the cluster 
summary: Nachdem die Volumes auf die neuen Knoten verschoben wurden, entfernen Sie die ursprünglichen Knoten aus dem Cluster. Wenn Sie einen Knoten entfernen, wird die Konfiguration des Knotens gelöscht und alle Festplatten werden initialisiert. 
---
= Entfernen Sie die ursprünglichen Knoten aus dem Cluster.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem die Volumes von den ursprünglichen Knoten auf die neuen Knoten verschoben und die Daten-LIFs verschoben oder gelöscht wurden, werden die ursprünglichen Knoten aus dem Cluster entfernt. Wenn Sie einen Knoten entfernen, wird die Konfiguration des Knotens gelöscht und alle Festplatten werden initialisiert.

.Schritte
. [[disable-ha]]Deaktiviert die Hochverfügbarkeitskonfiguration (HA) auf den ursprünglichen Knoten:
+
`storage failover modify -node <original_node_name> -enabled false`

. Zugriff auf die erweiterte Berechtigungsebene:
+
`set -privilege advanced`

. Identifizieren Sie den Knoten mit Epsilon:
+
`cluster show`

+
Im folgenden Beispiel enthält „node0“ derzeit Epsilon:

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. [[epsilon-true]]Wenn einer der ursprünglichen Knoten Epsilon enthält, verschieben Sie Epsilon auf einen Knoten, den Sie nicht aus dem Cluster entfernen:
+
.. Entferne Epsilon vom ursprünglichen Knoten:
+
`cluster modify -node <original_node_name> -epsilon false`

.. Weisen Sie Epsilon einem anderen Knoten zu:
+
`cluster modify -node <new_node_name> -epsilon true`



. Identifizieren Sie den aktuellen Masterknoten:
+
`cluster ring show`

+
Der Master-Knoten ist der Knoten, der Prozesse wie beispielsweise … enthält. `mgmt`, `vldb`, `vifmgr`, `bcomd`, Und `crs`Die

. Wenn der zu entfernende Knoten der aktuelle Masterknoten ist, muss ein im Cluster verbleibender Knoten als Masterknoten gewählt werden:
+
.. Den aktuellen Masterknoten von der Teilnahme am Cluster ausschließen:
+
`cluster modify -node <original_node_name> -eligibility false`

+
Der Knoten wird als fehlerhaft markiert, bis die Berechtigung wiederhergestellt ist. Wenn der Master-Knoten nicht mehr als Master geeignet ist, wird einer der verbleibenden Knoten vom Cluster-Quorum zum neuen Master gewählt.

+
[NOTE]
====
Wenn Sie diesen Schritt am ersten Knoten eines HA-Paares durchführen, sollten Sie nur diesen Knoten als nicht geeignet markieren. Ändern Sie den Status des HA-Partners nicht.

Wenn der Partnerknoten als neuer Master ausgewählt wird, müssen Sie überprüfen, ob er Epsilon enthält. Wenn der Partnerknoten Epsilon enthält, müssen Sie Epsilon auf einen anderen Knoten verschieben, der im Cluster verbleibt, bevor Sie ihn für ungültig erklären. Dies tun Sie, wenn Sie diese Schritte wiederholen, um den Partnerknoten zu entfernen.

====
.. Den vorherigen Masterknoten wieder für die Teilnahme am Cluster zulassen:
+
`cluster modify -node <node_name> -eligibility true`



. Melden Sie sich auf einem Knoten, der im Cluster verbleibt, an der Remote-Knotenverwaltungs-LIF oder der Clusterverwaltungs-LIF an und entfernen Sie jeden ursprünglichen Knoten aus dem Cluster (erweiterte Berechtigungsstufe):
+
Mit Knotennamen:

+
[source, cli]
----
cluster remove-node -node <original_node_name>
----
+
Mit Knoten-IP:

+
[source, cli]
----
cluster remove-node -cluster_ip <original_node_ip>
----
+
Wenn Sie einen Cluster mit gemischten Versionen haben und den letzten Knoten mit der niedrigeren Version entfernen, verwenden Sie die `-skip-last-low-version-node-check` Parameter mit diesen Befehlen.

+
Das System informiert Sie über Folgendes:

+
** Sie müssen außerdem den Failover-Partner des Knotens aus dem Cluster entfernen.
** Nachdem der Knoten entfernt wurde und bevor er wieder einem Cluster beitreten kann, müssen Sie die Bootmenüoption *(4) Konfiguration löschen und alle Datenträger initialisieren* oder die Option *(9) Erweiterte Laufwerkspartitionierung konfigurieren* verwenden, um die Konfiguration des Knotens zu löschen und alle Datenträger zu initialisieren.
+
Es wird eine Fehlermeldung generiert, wenn Bedingungen vorliegen, die vor dem Entfernen des Knotens erfüllt werden müssen. Die Meldung könnte beispielsweise darauf hinweisen, dass der Knoten über gemeinsam genutzte Ressourcen verfügt, die Sie entfernen müssen, oder dass sich der Knoten in einer Cluster-HA-Konfiguration oder einer Speicherausfallkonfiguration befindet, die Sie deaktivieren müssen.

+
Wenn der Knoten der Quorum-Master ist, verliert der Cluster kurzzeitig das Quorum und erreicht es dann wieder. Dieser Quorumverlust ist vorübergehend und hat keine Auswirkungen auf Datenoperationen.



. Wenn eine Fehlermeldung auf Fehlerbedingungen hinweist, beheben Sie diese und führen Sie den Vorgang erneut aus. `cluster remove-node` oder `cluster unjoin` Befehl.
+
Nachdem ein Knoten erfolgreich aus dem Cluster entfernt wurde, startet er automatisch neu.

. Wenn Sie den Knoten für einen anderen Zweck verwenden, löschen Sie die Knotenkonfiguration und initialisieren Sie alle Festplatten:
+
.. Drücken Sie während des Bootvorgangs Strg+C, um das Bootmenü anzuzeigen, wenn Sie dazu aufgefordert werden.
.. Wählen Sie im Bootmenü die Option *(4) Konfiguration bereinigen und alle Festplatten initialisieren*.


. [[return-admin]]Zurück zur Administratorberechtigungsstufe auf einem der neuen Knoten im Cluster:
+
[source, cli]
----
set -privilege admin
----
. Schritte wiederholen <<disable-ha,1>> Zu <<return-admin,10>> um den Failover-Partner aus dem Cluster zu entfernen.
. Wenn nur noch zwei Nodes vorhanden sind, konfigurieren Sie Hochverfügbarkeit für das Cluster mit zwei Nodes:
+
`cluster ha modify -configured true`



.Was kommt als Nächstes?
link:upgrade-complete-move-volumes.html["Schließen Sie das Upgrade der Move-Volumes ab"]
