---
permalink: upgrade/upgrade_move_linux_iscsi_hosts_to_new_nodes.html 
sidebar: sidebar 
keywords: node, old, new, iscsi, host, connection, moving, move, linux, set, up, add, report, removing, remove, rescan, path 
summary: Verschieben Sie Ihre SAN-Volumes zu den neuen Knoten, indem Sie neue iSCSI-Verbindungen erstellen und die iSCSI-Pfade zu den neuen Knoten erneut scannen. 
---
= Verschieben Sie Linux-iSCSI-Hosts auf neue Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie iSCSI-SAN-Volumes auf neue Nodes verschieben können, müssen Sie neue iSCSI-Verbindungen erstellen und die iSCSI-Pfade zu den neuen Nodes erneut scannen.

Wenn Sie iSCSI-SAN-Volumes beim Upgrade durch Verschieben von Volumes nicht verschieben müssen, können Sie diesen Vorgang überspringen und mit fortfahren link:upgrade-create-aggregate-move-volumes.html["Erstellung eines Aggregats und Verschiebung von Volumes zu den neuen Nodes"].

.Über diese Aufgabe
* IPv4-Schnittstellen werden beim Einrichten der neuen iSCSI-Verbindungen erstellt.
* Die Host-Befehle und Beispiele sind spezifisch für Linux-Betriebssysteme.




== Schritt 1: Einrichtung neuer iSCSI-Verbindungen

Um die iSCSI-Verbindungen zu verschieben, richten Sie neue iSCSI-Verbindungen zu den neuen Knoten ein.

.Schritte
. Erstellen Sie iSCSI-Schnittstellen auf den neuen Knoten, und prüfen Sie die Ping-Verbindung zwischen den iSCSI-Hosts und den neuen Schnittstellen auf den neuen Knoten.
+
https://docs.netapp.com/us-en/ontap/networking/create_a_lif.html["Netzwerkschnittstellen erstellen"^]

+
Alle iSCSI-Schnittstellen der SVM sollten vom iSCSI-Host erreichbar sein.

. Identifizieren Sie auf dem iSCSI-Host die vorhandenen iSCSI-Verbindungen vom Host zum alten Knoten:
+
[source, cli]
----
iscsiadm -m session
----
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m session
tcp: [1] 10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
tcp: [2] 10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
----
. Überprüfen Sie auf dem neuen Node die Verbindungen vom neuen Node:
+
[source, cli]
----
iscsi session show -vserver <svm-name>
----
+
[listing]
----
node_A_1-new::*> iscsi session show -vserver vsa_1
 Tpgroup Initiator Initiator
Vserver Name TSIH Name ISID Alias
--------- ------- ---- ------------------------ --------- ---------------------
vsa_1 iscsi_lf__n1_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:01 scspr1789621001.gdl.englab.netapp.com
vsa_1 iscsi_lf__n2_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:02 scspr1789621001.gdl.englab.netapp.com
2 entries were displayed.
----
. Führen Sie auf dem neuen Node die iSCSI-Schnittstellen in ONTAP für die SVM auf, die die Schnittstellen enthält:
+
[source, cli]
----
iscsi interface show -vserver <svm-name>
----
+
[listing]
----
sti8200mcchtp001htp_siteA::*> iscsi interface show -vserver vsa_1
 Logical Status Curr Curr
Vserver Interface  TPGT Admin/Oper IP Address Node Port Enabled
------- ---------- ---- ---------- --------------- ----------- ---- -------
vsa_1 iscsi_lf__n1_p1_ 1156 up/up 10.230.68.236 sti8200mcc-htp-001 e0g true
vsa_1 iscsi_lf__n1_p2_ 1157 up/up fd20:8b1e:b255:805e::78c9 sti8200mcc-htp-001 e0h true
vsa_1 iscsi_lf__n2_p1_ 1158 up/up 10.230.68.237 sti8200mcc-htp-002 e0g true
vsa_1 iscsi_lf__n2_p2_ 1159 up/up fd20:8b1e:b255:805e::78ca sti8200mcc-htp-002 e0h true
vsa_1 iscsi_lf__n3_p1_ 1183 up/up 10.226.43.134 sti8200mccip-htp-005 e0c true
vsa_1 iscsi_lf__n4_p1_ 1188 up/up 10.226.43.142 sti8200mccip-htp-006 e0c true
6 entries were displayed.
----
. Führen Sie auf dem iSCSI-Host die Ermittlung auf einer der iSCSI-IP-Adressen auf der SVM aus, um die neuen Ziele zu ermitteln:
+
[source, cli]
----
iscsiadm -m discovery -t sendtargets -p iscsi-ip-address
----
+
Die Erkennung kann mit jeder beliebigen IP-Adresse der SVM ausgeführt werden, einschließlich nicht-iSCSI-Schnittstellen.

+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m discovery -t sendtargets -p 10.230.68.236:3260
10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.226.43.142:3260,1188 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.226.43.134:3260,1183 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
----
. Melden Sie sich auf dem iSCSI-Host bei allen erkannten Adressen an:
+
[source, cli]
----
iscsiadm -m node -L all -T node-address -p portal-address -l
----
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m node -L all -T iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 -p 10.230.68.236:3260 -l
Logging in to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.142,3260] (multiple)
Logging in to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.134,3260] (multiple)
Login to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.142,3260] successful.
Login to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.134,3260] successful.
----
. Überprüfen Sie auf dem iSCSI-Host die Anmeldung und Verbindungen:
+
[source, cli]
----
iscsiadm -m session
----
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m session
tcp: [1] 10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
tcp: [2] 10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
tcp: [3] 10.226.43.142:3260,1188 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
----
. Überprüfen Sie auf dem neuen Node die Anmeldung und die Verbindung mit dem Host:
+
[source, cli]
----
iscsi initiator show -vserver <svm-name>
----
+
[listing]
----
sti8200mcchtp001htp_siteA::*> iscsi initiator show -vserver vsa_1
 Tpgroup Initiator
Vserver Name             TSIH Name                  ISID              Igroup Name
------- --------         ---- --------------------- ----------------- -----------------
vsa_1 iscsi_lf__n1_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:01 igroup_linux
vsa_1 iscsi_lf__n2_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:02 igroup_linux
vsa_1 iscsi_lf__n3_p1_ 1 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:04 igroup_linux
vsa_1 iscsi_lf__n4_p1_ 1 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:03 igroup_linux
4 entries were displayed.
----


.Ergebnis
Am Ende dieser Aufgabe kann der Host alle iSCSI-Schnittstellen sehen (auf den alten und neuen Knoten) und ist bei allen diesen Schnittstellen angemeldet.

LUNs und Volumes werden weiterhin physisch auf den alten Knoten gehostet. Da LUNs nur für die alten Node-Schnittstellen gemeldet werden, zeigt der Host nur Pfade über den alten Node an. Um dies zu sehen, führen Sie den aus `sanlun lun show -p` Und `multipath -ll -d` Befehle auf dem Host und überprüfen Sie die Befehlsausgaben.

[listing]
----
[root@scspr1789621001 ~]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ -------------------
host vserver
path path /dev/ host vserver
state     type       node    adapter      LIF
--------- ---------- ------- ------------ -------------------
up        primary    sdk     host3        iscsi_lf__n2_p1_
up        secondary  sdh     host2        iscsi_lf__n1_p1_
[root@scspr1789621001 ~]# multipath -ll -d
3600a098038304646513f4f674e52774b dm-5 NETAPP ,LUN C-Mode
size=2.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| `- 3:0:0:4 sdk 8:160 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
 `- 2:0:0:4 sdh 8:112 active ready running
----


== Schritt 2: Fügen Sie die neuen Knoten als Reporting-Knoten

Nachdem Sie die Verbindungen zu den neuen Nodes eingerichtet haben, fügen Sie die neuen Nodes als Reporting-Nodes hinzu.

.Schritte
. Führen Sie auf dem neuen Node die Reporting-Nodes für LUNs auf der SVM auf:
+
[source, cli]
----
lun mapping show -vserver <svm-name> -fields reporting-nodes -ostype linux
----
+
Die folgenden Nodes für die Berichterstellung sind lokale Nodes, da sich LUNs physisch auf den alten Knoten Node_A_1-old und Node_A_2-old befinden.

+
[listing]
----
node_A_1-new::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux
vserver path                         igroup       reporting-nodes
------- ---------------------------- ------------ ---------------------------
vsa_1   /vol/vsa_1_vol1/lun_linux_2  igroup_linux node_A_1-old,node_A_2-old
.
.
.
vsa_1   /vol/vsa_1_vol9/lun_linux_19 igroup_linux node_A_1-old,node_A_2-old
12 entries were displayed.
----
. Fügen Sie auf dem neuen Node Reporting-Nodes hinzu:
+
[source, cli]
----
lun mapping add-reporting-nodes -vserver <svm-name> -path /vol/vsa_1_vol*/lun_linux_* -nodes node1,node2 -igroup <igroup_name>
----
+
[listing]
----
node_A_1-new::*> lun mapping add-reporting-nodes -vserver vsa_1 -path /vol/vsa_1_vol*/lun_linux_* -nodes node_A_1-new,node_A_2-new
-igroup igroup_linux
12 entries were acted on.
----
. Überprüfen Sie auf dem neuen Node, ob die neu hinzugefügten Nodes vorhanden sind:
+
[source, cli]
----
lun mapping show -vserver <svm-name> -fields reporting-nodes -ostype linux vserver path igroup reporting-nodes
----
+
[listing]
----
node_A_1-new::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux vserver path igroup reporting-nodes
------- --------------------------- ------------ -------------------------------------------------------------------------------
vsa_1 /vol/vsa_1_vol1/lun_linux_2 igroup_linux node_A_1-old,node_A_2-old,node_A_1-new,node_A_2-new
vsa_1 /vol/vsa_1_vol1/lun_linux_3 igroup_linux node_A_1-old,node_A_2-old,node_A_1-new,node_A_2-new
.
.
.
12 entries were displayed.
----
. Der `sg3-utils` Das Paket muss auf dem Linux-Host installiert sein. Dies verhindert ein `rescan-scsi-bus.sh utility not found` Fehler beim erneuten Scannen des Linux-Hosts für die neu zugeordneten LUNs mithilfe des `rescan-scsi-bus` Befehl.
+
Überprüfen Sie auf dem Host, ob der `sg3-utils` Paket ist installiert:

+
--
** Für eine Debian-basierte Distribution:
+
[source, cli]
----
dpkg -l | grep sg3-utils
----
** Für eine Red hat basierte Distribution:
+
[source, cli]
----
rpm -qa | grep sg3-utils
----


--
+
Installieren Sie bei Bedarf den `sg3-utils` Paket auf dem Linux-Host:

+
[source, cli]
----
sudo apt-get install sg3-utils
----
. Scannen Sie auf dem Host den SCSI-Bus erneut auf dem Host, und ermitteln Sie die neu hinzugefügten Pfade:
+
[source, cli]
----
/usr/bin/rescan-scsi-bus.sh -a
----
+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -a
Scanning SCSI subsystem for new devices
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
 Scanning for device 2 0 0 0 ...
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
0 device(s) removed.
----
. Führen Sie auf dem iSCSI-Host die neu hinzugefügten Pfade auf:
+
[source, cli]
----
sanlun lun show -p
----
+
Für jede LUN werden vier Pfade angezeigt.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
------- ---------- ------- ----------- ---------------------
host vserver
path path /dev/ host vserver
state   type       node    adapter     LIF
------  ---------- ------- ----------- ---------------------
up      primary    sdk      host3      iscsi_lf__n2_p1_
up      secondary  sdh     host2       iscsi_lf__n1_p1_
up      secondary  sdag    host4       iscsi_lf__n4_p1_
up      secondary  sdah    host5       iscsi_lf__n3_p1_
----
. Verschieben Sie auf dem neuen Node das Volume/die Volumes, die LUNs enthalten, von den alten Nodes auf die neuen Nodes.
+
[listing]
----
node_A_1-new::*> vol move start -vserver vsa_1 -volume vsa_1_vol1 -destination-aggregate sti8200mccip_htp_005_aggr1
[Job 1877] Job is queued: Move "vsa_1_vol1" in Vserver "vsa_1" to aggregate "sti8200mccip_htp_005_aggr1". Use the "volume move show -vserver
vsa_1 -volume vsa_1_vol1" command to view the status of this operation.
node_A_1-new::*> vol move show
Vserver  Volume      State       Move       Phase            Percent-Complete  Time-To-Complete
-------- ----------  --------    ---------- ---------------- ----------------  ----------------
vsa_1    vsa_1_vol1  healthy                initializing     -                 -
----
. Überprüfen Sie nach Abschluss der Verschiebung des Volume zu den neuen Nodes, ob das Volume online ist:
+
[source, cli]
----
volume show -state
----
. Die iSCSI-Schnittstellen auf den neuen Nodes, auf denen sich die LUN jetzt befindet, werden als primäre Pfade aktualisiert. Wenn der primäre Pfad nach der Volume-Verschiebung nicht aktualisiert wird, führen Sie aus `/usr/bin/rescan-scsi-bus.sh -a` Und `multipath -v3` Auf dem Host oder warten Sie einfach, bis der Multipath-Rescanning stattfindet.
+
Im folgenden Beispiel ist der primäre Pfad eine LIF auf dem neuen Node.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ -----------------------
host vserver
path path /dev/ host vserver
state     type       node    adapter      LIF
--------- ---------- ------- ------------ ------------------------
up        primary    sdag    host4        iscsi_lf__n4_p1_
up        secondary  sdk     host3        iscsi_lf__n2_p1_
up        secondary  sdh     host2        iscsi_lf__n1_p1_
up        secondary  sdah    host5        iscsi_lf__n3_p1_
----




== Schritt 3: Entfernen Sie Reporting Nodes und scannen Sie Pfade neu

Sie müssen die Berichtsknoten entfernen und die Pfade erneut scannen.

.Schritte
. Entfernen Sie auf dem neuen Knoten Remote-Reporting-Knoten (die neuen Knoten) für die Linux-LUNs:
+
[source, cli]
----
lun mapping remove-reporting-nodes -vserver <svm-name> -path * -igroup <igroup_name> -remote-nodes true
----
+
In diesem Fall sind die Remote-Knoten alte Knoten.

+
[listing]
----
node_A_1-new::*> lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true
12 entries were acted on.
----
. Überprüfen Sie auf dem neuen Node die Reporting-Nodes für die LUNs:
+
[source, cli]
----
lun mapping show -vserver <svm-name> -fields reporting-nodes -ostype linux
----
+
[listing]
----
node_A_1-new::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux
vserver  path                         igroup        reporting-nodes
-------  ---------------------------  ------------  -------------------------
vsa_1    /vol/vsa_1_vol1/lun_linux_2  igroup_linux  node_A_1-new,node_A_2-new
vsa_1    /vol/vsa_1_vol1/lun_linux_3  igroup_linux  node_A_1-new,node_A_2-new
vsa_1    /vol/vsa_1_vol2/lun_linux_4  group_linux   node_A_1-new,node_A_2-new
.
.
.
12 entries were displayed.
----
. Der `sg3-utils` Das Paket muss auf dem Linux-Host installiert sein. Dies verhindert ein `rescan-scsi-bus.sh utility not found` Fehler beim erneuten Scannen des Linux-Hosts für die neu zugeordneten LUNs mithilfe des `rescan-scsi-bus` Befehl.
+
Überprüfen Sie auf dem Host, ob der `sg3-utils` Paket ist installiert:

+
--
** Für eine Debian-basierte Distribution:
+
[source, cli]
----
dpkg -l | grep sg3-utils
----
** Für eine Red hat basierte Distribution:
+
[source, cli]
----
rpm -qa | grep sg3-utils
----


--
+
Installieren Sie bei Bedarf den `sg3-utils` Paket auf dem Linux-Host:

+
[source, cli]
----
sudo apt-get install sg3-utils
----
. Scannen Sie auf dem iSCSI-Host den SCSI-Bus erneut:
+
[source, cli]
----
/usr/bin/rescan-scsi-bus.sh -r
----
+
Die Pfade, die entfernt werden, sind die Pfade von den alten Knoten.

+
[listing]
----
[root@scspr1789621001 ~]# /usr/bin/rescan-scsi-bus.sh -r
Syncing file systems
Scanning SCSI subsystem for new devices and remove devices that have disappeared
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
sg0 changed: LU not available (PQual 1)
REM: Host: scsi2 Channel: 00 Id: 00 Lun: 00
DEL: Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
sg2 changed: LU not available (PQual 1)
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
24 device(s) removed.
 [2:0:0:0]
 [2:0:0:1]
.
.
.
----
. Überprüfen Sie auf dem iSCSI-Host, ob nur Pfade von den neuen Nodes sichtbar sind:
+
[source, cli]
----
sanlun lun show -p
----
+
[source, cli]
----
multipath -ll -d
----

