---
permalink: upgrade/upgrade-decide-to-use-this-guide.html 
sidebar: sidebar 
keywords:  
summary: Dieser Inhalt beschreibt, wie Sie Controller Hardware eines AFF Systems oder ein FAS System in einem Cluster durch das Verschieben von Storage oder Volumes aktualisieren. 
---
= Entscheiden Sie, ob Sie ein Upgrade durch Verschieben von Volumes oder Storage durchführen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dieser Inhalt beschreibt, wie die Controller-Hardware eines AFF, FAS oder ASA Systems in einem Cluster durch das Verschieben von Storage oder Volumes aktualisiert wird.

Gehen Sie folgendermaßen vor, wenn Sie die Controller-Hardware in den folgenden Situationen aktualisieren möchten:

[NOTE]
====
* ASA-Upgrades auf ein ASA r2-Ersatzsystem werden nicht unterstützt. Informationen zur Migration von Daten von einem ASA auf ein ASA r2-System finden Sie unter link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html["Aktivieren Sie den Datenzugriff von SAN-Hosts auf Ihr ASA r2 Storage-System"^].
* Bei einem Upgrade auf ein in ONTAP 9.15.1 oder höher eingeführtes System konvertiert ONTAP die Storage-Effizienz vorhandener Volumes und wendet die neuen Storage-Effizienzfunktionen an, die die Hardware-Offload-Funktion nutzen. Dies ist ein automatischer Hintergrundprozess, ohne sichtbare Auswirkungen auf die Leistung des Systems.
+
** Für AFF A20, AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60 und AFF C80 konvertiert ONTAP die Storage-Effizienz aller vorhandenen Thin Provisioning Volumes, auch wenn diese keine Storage-Effizienz nutzen.
** Bei einem FAS70 und FAS90 System konvertiert ONTAP nur die Storage-Effizienz vorhandener Thin Provisioning Volumes, deren Storage-Effizienz vor dem Upgrade aktiviert wurde.
+
link:https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["Erfahren Sie mehr über Storage-Effizienz"^].



* Die Hardware-Upgrade-Verfahren wurden in ONTAP 9.8 mit der Einführung der automatischen Port-Platzierung vereinfacht.


====
* Ihre ursprünglichen und neuen Nodes sind kompatibel und werden unterstützt.
* Auf den ursprünglichen und den neuen Nodes wird ONTAP 9.0 oder höher ausgeführt. NetApp empfiehlt, wenn möglich, auf den ursprünglichen und neuen Nodes dieselbe ONTAP-Version zu verwenden.
+
Wenn Ihr Controller-Upgrade gemischte ONTAP-Versionen umfasst, finden Sie weitere Informationen unter https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html["ONTAP Cluster mit gemischten Versionen"^] Finden Sie weitere Informationen.

* Auf den neuen Nodes werden die IP-Adressen, Netzwerkmasken und Gateways der ursprünglichen Nodes erneut verwendet.
* Sie planen ein Upgrade der Controller Hardware durch Verschieben von Storage oder Volumes.
* Bei einem Upgrade des Storage werden Sie darauf vorbereitet, einen störenden Vorgang durchzuführen.
+
Ein Upgrade durch Verschiebung von Volumes ist unterbrechungsfrei.

* Ein Node eines unterstützten Modells soll in ein Festplatten-Shelf konvertiert und anschließend mit den neuen Nodes hinzugefügt werden.


Informationen zum Aktualisieren einer MetroCluster-Konfiguration finden Sie unter https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["Aktualisieren, Aktualisieren oder erweitern der MetroCluster Konfiguration"^].

.Verwandte Informationen
* link:upgrade-considerations.html["Überlegungen für ein Upgrade der Controller-Hardware"]
* link:../choose_controller_upgrade_procedure.html["Wählen Sie Methoden zum Upgrade der Controller-Hardware"]
* https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html["Hier finden Sie Verfahren für MetroCluster-Wartungsarbeiten"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]

