---
permalink: upgrade/upgrade_reassign_drives_node2_to_node4.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node2, node4, reassign, drives 
summary: Verbinden Sie Knoten 2 physisch mit knoten 4, bevor Sie Laufwerke von Knoten 2 zu knoten 4 neu zuweisen. 
---
= Weisen Sie Laufwerke von Knoten 2 zu knoten 4 neu zu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Konvertieren von AFF A250 Knoten 2 in ein NS224 Laufwerk-Shelf und Anschluss an AFF A400 knoten 4, müssen Sie die Laufwerke, die zuvor gehörte zu Knoten 2 zu Knoten 4 neu zuweisen.

.Bevor Sie beginnen
Vergewissern Sie sich, dass sich an der LOADER-Eingabeaufforderung sowohl Knoten 3 als auch knoten 4 im Standby-Modus befinden.

.Über diese Aufgabe
Sie führen die folgenden Schritte auf knoten 4 aus.

.Schritte
. Booten sie node 4 an der LOADER-Eingabeaufforderung im Wartungsmodus:
+
`boot_ontap maint`

. Zeigen Sie den Status der 100-GbE-Schnittstellen an:
+
`storage port show`

. Legen Sie 100-GbE-Schnittstellen auf Storage-Ports fest:
+
`storage port modify -p e0c -m storage`

+
`storage port modify -p e0d -m storage`

. Überprüfen Sie die Modusänderungen an den 100-GbE-Schnittstellen:
+
`storage port show`

+
Die Ausgabe wie im folgenden Beispiel sollte angezeigt werden:

+
[listing]
----
*> storage port modify -p e0c -m storage
Nov 10 16:27:23 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0c to storage mode.

Nov 10 16:27:29 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8885.

*> storage port modify -p e0d -m storage
Nov 10 16:27:34 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0d to storage mode.

Nov 10 16:27:38 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8886.

*> storage port show
Port Type Mode    Speed(Gb/s) State    Status  VLAN ID
---- ---- ------- ----------- -------- ------- -------
e0c  ENET storage 100 Gb/s    enabled  online  30
e0d  ENET storage 100 Gb/s    enabled  offline 30
----
. Alle angeschlossenen Laufwerke anzeigen:
+
`disk show -v`

. Notieren Sie den lokalen System-ID-Wert; dies ist die System-ID von node4. Notieren Sie auch die System-IDs von node1 und node2 aus der Spalte „EIGENTÜMER“.
. Weisen Sie alle Laufwerke von Knoten 2 zu knoten 4 neu zu:
+
`disk reassign -s _node2_system_ID_ -d _node4_system_ID_ -p _node1_system_ID_`

. Überprüfen Sie, ob alle neu zugewiesenen Laufwerke der neuen System-ID angezeigt werden:
+
`disk show -s _node4_System_ID_`

+

NOTE: Wenn Laufwerke nicht sichtbar sind, *STOP* und wenden Sie sich an den technischen Support, um Hilfe zu erhalten.

. Überprüfen Sie, ob das Root-Aggregat von node2 in der Ausgabe gemeldet wird und das Aggregat online ist:
+
`aggr status`

. Beenden des Wartungsmodus:
+
`halt`



.Was kommt als Nächstes?
link:upgrade_migrate_aggregates_epsilon_lifs_node1_to_node4.html["Migrieren Sie Datenaggregate, Epsilon und LIFs auf Node 1 nach node 4"]
