---
permalink: upgrade/upgrade-attach-shelves-reassign-disks.html 
sidebar: sidebar 
keywords: reassign, disk, belong, node1, node2, node3, node4, node, attach, storage, shelves, shelf, reassign, ownership, attach storage shelves reassign disk ownership 
summary: Sie müssen die Festplatten, die zu node1 bzw. node2 gehörten, Node3 bzw. node4 neu zuweisen. 
---
= Verbinden Sie Storage Shelfs und weisen Sie Festplatten neu zu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Festplatten, die zu node1 bzw. node2 gehörten, Node3 bzw. node4 neu zuweisen.

.Über diese Aufgabe
Die Schritte in diesem Abschnitt werden auf node3 und node4 durchgeführt. Jeder Schritt wird zunächst auf node3 und dann auf node4 abgeschlossen, bevor zum nächsten Schritt übergegangen wird.

[[reassign-spare-disks-step1]]
.Schritte
. Die Kabel der zuvor angeschlossenen Storage Shelves werden verbunden:
+
** Die Kabel von Node1 werden mit Node3 verbunden.
** Die Kabel von Node2 werden mit Node4 verbunden.
+

CAUTION: Während dieses Upgrade-Vorgangs dürfen keine neuen Shelves an node3 oder node4 angeschlossen werden. Neue Shelves können nach Abschluss des Controller-Upgrades unterbrechungsfrei an das System angeschlossen werden.



. Stellen Sie die Stromversorgung und die physische Konnektivität der Shelfs sicher.
. Von der Eingabeaufforderung node3-LOADER, Booten in Wartungsmodus:
+
`boot_ontap maint`

. System-ID von node3 anzeigen:
+
`disk show -v`

+
[listing]
----
*> disk show -v
Local System ID: 101268854
...
----
+
Notieren Sie die System-ID von node3 zur Verwendung in <<reassign-disks-and-aggregates,Schritt 5>>.



[[reassign-disks-and-aggregates]]
. Datenträger und Datenaggregate neu zuweisen:
+
[role="tabbed-block"]
====
.Neu zuweisen an node3
--
Die Ersatzfestplatten von node1, die zum Root-Aggregat gehören, sowie alle Datenaggregate werden node3 zugewiesen:

`disk reassign -s <node1_sysid> -d <node3_sysid> -p <node4_sysid>`

** Der Parameter  `node1_sysid` ist der Wert, den Sie in _Herunterfahren der ursprünglichen Knoten_ aufgezeichnet haben, link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["Schritt 5"].
** Geben Sie den Parameter  `-p <node2_sysid>` nur an, wenn gemeinsam genutzte Datenträger vorhanden sind.


--
.Neu zuweisen an node4
--
Weisen Sie die Ersatzfestplatten von node2, die zum Root-Aggregat gehören, sowie alle Datenaggregate node4 zu:

`disk reassign -s <node2_sysid> -d <node4_sysid> -p <node3_sysid>`

** Der Parameter `node2_sysid` ist der Wert, den Sie in _Herunterfahren der ursprünglichen Knoten_ aufgezeichnet haben,link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["Schritt 5"].
** Geben Sie den Parameter  `-p <node3_sysid>` nur an, wenn gemeinsam genutzte Datenträger vorhanden sind.


--
====
+
Vom System wird eine Meldung wie die folgende angezeigt:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?y
----
. Eingabe `y` Um fortzufahren.
+
Vom System wird eine Meldung wie die folgende angezeigt:

+
[listing]
----
The system displays the following message:
Disk ownership will be updated on all disks previously belonging to Filer with sysid
<sysid>.
Do you want to continue (y/n)? y
----
. Eingabe `y` Um fortzufahren.
. Bestätigen Sie, dass das Root-Aggregat von node1 auf festgelegt ist `root` Im Feld „Optionen“ und dass andere Aggregate online sind:
+
`aggr status`

+
Sie sollten eine Ausgabe wie die folgende sehen:

+
[listing]
----
*> aggr status
           Aggr State           Status                Options
          aggr0 online          raid_dp, aggr         root
                                64-bit
----
. [[reassign-spare-disks-step9]]Wartungsmodus beenden:
+
`halt`

. Wiederholen Sie <<reassign-spare-disks-step1,Schritt 1>> bis <<reassign-spare-disks-step9,Schritt 9>> auf Knoten 4.


.Was kommt als Nächstes?
Nach dem Anbringen der Speicherregale und der Neuzuweisung der Festplattenzugehörigkeit link:upgrade-restore-root-volume-config.html["Wiederherstellung der Root-Volume-Konfiguration"].
