---
permalink: upgrade/upgrade-reset-default-configuration-node3-and-node4.html 
sidebar: sidebar 
keywords: confirm, configuration, information, boot, media, interfere, controller, upgrade, reset, node3, node4, node, default, setting, reset default configuration on the new nodes 
summary: Um sicherzustellen, dass Konfigurationsinformationen auf dem Startmedium nicht das Controller-Upgrade beeinträchtigen, müssen Sie die Konfigurationen von node3 und node4 auf die Standardeinstellungen zurücksetzen. 
---
= Setzen Sie die Standardkonfiguration auf den neuen Nodes zurück
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um sicherzustellen, dass Konfigurationsinformationen auf dem Startmedium nicht das Controller-Upgrade beeinträchtigen, müssen Sie die Konfigurationen von node3 und node4 auf die Standardeinstellungen zurücksetzen.

Sie müssen die folgenden Schritte auf node3 und node4 ausführen. Sie können die Schritte auf jedem Knoten parallel ausführen.

. Starten Sie den Knoten im Startmenü:
+
`boot_ontap menu`

. Geben Sie an der Eingabeaufforderung des Startmenüs ein `wipeconfig` Und drücken Sie dann die Eingabetaste.
+
Auf dem folgenden Bildschirm wird die Eingabeaufforderung des Startmenüs angezeigt

+
[listing]
----
Please choose one of the following:

    (1) Normal Boot.
    (2) Boot without /etc/rc.
    (3) Change password.
    (4) Clean configuration and initialize all disks.
    (5) Maintenance mode boot.
    (6) Update flash from backup config.
    (7) Install new software first.
    (8) Reboot node.
    (9) Configure Advanced Drive Partitioning.
    Selection (1-9)?  wipeconfig
----
. Eingabe `yes` Wenn eine Eingabeaufforderung wie die folgende angezeigt wird:
+
[listing]
----
This option deletes critical system configuration, including cluster membership.
Warning: do not run this option on a HA node that has been taken over.
Are you sure you want to continue?: yes
Rebooting to finish wipeconfig request.
----
+
Das System initiiert den `wipeconfig` Verfahren und starten Sie neu. Nach Abschluss des Vorgangs kehrt das System zum Startmenü zurück.

. Geben Sie im Boot-Menü 8 ein, um den Node neu zu booten, und drücken Sie während des Autobootens *Strg-C*, um den Node an der LOADER-Eingabeaufforderung zu stoppen.

