---
permalink: upgrade/upgrade-remove-original-nodes.html 
sidebar: sidebar 
keywords: volume, move, node, remove, original, cluster, configuration, disk, initialize, remove the original nodes from the cluster 
summary: Nachdem die Volumes auf die neuen Knoten verschoben wurden, entfernen Sie die ursprünglichen Knoten aus dem Cluster. Wenn Sie einen Knoten entfernen, wird die Konfiguration des Knotens gelöscht und alle Festplatten werden initialisiert. 
---
= Entfernen Sie die ursprünglichen Knoten aus dem Cluster.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem die Volumes von den ursprünglichen Knoten auf die neuen Knoten verschoben und die Daten-LIFs verschoben oder gelöscht wurden, werden die ursprünglichen Knoten aus dem Cluster entfernt. Wenn Sie einen Knoten entfernen, wird die Konfiguration des Knotens gelöscht und alle Festplatten werden initialisiert.

.Schritte
. [[disable-ha]]Deaktiviert die Hochverfügbarkeitskonfiguration (HA) auf den ursprünglichen Knoten:
+
[source, cli]
----
storage failover modify -node <original_node_name> -enabled false
----


. Ändern Sie die Berechtigungsstufe auf „advanced“:
+
[source, cli]
----
set -privilege advanced
----
. Identifizieren Sie den Knoten im Cluster, der epsilon hat:
+
[source, cli]
----
cluster show
----
+
Im folgenden Beispiel enthält „node0“ derzeit Epsilon:

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. [[epsilon-true]]Wenn der Knoten, den Sie entfernen, Epsilon enthält:
+
.. Verschiebe epsilon von dem Knoten, den du entfernst:
+
[source, cli]
----
cluster modify -node <name_of_node_to_be_removed> -epsilon false
----
.. Verschieben Sie epsilon auf einen Knoten, den Sie nicht entfernen:
+
[source, cli]
----
cluster modify -node <node_name> -epsilon true
----


. Identifizieren Sie den aktuellen Masterknoten:
+
[source, cli]
----
cluster ring show
----
+
Der Master-Knoten ist der Knoten, der Prozesse wie beispielsweise … enthält. `mgmt`, `vldb`, `vifmgr`, `bcomd`, Und `crs`Die

. Wenn der Knoten, den Sie entfernen, der aktuelle Master-Knoten ist, aktivieren Sie einen anderen Knoten im Cluster, damit er als Master-Knoten gewählt werden kann:
+
.. Den aktuellen Masterknoten von der Teilnahme am Cluster ausschließen:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility false
----
+
Der Knoten wird als fehlerhaft markiert, bis die Eignung wiederhergestellt ist. Wenn der Master-Knoten seine Eignung verliert, wird einer der verbleibenden Knoten vom Cluster-Quorum zum neuen Master gewählt.

+
[NOTE]
====
Wenn Sie diesen Schritt auf dem ersten Knoten eines HA-Paares durchführen, sollten Sie nur diesen Knoten als nicht geeignet markieren. Ändern Sie nicht den Status des HA-Partners.

Wenn der Partnerknoten als neuer Master ausgewählt wird, müssen Sie überprüfen, ob er Epsilon hält, bevor Sie ihn für nicht berechtigt erklären. Wenn der Partnerknoten Epsilon hält, müssen Sie Epsilon auf einen anderen, im Cluster verbleibenden Knoten verschieben, bevor Sie ihn für nicht berechtigt erklären. Sie tun dies, wenn Sie diese Schritte wiederholen, um den Partnerknoten zu entfernen.

====
.. Den vorherigen Masterknoten wieder für die Teilnahme am Cluster zulassen:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility true
----


. Melden Sie sich bei der Remote-Knotenverwaltungs-LIF oder der Clusterverwaltungs-LIF auf einem Knoten an, den Sie nicht aus dem Cluster entfernen.
. Entfernen Sie die Knoten aus dem Cluster:
+
|===
| Für diese ONTAP Version... | Befehl 


 a| 
ONTAP 9.3
 a| 
[source, cli]
----
cluster unjoin
----


 a| 
ONTAP 9.4 und höher
 a| 
Mit Knotennamen:

[source, cli]
----
cluster remove-node -node <node_name>
----
Mit Knoten-IP:

[source, cli]
----
cluster remove-node -cluster_ip <node_ip>
----
|===
+
Wenn Sie einen Cluster mit gemischten Versionen haben und den letzten Knoten mit der niedrigeren Version entfernen, verwenden Sie die `-skip-last-low-version-node-check` Parameter mit diesen Befehlen.

+
Das System informiert Sie über Folgendes:

+
** Sie müssen außerdem den Failover-Partner des Knotens aus dem Cluster entfernen.
** Nachdem der Knoten entfernt wurde und bevor er wieder einem Cluster beitreten kann, müssen Sie die Bootmenüoption *(4) Konfiguration löschen und alle Datenträger initialisieren* oder die Option *(9) Erweiterte Laufwerkspartitionierung konfigurieren* verwenden, um die Konfiguration des Knotens zu löschen und alle Datenträger zu initialisieren.
+
Es wird eine Fehlermeldung generiert, wenn Bedingungen vorliegen, die vor dem Entfernen des Knotens erfüllt werden müssen. Die Meldung könnte beispielsweise darauf hinweisen, dass der Knoten über gemeinsam genutzte Ressourcen verfügt, die Sie entfernen müssen, oder dass sich der Knoten in einer Cluster-HA-Konfiguration oder einer Speicherausfallkonfiguration befindet, die Sie deaktivieren müssen.

+
Wenn der Knoten der Quorum-Master ist, verliert der Cluster kurzzeitig das Quorum und stellt es anschließend wieder her. Dieser Quorumverlust ist temporär und hat keine Auswirkungen auf Datenoperationen.



. Wenn eine Fehlermeldung auf Fehlerbedingungen hinweist, beheben Sie diese und führen Sie den Vorgang erneut aus. `cluster remove-node` oder `cluster unjoin` Befehl.
+
Der Knoten startet nach erfolgreicher Entfernung aus dem Cluster automatisch neu.

. Wenn Sie den Knoten für einen anderen Zweck verwenden, löschen Sie die Knotenkonfiguration und initialisieren Sie alle Festplatten:
+
.. Drücken Sie während des Bootvorgangs Strg+C, um das Bootmenü anzuzeigen, wenn Sie dazu aufgefordert werden.
.. Wählen Sie im Bootmenü die Option *(4) Konfiguration bereinigen und alle Festplatten initialisieren*.


. [[return-admin]]Zurück zur Administrator-Berechtigungsstufe:
+
[source, cli]
----
set -privilege admin
----


. Schritte wiederholen <<disable-ha,1>> Zu <<return-admin,10>> um den Failover-Partner aus dem Cluster zu entfernen.
. Wenn nur noch zwei Nodes vorhanden sind, konfigurieren Sie Hochverfügbarkeit für das Cluster mit zwei Nodes:
+
[source, cli]
----
cluster ha modify -configured true
----


.Was kommt als Nächstes?
link:upgrade-complete-move-volumes.html["Schließen Sie das Upgrade der Move-Volumes ab"]
