---
permalink: upgrade/upgrade-move-lifs-to-new-nodes.html 
sidebar: sidebar 
keywords: move, volume, original, node, migrate, non-san, lif, cluster-management, move non-san data lifs and cluster management lifs to the new nodeas 
summary: Nachdem Sie die Volumes von den ursprünglichen Nodes verschoben haben, müssen Sie die logischen Datenschnittstellen und Cluster-Management-LIFs von den ursprünglichen Nodes auf die neuen Nodes migrieren. 
---
= Verschieben Sie nicht-SAN-Daten-LIFs und Cluster-Management-LIFs auf die neuen Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die Volumes von den ursprünglichen Nodes verschoben haben, müssen Sie die Daten-LIFs und Cluster-Management-LIFs von den ursprünglichen Nodes auf die neuen Nodes migrieren.

.Über diese Aufgabe
Sie können keine LIF migrieren, die für Copy-Offload-Vorgänge verwendet wird – mit VMware vStorage APIs for Array Integration (VAAI).

.Schritte
. Melden Sie sich mit der Cluster-Management-LIF an, und führen Sie alle LIFs auf den ursprünglichen Nodes auf (kommagetrennte Liste):
+
[source, cli]
----
network interface show -curr-node <list_of_original_node_names>
----
. Ändern Sie die Home-Ports für die nicht-SAN-Daten-LIFs von den ursprünglichen Nodes in die neuen Nodes:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-node <new_node_name> -home-port {<netport|ifgrp>}
----
. Führen Sie eine der folgenden Aktionen durch:
+
[cols="1,2"]
|===
| Migration... | Geben Sie anschließend ein... 


 a| 
Ein spezifisches LIF
 a| 
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <dest_node_name> -destination-port <dest_port_name>
----


 a| 
Alle LIFs für Daten-LIFs und Cluster-Management, die nicht im SAN sind
 a| 
[source, cli]
----
network interface migrate-all -node <node_name>
----
|===
+
Mit dem folgenden Befehl wird ein LIF namens „Datenditalif1“ auf der SVM „vs0“ zum Port „e0d“ auf „node0b“ migriert:

+
[source, cli]
----
cluster::> network interface migrate -vserver vs0 -lif datalif1 -destination-node node0b -destination-port e0d
----
+
Mit dem folgenden Befehl werden alle Daten- und Cluster-Management-LIFs vom aktuellen (lokalen) Node migriert:

+
[source, cli]
----
cluster::> network interface migrate-all -node local
----
. Überprüfen Sie, ob der Home-Node der Cluster-Management-LIF sich auf einem der ursprünglichen Nodes befindet:
+
[source, cli]
----
network interface show -lif cluster_mgmt -fields home-node
----
. Wenn sich der Home-Node der Cluster-Management-LIF auf einem der ursprünglichen Nodes befindet, führen Sie die folgenden Schritte aus:
+
.. Wechseln Sie den Home-Node der Cluster-Management-LIF auf einen der neuen Nodes:
+
[source, cli]
----
network interface modify -vserver <cluster_name> -lif cluster_mgmt -home-node <new_node_name> -home-port {<netport|ifgrp>}
----
.. Migrieren Sie die Cluster-Management-LIF auf einen der neuen Nodes:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif cluster-mgmt -destination-node <new_node_name> -destination-port {<netport|ifgrp>}
----




.Was kommt als Nächstes?
link:upgrade_move_delete_recreate_san_lifs.html["Verschieben, Löschen oder Erstellen von SAN-LIFs"]
