---
permalink: upgrade/upgrade-unjoin-original-nodes-move-volumes.html 
sidebar: sidebar 
keywords: volume, move, node, unjoin, original, cluster, configuration, disk, initialize, unjoin the original nodes from the cluster 
summary: Nachdem die Volumes zu den neuen Nodes verschoben wurden, werden die ursprünglichen Nodes aus dem Cluster entfernt. Wenn Sie einen Knoten nicht beitreten, wird die Konfiguration des Knotens gelöscht und alle Festplatten werden initialisiert. 
---
= Heben Sie die Verbindung der ursprünglichen Nodes vom Cluster auf
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem die Volumes zu den neuen Nodes verschoben wurden, werden die ursprünglichen Nodes aus dem Cluster entfernt. Wenn Sie einem Node nicht beitreten, wird die Konfiguration des Node gelöscht und alle Festplatten werden initialisiert.

.Schritte
. Deaktivieren Sie die Hochverfügbarkeitskonfiguration auf den ursprünglichen Knoten: `storage failover modify -node _original_node_name_ -enabled false`
. Zugriff auf die erweiterte Berechtigungsebene:
+
`set -privilege advanced`

. Identifizieren Sie den Knoten mit Epsilon:
+
`cluster show`

+
Im folgenden Beispiel enthält „node0“ derzeit Epsilon:

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. Wenn einer der ursprünglichen Knoten das Epsilon hält, verschieben Sie das Epsilon auf einen anderen Knoten:
+
.. Entfernen Sie das Epsilon vom ursprünglichen Knoten: +
`cluster modify -node _original_node_name_ -epsilon false`
.. Weisen Sie Epsilon einem anderen Knoten zu: +
`cluster modify -node _new_node_name_ -epsilon true`


. Von einem Node, der im Cluster verbleiben wird, werden alle ursprünglichen Nodes vom Cluster entfernt (erweiterte Berechtigungsebene):
+
`cluster unjoin -node _original_node_name_`

+
Vom System wird eine Meldung wie die folgende angezeigt:

+
[listing]
----
Warning: This command will unjoin node node_name from the cluster. You
         must unjoin the failover partner as well. After the node is
         successfully unjoined, erase its configuration and initialize all
         disks by using the "Clean configuration and initialize all disks (4)"
         option from the boot menu.
         Do you want to continue? {y|n}: y
----
. Eingabe `y` Um fortzufahren.
+
Der nicht verbundene Knoten wird automatisch neu gestartet und stoppt im Boot-Menü.

. Wählen Sie im Startmenü des nicht verbundenen Knotens die Option *(4) Clean Configuration aus und initialisieren Sie alle Festplatten*, um die Konfiguration des Knotens zu löschen und alle Festplatten zu initialisieren.
+
Vom System wird eine Meldung wie die folgende angezeigt:

+
[listing]
----
Zero disks, reset config and install a new file system?:
This will erase all the data on the disks, are you sure?:
----
. Eingabe `y` An beiden Aufforderungen.
. Wenn nur noch zwei Nodes vorhanden sind, konfigurieren Sie Hochverfügbarkeit für das Cluster mit zwei Nodes:
+
`cluster ha modify -configured true`


