---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/complete-preparation-for-upgrade.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Speicherverschlüsselung konfigurieren und verwalten, Authentifizierungsschlüssel verwalten und die SnapMirror-Beziehungen beim Upgrade auf Controller, die in ONTAP 9.15.1 oder später eingeführt wurden, mithilfe des  `system controller replace` Befehls in den Ruhezustand versetzen.' 
---
= Schließen Sie die Vorbereitung für das Upgrade ab
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über ONTAP-Lizenzierung und die Verwaltung der Speicherverschlüsselung mithilfe des Onboard Key Manager (OKM). Optional können Sie die SnapMirror-Beziehungen stilllegen.



[[learn-about-ontap-licensing]]
== Erfahren Sie mehr über ONTAP-Lizenzierung

Ausführliche Informationen zur ONTAP-Lizenzierung finden Sie unter https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["Lizenzmanagement"^].


NOTE: Wenn Sie nicht lizenzierte Funktionen auf dem Controller verwenden, kann es sein, dass Sie Ihre Lizenzvereinbarung nicht einhalten.



[[manage-storage-encryption-using-the-onboard-key-manager]]
[[manage_storage_encryption_using_okm]]
== Management der Storage-Verschlüsselung mit dem Onboard Key Manager

Verwenden Sie den Onboard Key Manager (OKM) zur Verwaltung der Verschlüsselungsschlüssel. Wenn Sie den OKM eingerichtet haben, müssen Sie die Passphrase und die Sicherungsdaten vor Beginn des Upgrades notieren.

.Schritte
. Notieren Sie die Cluster-weite Passphrase.
+
Dies ist die Passphrase, die eingegeben wurde, als das OKM mit der CLI oder REST-API konfiguriert oder aktualisiert wurde.

. Überprüfen Sie die Passphrase und den Schlüsselmanager-Vorgang:
+
`security key-manager onboard sync`

+
Geben Sie bei Aufforderung die clusterweite OKM-Passphrase ein, die Sie im vorherigen Schritt aufgezeichnet haben.

. Vergewissern Sie sich, dass cc-mode aktiviert ist, indem Sie die Ausgabe des folgenden Befehls überprüfen:
+
`security key-manager config show`

. Sichern Sie die Key-Manager-Informationen:
+
`security key-manager onboard show-backup`





[[optionally-quiesce-the-snapmirror-relationships]]
== Optional können die SnapMirror-Beziehungen angehalten werden

Bevor Sie mit dem Verfahren fortfahren, müssen Sie bestätigen, dass alle SnapMirror Beziehungen stillgelegt werden. Wenn eine SnapMirror Beziehung stillgelegt wird, bleibt es bei einem Neustart und einem Failover stillgelegt.

.Schritte
. Überprüfen Sie den SnapMirror Beziehungsstatus auf dem Ziel-Cluster:
+
`snapmirror show`

+
[NOTE]
====
Wenn der Status „Übertragen“ lautet, müssen Sie diese Transfers abbrechen:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
Der Abbruch schlägt fehl, wenn sich die SnapMirror-Beziehung nicht im Zustand „Übertragen“ befindet.

. Alle Beziehungen zwischen dem Cluster stilllegen:
+
`snapmirror quiesce -destination-vserver *`



.Was kommt als Nächstes?
Nach der Vorbereitung des Upgrades, link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["Nicht-Root-Aggregate und NAS-Daten-LIFs, die Knoten1 gehören, zu Knoten2 verschieben"].
