---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'Entscheiden Sie mithilfe von Befehlen, ob Sie Controller, die ONTAP 9.15.1 oder höher ausführen, mit ARL aktualisieren `system controller replace` .' 
---
= Entscheiden Sie, ob Sie das Verfahren zur Aggregatverschiebung verwenden
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieses Verfahren beschreibt, wie Sie die Storage Controller in einem HA-Paar mit neuen Controllern aktualisieren, während die vorhandenen Daten und Festplatten erhalten bleiben. Dies ist ein komplexes Verfahren, das nur von erfahrenen Administratoren verwendet werden sollte.

Sie können dieses Verfahren unter folgenden Umständen verwenden:

* Sie verwenden ONTAP 9.15.1 oder höher.
* Sie möchten die neuen Controller nicht als neues HA-Paar zum Cluster hinzufügen und die Daten mithilfe der Volume-Verschiebung migrieren.
* Sie sind in der Verwaltung von ONTAP erfahren und sind mit den Risiken der Arbeit im Diagnose-Privilege-Modus vertraut.



NOTE: Dabei können Sie NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) und NetApp Aggregate Encryption (NAE) verwenden.

Sie können dieses Verfahren unter folgenden Umständen nicht verwenden:

* Sie führen ein Upgrade eines AFF A800 auf einen AFF A70 oder AFF A90 durch. Informationen zum Durchführen dieses AFF A800 Upgrades finden Sie unter link:other_references.html["Quellen"] Link zu den Befehlen „System Controller ersetzen“ verwenden, um Controller-Modelle im gleichen Chassis zu aktualisieren_.
* Sie aktualisieren ein V-Series System oder ein FlexArray Virtualisierungs-Storage-System mit einem externen Array als Back-End Storage. Wenden Sie sich an den technischen Support, wenn Sie Optionen zum Upgrade eines V-Series oder FlexArray Systems benötigen.
* Sie aktualisieren eine MetroCluster FC- oder IP-Konfiguration. Informationen zum Upgrade einer MetroCluster-Konfiguration finden Sie unter, um eine link:other_references.html["Quellen"] Verknüpfung zur _MetroCluster-Upgrade- und Erweiterungsdokumentation_ zu erhalten.


[[sys_Commands_9151_supported_Systems]]die folgende Tabelle zeigt die unterstützte Modellmatrix für das Controller-Upgrade.

|===
| Vorhandene Controller | Ersatz-Controller | Unterstützt ab ONTAP... 


| FAS8200, FAS8300, FAS8700, FAS9000 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70, AFF A90, AFF A1K | 9.15.1 


| AFF A900 | AFF A90, AFF A1K | 9.15.1 
|===
[NOTE]
====
AFF A70 und AFF A90 sind integrierte Systeme mit zwei integrierten Festplatten und zwei Controllern in einem einzelnen Gehäuse.

* Wenn Sie ein Upgrade auf eine AFF A70 oder AFF A90 mit internen Laufwerken durchführen, müssen Sie vor dem Upgrade die Eigentumsrechte für diese Laufwerke entfernen. Nach Abschluss des Upgrades können Sie die internen Laufwerke den AFF A70- oder AFF A90-Nodes zuweisen und sie zur Erstellung von Datenaggregaten verwenden. Die Migration von Root- oder Datenaggregaten auf interne Laufwerke ist nicht zwingend erforderlich.
* Wenn Sie ohne interne Laufwerke ein Upgrade auf eine AFF A70 oder AFF A90 durchführen, müssen Sie nach Abschluss des Upgrades keine internen Laufwerke zuweisen.


Wenn die Kombination aus dem Controller-Upgrade-Modell nicht in der oben stehenden Tabelle aufgeführt ist, wenden Sie sich an den technischen Support.

====
Wenn Sie eine andere Methode zum Upgrade der Controller-Hardware bevorzugen und bereit sind, Volume-Verschiebungen durchzuführen, lesen Sie link:other_references.html["Quellen"] Link zu _Upgrade durch Verschieben von Volumes oder Storage_.

Siehe link:other_references.html["Quellen"] Zum Link zum Dokumentationszentrum _ONTAP 9_, wo Sie auf die Produktdokumentation zu ONTAP 9 zugreifen können.
