---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'Entscheiden Sie mithilfe von Befehlen, ob Sie Controller, die ONTAP 9.15.1 oder höher ausführen, mit ARL aktualisieren `system controller replace` .' 
---
= Entscheiden Sie, ob Sie das Verfahren zur Aggregatverschiebung verwenden
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieses Verfahren beschreibt, wie Sie die Storage Controller in einem HA-Paar mit neuen Controllern aktualisieren, während die vorhandenen Daten und Festplatten erhalten bleiben. Dies ist ein komplexes Verfahren, das nur von erfahrenen Administratoren verwendet werden sollte.



== Unterstützte Upgrades für ARL

Unter den folgenden Bedingungen können Sie ein Node-Paar aktualisieren:

* Sie verwenden ONTAP 9.15.1 oder höher.
* Sie möchten die neuen Controller nicht als neues HA-Paar zum Cluster hinzufügen und die Daten mithilfe der Volume-Verschiebung migrieren.
* Sie sind in der Verwaltung von ONTAP erfahren und sind mit den Risiken der Arbeit im Diagnose-Privilege-Modus vertraut.



NOTE: Dabei können Sie NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) und NetApp Aggregate Encryption (NAE) verwenden.

[[sys_Commands_9151_supported_Systems]]die folgende Tabelle zeigt die unterstützte Modellmatrix für das Controller-Upgrade.

|===
| Vorhandene Controller | Ersatz-Controller | Unterstützt ab ONTAP... 


| AFF A400 | AFF A50 ^2^ | 9.16.1 


| AFF A300 | AFF A50 ^2^ | 9.16.1 


| AFF A220, AFF A150 | AFF A20 ^2^ | 9.16.1 ^1^ 


| FAS8200, FAS8300, FAS8700, FAS9000 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70 ^2^ , AFF A90 ^2^, AFF A1K | 9.15.1 


| AFF A900 | AFF A90 ^2^, AFF A1K | 9.15.1 
|===
^1^ für ein Upgrade auf ein AFF A20 müssen Sie zunächst ein AFF A150 oder AFF A220 in ein DS224C Shelf konvertieren, indem Sie das Controller-Modul durch ein IOM12-Modul ersetzen. Siehe link:../upgrade/upgrade-convert-node-to-shelf.html["Konvertieren eines ursprünglichen Node in ein Laufwerk-Shelf"].

^2^ die AFF A20, AFF A50, AFF A70 und AFF A90 sind integrierte Systeme mit zwei Controllern in einer HA-Konfiguration und integrierten Festplatten in einem einzelnen Gehäuse:

* Wenn Sie ein Upgrade auf ein AFF A20, AFF A70 oder AFF A90 mit internen Laufwerken durchführen, müssen Sie die Eigentumsrechte für diese internen Laufwerke vor dem Upgrade entfernen. Nach Abschluss des Upgrades können Sie die internen Laufwerke den AFF Nodes A20, AFF A70 oder AFF A90 zuweisen und sie zur Erstellung von Datenaggregaten verwenden. Die Migration von Root- oder Datenaggregaten auf interne Laufwerke ist nicht zwingend erforderlich.
* Wenn Sie ein Upgrade auf ein AFF A20, AFF A70 oder AFF A90 ohne interne Laufwerke durchführen, müssen Sie nach Abschluss des Upgrades keine internen Laufwerke zuweisen.


Wenn die Kombination aus dem Controller-Upgrade-Modell nicht in der oben stehenden Tabelle aufgeführt ist, wenden Sie sich an den technischen Support.



== Upgrades werden für ARL nicht unterstützt

Sie können Upgrades mithilfe von ARL unter folgenden Umständen nicht durchführen:

* Sie führen eines der folgenden Upgrades durch:
+
|===
| Vorhandene Controller | Ersatz-Controller 


| AFF A250 | AFF A50, AFF A30 


| AFF A800 | AFF A70, AFF A90 


| AFF C250 | AFF C30, AFF C60 


| AFF C800 | AFF C80 
|===
+
Um ein Upgrade durchzuführen, das in der obigen Tabelle aufgeführt ist, siehe link:other_references.html["Quellen"]Link zu den Befehlen „ System Controller ersetzen “ verwenden, um Controller-Modelle im gleichen Chassis zu aktualisieren_.

* Sie aktualisieren ein V-Series System oder ein FlexArray Virtualisierungs-Storage-System mit einem externen Array als Back-End Storage. Wenden Sie sich an den technischen Support, wenn Sie Optionen zum Upgrade eines V-Series oder FlexArray Systems benötigen.
* Sie aktualisieren eine MetroCluster FC- oder IP-Konfiguration. Informationen zum Upgrade einer MetroCluster-Konfiguration finden Sie unter, um eine link:other_references.html["Quellen"] Verknüpfung zur _MetroCluster-Upgrade- und Erweiterungsdokumentation_ zu erhalten.


Wenn Sie eine andere Methode zum Upgrade der Controller-Hardware bevorzugen und bereit sind, Volume-Verschiebungen durchzuführen, lesen Sie link:other_references.html["Quellen"] Link zu _Upgrade durch Verschieben von Volumes oder Storage_.

Siehe link:other_references.html["Quellen"] Zum Link zum Dokumentationszentrum _ONTAP 9_, wo Sie auf die Produktdokumentation zu ONTAP 9 zugreifen können.
