---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'Entscheiden Sie mithilfe von Befehlen, ob Sie Controller, die ONTAP 9.15.1 oder höher ausführen, mit ARL aktualisieren `system controller replace` .' 
---
= Entscheiden Sie, ob Sie dieses Verfahren zur Aggregatverlagerung verwenden möchten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es gibt verschiedene Methoden zur Aggregate Relocation (ARL) für die Aktualisierung der Controller-Hardware. Dieses ARL-Verfahren beschreibt, wie Sie ein HA-Controller-Paar in AFF- und FAS-Speichersystemen, die in ONTAP 9.15.1 oder höher eingeführt wurden, mit neuen Controllern aktualisieren und dabei die vorhandenen Daten und Festplatten beibehalten. Dies ist ein komplexes Verfahren, das nur von erfahrenen ONTAP-Administratoren verwendet werden sollte.

Um Ihnen bei der Entscheidung zu helfen, ob dieses ARL-Verfahren für Ihr Controller-Hardware-Upgrade geeignet ist, sollten Sie alle folgenden Umstände für unterstützte und nicht unterstützte Upgrades überprüfen.



== Unterstützte Upgrades für dieses ARL-Verfahren

Sie können dieses ARL-Verfahren verwenden, um ein Knotenpaar unter den folgenden Umständen zu aktualisieren:

* Sie verwenden ONTAP 9.15.1 oder höher.
* Sie möchten die neuen Controller nicht als neues HA-Paar zum Cluster hinzufügen und die Daten mithilfe der Volume-Verschiebung migrieren.
* Sie verfügen über viel Erfahrung in der Administration von ONTAP und sind mit den Risiken vertraut, die mit der Arbeit im Diagnosemodus verbunden sind.
* Ihre Hardware-Upgrade-Kombination finden Sie in der <<sys_commands_9151_supported_systems,Unterstützte Modellmatrix>> .



NOTE: Dabei können Sie NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) und NetApp Aggregate Encryption (NAE) verwenden.



== Upgrades werden für dieses ARL-Verfahren nicht unterstützt

Unter den folgenden Umständen können Sie dieses ARL-Verfahren nicht zum Upgrade eines Knotenpaars verwenden:

* Sie führen eines der folgenden Upgrades durch:
+
|===
| Vorhandene Controller | Ersatz-Controller 


| AFF A250 | AFF A50, AFF A30 


| AFF A800 | AFF A70, AFF A90 


| AFF C250 | AFF C30, AFF C60 


| AFF C800 | AFF C80 
|===
+
Um ein Upgrade durchzuführen, das in der obigen Tabelle aufgeführt ist, siehe link:other_references.html["Quellen"]Link zu den Befehlen „ System Controller ersetzen “ verwenden, um Controller-Modelle im gleichen Chassis zu aktualisieren_.

* Sie führen ein Upgrade einer MetroCluster FC- oder IP-Konfiguration durch. Informationen zum Upgrade einer MetroCluster-Konfiguration finden Sie unter, um eine link:other_references.html["Quellen"] Verknüpfung zur _MetroCluster-Upgrade- und Erweiterungsdokumentation_ zu erhalten.




== Unterstützte System-Upgrade-Kombinationen

Die folgende Tabelle zeigt die unterstützten Controller-Upgrade-Kombinationen mit ARL für AFF- und FAS-Systeme ab ONTAP 9.15.1. Sollte Ihre Controller-Upgrade-Kombination nicht aufgeführt sein, wenden Sie sich an den technischen Support.

|===
| Vorhandene Controller | Ersatz-Controller | Unterstützt ab ONTAP... 


| AFF A400 | AFF A50 ^2^ | 9.16.1 


| AFF A300 | AFF A50 ^2^ | 9.16.1 


| AFF A220, AFF A150 | AFF A20 ^2^ | 9.16.1 ^1^ 


| AFF C400 | AFF C60, AFF C80 | 9.16.1 


| FAS8200, FAS8300 UND FAS9000 | FAS70, FAS90 UND FAS50 | 9.15.1P3 für FAS70, FAS90 9.16.1P2 für FAS50 


| FAS8700 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70 ^2^ , AFF A90 ^2^, AFF A1K | 9.15.1 


| AFF A900 | AFF A90 ^2^, AFF A1K | 9.15.1 
|===
^1^ für ein Upgrade auf ein AFF A20 müssen Sie zunächst ein AFF A150 oder AFF A220 in ein DS224C Shelf konvertieren, indem Sie das Controller-Modul durch ein IOM12-Modul ersetzen. Siehe link:../upgrade/upgrade-convert-node-to-shelf.html["Konvertieren eines ursprünglichen Node in ein Laufwerk-Shelf"].

^2^ die AFF A20, AFF A50, AFF A70 und AFF A90 sind integrierte Systeme mit zwei Controllern in einer HA-Konfiguration und integrierten Festplatten in einem einzelnen Gehäuse:

* Wenn Sie ein Upgrade auf ein AFF A20, AFF A50, AFF A70 oder AFF A90 mit internen Laufwerken durchführen, müssen Sie vor dem Upgrade die Eigentumsrechte für diese internen Laufwerke entfernen. Nach Abschluss des Upgrades können Sie die internen Laufwerke den AFF Nodes A20, AFF A50, AFF A70 oder AFF A90 zuweisen und sie zur Erstellung von Datenaggregaten verwenden. Sie müssen keine Root- oder Datenaggregate auf interne Laufwerke migrieren.
* Wenn Sie ohne interne Laufwerke auf ein AFF A20, AFF A50, AFF A70 oder AFF A90 aktualisieren, müssen Sie nach Abschluss des Upgrades keine internen Laufwerke zuweisen.




== Wählen Sie ein anderes Verfahren zum Hardware-Upgrade

* link:../upgrade-arl/index.html["Überprüfen Sie die verfügbaren alternativen ARL-Methoden zum Aktualisieren der Controller-Hardware"].
* Wenn Sie eine andere Methode zum Upgrade der Controller-Hardware bevorzugen und bereit sind, Volume-Verschiebungen durchzuführen, lesen Sie link:other_references.html["Quellen"] Link zu _Upgrade durch Verschieben von Volumes oder Storage_.


.Verwandte Informationen
Siehe link:other_references.html["Quellen"] um auf die _ONTAP 9-Dokumentation_ zu verlinken.
