---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/issues_in_multiple_stages_of_procedure.html 
keywords: issues, arise, multiple, stages, procedure 
summary: 'Informationen zu Problemen, die beim Aktualisieren von Controllern, die ONTAP 9.15.1 oder höher ausführen, mithilfe von Befehlen auftreten `system controller replace` können.' 
---
= Probleme, die in mehreren Phasen des Verfahrens auftreten können
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Einige Probleme können in verschiedenen Phasen des Verfahrens auftreten.



== Unerwartete Ausgabe des „Storage Failover show“-Befehls

Wenn während der Prozedur der Node, der alle Daten hostet, „Panik und“ oder versehentlich neu gebootet wird, wird möglicherweise die unerwartete Ausgabe für den angezeigt `storage failover show` Befehl vor und nach dem Neubooten, Panic oder aus- und Wiedereinschalten.

.Über diese Aufgabe
Möglicherweise wird eine unerwartete Ausgabe von der angezeigt `storage failover show` Befehl in Phase 2, Stufe 3, Stufe 4 oder Stufe 5.

Das folgende Beispiel zeigt die erwartete Ausgabe von `storage failover show` Befehl, wenn auf dem Node, der alle Datenaggregate hostet, kein Neubooten oder „Panic“ erfolgt:

....
cluster::> storage failover show

                   Takeover
Node     Partner   Possible  State Description
-------  --------  --------- -----------------
node1    node2     false     Unknown
node2    node1     false     Node owns partner aggregates as part of the non-disruptive head upgrade procedure. Takeover is not possible: Storage failover is disabled.
....
Das folgende Beispiel zeigt die Ausgabe von `storage failover show` Befehl nach einem Neubooten oder Panic:

....
cluster::> storage failover show

                   Takeover
Node     Partner   Possible  State Description
-------  --------  --------- -----------------
node1    node2     -         Unknown
node2    node1     false     Waiting for node1, Partial giveback, Takeover is not possible: Storage failover is disabled
....
Obwohl die Ausgabe sagt, dass sich ein Node im teilweise Giveback befindet und der Storage-Failover deaktiviert ist, können Sie diese Meldung ignorieren.

.Schritte
Es ist keine Aktion erforderlich. Fahren Sie mit dem Upgrade des Node-Paars fort.
