---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/manage-authentication-using-kmip-servers.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Speicherverschlüsselung konfigurieren und verwalten, Authentifizierungsschlüssel verwalten und die SnapMirror-Beziehungen beim Upgrade auf Controller, die in ONTAP 9.15.1 oder später eingeführt wurden, mithilfe des  `system controller replace` Befehls in den Ruhezustand versetzen.' 
---
= Authentifizierungsmanagement mit KMIP-Servern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können KMIP-Server (Key Management Interoperability Protocol) für das Management von Authentifizierungsschlüssel verwenden.

.Schritte
. Hinzufügen eines neuen Controllers:
+
`security key-manager external enable`

. Fügen Sie den Schlüsselmanager hinzu:
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server konfiguriert und für alle Nodes im Cluster verfügbar sind:
+
`security key-manager external show-status`

. Stellen Sie die Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern auf den neuen Knoten wieder her:
+
`security key-manager external restore -node _new_controller_name_`



.Was kommt als Nächstes?
Nach der Verwaltung der Authentifizierung mithilfe von KMIP-Servern, link:ensure_new_controllers_are_set_up_correctly.html["Vergewissern Sie sich, dass die neuen Controller korrekt eingerichtet sind."].
