---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2, node3 
summary: 'Überprüfen Sie mithilfe von Befehlen, ob die node1 NAS-Daten-LIFs auf node2 von node2 auf node3 verschoben werden, wenn Sie Controller mit ONTAP 9.15.1 oder höher aktualisieren `system controller replace` .' 
---
= Verschieben Sie Aggregate ohne Root-Root-Fehler und NAS-Daten-LIFs, die sich im Besitz von node1 befinden, von node2 auf node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die Netzwerkkonfiguration auf node3 und bevor Sie Aggregate von node2 auf node3 verschoben haben, müssen Sie überprüfen, ob die NAS-Daten-LIFs, die zu node1 gehören und sich derzeit auf node2 befinden, von node2 in node3 verschoben werden. Sie müssen außerdem überprüfen, ob die SAN-LIFs auf node3 vorhanden sind.

.Über diese Aufgabe
Remote-LIFs verarbeiten den Datenverkehr zu SAN-LUNs während des Upgrades. Das Verschieben von SAN-LIFs ist für den Zustand des Clusters oder des Service während des Upgrades nicht erforderlich. SAN LIFs werden nicht verschoben, es sei denn, sie müssen neuen Ports zugeordnet werden. Sie überprüfen, ob die LIFs sich in einem ordnungsgemäßen Zustand befinden und sich auf den entsprechenden Ports befinden, nachdem Sie node3 in den Online-Modus versetzt haben.

.Schritte
. Die iSCSI LIFs finden automatisch die richtigen Home Ports mithilfe der Erreichbarkeit. Die FC- und NVMe/FC-SAN-LIFs werden nicht automatisch verschoben. Sie zeigen weiterhin den Home-Port an, an dem sie vor dem Upgrade waren.
+
Prüfen Sie die SAN LIFs auf Knoten3:

+
.. Ändern Sie alle iSCSI SAN LIFs, die über einen „down“-Status für die neuen Daten-Ports verfügen:
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <iscsi_san_lif> admin down
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <iscsi_san_lif> port <new_port> node <node>
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <iscsi_san_lif>
----
.. Ändern Sie alle FC- und NVMe/FC-SAN-LIFs, die den neuen Controller Zuhause haben, und melden Sie den Betriebsstatus der FCP-Ports am neuen Controller an:
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <fc_san_lif> admin down
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <fc_san_lif> port <new_port> node <node>
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <fc_san_lif>
----


. Wiederaufnahme des Betriebs der Versetzung:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt die folgenden Aufgaben aus:

+
** Cluster-Quorum-Prüfung
** System-ID-Prüfung
** Prüfung der Bildversion
** Überprüfung der Zielplattform
** Prüfung der Netzwerkanachabilität


+
Der Vorgang unterbricht in dieser Phase in der Überprüfung der Netzwerknachprüfbarkeit.

. Wiederaufnahme des Betriebs der Versetzung:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt folgende Prüfungen durch:

+
** Cluster-Zustandsprüfung
** LIF-Statusüberprüfung für Cluster


+
Nach Durchführung dieser Prüfungen verschiebt das System die nicht-Root-Aggregate und NAS-Daten-LIFs, die sich im Besitz von node1 befinden, auf den neuen Controller, node3. Der Controller-Ersatzvorgang hält nach Abschluss der Ressourcenverschiebung die Pause ein.

. Überprüfen Sie den Status der Aggregatverschiebung und der LIF-Verschiebung von NAS-Daten:
+
[source, cli]
----
system controller replace show-details
----
+
Wenn der Austausch des Controllers unterbrochen wird, prüfen und korrigieren Sie den Fehler, falls zutreffend, und führen Sie das Problem anschließend aus `resume` Um den Vorgang fortzusetzen.

. Falls erforderlich, stellen Sie verschobene LIFs wieder her und setzen Sie sie zurück oder migrieren und modifizieren Sie die node1 LIFs, die nicht automatisch zu node3 verschoben wurden, manuell.
+
[role="tabbed-block"]
====
.Versetzte LIFs wiederherstellen und zurücksetzen
--
.. Liste aller verschobenen LIFs:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Wenn LIFs verschoben werden, stellen Sie den Home-Node wieder in Knoten 3 wieder her:
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node3_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Manuelle Migration und Modifizierung von LIFs
--
.. Migrieren Sie die LIFs, die nicht automatisch auf Knoten 3 verschoben wurden:
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node3_nodename> -destination-port <port_on_node3>
----
.. Ändern Sie den Home-Knoten und den Home-Port für die migrierten LIFs:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node3_nodename> -home-port <home_port>
----


--
====
. Setzen Sie den Vorgang fort, um das System zur Durchführung der erforderlichen Nachprüfungen zu auffordern:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt die folgenden Nachprüfungen durch:

+
** Cluster-Quorum-Prüfung
** Cluster-Zustandsprüfung
** Aggregatrekonstruktion
** Aggregatstatus-Prüfung
** Überprüfung des Festplattenstatus
** LIF-Statusüberprüfung für Cluster
** Lautstärkerprüfung



