---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/restore_key-manager_configuration_node3.html 
keywords: restoring, key-manager, configuration, node3, nve, arl, encryption, netapp, volume 
summary: 'Falls erforderlich, wird die Key-Manager-Konfiguration auf Knoten 3 beim Upgrade auf die in ONTAP 9.15.1 oder höher eingeführten Controller mithilfe von  `system controller replace` Befehlen wiederhergestellt.' 
---
= Wiederherstellung der Key-Manager-Konfiguration auf Knoten 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn Sie mithilfe von NetApp Volume Encryption (NVE) und NetApp Aggregate Encryption (NAE) Volumes auf dem System verschlüsseln, muss die Verschlüsselungskonfiguration mit den neuen Nodes synchronisiert werden. Wenn Sie den Schlüsselmanager nicht synchronisieren, können beim Verschieben der Node1-Aggregate mit ARL von node2 auf node3 Ausfälle auftreten, da node3 nicht über die erforderlichen Schlüssel zum Online-Zugriff verschlüsselter Volumes und Aggregate verfügt.

.Über diese Aufgabe
Die Verschlüsselungskonfiguration mit den neuen Nodes synchronisieren, indem Sie die folgenden Schritte durchführen:

.Schritte
. Führen Sie den folgenden Befehl von node3 aus:
+
`security key-manager onboard sync`

. Überprüfen Sie, ob der SVM-KEK-Schlüssel auf „true“ in node3 wiederhergestellt wird, bevor Sie die Datenaggregate verschieben:
+
[listing]
----
::> security key-manager key query -node node3 -fields restored -key-type SVM-KEK
----
+
.Beispiel
[listing]
----
::> security key-manager key query -node node3 -fields restored -key-type SVM-KEK

node     vserver   key-server   key-id                                  restored
-------- --------- -----------  --------------------------------------- --------
node3    svm1      ""           00000000000000000200000000000a008a81976 true
                                2190178f9350e071fbb90f00000000000000000
----


.Was kommt als Nächstes?
Nach der Wiederherstellung der Key-Manager-Konfiguration auf node3, link:move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html["Nicht-Root-Aggregate und NAS-Daten-LIFs, die node1 gehören, von node2 nach node3 verschieben"].
