---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/retire_node1.html 
keywords: retiring, node 
summary: 'Das HA-Paar mit node2 wird deaktiviert und node1 wird heruntergefahren, wenn auf Controller aktualisiert wird, die in ONTAP 9.15.1 oder später eingeführt wurden, indem  `system controller replace` Befehle verwendet werden.' 
---
= Node1 ausmustern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um Knoten1 außer Betrieb zu nehmen, setzen Sie den automatisierten Vorgang fort, um das HA-Paar mit Knoten2 zu deaktivieren und Knoten1 ordnungsgemäß herunterzufahren.  Später im Verfahren entfernen Sie Knoten1 aus dem Rack oder Gehäuse.

.Schritte
. Vorgang fortsetzen:
+
`system controller replace resume`

. Vergewissern Sie sich, dass node1 angehalten wurde:
+
`system controller replace show-details`



.Nachdem Sie fertig sind
Stellen Sie nach der Außerbetriebnahme von Knoten1 sicher, dass er ausgeschaltet und nicht mit dem Netzwerk verbunden ist.  Belassen Sie die alte Hardware von Knoten1 in diesem Zustand, bis Sie das Upgrade von Knoten1 und Knoten2 abgeschlossen haben.  Sie können dann Knoten1 währendlink:manage-authentication-using-kmip-servers.html["Phase 6: Schließen Sie das Upgrade ab"] .

.Was kommt als Nächstes?
Nach der Außerbetriebnahme von node1, link:prepare_for_netboot.html["Vorbereitung auf den Netzwerkstart"].
