---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/retire_node2.html 
keywords: retire, node2 
summary: 'Node2 muss heruntergefahren und aus dem Rack oder Chassis entfernt werden, wenn auf Controller aktualisiert wird, die in ONTAP 9.15.1 oder höher eingeführt wurden, indem  `system controller replace` Befehle verwendet werden.' 
---
= Node2 ausmustern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um Knoten2 außer Betrieb zu nehmen, fahren Sie Knoten2 ordnungsgemäß herunter und entfernen ihn dann aus dem Rack oder Gehäuse.

.Schritte
. Vorgang fortsetzen:
+
`system controller replace resume`

+
Der Knoten wird automatisch angehalten.



.Nachdem Sie fertig sind
Stellen Sie nach der Außerbetriebnahme von Knoten2 sicher, dass er ausgeschaltet und nicht mit dem Netzwerk verbunden ist.  Belassen Sie die alte Hardware von Knoten2 in diesem Zustand, bis Sie das Upgrade von Knoten1 und Knoten2 abgeschlossen haben.  Sie können dann Knoten2 währendlink:manage-authentication-using-kmip-servers.html["Phase 6: Schließen Sie das Upgrade ab"] .

.Was kommt als Nächstes?
Nach der Außerbetriebnahme von node2, link:install_boot_node4.html["Node4 installieren und starten"].
