---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_3_index.html 
keywords: installing, booting, node3, install, cluster, stage 3 
summary: 'Phase 3-Prozesssequenz für ein ARL-Upgrade mithilfe von `system controller replace` Befehlen auf Controllern, die ONTAP 9.15.1 oder höher ausführen.' 
---
= Phase-3-Übersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In Phase 3 installieren und booten Sie node3, überprüfen, ob die Cluster- und Node-Management-Ports von node1 auf node3 online geschaltet sind, und überprüfen Sie die Installation von node3. Wenn Sie NetApp Volume Encryption (NVE) verwenden, stellen Sie die Konfiguration des Schlüsselmanagers wieder her. Außerdem werden die LIFs für NAS-Daten-LIFs und nicht-Root-Aggregate von node2 auf node3 verschoben und Sie überprüfen, ob die SAN-LIFs auf node3 vorhanden sind.

.Schritte
. link:install_boot_node3.html["Installieren und booten Sie node3"]
. link:verify_node3_installation.html["Überprüfen Sie die Installation von node3"]
. link:restore_key-manager_configuration_node3.html["Wiederherstellung der Key-Manager-Konfiguration auf Knoten 3"]
. link:move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html["Verschieben Sie Aggregate ohne Root-Root-Fehler und NAS-Daten-LIFs, die sich im Besitz von node1 befinden, von node2 auf node3"]

