---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_5_index.html 
keywords: install, boot, node4, node2, node-management, stage 5 
summary: 'Phase 5-Prozesssequenz für ein ARL-Upgrade mithilfe von `system controller replace` Befehlen auf Controllern, die ONTAP 9.15.1 oder höher ausführen.' 
---
= Phase-5-Übersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Phase 5 installieren und booten Sie node4, überprüfen, ob die Cluster- und Node-Management-Ports von node2 auf node4 online geschaltet sind, und überprüfen Sie die Installation von node4. Wenn Sie NVE verwenden, stellen Sie die Konfiguration für Schlüsselmanager wieder her. Außerdem werden Knoten2-NAS-Daten-LIFs und nicht-Root-Aggregate von node3 auf node4 verschoben und überprüft, ob die SAN-LIFs auf node4 vorhanden sind.

.Schritte
. link:install_boot_node4.html["installieren und booten sie node4"]
. link:verify_node4_installation.html["Überprüfen Sie die installation von node4"]
. link:restore_key-manager_config_node4.html["Wiederherstellen der Key-Manager-Konfiguration auf node4"]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html["Verschieben Sie Aggregate ohne Root-Root-Fehler und NAS-Daten-LIFs, die sich im Besitz von node2 befinden, von node3 auf node4"]

