---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_6_index.html 
keywords: complete upgrade, node, unified, target, storage, encryption, stage 6 
summary: 'Phase 6-Prozesssequenz für ein ARL-Upgrade mithilfe von `system controller replace` Befehlen auf Controllern, die ONTAP 9.15.1 oder höher ausführen.' 
---
= Phase-6-Übersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Phase 6 bestätigen Sie, dass die neuen Nodes ordnungsgemäß eingerichtet wurden. Bei aktivierter Verschlüsselung konfigurieren und einrichten Sie Storage Encryption bzw. NetApp Volume Encryption. Zudem sollten die alten Nodes außer Betrieb gesetzt und der SnapMirror Betrieb fortgesetzt werden.

.Schritte
. link:manage-authentication-using-kmip-servers.html["Authentifizierungsmanagement mit KMIP-Servern"]
. link:ensure_new_controllers_are_set_up_correctly.html["Vergewissern Sie sich, dass die neuen Controller ordnungsgemäß eingerichtet sind"]
. link:set_up_storage_encryption_new_module.html["Richten Sie Storage Encryption auf dem neuen Controller-Modul ein"]
. link:set_up_netapp_volume_encryption_new_module.html["Einrichtung von NetApp Volume oder Aggregate Encryption auf dem neuen Controller-Modul"]
. link:decommission_old_system.html["Ausmustern des alten Systems"]
. link:resume_snapmirror_operations.html["Setzen Sie den SnapMirror Betrieb fort"]


[NOTE]
====
Die AFF Systeme A70, AFF A90 und AFF A1K verwenden 100-GbE-Netzwerk-Ports sowohl für Cluster- als auch für HA-Verbindungen. Diese Systeme können 10-GbE- oder 25-GbE-Clusterverbindungen zu älteren Cluster-Switches unterstützen. NetApp empfiehlt jedoch ein Upgrade auf eine Clustergeschwindigkeit von 100 GbE, wenn die 10-GbE- und 25-GbE-Switches nicht mehr benötigt werden. Weitere Informationen finden Sie in den folgenden Knowledge Base-Artikeln:

* link:https://kb.netapp.com/?title=on-prem%2Fontap%2FOHW%2FOHW-KBs%2FHow_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup_on_AFF_A1K%252C_AFF_A90_or_AFF_A70["So konfigurieren Sie 10G- oder 25G-Cluster-Ports bei einem neuen Cluster-Setup auf AFF A1K, AFF A90 oder AFF A70"^]
* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_an_existing_cluster_from_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports_on_an_AFF_A1K_AFF_A90_or_AFF_A70["Wie konvertiert man einen vorhandenen Cluster von 10G- oder 25G-Cluster-Ports in 40G- oder 100G-Cluster-Ports auf einem AFF A1K, AFF A90 oder AFF A70"^]


Wenn Sie e0a oder e0b Cluster-Ports auf dem vorhandenen Node nicht mit den Cluster-Ports auf dem neuen Node verbinden können, finden Sie unter link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp Bugs Online Fehler-ID CONTAP-166978"^].

====