---
sidebar: sidebar 
permalink: upgrade-arl-auto/get_ip_address_of_external_kms_for_storage_encryption.html 
keywords: IP address, external, key management, server, storage encryption, kmip, onboard key management 
summary: 'Konfiguration und Management der Storage-Verschlüsselung, Management der Authentifizierungsschlüssel und Stilllegung der SnapMirror Beziehungen, wenn Sie ein Upgrade von Controllern mit ONTAP 9.5 zu 9.7 durchführen `system controller replace` Befehle.' 
---
= Holen Sie sich eine IP-Adresse eines externen Verschlüsselungsmanagementservers für die Speicherverschlüsselung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nach dem Upgrade müssen Sie Storage Encryption sofort konfigurieren und einen Cluster-weiten Authentifizierungsschlüssel einrichten, um die vorherigen Authentifizierungsschlüssel auf Node-Ebene zu ersetzen.

.Schritte
. Installieren Sie die erforderlichen SSL-Zertifikate (Secure Sockets Layer) von Clients und Servern, die für die Kommunikation mit den Schlüsselverwaltungsservern erforderlich sind:
+
`security certificate install`

. Konfigurieren Sie die Storage-Verschlüsselung auf allen Nodes mithilfe des folgenden Befehls auf jedem Node:
+
`security key-manager setup`

. Fügen Sie für jeden Verschlüsselungsmanagementserver die IP-Adresse hinzu:
+
`security key-manager add`

. Vergewissern Sie sich, dass dieselben Verschlüsselungsmanagement-Server konfiguriert und auf allen Knoten im Cluster verfügbar sind:
+
`security key-manager show -status`

. Erstellen Sie einen neuen clusterweiten Authentifizierungsschlüssel:
+
`security key-manager create-key`

. Notieren Sie sich die neue Authentifizierungsschlüssel-ID.
. Rekeyfür alle Self-Encrypting Drives mit dem neuen Authentifizierungsschlüssel:
+
`storage encryption disk modify -disk * -data-key-id _authentication_key_id_`





== Authentifizierungsmanagement mit KMIP-Servern

Von ONTAP 9.5 bis 9.7 können KMIP-Server (Key Management Interoperability Protocol) Authentifizierungsschlüssel managen.

Schritte

. Hinzufügen eines neuen Controllers:
+
`security key-manager setup -node _new_controller_name_`

. Fügen Sie den Schlüsselmanager hinzu:
+
`security key-manager -add _key_management_server_ip_address_`

. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server konfiguriert und für alle Nodes im Cluster verfügbar sind:
+
`security key-manager show -status`

. Stellen Sie die Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern auf den neuen Knoten wieder her:
+
`security key-manager restore -node _new_controller_name_`

. Rekeyfür alle selbstverschlüsselnden Festplatten mit dem neuen Authentifizierungsschlüssel:
+
`storage encryption disk modify -disk * [-data-key-id nonMSID AK]`

. Wenn Sie den Federal Information Processing Standard (FIPS) verwenden, müssen Sie alle selbstverschlüsselnden Festplatten mit dem neuen Authentifizierungsschlüssel neu verschlüsseln:
+
`storage encryption disk modify -disk * [-fips-key-id nonMSID AK]`





== Management der Storage-Verschlüsselung mit Onboard Key Manager

Sie können den OKM verwenden, um die Verschlüsselung zu verwalten. Wenn Sie OKM verwenden möchten, müssen Sie vor dem Upgrade die Passphrase und das Sicherungsmaterial aufzeichnen.

.Schritte
. Speichern Sie die Passphrase an einem sicheren Ort.
. Backup für Recovery-Zwecke erstellen. Führen Sie den folgenden Befehl aus und speichern Sie die Ausgabe:
+
`security key-manager onboard show-backup`





== Stilllegen der SnapMirror Beziehungen (optional)

Bevor Sie mit dem Verfahren fortfahren, müssen Sie bestätigen, dass alle SnapMirror Beziehungen stillgelegt werden. Wenn eine SnapMirror Beziehung stillgelegt wird, bleibt es bei einem Neustart und einem Failover stillgelegt.

.Schritte
. Überprüfen Sie den SnapMirror Beziehungsstatus auf dem Ziel-Cluster:
+
`snapmirror show`

+
[NOTE]
====
Wenn der Status „Übertragen“ lautet, müssen Sie diese Transfers abbrechen:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
Der Abbruch schlägt fehl, wenn sich die SnapMirror-Beziehung nicht im Zustand „Übertragen“ befindet.

. Alle Beziehungen zwischen dem Cluster stilllegen:
+
`snapmirror quiesce -destination-vserver _vserver_name_`


