---
sidebar: sidebar 
permalink: upgrade-arl-auto/guidelines_for_upgrading_controllers_with_arl.html 
keywords: upgrade, controllers, guidelines, ARL, aggregate relocation, supported upgrades, two-node, cluster, troubleshoot 
summary: 'Ermitteln Sie, ob Sie Controller mit ONTAP 9.5 auf 9.7 mit aktualisieren können `system controller replace` Befehle.' 
---
= Richtlinien für das Controller-Upgrade mit ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um zu verstehen, ob Sie bei einem Controller-Upgrade von ONTAP 9.5 auf ONTAP 9.7 mit Aggregate Relocation (ARL) arbeiten können, hängt von der Plattform und der Konfiguration der ursprünglichen Controller sowie von dem Ersatz-Controller ab.



== Unterstützte Upgrades für ARL

Wenn Sie ein Node-Paar mit diesem ARL-Verfahren für ONTAP 9.5 auf ONTAP 9.7 aktualisieren, müssen Sie sicherstellen, dass ARL an den Original- und Ersatz-Controllern ausgeführt werden kann.

Sie sollten die Größe aller definierten Aggregate und die Anzahl der Festplatten überprüfen, die vom ursprünglichen System unterstützt werden. Dann müssen Sie die Aggregatgröße und Anzahl der unterstützten Festplatten mit der Aggregatgröße und der Anzahl der vom neuen System unterstützten Festplatten vergleichen. Siehe link:other_references.html["Quellen"] Link zum _Hardware Universe_, wo diese Information verfügbar ist. Die Aggregatgröße und die Anzahl der vom neuen System unterstützten Festplatten müssen gleich oder größer sein als die Aggregatgröße und Anzahl der vom ursprünglichen System unterstützten Festplatten.

Sie sollten in den Cluster-Mischregeln validieren, ob neue Nodes zusammen mit den vorhandenen Nodes in das Cluster integriert werden können, wenn der ursprüngliche Controller ersetzt wird. Weitere Informationen zu Regeln für die Kombination von Clustern finden Sie unter link:other_references.html["Quellen"] Zum Verknüpfen mit der _Hardware Universe_.


NOTE: Bevor Sie ein AFF-Systemupgrade durchführen, müssen Sie ONTAP auf Version 9.5P1 oder neuer aktualisieren. Diese Versionsebenen sind für ein erfolgreiches Upgrade erforderlich.


NOTE: Informationen zum Upgrade eines Systems, das interne Laufwerke unterstützt (z. B. eine FAS2700 oder AFF A250), aber KEINE internen Laufwerke enthält, finden Sie unter link:other_references.html["Quellen"] Und verwenden Sie das Verfahren in der _Aggregate Relocation, um den für Ihre Version von ONTAP korrekten Controller-Hardware_-Inhalt manuell zu aktualisieren.

Wenn Sie ONTAP 9.6P11, 9.7P8 oder neuere Versionen verwenden, wird empfohlen, die Aktivierung von Connectivity, Lebendigkeit und Availability Monitor (CLAM)-Übernahme zu aktivieren, um das Cluster bei bestimmten Node-Ausfällen in Quorum zurückzugeben. Der `kernel-service` Für Befehl ist der erweiterte Zugriff auf die Berechtigungsebene erforderlich. Weitere Informationen finden Sie unter: https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436["NetApp KB-Artikel SU436: DIE CLAM-Übernahme hat sich die Standardkonfiguration geändert"^].

Das Controller-Upgrade mit ARL wird auf Systemen unterstützt, die mit SnapLock Enterprise undSnapLock Compliance Volumes konfiguriert sind.



== 2-Node-Cluster ohne Switches

Wenn Sie Nodes in einem 2-Node-Cluster ohne Switches aktualisieren, können Sie die Nodes im Cluster ohne Switches während des Upgrades belassen. Sie müssen sie nicht in ein Switch-Cluster konvertieren.



== Upgrades werden für ARL nicht unterstützt

Sie können die folgenden Aktualisierungen nicht ausführen:

* Zum Austausch von Controllern, die die mit den ursprünglichen Controllern verbundenen Platten-Shelfs nicht unterstützen
+
Siehe link:other_references.html["Quellen"] Um Informationen zur Hardware Universe Festplattenunterstützung zu erhalten.

* Um Controller der Einstiegsklasse mit internen Laufwerken zu erhalten, beispielsweise eine FAS 2500.
+
Informationen zum Upgrade von Controllern der Einstiegsklasse mit internen Laufwerken finden Sie unter link:other_references.html["Quellen"] Link zu _Upgrade durch Verschiebung von Volumes oder Storage_ und Vorgang _Upgrade eines Node-Paares, auf dem Clustered Data ONTAP durch Verschieben von Volumes_ ausgeführt wird.





== MetroCluster FC-Konfiguration

In einer MetroCluster FC-Konfiguration müssen die Knoten für Disaster Recovery/Failover-Standort so schnell wie möglich ersetzt werden. Nichtübereinstimmungen in Controller-Modellen innerhalb einer MetroCluster-Konfiguration werden nicht unterstützt, da dies dazu führen kann, dass die Disaster Recovery-Spiegelung offline geht. Verwenden Sie die  `-skip-metrocluster-check true` Befehl zum Umgehen von MetroCluster-Prüfungen, wenn Sie Knoten am zweiten Standort ersetzen.



== Fehlerbehebung

Möglicherweise ist beim Upgrade des Node-Paars ein Fehler auftritt. Der Node kann abstürzen, Aggregate werden möglicherweise nicht verschoben oder LIFs werden nicht migriert. Die Ursache des Fehlers und seiner Lösung hängt davon ab, wann der Fehler während des Aktualisierungsvorgangs aufgetreten ist.

Eine Beschreibung der verschiedenen Phasen des Verfahrens finden Sie in der Tabelle im Abschnitt „Übersicht über das ARL-Upgrade“. Informationen über mögliche Ausfälle werden in der Phase des Verfahrens aufgelistet.

Sollten beim Upgrade der Controller Probleme auftreten, lesen Sie bitte die link:aggregate_relocation_failures.html["Fehlerbehebung"] Abschnitt. Die Informationen zu möglichen Fehlern sind nach Phase des Verfahrens im Abschnitt link:arl_upgrade_workflow.html["ARL-Upgradesequenz"] .

Wenn Sie keine Lösung für das Problem finden, wenden Sie sich an den technischen Support.
