---
sidebar: sidebar 
permalink: upgrade-arl-auto/guidelines_for_upgrading_controllers_with_arl.html 
keywords: upgrade, controllers, guidelines, ARL, aggregate relocation, supported upgrades, two-node, cluster, troubleshoot 
summary: 'Ermitteln Sie, ob Sie Controller mit ONTAP 9.5 auf 9.7 mit aktualisieren können `system controller replace` Befehle.' 
---
= Richtlinien für das Controller-Upgrade mit ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um zu verstehen, ob Sie bei einem Controller-Upgrade von ONTAP 9.5 auf ONTAP 9.7 mit Aggregate Relocation (ARL) arbeiten können, hängt von der Plattform und der Konfiguration der ursprünglichen Controller sowie von dem Ersatz-Controller ab.



[[supported-upgrades-for-arl]]
== Unterstützte Upgrades für ARL

Wenn Sie ein Node-Paar mit diesem ARL-Verfahren für ONTAP 9.5 auf ONTAP 9.7 aktualisieren, müssen Sie sicherstellen, dass ARL an den Original- und Ersatz-Controllern ausgeführt werden kann.

Sie sollten die Größe aller definierten Aggregate und die Anzahl der vom ursprünglichen System unterstützten Festplatten überprüfen. Anschließend sind die Aggregatgrößen und die Anzahl der unterstützten Festplatten mit der Aggregatgröße und der Anzahl der unterstützten Festplatten des neuen Systems zu vergleichen. Siehe link:other-references.html["Quellen"] für einen Link zum _Hardware Universe_, in dem diese Informationen verfügbar sind. Die Aggregatgröße und die Anzahl der vom neuen System unterstützten Festplatten müssen mindestens so groß sein wie die Aggregatgröße und die Anzahl der vom ursprünglichen System unterstützten Festplatten.

In den Cluster-Mixing-Regeln ist zu prüfen, ob neue Knoten beim Austausch des ursprünglichen Controllers zusammen mit den bestehenden Knoten Teil des Clusters werden können. Weitere Informationen zu Cluster-Mixing-Regeln sind unter link:other-references.html["Quellen"] dem Link zum _Hardware Universe_ zu finden.


NOTE: Bevor Sie ein AFF-Systemupgrade durchführen, müssen Sie ONTAP auf Version 9.5P1 oder neuer aktualisieren. Diese Versionsebenen sind für ein erfolgreiches Upgrade erforderlich.


NOTE: Wenn ein System aktualisiert wird, das interne Laufwerke unterstützt (zum Beispiel ein FAS2700 oder AFF A250), aber keine internen Laufwerke besitzt, beachten Sie link:other-references.html["Quellen"] und verwenden Sie das Verfahren im Inhalt _Aggregate-Verschiebung zur manuellen Aktualisierung der Controller-Hardware_, das für Ihre Version von ONTAP korrekt ist.

Wenn Sie ONTAP 9.6P11, 9.7P8 oder neuere Versionen verwenden, wird empfohlen, die Aktivierung von Connectivity, Lebendigkeit und Availability Monitor (CLAM)-Übernahme zu aktivieren, um das Cluster bei bestimmten Node-Ausfällen in Quorum zurückzugeben. Der `kernel-service` Für Befehl ist der erweiterte Zugriff auf die Berechtigungsebene erforderlich. Weitere Informationen finden Sie unter: https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436["NetApp KB-Artikel SU436: DIE CLAM-Übernahme hat sich die Standardkonfiguration geändert"^].

Das Controller-Upgrade mit ARL wird auf Systemen unterstützt, die mit SnapLock Enterprise undSnapLock Compliance Volumes konfiguriert sind.



[[two-node-switchless-clusters]]
== 2-Node-Cluster ohne Switches

Wenn Sie Nodes in einem 2-Node-Cluster ohne Switches aktualisieren, können Sie die Nodes im Cluster ohne Switches während des Upgrades belassen. Sie müssen sie nicht in ein Switch-Cluster konvertieren.



[[upgrades-not-supported-for-arl]]
== Upgrades werden für ARL nicht unterstützt

Sie können die folgenden Aktualisierungen nicht ausführen:

* Zum Austausch von Controllern, die die mit den ursprünglichen Controllern verbundenen Platten-Shelfs nicht unterstützen
+
Siehe link:other-references.html["Quellen"] zum Verweis auf _Hardware Universe_ für Informationen zur Festplattenunterstützung.

* Zu Einstiegs-Controllern mit internen Laufwerken, zum Beispiel ein FAS2750.
+
Wenn Sie Einstiegs-Controller mit internen Laufwerken aufrüsten möchten, siehe link:other-references.html["Quellen"] den Link _Upgrade durch Verschieben von Volumes oder Storage_ und gehen Sie zur Prozedur _Upgrade eines Node-Paares mit clustered Data ONTAP durch Verschieben von Volumes_.





[[metrocluster-fc-configuration]]
== MetroCluster FC-Konfiguration

In einer MetroCluster FC-Konfiguration müssen die Knoten für Disaster Recovery/Failover-Standort so schnell wie möglich ersetzt werden. Nichtübereinstimmungen in Controller-Modellen innerhalb einer MetroCluster-Konfiguration werden nicht unterstützt, da dies dazu führen kann, dass die Disaster Recovery-Spiegelung offline geht. Verwenden Sie die  `-skip-metrocluster-check true` Befehl zum Umgehen von MetroCluster-Prüfungen, wenn Sie Knoten am zweiten Standort ersetzen.



[[troubleshoot]]
== Fehlerbehebung

Möglicherweise ist beim Upgrade des Node-Paars ein Fehler auftritt. Der Node kann abstürzen, Aggregate werden möglicherweise nicht verschoben oder LIFs werden nicht migriert. Die Ursache des Fehlers und seiner Lösung hängt davon ab, wann der Fehler während des Aktualisierungsvorgangs aufgetreten ist.

Eine Beschreibung der verschiedenen Phasen des Verfahrens finden Sie in der Tabelle im Abschnitt „Übersicht über das ARL-Upgrade“. Informationen über mögliche Ausfälle werden in der Phase des Verfahrens aufgelistet.

Sollten beim Aktualisieren der Controller Probleme auftreten, konsultieren Sie bitte dielink:aggregate_relocation_failures.html["Fehlerbehebung"] Abschnitt.  Die Informationen über mögliche Fehler sind nach den einzelnen Phasen des Verfahrens aufgelistet.link:overview_of_the_arl_upgrade.html["ARL-Upgradesequenz"] Die

Wenn Sie keine Lösung für das Problem finden, wenden Sie sich an den technischen Support.
