---
sidebar: sidebar 
permalink: upgrade-arl-auto/manage-authentication-using-kmip-servers.html 
keywords: IP address, external, key management, server, storage encryption, kmip, onboard key management 
summary: 'Konfiguration und Management der Storage-Verschlüsselung, Management der Authentifizierungsschlüssel und Stilllegung der SnapMirror Beziehungen, wenn Sie ein Upgrade von Controllern mit ONTAP 9.5 zu 9.7 durchführen `system controller replace` Befehle.' 
---
= Authentifizierungsmanagement mit KMIP-Servern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Von ONTAP 9.5 bis 9.7 können KMIP-Server (Key Management Interoperability Protocol) Authentifizierungsschlüssel managen.

Schritte

. Hinzufügen eines neuen Controllers:
+
`security key-manager setup -node _new_controller_name_`

. Fügen Sie den Schlüsselmanager hinzu:
+
`security key-manager -add _key_management_server_ip_address_`

. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server konfiguriert und für alle Nodes im Cluster verfügbar sind:
+
`security key-manager show -status`

. Stellen Sie die Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern auf den neuen Knoten wieder her:
+
`security key-manager restore -node _new_controller_name_`


