---
sidebar: sidebar 
permalink: upgrade-arl-auto/manage_storage_encryption_using_okm.html 
keywords: IP address, external, key management, server, storage encryption, kmip, onboard key management 
summary: 'Konfiguration und Management der Storage-Verschlüsselung, Management der Authentifizierungsschlüssel und Stilllegung der SnapMirror Beziehungen, wenn Sie ein Upgrade von Controllern mit ONTAP 9.5 zu 9.7 durchführen `system controller replace` Befehle.' 
---
= Schließen Sie die Vorbereitung für das Upgrade ab
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/




[[manage-storage-encryption-using-the-onboard-key-manager]]
== Management der Storage-Verschlüsselung mit dem Onboard Key Manager

Verwenden Sie den Onboard Key Manager (OKM) zur Verwaltung der Verschlüsselungsschlüssel. Wenn Sie den OKM eingerichtet haben, müssen Sie die Passphrase und die Sicherungsdaten vor Beginn des Upgrades notieren.

.Schritte
. Notieren Sie die Cluster-weite Passphrase.
+
Dies ist die Passphrase, die eingegeben wurde, als das OKM mit der CLI oder REST-API konfiguriert oder aktualisiert wurde.

. Überprüfen Sie die Passphrase und den Schlüsselmanager-Vorgang:
+
`security key-manager onboard sync`

+
Geben Sie bei Aufforderung die clusterweite OKM-Passphrase ein, die Sie im vorherigen Schritt aufgezeichnet haben.

. Vergewissern Sie sich, dass cc-mode aktiviert ist, indem Sie die Ausgabe des folgenden Befehls überprüfen:
+
`security key-manager config show`

. Sichern Sie die Key-Manager-Informationen:
+
`security key-manager onboard show-backup`





[[optionally-quiesce-the-snapmirror-relationships]]
== Optional können die SnapMirror-Beziehungen angehalten werden

Bevor Sie mit dem Verfahren fortfahren, müssen Sie bestätigen, dass alle SnapMirror Beziehungen stillgelegt werden. Wenn eine SnapMirror Beziehung stillgelegt wird, bleibt es bei einem Neustart und einem Failover stillgelegt.

.Schritte
. Überprüfen Sie den SnapMirror Beziehungsstatus auf dem Ziel-Cluster:
+
`snapmirror show`

+
[NOTE]
====
Wenn der Status „Übertragen“ lautet, müssen Sie diese Transfers abbrechen:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
Der Abbruch schlägt fehl, wenn sich die SnapMirror-Beziehung nicht im Zustand „Übertragen“ befindet.

. Alle Beziehungen zwischen dem Cluster stilllegen:
+
`snapmirror quiesce -destination-vserver *`


