---
sidebar: sidebar 
permalink: upgrade-arl-auto/overview_of_the_arl_upgrade.html 
keywords: aggregate relocation, upgrade, process, overview, stages 
summary: 'Erfahren Sie, wie Sie ein Controller-Upgrade mit ONTAP 9.5 auf 9.7 mit durchführen `system controller replace` Befehle funktionieren.' 
---
= Überblick über das ARL Upgrade
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie die Nodes mit ARL aktualisieren, sollten Sie unbedingt verstehen, wie das Verfahren funktioniert. In diesem Inhalt wird das Verfahren in mehrere Phasen unterteilt.



== Aktualisieren Sie das Node-Paar

Zum Upgrade des Node-Paars müssen Sie die ursprünglichen Nodes vorbereiten und dann für die ursprünglichen und die neuen Nodes eine Reihe von Schritten ausführen. Anschließend können Sie die ursprünglichen Knoten außer Betrieb nehmen.



== Übersicht über die ARL-Upgrade-Sequenz

Während des Verfahrens aktualisieren Sie die ursprüngliche Controller Hardware mit der Ersatz-Controller-Hardware, einem Controller gleichzeitig. Nutzen Sie die HA-Paar-Konfiguration, um das Eigentum von Aggregaten ohne Root-Berechtigungen zu verschieben. Alle Aggregate außerhalb der Root-Ebene müssen zwei Umlagerungen durchlaufen, um das endgültige Ziel zu erreichen, nämlich den korrekten aktualisierten Node.

Jedes Aggregat hat einen Hausbesitzer und aktuellen Eigentümer. Der Hausbesitzer ist der eigentliche Eigentümer des Aggregats, und der aktuelle Eigentümer ist der temporäre Eigentümer.

Die folgende Tabelle beschreibt die grundlegenden Aufgaben, die Sie in den einzelnen Phasen ausführen, und den Zustand der Aggregateigentümer am Ende der Phase. Detaillierte Schritte sind im weiteren Verlauf des Verfahrens aufgeführt:

[cols="25,75"]
|===
| Stufe | Schritte 


| link:stage_1_index.html["Stufe 1: Bereiten Sie sich auf das Upgrade vor"]  a| 
. Führen Sie Vorabprüfungen durch, um zu überprüfen, ob Sie den Vorgang durchführen können.
. Netbootvorgang vorbereiten (optional).


Gesamteigentum am Ende von Phase 1:

* Node1 ist der Hausbesitzer und der aktuelle Besitzer der node1 Aggregate.
* Node2 ist der Hausbesitzer und der aktuelle Besitzer der node2 Aggregate.




| link:stage_2_index.html["Stufe 2: Knoten1 verschieben und ausmustern"]  a| 
. Verschieben Sie Aggregate außerhalb der Root-Ebene von node1 nach node2.
. Verschieben Sie LIFs, die nicht-SAN-Daten-LIFs im Besitz von node1 sind, auf Knoten 2.
. Node1 ausmustern.


Gesamteigentum am Ende von Phase 2:

* Node2 ist der aktuelle Besitzer von node1 Aggregaten.
* Node2 ist der Hausbesitzer und der aktuelle Besitzer von node2 Aggregaten.




| link:stage_3_index.html["Phase 3: Installieren und booten Sie node3"]  a| 
. Installieren und booten Sie node3.
. Legen Sie die FC- oder CNA-Konfiguration fest.
. Ports von node1 nach node3 zuordnen.
. Vergewissern Sie sich, dass node3 erfolgreich installiert wurde.
. Verschieben Sie LIFs, die nicht-SAN-Daten-LIFs im Besitz von node1 sind, von Knoten 2 auf Knoten 3.
. Verschiebung von nicht-Root-Aggregaten im Besitz von node1 von node2 auf node3


Gesamteigentum am Ende von Stufe 3:

* Node3 ist der Hausbesitzer und der aktuelle Besitzer von node1 Aggregaten.
* Node2 ist der Hausbesitzer und der aktuelle Besitzer von node2 Aggregaten.




| link:stage_4_index.html["Phase 4: Knoten2 verschieben und ausmustern"]  a| 
. Verschieben Sie Aggregate ohne Root-Root-Fehler von node2 auf node3.
. Verschieben Sie LIFs, die nicht-SAN-Daten-LIFs im Besitz von node2 sind, auf Knoten 3.
. Node2 ausmustern.


Gesamteigentum am Ende von Stufe 4:

* Node3 ist der Hausbesitzer und aktuelle Besitzer von Aggregaten, die ursprünglich zu node1 gehörten.
* Node2 ist der Hausbesitzer von node2 Aggregaten.
* Node3 ist der aktuelle Besitzer von node2 Aggregaten.




| link:stage_5_index.html["Phase 5: installieren und booten sie node4"]  a| 
. installieren und booten sie node4.
. Legen Sie die FC- oder CNA-Konfiguration auf node4 fest.
. Weisen Sie Ports von node2 nach node4 zu.
. Überprüfen Sie die installation von node4.
. Verschieben von LIFs ohne SAN-Daten im Besitz von node2 von node3 auf node4 und Überprüfen der SAN-LIFs auf node4.


Gesamteigentum am Ende von Stufe 5:

* Node3 ist der Hausbesitzer und aktuelle Besitzer der Aggregate, die ursprünglich zu node1 gehörten.
* Node4 ist der Hausbesitzer und aktuelle Besitzer von Aggregaten, die ursprünglich zu node2 gehörten.




| link:stage_6_index.html["Phase 6: Schließen Sie das Upgrade ab"]  a| 
. Überprüfen Sie, ob das System ordnungsgemäß eingerichtet ist.
. Richten Sie Storage Encryption auf dem neuen Controller-Modul ein.
. Setzen Sie bei Bedarf den SnapMirror Betrieb fort.


|===