---
sidebar: sidebar 
permalink: upgrade-arl-auto/relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node3 
summary: 'Verschieben Sie Aggregate und NAS-Daten-LIFs von Knoten 1 auf Knoten 2 und verschieben Sie die Ressourcen anderer 1 in Knoten 3, wenn Sie Controller mit ONTAP 9.5 auf 9.7 aktualisieren `system controller replace` Befehle.' 
---
= Verschieben von Aggregaten ohne Root-Wurzeln und NAS-Daten-LIFs, die sich im Besitz von node1 befinden, auf Knoten 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie node1 durch Node3 ersetzen können, müssen Sie die nicht-Root-Aggregate und NAS-Daten-LIFs von node1 auf node2 verschieben, bevor Sie die Ressourcen von node1 schließlich in node3 verschieben.

Der Vorgang muss bereits angehalten werden, wenn Sie mit der Aufgabe beginnen. Sie müssen den Vorgang manuell fortsetzen.

Remote-LIFs verarbeiten den Datenverkehr zu SAN-LUNs während des Upgrades. Das Verschieben von SAN-LIFs ist für den Zustand des Clusters oder des Service während des Upgrades nicht erforderlich. Sie müssen überprüfen, ob die LIFs sich in einem ordnungsgemäßen Zustand befinden und sich auf den entsprechenden Ports befinden, nachdem Sie node3 in den Online-Modus versetzt haben.


NOTE: Der Home-Inhaber für die Aggregate und LIFs wird nicht geändert, nur der aktuelle Besitzer wird geändert.

.Schritte
. Wiederaufnahme der Vorgänge für die Aggregatverschiebung und die LIF-Verschiebung von NAS-Daten:
+
`system controller replace resume`

+
Alle Aggregate ohne Root-Root-Root-Root-Daten und LIFs werden von node1 auf node2 migriert.

+
Der Vorgang angehalten, damit Sie überprüfen können, ob alle node1-Aggregate und LIFs für nicht-SAN-Daten in node2 migriert wurden.

. Überprüfen Sie den Status der Aggregatverschiebung und der LIF-Verschiebung von NAS-Daten:
+
`system controller replace show-details`

. Wenn der Vorgang noch angehalten wird, vergewissern Sie sich, dass alle nicht-Root-Aggregate online sind, damit ihr Status bei node2 lautet:
+
`storage aggregate show -node _node2_ -state online -root false`

+
Das folgende Beispiel zeigt, dass die nicht-Root-Aggregate auf node2 online sind:

+
[listing]
----
cluster::> storage aggregate show -node node2 state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
Wenn die Aggregate offline gegangen sind oder in node2 fremd geworden sind, bringen Sie sie mit dem folgenden Befehl auf node2, einmal für jedes Aggregat online:

+
`storage aggregate online -aggregate _aggr_name_`

. Überprüfen Sie, ob alle Volumes auf node2 online sind, indem Sie den folgenden Befehl auf node2 verwenden und seine Ausgabe überprüfen:
+
`volume show -node _node2_ -state offline`

+
Wenn ein Volume auf node2 offline ist, bringen Sie sie mit dem folgenden Befehl auf node2 für jedes Volume online:

+
`volume online -vserver _vserver_name_ -volume _volume_name_`

+
Der `_vserver_name_` Die Verwendung mit diesem Befehl ist in der Ausgabe des vorherigen gefunden `volume show` Befehl.



. [[schritt5]]Wenn die Ports, die derzeit Daten-LIFs hosten, nicht auf der neuen Hardware vorhanden sind, entfernen Sie sie aus der Broadcast-Domäne:
+
`network port broadcast-domain remove-ports`

. Wenn irgendwelche LIFs ausgefallen sind, setzen Sie den Administratorstatus der LIFs auf `up` Geben Sie den folgenden Befehl ein, einmal für jede LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_-home-node _nodename_ -status-admin up`

. Wenn Schnittstellengruppen oder VLANs konfiguriert sind, führen Sie die folgenden Teilschritte aus:
+
.. Wenn Sie sie noch nicht gespeichert haben, notieren Sie die VLAN- und Schnittstellengruppen-Informationen, damit Sie die VLANs und Schnittstellengruppen auf node3 neu erstellen können, nachdem node3 gestartet wurde.
.. Entfernen Sie die VLANs aus den Schnittstellengruppen:
+
`network port vlan delete -node _nodename_ -port _ifgrp_ -vlan-id _VLAN_ID_`

+

NOTE: Befolgen Sie die Korrekturmaßnahme, um alle Fehler zu beheben, die vom befehl vlan delete vorgeschlagen werden.

.. Geben Sie den folgenden Befehl ein und überprüfen Sie seine Ausgabe, um zu sehen, ob Schnittstellengruppen auf dem Node konfiguriert sind:
+
`network port ifgrp show -node _nodename_ -ifgrp _ifgrp_name_ -instance`

+
Das System zeigt Schnittstellengruppeninformationen für den Node an, wie im folgenden Beispiel gezeigt:

+
[listing]
----
cluster::> network port ifgrp show -node node1 -ifgrp a0a -instance
                 Node: node1
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode_lacp
          MAC Address: 02:a0:98:17:dc:d4
   Port Participation: partial
        Network Ports: e2c, e2d
             Up Ports: e2c
           Down Ports: e2d
----
.. Wenn Schnittstellengruppen auf dem Node konfiguriert sind, notieren Sie die Namen dieser Gruppen und der ihnen zugewiesenen Ports. Löschen Sie dann die Ports, indem Sie den folgenden Befehl eingeben, und zwar einmal für jeden Port:
+
`network port ifgrp remove-port -node _nodename_ -ifgrp _ifgrp_name_ -port _netport_`




