---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_up_netapp_volume_encryption_new_module.html 
keywords: set up, netapp volume encryption, controller, module, nve, node 
summary: 'Konfigurieren Sie bei Bedarf das neue Controller-Modul für NVE oder NAE, wenn Sie mithilfe von Controller aktualisieren, die ONTAP 9.5 auf 9.7 ausführen `system controller replace` Befehle.' 
---
= Einrichtung von NetApp Volume oder Aggregate Encryption auf dem neuen Controller-Modul
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn der ersetzte Controller oder der HA-Partner (High Availability, Hochverfügbarkeit) des neuen Controllers NetApp Volume Encryption (NVE) oder NetApp Aggregate Encryption (NAE) verwendet, muss das neue Controller-Modul für NVE oder NAE konfiguriert werden.

.Über diese Aufgabe
Dieses Verfahren umfasst Schritte, die auf dem neuen Controller-Modul ausgeführt werden. Sie müssen den Befehl auf dem richtigen Node eingeben.

[role="tabbed-block"]
====
.ONTAP 9.6 und 9.7
--
*Konfigurieren Sie NVE oder NAE auf Controllern mit ONTAP 9.6 oder 9.7*

.Schritte
. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server weiterhin verfügbar sind, deren Status und ihre Authentifizierungsdaten folgendermaßen sind:
+
`security key-manager key query -node node`

. Fügen Sie die im vorherigen Schritt aufgeführten Verschlüsselungsmanagement-Server der Liste des zentralen Management-Servers des neuen Controllers hinzu:
+
.. Fügen Sie den Schlüsselverwaltungsserver hinzu:
+
`security key-manager -add _key_management_server_ip_address_`

.. Wiederholen Sie den vorherigen Schritt für jeden aufgeführten Key Management Server.
+
Sie können bis zu vier Verschlüsselungsmanagement-Server verknüpfen.

.. Überprüfen Sie, ob die Verschlüsselungsmanagementserver erfolgreich hinzugefügt wurden:
+
`security key-manager show`



. Führen Sie auf dem neuen Controller-Modul den Setup-Assistenten für das Verschlüsselungsmanagement aus, um die wichtigsten Management-Server einzurichten und zu installieren.
+
Sie müssen dieselben Key Management-Server installieren, die auf dem vorhandenen Controller-Modul installiert sind.

+
.. Starten Sie den Setup-Assistenten für den Schlüsselmanagementserver auf dem neuen Knoten:
+
`security key-manager setup -node _new_controller_name_`

.. Führen Sie die Schritte im Assistenten zum Konfigurieren von Verschlüsselungsmanagementservern durch.


. Stellen Sie Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern mit dem neuen Knoten wieder her.
+
** Authentifizierung für externen Schlüsselmanager wiederherstellen:
+
`security key-manager external restore`

+
Für diesen Befehl ist die OKM-Passphrase (Onboard Key Manager) erforderlich.

+
Weitere Informationen finden Sie im Knowledge Base-Artikel https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["So stellen Sie die Konfiguration des externen Schlüsselmanager-Servers aus dem ONTAP-Startmenü wieder her"^].

** Authentifizierung für den OKM wiederherstellen:
+
`security key-manager onboard sync`





--
.ONTAP 9.5
--
*NVE oder NAE auf Controllern mit ONTAP 9.5* konfigurieren

.Schritte
. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server weiterhin verfügbar sind, deren Status und ihre Authentifizierungsdaten folgendermaßen sind:
+
`security key-manager key show`

. Fügen Sie die im vorherigen Schritt aufgeführten Verschlüsselungsmanagement-Server der Liste des zentralen Management-Servers des neuen Controllers hinzu:
+
.. Fügen Sie den Schlüsselverwaltungsserver hinzu:
+
`security key-manager -add _key_management_server_ip_address_`

.. Wiederholen Sie den vorherigen Schritt für jeden aufgeführten Key Management Server.
+
Sie können bis zu vier Verschlüsselungsmanagement-Server verknüpfen.

.. Überprüfen Sie, ob die Verschlüsselungsmanagementserver erfolgreich hinzugefügt wurden:
+
`security key-manager show`



. Führen Sie auf dem neuen Controller-Modul den Setup-Assistenten für das Verschlüsselungsmanagement aus, um die wichtigsten Management-Server einzurichten und zu installieren.
+
Sie müssen dieselben Key Management-Server installieren, die auf dem vorhandenen Controller-Modul installiert sind.

+
.. Starten Sie den Setup-Assistenten für den Schlüsselmanagementserver auf dem neuen Knoten:
+
`security key-manager setup -node _new_controller_name_`

.. Führen Sie die Schritte im Assistenten zum Konfigurieren von Verschlüsselungsmanagementservern durch.


. Stellen Sie Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern mit dem neuen Knoten wieder her.
+
** Authentifizierung für externen Schlüsselmanager wiederherstellen:
+
`security key-manager external restore`

+
Für diesen Befehl ist die OKM-Passphrase (Onboard Key Manager) erforderlich.

+
Weitere Informationen finden Sie im Knowledge Base-Artikel https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["So stellen Sie die Konfiguration des externen Schlüsselmanager-Servers aus dem ONTAP-Startmenü wieder her"^].

** Restore-Authentifizierung für OKM:
+
`security key-manager setup -node _node_name_`





--
====
.Nachdem Sie fertig sind
Überprüfen Sie, ob Volumes offline geschaltet wurden, da Authentifizierungsschlüssel nicht verfügbar waren oder externe Schlüsselverwaltungsserver nicht erreicht werden konnten. Stellen Sie diese Volumes mit der wieder online `volume online` Befehl.
