---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_up_netapp_volume_encryption_new_module.html 
keywords: set up, netapp volume encryption, controller, module, nve, node 
summary: 'Konfigurieren Sie bei Bedarf das neue Controller-Modul für NVE, wenn Sie Controller mit ONTAP 9.5 auf 9.7 aktualisieren `system controller replace` Befehle.' 
---
= Richten Sie NetApp Volume Encryption auf dem neuen Controller-Modul ein
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn der ersetzte Controller oder der HA-Partner des neuen Controllers NetApp Volume Encryption verwendet, müssen Sie das neue Controller-Modul für NetApp Volume Encryption konfigurieren.

.Über diese Aufgabe
Dieses Verfahren umfasst Schritte, die auf dem neuen Controller-Modul ausgeführt werden. Sie müssen den Befehl auf dem richtigen Node eingeben.

.Schritte
. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server weiterhin verfügbar sind, deren Status und ihre Authentifizierungsdaten folgendermaßen sind:
+
[cols="30,70"]
|===
| Für diese ONTAP-Version… | Befehl 


| ONTAP 9.6 oder 9.7 | `security key-manager key query -node node` 


| ONTAP 9.5 | `security key-manager key show` 
|===
. Fügen Sie die im vorherigen Schritt aufgeführten Verschlüsselungsmanagement-Server der Liste des zentralen Management-Servers des neuen Controllers hinzu:
+
.. Fügen Sie den Schlüsselverwaltungsserver hinzu:
+
`security key-manager -add _key_management_server_ip_address_`

.. Wiederholen Sie den vorherigen Schritt für jeden aufgeführten Key Management Server.
+
Sie können bis zu vier Verschlüsselungsmanagement-Server verknüpfen.

.. Überprüfen Sie, ob die Verschlüsselungsmanagementserver erfolgreich hinzugefügt wurden:
+
`security key-manager show`



. Führen Sie auf dem neuen Controller-Modul den Setup-Assistenten für das Verschlüsselungsmanagement aus, um die wichtigsten Management-Server einzurichten und zu installieren.
+
Sie müssen dieselben Key Management-Server installieren, die auf dem vorhandenen Controller-Modul installiert sind.

+
.. Starten Sie den Setup-Assistenten für den Schlüsselmanagementserver auf dem neuen Knoten:
+
`security key-manager setup -node _new_controller_name_`

.. Führen Sie die Schritte im Assistenten zum Konfigurieren von Verschlüsselungsmanagementservern durch.


. Stellen Sie Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern mit dem neuen Knoten wieder her.
+
** Authentifizierung für externen Schlüsselmanager wiederherstellen:
+
`security key-manager external restore`

+
Für diesen Befehl ist die OKM-Passphrase (Onboard Key Manager) erforderlich.

** Restore-Authentifizierung für OKM:
+
[cols="30,70"]
|===
| Für diese ONTAP-Version… | Befehl 


| ONTAP 9.6 oder 9.7 | `security key-manager onboard sync` 


| ONTAP 9.5 | `security key-manager setup -node _node_name_` 
|===




.Nachdem Sie fertig sind
Überprüfen Sie, ob Volumes offline geschaltet wurden, da Authentifizierungsschlüssel nicht verfügbar waren oder externe Schlüsselverwaltungsserver nicht erreicht werden konnten. Stellen Sie diese Volumes mit der wieder online `volume online` Befehl.
