---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_2_index.html 
keywords: Prepare nodes for upgrade, storage encryption, KMS, key management server, stage 2 
summary: 'Phase 2-Prozessreihenfolge für ein ARL-Upgrade mit `system controller replace` Befehle auf Controllern mit ONTAP 9.5 zu 9.7.' 
---
= Phase-2-Übersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Während Phase 2 werden node1-Aggregate und NAS-Daten-LIFs in Knoten 2 verschoben. Dieser Prozess ist weitgehend automatisiert; der Vorgang hält an, damit Sie seinen Status überprüfen können. Sie müssen den Vorgang manuell fortsetzen. Bei Bedarf verschieben Sie fehlerhafte oder Vetos Aggregate. Sie zeichnen auch die erforderlichen node1-Informationen auf, nehmen Node1 außer Betrieb und bereiten den Netzboot node3 und node4 später im Verfahren vor.

.Schritte
. link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["Verschieben von Aggregaten ohne Root-Wurzeln und NAS-Daten-LIFs, die sich im Besitz von node1 befinden, auf Knoten 2"]
. link:relocate_failed_or_vetoed_aggr.html["Verschiebung ausgefallener oder Vetos von Aggregaten"]
. link:retire_node1.html["Node1 ausmustern"]
. link:prepare_for_netboot.html["Vorbereitungen für den Netzboot"]

