---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_3_index.html 
keywords: stage 3, install node3, non-SAN data LIFs, non-root aggregates 
summary: 'Phase 3-Prozessreihenfolge für ein ARL-Upgrade mit `system controller replace` Befehle auf Controllern mit ONTAP 9.5 zu 9.7.' 
---
= Phase-3-Übersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Phase 3 installieren und booten Sie node3, ordnen Sie die Cluster- und Node-Management-Ports von node1 zu node3 zu und überprüfen die Installation node3. Wenn erforderlich, legen Sie die FC- oder UTA/UTA2-Konfiguration auf node3 fest und bestätigen, dass node3 Quorum beigetreten ist. Außerdem werden die LIFs für NAS-Daten-LIFs und nicht-Root-Aggregate von node2 auf node3 verschoben und Sie überprüfen, ob die SAN-LIFs auf node3 vorhanden sind.

.Schritte
. link:install_boot_node3.html["Installieren und booten Sie node3"]
. link:set_fc_or_uta_uta2_config_on_node3.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node3 fest"]
. link:map_ports_node1_node3.html["Ports von node1 nach node3 zuordnen"]
. link:join_quorum_node_has_different_ports_stage3.html["Beitritt zum Quorum, wenn ein Knoten über einen anderen Satz von Netzwerkports verfügt"]
. link:verify_node3_installation.html["Überprüfen Sie die Installation von node3"]
. link:move_non_root_aggr_nas_lifs_node1_from_node2_to_node3.html["Verschieben Sie Aggregate ohne Root-Root-Fehler und NAS-Daten-LIFs, die sich im Besitz von node1 befinden, von node2 auf node3"]

