---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_5_index.html 
keywords: install, boot, node4, node2, node-management,  stage 5 
summary: 'Phase 5-Prozessreihenfolge für ein ARL-Upgrade mit `system controller replace` Befehle auf Controllern mit ONTAP 9.5 zu 9.7.' 
---
= Phase 5: installieren und booten sie node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Phase 5 installieren und booten Sie node4, ordnen das Cluster und die Node-Management-Ports von node2 nach node4 zu und überprüfen die Installation von node4. Sie verschieben außerdem die NAS-Daten-LIFs, die Eigentum von node2 sind, von node3 auf node4 und verschieben die Aggregate von node2 auf node4.

.Schritte
. link:install_boot_node4.html["installieren und booten sie node4"]
. link:set_fc_or_uta_uta2_config_node4.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node4 fest"]
. link:map_ports_node2_node4.html["Weisen Sie Ports von node2 nach node4 zu"]
. link:join_quorum_node_has_different_ports_stage5.html["Fügen Sie dem Quorum bei, wenn ein Node über einen anderen Satz an Netzwerkports verfügt"]
. link:verify_node4_installation.html["Überprüfen Sie die installation von node4"]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html["Verschieben Sie Aggregate ohne Root-Root-Fehler und NAS-Daten-LIFs, die sich im Besitz von node2 befinden, von node3 auf node4"]

