= Konfigurieren Sie FC-Ports auf node4
:allow-uri-read: 




== Konfigurieren Sie FC-Ports auf node4

Wenn Knoten 4 über FC-Ports verfügt (entweder integriert oder auf einem zusätzlichen FC-Adapter), müssen Sie die Portkonfigurationen auf dem Knoten festlegen, bevor Sie ihn in Betrieb nehmen, da die Ports bei der Auslieferung der Systeme nicht vorkonfiguriert sind.  Wenn Sie die Ports nicht wie erforderlich konfigurieren, kann es zu einer Dienstunterbrechung kommen.

.Bevor Sie beginnen
Sie müssen die Werte der FC-Port-Einstellungen von node2 haben, die Sie im Abschnitt gespeichert haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"].

.Über diese Aufgabe
Sie können diesen Abschnitt überspringen, wenn Ihr System über keine FC-Konfigurationen verfügt. Wenn Ihr System über integrierte UTA/UTA2-Ports oder einen UTA/UTA2-Adapter verfügt, konfigurieren Sie sie in <<UTA/UTA2-Ports auf node4 prüfen und konfigurieren>>.


IMPORTANT: Geben Sie die Befehle in diesem Abschnitt an der Shell-Eingabeaufforderung im Wartungsmodus ein.

.Schritte
. Zeigen Sie Informationen zu allen FC- und konvergenten Netzwerkadaptern auf dem System an:
+
`system node hardware unified-connect show`

. Vergleichen Sie die FC-Einstellungen auf node4 mit den Einstellungen, die Sie zuvor aus node1 erfasst haben.
. Ändern Sie die FC-Ports auf node4 nach Bedarf:
+
** So programmieren Sie als Zielports:
+
`ucadmin modify -m fc -t target _adapter_`

+
Zum Beispiel: `ucadmin modify -m fc -t target 2a`

** So programmieren Sie Initiator-Ports:
+
`ucadmin modify -m fc -t initiator _adapter_`

+
`-t` Ist der FC4-Typ: Target oder Initiator.

+
Zum Beispiel: `ucadmin modify -m fc -t initator 2b`



. Stoppen Sie den Knoten:
+
`halt`

. Booten Sie das System über die LOADER-Eingabeaufforderung:
+
`boot_ontap menu`

. Nachdem Sie den Befehl eingegeben haben, warten Sie, bis das System an der Eingabeaufforderung der Boot-Umgebung angehalten wird.
. Wählen Sie die Option `5` Wählen Sie im Bootmenü für den Wartungsmodus aus.

