= 
:allow-uri-read: 


. [[step7]]Netzboot auf Node3 durchführen:
+
[cols="30,70"]
|===
| Für... | Dann... 


| Systeme der FAS/AFF8000 Serie | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| Alle anderen Systeme | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
Der `<path_to_the_web-accessible_directory>` Sollten Sie dazu führen, wo Sie das heruntergeladen haben `<ontap_version>_image.tgz` Im Abschnitt link:prepare_for_netboot.html["Vorbereitungen für den Netzboot"].

+

NOTE: Unterbrechen Sie den Startvorgang nicht.

. [[Schritt8]] im Startmenü Option wählen `(7) Install new software first`.
+
Mit dieser Menüoption wird das neue ONTAP-Image auf das Startgerät heruntergeladen und installiert.

+

NOTE: Ignorieren Sie die folgende Meldung: `This procedure is not supported for Non-Disruptive Upgrade on an HA pair`. Der Hinweis gilt für unterbrechungsfreie Upgrades der ONTAP und keine Upgrades von Controllern. Aktualisieren Sie den neuen Node immer als Netzboot auf das gewünschte Image. Wenn Sie eine andere Methode zur Installation des Images auf dem neuen Controller verwenden, wird möglicherweise das falsche Image installiert. Dieses Problem gilt für alle ONTAP Versionen.

. [[steep9]] Wenn Sie aufgefordert werden, den Vorgang fortzusetzen, geben Sie ein `y`, Und wenn Sie zur Eingabe des Pakets aufgefordert werden, geben Sie die URL ein:
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. [[Schritt10]]Vervollständigen Sie die folgenden Teilschritte, um das Controller-Modul neu zu starten:
+
.. Eingabe `n` So überspringen Sie die Backup-Recovery, wenn folgende Eingabeaufforderung angezeigt wird:
+
`Do you want to restore the backup configuration now? {y|n}`

.. Eingabe `y` Um den Neustart zu starten, wenn die folgende Eingabeaufforderung angezeigt wird:
+
`The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}`

+
Das Controller-Modul wird neu gestartet, stoppt aber im Startmenü, da das Boot-Gerät neu formatiert wurde und die Konfigurationsdaten wiederhergestellt werden müssen.



. [[Schritt11]]Wählen Sie den Wartungsmodus aus `5` Öffnen Sie das Startmenü, und geben Sie ein `y` Wenn Sie aufgefordert werden, den Startvorgang fortzusetzen.
. [[steep12]]] Überprüfen Sie, ob Controller und Chassis als ha konfiguriert sind:
+
`ha-config show`

+
Das folgende Beispiel zeigt die Ausgabe von `ha-config show` Befehl:

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: Das System zeichnet in einem PROM auf, ob es sich um ein HA-Paar oder eine eigenständige Konfiguration handelt. Der Status muss auf allen Komponenten im Standalone-System oder im HA-Paar der gleiche sein.

. [[Schritt13]]Wenn Controller und Chassis nicht als ha konfiguriert sind, verwenden Sie zum Korrigieren der Konfiguration die folgenden Befehle:
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Wenn Sie eine MetroCluster-Konfiguration haben, verwenden Sie die folgenden Befehle, um den Controller und das Chassis zu ändern:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[steep14]]Wartungsmodus beenden:
+
`halt`

+
Unterbrechen Sie den Autoboot, indem Sie auf drücken `Ctrl-C` An der Eingabeaufforderung für die Boot-Umgebung.

. [[ste15]] auf node2 überprüfen Sie Datum, Uhrzeit und Zeitzone des Systems:
+
`date`

. [[step16]]prüfen Sie das Datum in node3 mithilfe des folgenden Befehls an der Eingabeaufforderung der Boot-Umgebung:
+
`show date`

. [[step17]]Geben Sie bei Bedarf das Datum auf node3 ein:
+
`set date _mm/dd/yyyy_`

. [[step18]] auf node3 überprüfen Sie die Zeit mit dem folgenden Befehl an der Eingabeaufforderung der Boot-Umgebung:
+
`show time`

. [[ste19]]Ggf. Die Zeit auf node3 einstellen:
+
`set time _hh:mm:ss_`

. [[ste20]]Geben Sie bei Bedarf die Partner-System-ID auf node3 ein:
+
`setenv partner-sysid _node2_sysid_`

+
.. Einstellungen speichern:
+
`saveenv`



. [[Auto_install3_step21]]auf dem neuen Knoten, in Boot-Loader, das `partner-sysid` Parameter muss festgelegt werden. Für Knoten 3, `partner-sysid` Muss der von node2 sein. Überprüfen Sie die `partner-sysid` Für Knoten 3:
+
`printenv partner-sysid`

. [[steep22]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="30,70"]
|===
| Wenn Ihr System... | Beschreibung 


| Verfügt über Festplatten und keinen Back-End-Speicher | Gehen Sie zu <<auto_install3_step23,Schritt 23>> 


| Ist ein V-Series System oder ein System mit FlexArray Virtualisierungssoftware, die mit Storage-Arrays verbunden ist  a| 
.. Weiter mit Abschnitt link:set_fc_or_uta_uta2_config_on_node3.html["Einstellen der FC- oder UTA/UTA2-Konfiguration auf node3"] Und vervollständigen Sie die Unterabschnitte in diesem Abschnitt.
.. Kehren Sie zu diesem Abschnitt zurück, und führen Sie die verbleibenden Schritte aus. Beginnen Sie mit <<auto_install3_step23,Schritt 23>>.


*Wichtig*: Sie müssen FC Onboard-Ports, CNA Onboard Ports und CNA-Karten neu konfigurieren, bevor Sie ONTAP auf der V-Serie oder dem System mit FlexArray Virtualisierungssoftware booten.

|===
. [[Auto_install3_steep23]]Fügen Sie die FC-Initiator-Ports des neuen Node zu den Switch-Zonen hinzu.
+
Wenn Ihr System über ein Tape-SAN verfügt, müssen Sie das Zoning für die Initiatoren benötigen. Ändern Sie gegebenenfalls die integrierten Ports an den Initiator, indem Sie auf das verweisen link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Konfigurieren von FC-Ports auf node3"]. Weitere Anweisungen zum Zoning finden Sie in der Dokumentation des Storage-Arrays und des Zoning.

. [[steep24]]Fügen Sie die FC-Initiator-Ports dem Speicher-Array als neue Hosts hinzu, und ordnen Sie die Array-LUNs den neuen Hosts zu.
+
Anweisungen finden Sie in der Dokumentation für das Storage-Array und Zoning.

. [[Schritt25]]Ändern Sie die WWPN-Werte (Worldwide Port Name) in den Host- oder Volume-Gruppen, die mit Array-LUNs auf dem Speicher-Array verknüpft sind.
+
Durch die Installation eines neuen Controller-Moduls werden die WWPN-Werte geändert, die den einzelnen integrierten FC-Ports zugeordnet sind.

. [[Schritt26]]Wenn Ihre Konfiguration ein Switch-basiertes Zoning verwendet, passen Sie das Zoning an die neuen WWPN-Werte an.
. [[steep27]]] stellen Sie die ein `bootarg.storageencryption.support` Und `kmip.init.maxwait` Variablen, um eine Boot-Schleife zu vermeiden, nachdem die node1-Konfiguration geladen wurde.
+
Falls Sie dies noch nicht bereits in der Prozedur getan haben, lesen Sie den Artikel in der Knowledge Base https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_tell_I_have_FIPS_drives_installed["Wie zu sagen ist, dass ich FIPS-Laufwerke installiert habe"^] Ermitteln der Art der verwendeten Self-Encrypting Drives.

+
[cols="35,65"]
|===
| Wenn die folgenden Laufwerke verwendet werden… | Dann… 


| NetApp Storage Encryption (NSE) Laufwerke, die der Self-Encryption-Anforderung von FIPS 140-2 Level 2 entsprechen  a| 
** `setenv bootarg.storageencryption.support *true*`
** `setenv kmip.init.maxwait off`




| NetApp ohne FIPS SEDs  a| 
** `setenv bootarg.storageencryption.support *false*`
** `setenv kmip.init.maxwait off`


|===
+
[NOTE]
====
** FIPS-Laufwerke können nicht mit anderen Laufwerkstypen auf demselben Node oder HA-Paar kombiniert werden.
** SEDs können mit Laufwerken ohne Verschlüsselung auf demselben Node oder HA-Paar kombiniert werden.
** Wenn ein Stromausfall auftritt, nachdem Sie den festgelegt haben `kmip.init.maxwait` Variabel auf `off`Wenden Sie sich an den technischen Support, um Hilfe zu erhalten, um möglichen Datenverlust zu vermeiden.
** Sobald das Controller-Upgrade auf dem HA-Paar abgeschlossen ist, müssen Sie den festlegen `kmip.init.maxwait` Variabel. Siehe link:ensure_new_controllers_are_set_up_correctly.html["Vergewissern Sie sich, dass die neuen Controller ordnungsgemäß eingerichtet sind"].


====
. [[Schritt28]]Boot-Knoten im Boot-Menü:
+
`boot_ontap menu`

+
Wenn Sie keine FC- oder UTA/UTA2-Konfiguration haben, ausführen link:set_fc_or_uta_uta2_config_on_node3.html#auto9597_check_node3_step15["UTA/UTA2-Ports in node3, Schritt 15, prüfen und konfigurieren"] Damit node3 die Festplatten von node1 erkennen kann.


