= Management der Storage-Verschlüsselung mit dem Onboard Key Manager
:allow-uri-read: 




[[manage-storage-encryption-using-the-onboard-key-manager]]
== Management der Storage-Verschlüsselung mit dem Onboard Key Manager

Verwenden Sie den Onboard Key Manager (OKM) zur Verwaltung der Verschlüsselungsschlüssel. Wenn Sie den OKM eingerichtet haben, müssen Sie die Passphrase und die Sicherungsdaten vor Beginn des Upgrades notieren.

.Schritte
. Notieren Sie die Cluster-weite Passphrase.
+
Dies ist die Passphrase, die eingegeben wurde, als das OKM mit der CLI oder REST-API konfiguriert oder aktualisiert wurde.

. Überprüfen Sie die Passphrase und den Schlüsselmanager-Vorgang:
+
`security key-manager onboard sync`

+
Geben Sie bei Aufforderung die clusterweite OKM-Passphrase ein, die Sie im vorherigen Schritt aufgezeichnet haben.

. Vergewissern Sie sich, dass cc-mode aktiviert ist, indem Sie die Ausgabe des folgenden Befehls überprüfen:
+
`security key-manager config show`

. Sichern Sie die Key-Manager-Informationen:
+
`security key-manager onboard show-backup`


