= UTA/UTA2-Ports in node3 prüfen und konfigurieren
:allow-uri-read: 




== UTA/UTA2-Ports in node3 prüfen und konfigurieren

Wenn node3 Onboard UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Konfiguration der Ports überprüfen und sie möglicherweise neu konfigurieren, je nachdem, wie Sie das aktualisierte System verwenden möchten.

.Bevor Sie beginnen
Sie müssen die richtigen SFP+ Module für die UTA/UTA2-Ports besitzen.

.Über diese Aufgabe
Wenn Sie einen Unified Target Adapter (UTA/UTA2)-Port für FC verwenden möchten, müssen Sie zuerst überprüfen, wie der Port konfiguriert ist.


NOTE: Bei NetApp Marketingmaterialien wird möglicherweise der Begriff UTA2 verwendet, um sich auf CNA-Adapter und Ports zu beziehen. Allerdings verwendet die CLI den Begriff CNA.

Sie können die `ucadmin show` Befehl zum Anzeigen oder Überprüfen der aktuellen Portkonfiguration, wie in der folgenden Beispielausgabe gezeigt:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
DIE UTA2-Ports können im nativen FC-Modus oder im UTA/UTA2-Modus konfiguriert werden. Der FC-Modus unterstützt FC Initiator und FC Target. Der UTA-/UTA2-Modus ermöglicht gleichzeitige NIC- und FCoE-Traffic über die gleiche 10-GbE-SFP+-Schnittstelle und unterstützt FC-Ziele.

Möglicherweise finden Sie UTA/UTA2-Anschlüsse auf einem Zusatzadapter oder auf dem Controller-Motherboard und diese weisen die folgenden Konfigurationen auf. Sie sollten jedoch die Konfiguration der UTA/UTA2-Anschlüsse auf dem Node3 überprüfen und diese gegebenenfalls ändern:

* UTA-/UTA2-Karten, die bestellt werden, werden vor dem Versand konfiguriert, um die von Ihnen geforderte Persönlichkeit zu erhalten.
* DIE UTA2-Karten, die separat vom Controller bestellt werden, werden mit der standardmäßigen FC-Zielgruppe ausgeliefert.
* Onboard UTA/UTA2-Ports auf neuen Controllern werden vor dem Versand konfiguriert, um die Persönlichkeit zu erhalten, die Sie anfordern.
+

WARNING: Sie müssen sich im Wartungsmodus befinden, um UTA/UTA2-Ports zu konfigurieren.  Geben Sie die Befehle in diesem Abschnitt an der Shell-Eingabeaufforderung im Wartungsmodus ein.



.Schritte
. Wenn das aktuelle SFP+-Modul nicht mit der gewünschten Verwendung übereinstimmt, ersetzen Sie es durch das richtige SFP+-Modul.
+
Wenden Sie sich an Ihren NetApp Ansprechpartner, um das richtige SFP+ Modul zu erhalten.

. Überprüfen Sie die UTA/UTA2-Porteinstellungen:
+
`ucadmin show`

+
Untersuchen Sie die Ausgabe und stellen Sie fest, ob die UTA/UTA2-Ports die gewünschte Persönlichkeit haben.

+
Die Ausgabe im folgenden Beispiel zeigt, dass sich der Typ des Adapters „1b“ in „Initiator“ ändert und dass sich der Modus der Adapter „2a“ und „2b“ in „cna“ ändert.  Der CNA-Modus ermöglicht Ihnen, die Karte als Netzwerkadapter zu verwenden.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. Führen Sie eine der folgenden Aktionen durch:
+
[cols="30,70"]
|===
| Wenn die UTA/UTA2-Ports... | Dann… 


| Haben Sie nicht die Persönlichkeit, die Sie wollen | Gehe zu<<auto_check3_step4,Schritt 4>> . 


| Haben Sie die Persönlichkeit, die Sie wollen | Überspringen Sie Schritt 4 bis Schritt 8 und gehen Sie zu<<auto_check3_step9,Schritt 9>> . 
|===
. [[auto_check3_step4]]Führen Sie eine der folgenden Aktionen aus:
+
[cols="30,70"]
|===
| Wenn Sie konfigurieren... | Dann… 


| Ports auf einer UTA/UTA2-Karte | Gehe zu<<auto_check3_step5,Schritt 5>> 


| Onboard UTA/UTA2-Ports | Überspringen Sie Schritt 5 und gehen Sie zu<<auto_check3_step6,Schritt 6>> . 
|===
. [[auto_check3_step5]]Wenn sich der Adapter im Initiatormodus befindet und der UTA/UTA2-Port online ist, schalten Sie den UTA/UTA2-Port offline:
+
`storage disable adapter <adapter_name>`

+
Adapter im Zielmodus sind im Wartungsmodus automatisch offline.

. [[auto_check3_step6]]Wenn die aktuelle Konfiguration nicht der gewünschten Verwendung entspricht, ändern Sie die Konfiguration nach Bedarf:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` Ist der Persönlichkeitsmodus, `fc` Oder `cna`.
** `-t` Ist der Typ FC4, `target` Oder `initiator`.
+

NOTE: Sie müssen den FC-Initiator für Bandlaufwerke und MetroCluster -Konfigurationen verwenden.  Sie müssen das FC-Ziel für SAN-Clients verwenden.



. Schalten Sie alle Zielports online, indem Sie für jeden Port einmal den folgenden Befehl eingeben:
+
`storage enable adapter <adapter_name>`

. Verkabeln Sie den Port.

