= 
:allow-uri-read: 


. [[Auto_check3_step17]]Drücken Sie `Ctrl-C` Während des automatischen Bootens, um den Node auf dem zu beenden `LOADER>` Eingabeaufforderung:
. [[Schritt18]]wechseln Sie an der Loader-Eingabeaufforderung in den Wartungsmodus:
+
`boot_ontap maint`

. [[ste19]]] im Wartungsmodus werden alle zuvor festgelegten Initiator-Ports angezeigt, die sich jetzt im Zielmodus befinden:
+
`ucadmin show`

+
Ändern Sie die Ports zurück in den Initiatormodus:

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. [[steep20]]Überprüfen Sie, ob die Ports in den Initiatormodus geändert wurden:
+
`ucadmin show`

. [[step21]]Wartungsmodus beenden:
+
`halt`

+
[NOTE]
====
Wenn Sie ein Upgrade von einem System durchführen, das externe Festplatten unterstützt, auf ein System, das auch externe Festplatten unterstützt, gehen Sie zu <<auto_check3_step22,Schritt 22>>.

Wenn Sie ein Upgrade von einem System durchführen, das externe Festplatten unterstützt, auf ein System, das sowohl interne als auch externe Festplatten, wie z. B. ein AFF A800 System, unterstützt, finden Sie unter <<auto_check3_step23,Schritt 23>>.

====
. [[Auto_check3_step22]]an der Loader-Eingabeaufforderung booten:
+
`boot_ontap menu`

+
Beim Booten erkennt der Node jetzt alle Festplatten, die zuvor ihm zugewiesen waren, und kann wie erwartet gebootet werden.

+
Wenn die Cluster-Knoten, die Sie ersetzen, die Root-Volume-Verschlüsselung verwenden, kann die ONTAP-Software die Volume-Informationen nicht von den Festplatten lesen. Stellen Sie die Schlüssel für das Root-Volume wieder her:

+
.. Zurück zum speziellen Startmenü:
`LOADER> boot_ontap menu`
+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Wählen Sie *(10) Set Onboard Key Manager Recovery Secrets*
.. Eingabe `y` An der folgenden Eingabeaufforderung:
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. Geben Sie an der Eingabeaufforderung die Passphrase für das Schlüsselmanagement ein.
.. Geben Sie bei Aufforderung die Backup-Daten ein.
+

NOTE: Sie müssen die Passphrase und Sicherungsdaten im erhalten haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"] Abschnitt dieses Verfahrens.

.. Nachdem das System wieder zum speziellen Startmenü gestartet wurde, führen Sie die Option *(1) Normal Boot* aus
+

NOTE: In dieser Phase ist möglicherweise ein Fehler aufgetreten. Wenn ein Fehler auftritt, wiederholen Sie die Teilschritte in <<auto_check3_step22,Schritt 22>> Bis das System ordnungsgemäß gebootet wird.



. [[Auto_check3_step23]]Wenn Sie ein Upgrade von einem System mit externen Festplatten auf ein System durchführen, das interne und externe Festplatten unterstützt (z. B. AFF A800 Systeme), setzen Sie das node1-Aggregat als Root-Aggregat ein, um zu bestätigen, dass node3 aus dem Root-Aggregat von node1 bootet. Zum Festlegen des Root-Aggregats rufen Sie das Boot-Menü auf und wählen dann Option `5` Um in den Wartungsmodus zu wechseln.
+

CAUTION: *Die folgenden Teilschritte müssen in der angegebenen Reihenfolge ausgeführt werden; andernfalls kann es zu einem Ausfall oder sogar zu Datenverlust kommen.*

+
Im folgenden Verfahren wird node3 vom Root-Aggregat von node1 gestartet:

+
.. Wechseln in den Wartungsmodus:
+
`boot_ontap maint`

.. Überprüfen Sie die RAID-, Plex- und Prüfsummeninformationen für das node1 Aggregat:
+
`aggr status -r`

.. Überprüfen Sie den Status des node1-Aggregats:
+
`aggr status`

.. Bei Bedarf das node1 Aggregat online bringen:
+
`aggr_online root_aggr_from___node1__`

.. Verhindern Sie, dass das node3 vom ursprünglichen Root-Aggregat gebootet wird:
+
`aggr offline _root_aggr_on_node3_`

.. Legen Sie das node1-Root-Aggregat als das neue Root-Aggregat für node3 fest:
+
`aggr options aggr_from___node1__ root`

.. Überprüfen Sie, ob das Root-Aggregat von node3 offline ist und das Root-Aggregat für die von node1 hergebrachten Festplatten online ist und in den Root-Status eingestellt ist:
+
`aggr status`

+

NOTE: Wenn der vorherige Unterschritt nicht ausgeführt wird, kann node3 vom internen Root-Aggregat booten, oder es kann dazu führen, dass das System eine neue Cluster-Konfiguration übernimmt oder Sie aufgefordert werden, eine zu identifizieren.

+
Im Folgenden wird ein Beispiel für die Befehlsausgabe angezeigt:

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



