= Erfahren Sie mehr über ONTAP-Lizenzierung
:allow-uri-read: 




[[learn-about-ontap-licensing]]
== Erfahren Sie mehr über ONTAP-Lizenzierung

Einige Funktionen erfordern Lizenzen, die als _Packages_ ausgegeben werden, die eine oder mehrere Funktionen enthalten. Jeder Node im Cluster muss über seinen eigenen Schlüssel für jede Funktion im Cluster verfügen.

Wenn Sie keine neuen Lizenzschlüssel haben, stehen dem neuen Controller derzeit lizenzierte Funktionen im Cluster zur Verfügung. Durch die Verwendung nicht lizenzierter Funktionen auf dem Controller können Sie jedoch möglicherweise die Einhaltung Ihrer Lizenzvereinbarung verschließen. Sie sollten daher nach Abschluss des Upgrades den neuen Lizenzschlüssel oder die neuen Schlüssel für den neuen Controller installieren.

Siehe link:other-references.html["Quellen"] für einen Link zur _NetApp Support Site_, auf der neue 28-stellige Lizenzschlüssel für ONTAP erhältlich sind. Die Schlüssel sind im Bereich _My Support_ unter _Software licenses_ verfügbar. Falls die benötigten Lizenzschlüssel auf der Seite nicht vorhanden sind, kann Ihr NetApp Vertriebsmitarbeiter kontaktiert werden.

Detaillierte Informationen zur ONTAP-Lizenzierung finden Sie in link:other-references.html["Quellen"] dem _System Administration Reference_.
