= Konfigurieren Sie FC-Ports auf node3
:allow-uri-read: 




== Konfigurieren Sie FC-Ports auf node3

Wenn Knoten3 über FC-Ports verfügt (entweder integriert oder auf einem zusätzlichen FC-Adapter), müssen Sie die Portkonfigurationen auf dem Knoten festlegen, bevor Sie ihn in Betrieb nehmen, da die Ports bei der Auslieferung der Systeme nicht vorkonfiguriert sind.  Wenn Sie die Ports nicht konfigurieren, kann es zu einer Dienstunterbrechung kommen.

.Bevor Sie beginnen
Sie müssen die Werte der FC-Port-Einstellungen von node1 haben, die Sie im Abschnitt gespeichert haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"].

.Über diese Aufgabe
Sie können diesen Abschnitt überspringen, wenn Ihr System über keine FC-Konfigurationen verfügt. Wenn Ihr System über integrierte UTA/UTA2-Ports oder eine UTA/UTA2-Karte verfügt, konfigurieren Sie sie in <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.


IMPORTANT: Geben Sie die Befehle in diesem Abschnitt an der Shell-Eingabeaufforderung im Wartungsmodus ein.

.Schritte
. Vergleichen Sie die FC-Einstellungen auf Knoten3 mit den Einstellungen, die Sie zuvor von Knoten1 erfasst haben.
. Führen Sie eine der folgenden Aktionen aus, um die FC-Ports auf Knoten3 nach Bedarf zu ändern:
+
Im Wartungsmodus (Option 5 im Bootmenü):

+
** So programmieren Sie als Zielports:
+
`ucadmin modify -m fc -t target <adapter>`

+
Zum Beispiel: `ucadmin modify -m fc -t target 2a`

** So programmieren Sie Initiator-Ports:
+
`ucadmin modify -m fc -t initiator <adapter>`

+
Zum Beispiel: `ucadmin modify -m fc -t initator 2b`



. Überprüfen Sie die neuen Einstellungen, indem Sie den folgenden Befehl verwenden und die Ausgabe untersuchen:
+
`ucadmin show`

. Stoppen Sie den Knoten:
+
`halt`

. Booten Sie das System über die LOADER-Eingabeaufforderung:
+
`boot_ontap menu`

. Nachdem Sie den Befehl eingegeben haben, warten Sie, bis das System an der Eingabeaufforderung der Boot-Umgebung angehalten wird.
. Wählen Sie die Option `5` Wählen Sie im Bootmenü für den Wartungsmodus aus.

