= Konfigurieren Sie FC-Ports auf node3
:allow-uri-read: 




== Konfigurieren Sie FC-Ports auf node3

Wenn Knoten3 über FC-Ports verfügt (entweder integriert oder auf einem zusätzlichen FC-Adapter), müssen Sie die Portkonfigurationen auf dem Knoten festlegen, bevor Sie ihn in Betrieb nehmen, da die Ports bei der Auslieferung der Systeme nicht vorkonfiguriert sind.  Wenn Sie die Ports nicht konfigurieren, kann es zu einer Dienstunterbrechung kommen.

.Bevor Sie beginnen
Sie müssen die Werte der FC-Port-Einstellungen von node1 haben, die Sie in gespeichert haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"].

.Über diese Aufgabe
Sie können diesen Abschnitt überspringen, wenn Ihr System über keine FC-Konfigurationen verfügt. Wenn Ihr System über integrierte UTA/UTA2-Ports oder eine UTA/UTA2-Karte verfügt, konfigurieren Sie sie in <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.


IMPORTANT: Geben Sie die Befehle in diesem Abschnitt an der Cluster-Eingabeaufforderung ein.

.Schritte
. Zeigt Informationen zu allen FC- und konvergenten Netzwerkadaptern im System an.
+
`system node hardware unified-connect show`

. Vergleichen Sie die FC-Einstellungen von Knoten3 mit den Einstellungen, die Sie zuvor von Knoten1 erfasst haben.
. [[man_config_3_step3]]Führen Sie eine der folgenden Aktionen aus:
+
[cols="35,65"]
|===
| Wenn die FC-Standardeinstellungen auf den neuen Nodes sind... | Dann... 


| Das gleiche wie jene, die ihr auf Node1 gefangen habt | Gehe zu<<man_config_3_step9,Schritt 9>> . 


| Anders als jene, die du auf Node1 gefangen hast | Gehe zu<<man_config_3_step4,Schritt 4>> . 
|===
. [[man_config_3_step4]]Ändern Sie die FC-Ports auf Knoten3 nach Bedarf, indem Sie einen der folgenden Befehle eingeben:
+
** So programmieren Sie Zielanschlüsse:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** So programmieren Sie Initiator-Ports:
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` Ist der FC4-Typ: Target oder Initiator.



. Überprüfen Sie die neuen Einstellungen, indem Sie den folgenden Befehl eingeben und die Ausgabe prüfen:
+
`system node hardware unified-connect show`

. Beenden des Wartungsmodus:
+
`halt`

. Nachdem Sie den Befehl eingegeben haben, warten Sie, bis das System an der Eingabeaufforderung der Boot-Umgebung angehalten wird.
. Booten Sie Knoten3 an der Eingabeaufforderung der Boot-Umgebung:
+
`boot_ontap`

. [[man_config_3_step9]]Führen Sie eine der folgenden Aktionen aus:
+
** Wenn node3 eine UTA/UTA2-Karte oder Onboard-Ports zu UTA/UTA2 hat, gehen Sie zu <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.
** Wenn node3 keine UTA/UTA2-Karte oder Onboard-Ports UTA/UTA2 hat, überspringen <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>> Und gehen Sie zu link:map_ports_node1_node3.html["Ports von node1 nach node3 zuordnen"].



