= 
:allow-uri-read: 


. [[man_install3_step17] Wenn die auf node3 installierte ONTAP-Version dieselbe oder höher als die auf node1 installierte Version von ONTAP 9 ist, führen Sie die Liste auf und weisen Sie Festplatten der neuen node3 neu zu:
+
`boot_ontap`

+

WARNING: Wenn dieser neue Node jemals in einem anderen Cluster oder HA-Paar verwendet wurde, müssen Sie ausgeführt werden `wipeconfig` Bevor Sie fortfahren. Andernfalls kann es zu Serviceausfällen oder Datenverlusten kommen. Wenden Sie sich an den technischen Support, wenn der Ersatz-Controller zuvor verwendet wurde, insbesondere dann, wenn auf den Controllern ONTAP im 7-Mode ausgeführt wurde.

. Drücken Sie STRG+C, um das Startmenü anzuzeigen.
. [[man_install3_step19]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn das System, das Sie aktualisieren... | Dann... 


| Hat _Not_ die richtige oder aktuelle ONTAP-Version auf node3 | Gehe zu<<man_install3_step13,Schritt 13>> . 


| Verfügt über die richtige oder aktuelle Version von ONTAP auf node3 | Gehe zu<<man_install3_step18,Schritt 18>> . 
|===
. [[man_install3_step13]]Konfigurieren Sie die Netboot-Verbindung, indem Sie eine der folgenden Aktionen auswählen.
+

NOTE: Sie müssen den Management-Port und die IP als Netzboot-Verbindung verwenden. Verwenden Sie keine Daten-LIF-IP, oder sonst kann während des Upgrades ein Datenausfall auftreten.

+
[cols="35,65"]
|===
| Wenn DHCP (Dynamic Host Configuration Protocol) lautet... | Dann... 


| Wird Ausgeführt | Konfigurieren Sie die Verbindung automatisch, indem Sie an der Eingabeaufforderung der Boot-Umgebung den folgenden Befehl eingeben:
`ifconfig e0M -auto` 


| Nicht ausgeführt  a| 
Konfigurieren Sie die Verbindung manuell, indem Sie an der Eingabeaufforderung der Boot-Umgebung den folgenden Befehl eingeben:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` Ist die IP-Adresse des Speichersystems (obligatorisch).
`_netmask_` Ist die Netzwerkmaske des Storage-Systems (erforderlich).
`_gateway_` Ist das Gateway für das Speichersystem (erforderlich).
`_dns_addr_` Ist die IP-Adresse eines Namensservers in Ihrem Netzwerk (optional).
`_dns_domain_` Der Domain Name (DNS) ist der Domain-Name. Wenn Sie diesen optionalen Parameter verwenden, benötigen Sie in der Netzboot-Server-URL keinen vollqualifizierten Domänennamen. Sie benötigen nur den Host-Namen des Servers.


NOTE: Andere Parameter können für Ihre Schnittstelle erforderlich sein. Eingabe `help ifconfig` Details finden Sie in der Firmware-Eingabeaufforderung.

|===
. Führen Sie einen Netboot auf Knoten3 durch:
+
[cols="35,65"]
|===
| Für... | Dann... 


| Systeme der FAS/AFF8000 Serie | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/netboot/kernel` 


| Alle anderen Systeme | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/<ontap_version>_image.tgz` 
|===
+
Der `<path_to_the_web-accessible_directory>` Führt zu der Stelle, an der Sie das heruntergeladen haben `<ontap_version>_image.tgz` In link:prepare_for_netboot.html#man_netboot_Step1["Schritt 1"] Im Abschnitt _Vorbereiten für Netzboot_.

+

NOTE: Unterbrechen Sie den Startvorgang nicht.

. Wählen Sie im Bootmenü zunächst die Option *(7) Neue Software installieren*.
+
Mit dieser Menüoption wird das neue ONTAP-Image auf das Startgerät heruntergeladen und installiert.

+
Ignorieren Sie die folgende Meldung:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
Der Hinweis gilt für unterbrechungsfreie Upgrades der ONTAP und keine Upgrades von Controllern.

+

NOTE: Aktualisieren Sie den neuen Node immer als Netzboot auf das gewünschte Image. Wenn Sie eine andere Methode zur Installation des Images auf dem neuen Controller verwenden, wird möglicherweise das falsche Image installiert. Dieses Problem gilt für alle Versionen von ONTAP. Das Netzboot wird mit der Option kombiniert `(7) Install new software` Entfernt die Startmedien und platziert dieselbe ONTAP-Version-ONTAP auf beiden Bildpartitionen.

. Wenn Sie aufgefordert werden, den Vorgang fortzusetzen, geben Sie `y` , und geben Sie bei der Aufforderung zur Eingabe des Pakets die folgende URL ein:
+
`\http://<web_server_ip>/<path_to_web-accessible_directory>/<ontap_version_image>.tgz`

. Führen Sie die folgenden Teilschritte durch:
+
.. Eingabe `n` So überspringen Sie die Backup-Recovery, wenn folgende Eingabeaufforderung angezeigt wird:
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. Starten Sie den Neustart durch Eingabe `y` Wenn die folgende Eingabeaufforderung angezeigt wird:
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
Das Controller-Modul wird neu gestartet, stoppt aber im Startmenü, da das Boot-Gerät neu formatiert wurde und die Konfigurationsdaten wiederhergestellt werden müssen.



. [[man_install3_step18]]Wählen Sie *(5) Wartungsmodus-Boot* durch Eingabe `5` und geben Sie dann ein `y` wenn Sie aufgefordert werden, mit dem Booten fortzufahren.
. [[man_install3_step26]]bevor Sie fortfahren, fahren Sie mit fort link:set_fc_uta_uta2_config_node3.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node3 fest"] Um alle erforderlichen Änderungen an den FC- oder UTA/UTA2-Ports auf dem Node vorzunehmen.
+
Nehmen Sie die in diesen Abschnitten empfohlenen Änderungen vor, booten Sie den Node neu und wechseln Sie in den Wartungsmodus.

. Suchen Sie die System-ID von Knoten3:
+
`disk show -a`

+
Das System zeigt die System-ID des Node sowie Informationen über seine Festplatten an, wie im folgenden Beispiel dargestellt:

+
[listing]
----
 *> disk show -a
 Local System ID: 536881109
 DISK     OWNER                    POOL  SERIAL   HOME          DR
 HOME                                    NUMBER
 -------- -------------            ----- -------- ------------- -------------
 0b.02.23 nst-fas2520-2(536880939) Pool0 KPG2RK6F nst-fas2520-2(536880939)
 0b.02.13 nst-fas2520-2(536880939) Pool0 KPG3DE4F nst-fas2520-2(536880939)
 0b.01.13 nst-fas2520-2(536880939) Pool0 PPG4KLAA nst-fas2520-2(536880939)
 ......
 0a.00.0               (536881109) Pool0 YFKSX6JG              (536881109)
 ......
----
+

NOTE: Möglicherweise wird die Meldung angezeigt `disk show: No disks match option -a.` Nach Eingabe des Befehls. Dies ist keine Fehlermeldung, sodass Sie mit dem Verfahren fortfahren können.

. [[man_install3_step21]]Weisen Sie die Ersatzfestplatten von Knoten1, alle zum Root gehörenden Festplatten und alle Nicht-Root-Aggregate, die nicht zuvor zu Knoten2 verschoben wurden, neu zulink:relocate_non_root_aggr_node1_node2.html["Verschiebung von nicht-Root-Aggregaten von node1 auf node2"] .
+
Geben Sie das entsprechende Formular des ein `disk reassign` Befehl basierend auf der Frage, ob Ihr System freigegebene Festplatten hat:

+

NOTE: Wenn Sie auf Ihrem System freigegebene Festplatten, Hybrid-Aggregate oder beides haben, müssen Sie die korrekte verwenden `disk reassign` Befehl aus der folgenden Tabelle.

+
[cols="35,65"]
|===
| Wenn Disk-Typ... | Führen Sie dann den Befehl aus... 


| Mit gemeinsamen Festplatten | `disk reassign -s _node1_sysid_ -d _node3_sysid_ -p _node2_sysid_` 


| Ohne gemeinsame Festplatten | `disk reassign -s _node1_sysid_ -d _node3_sysid_` 
|===
+
Für das `_node1_sysid_` Wert: Verwenden Sie die in erfassten Informationen link:record_node1_information.html["Node1-Informationen aufzeichnen"]. Um den Wert für zu erhalten `_node3_sysid_`, Verwenden Sie die `sysconfig` Befehl.

+

NOTE: Der `-p` Die Option ist nur im Wartungsmodus erforderlich, wenn freigegebene Festplatten vorhanden sind.

+
Der `disk reassign` Befehl gibt nur die Festplatten wieder, für die `_node1_sysid_` Ist der aktuelle Eigentümer.

+
Vom System wird die folgende Meldung angezeigt:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?
----
. [[man_install3_steep29]]Geben Sie ein `n`.
+
Vom System wird die folgende Meldung angezeigt:

+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?
----
. [[man_install3_steep30]]Geben Sie ein `y`
+
Vom System wird die folgende Meldung angezeigt:

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)?
----
. [[man_install3_step31]]Geben Sie ein `y`.
. [[man_install3_step32]]Wenn Sie ein Upgrade von einem System mit externen Festplatten auf ein System durchführen, das interne und externe Festplatten unterstützt (zum Beispiel AFF A800 Systeme), setzen Sie das node1-Aggregat als root ein, um zu bestätigen, dass node3 aus dem Root-Aggregat von node1 startet.
+

WARNING: *Warnung*: Sie müssen die folgenden Teilschritte in der angegebenen Reihenfolge durchführen; andernfalls kann es zu einem Ausfall oder sogar zu Datenverlust kommen.

+
Im folgenden Verfahren wird node3 vom Root-Aggregat von node1 gestartet:

+
.. Überprüfen Sie die RAID-, Plex- und Prüfsummeninformationen für das node1 Aggregat:
+
`aggr status -r`

.. Überprüfen Sie den Status des node1-Aggregats:
+
`aggr status`

.. Bringen Sie das node1 Aggregat ggf. online:
+
`aggr_online _root_aggr_from_node1_`

.. Verhindern Sie, dass das node3 vom ursprünglichen Root-Aggregat gebootet wird:
`aggr offline _root_aggr_on_node3_`
.. Legen Sie das node1-Root-Aggregat als das neue Root-Aggregat für node3 fest:
+
`aggr options _aggr_from_node1_ root`

.. Überprüfen Sie, ob das Root-Aggregat von node3 offline ist und das Root-Aggregat für die von node1 hergebrachten Festplatten online ist und in den Root-Status eingestellt ist:
+
`aggr status`

+

NOTE: Wenn der vorherige Unterschritt nicht ausgeführt wird, kann node3 vom internen Root-Aggregat booten, oder es kann dazu führen, dass das System eine neue Cluster-Konfiguration übernimmt oder Sie aufgefordert werden, eine zu identifizieren.

+
Im Folgenden wird ein Beispiel für die Befehlsausgabe angezeigt:



+
[listing]
----
 ---------------------------------------------------------------
      Aggr State               Status          Options
 aggr0_nst_fas8080_15 online   raid_dp, aggr   root, nosnap=on
                               fast zeroed
                               64-bit

   aggr0 offline               raid_dp, aggr   diskroot
                               fast zeroed
                               64-bit
 ----------------------------------------------------------------------
----
. [[man_install3_step33]]Überprüfen Sie, ob Controller und Chassis als konfiguriert sind `ha`:
+
`ha-config show`

+
Im folgenden Beispiel wird die Ausgabe des Befehls ha-config show angezeigt:

+
[listing]
----
 *> ha-config show
    Chassis HA configuration: ha
    Controller HA configuration: ha
----
+
Systeme zeichnen sich in einem programmierbaren ROM (PROM) auf, unabhängig davon, ob sie sich in einem HA-Paar oder einer eigenständigen Konfiguration befinden. Der Status muss auf allen Komponenten im Standalone-System oder im HA-Paar der gleiche sein.

+
Wenn der Controller und das Chassis nicht als „ha“ konfiguriert wurden, korrigieren Sie die Konfiguration mit den folgenden Befehlen:

+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Wenn Sie eine MetroCluster-Konfiguration haben, verwenden Sie die folgenden Befehle, um den Controller und das Chassis zu ändern:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[man_install3_step34]]zerstören Sie die Mailboxen auf node3:
+
`mailbox destroy local`

+
Über die Konsole wird die folgende Meldung angezeigt:

+
[listing]
----
Destroying mailboxes forces a node to create new empty mailboxes, which clears any takeover state, removes all knowledge of out-of-date plexes of mirrored volumes, and will prevent management services from going online in 2-node cluster HA configurations. Are you sure you want to destroy the local mailboxes?
----
. [[man_install3_step35]]Geben Sie ein `y` Bestätigen Sie an der Eingabeaufforderung, dass Sie die lokalen Mailboxen zerstören möchten.
. [[man_install3_steep36]]Wartungsmodus beenden:
+
`halt`

+
Das System wird an der Eingabeaufforderung für die Boot-Umgebung angehalten.

. [[man_install3_step37]] auf node2 überprüfen Sie Datum, Uhrzeit und Zeitzone des Systems:
+
`date`

. [[man_install3_step38]] auf node3 prüfen Sie das Datum an der Eingabeaufforderung der Boot-Umgebung:
+
`show date`

. [[man_install3_step39]]Ggf. Das Datum auf node3 einstellen:
+
`set date _mm/dd/yyyy_`

. [[man_install3_step40]]in node3 überprüfen Sie die Zeit an der Eingabeaufforderung der Boot-Umgebung:
+
`show time`

. [[man_install3_step41]]Ggf. Die Zeit auf node3 einstellen:
+
`set time _hh:mm:ss_`

. [[man_install3_step42]]Überprüfen Sie, ob die Partnersystem-ID korrekt eingestellt ist, wie in<<man_install3_step21,Schritt 21>> unter dem Schalter -p:
+
`printenv partner-sysid`

. [[man_install3_step43]]Ggf. Setzen Sie die Partner-System-ID auf node3:
+
`setenv partner-sysid _node2_sysid_`

+
Einstellungen speichern:

+
`saveenv`

. [[man_install3_step44]]Öffnen Sie das Boot-Menü an der Eingabeaufforderung der Boot-Umgebung:
+
`boot_ontap menu`

. [[man_install3_step45]]Wählen Sie im Boot-Menü die Option *(6) Flash aus Backup config* aktualisieren, indem Sie eingeben `6` An der Eingabeaufforderung.
+
Vom System wird die folgende Meldung angezeigt:

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. [[man_install3_step46]]Geben Sie ein `y` An der Eingabeaufforderung.
+
Der Startvorgang läuft normal weiter, und das System fordert Sie dann auf, die Unstimmigkeit der System-ID zu bestätigen.

+

NOTE: Das System wird möglicherweise zweimal neu gestartet, bevor die Warnmeldung zur Nichtübereinstimmung angezeigt wird.

. [[man_install3_step47]]Bestätigen Sie die Diskrepanz, wie im folgenden Beispiel gezeigt:
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id (y|n) ? [n] y
----
+
Der Node kann vor dem normalen Booten eine Runde des Neubootens durchlaufen.

. [[man_install3_step48]]Einloggen in node3.

