= 
:allow-uri-read: 


Sie müssen node3 im Rack installieren, Verbindungen von node1 zu node3, Boot node3 übertragen und ONTAP installieren. Sie müssen auch jede der freien Festplatten von node1, alle Festplatten, die zum Root-Volume gehören, und alle nicht-Root-Aggregate, die nicht früher auf node2 verschoben wurden, neu zuweisen.

.Über diese Aufgabe
Sie müssen als Netzboot node3 wechseln, wenn nicht die gleiche Version von ONTAP 9 installiert ist auf node1. Nachdem Sie node3 installiert haben, starten Sie es vom ONTAP 9-Image, das auf dem Webserver gespeichert ist. Anschließend können Sie die richtigen Dateien auf das Boot-Medium herunterladen, um später das System zu booten. Siehe link:prepare_for_netboot.html["Vorbereitungen für den Netzboot"].

Sie müssen jedoch nicht als Netzboot auf Node3 setzen, wenn es die gleiche oder eine höhere Version von ONTAP 9 hat, die auf node1 installiert ist.

[IMPORTANT]
====
Wenn Sie ein mit Storage-Arrays verbundenes V-Series System oder ein System mit FlexArray-Virtualisierungssoftware aktualisieren, die mit Storage Arrays verbunden ist, sind die vollständigen Anforderungen unbedingt zu beachten <<man_install3_step1,Schritt 1>> Bis <<man_install3_step5,Schritt 5>>, Lassen Sie diesen Abschnitt bei <<man_install3_step6,Schritt 6>> Und befolgen Sie die Anweisungen unter link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Konfigurieren Sie FC-Ports auf node3"] Und link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["UTA/UTA2-Ports in node3 prüfen und konfigurieren"] Geben Sie nach Bedarf Befehle im Wartungsmodus ein. Sie müssen dann zu diesem Abschnitt zurückkehren und mit fortfahren <<man_install3_step7,Schritt 7>>.

Wenn Sie jedoch ein System mit Speicherfestplatten aktualisieren, müssen Sie diesen gesamten Abschnitt abschließen und anschließend mit fortfahren link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Konfigurieren Sie FC-Ports auf node3"] Und link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["UTA/UTA2-Ports in node3 prüfen und konfigurieren"], Eingabe von Befehlen an der Cluster-Eingabeaufforderung.

====
.Schritte
. [[man_install3_step1]] stellen Sie sicher, dass Sie Platz im Rack für node3 haben.
+
Wenn sich Node1 und Node2 in einem separaten Chassis befanden, können Sie Node3 in denselben Rack-Standort wie node1 platzieren. Wenn sich jedoch node1 mit node2 im selben Chassis befand, müssen Sie node3 in seinen eigenen Rack-Platz legen, vorzugsweise in der Nähe der Position von node1.

. [[Schritt2]]Installieren Sie Node3 im Rack gemäß der _Installations- und Setup-Anleitung_ für Ihr Node-Modell.
+

NOTE: Wenn Sie ein Upgrade auf ein System mit beiden Nodes im selben Chassis durchführen, installieren sie node4 sowohl im Chassis als auch in node3. Wenn Sie dies nicht tun, verhält sich der Node, wenn Sie node3 booten, wie in einer Dual-Chassis-Konfiguration. Und wenn Sie node4 booten, wird der Interconnect zwischen den Nodes nicht gestartet.

. [[Schritt3]]Kabelnode3, Verschieben der Verbindungen von node1 zu node3.
+
Die folgenden Referenzen helfen Ihnen dabei, geeignete Kabelverbindungen zu machen. Gehen Sie zu link:other_references.html["Quellen"] Um eine Verbindung zu ihnen zu machen.

+
** _Installations- und Setup-Anleitung_ oder _Installationsanforderungen für die FlexArray-Virtualisierung und Referenz_ für die node3-Plattform
** Das entsprechende Verfahren für das Festplatten-Shelf
** Die Dokumentation _High Availability Management_


+
Folgende Anschlüsse verkabeln:

+
** Konsole (Remote-Management-Port)
** Cluster-Ports
** Datenports
** Cluster- und Node-Management-Ports
** Storage
** SAN-Konfigurationen: ISCSI Ethernet und FC Switch Ports
+

NOTE: Möglicherweise müssen Sie die Interconnect-Karte oder die Cluster Interconnect-Kabelverbindung von node1 zu node3 nicht verschieben, da die meisten Plattform-Modelle über ein einzigartiges Interconnect-Kartenmodell verfügen. Für die MetroCluster-Konfiguration müssen Sie die FC-VI-Kabelverbindungen von node1 zu node3 verschieben. Wenn der neue Host keine FC-VI-Karte besitzt, müssen Sie möglicherweise die FC-VI-Karte verschieben.



. [[man_install3_step4]]Einschalten Sie die Stromversorgung auf node3, und unterbrechen Sie dann den Bootvorgang, indem Sie an der Konsole Strg-C drücken, um auf die Eingabeaufforderung der Boot-Umgebung zuzugreifen.
+
Wenn Sie ein Upgrade auf ein System mit beiden Nodes im gleichen Chassis durchführen, wird node4 auch neu gebootet. Allerdings kann man den node4-Stiefel bis später ignorieren.

+

NOTE: Wenn Sie node3 booten, wird möglicherweise die folgende Warnmeldung angezeigt:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]]Wenn die Warnmeldung in angezeigt wird <<man_install3_step4,Schritt 4>>, Nehmen Sie die folgenden Aktionen:
+
.. Überprüfen Sie auf Meldungen der Konsole, die auf ein anderes Problem als eine schwache NVRAM-Batterie hinweisen und ergreifen Sie gegebenenfalls erforderliche Korrekturmaßnahmen.
.. Warten Sie, bis der Akku geladen ist und der Bootvorgang abgeschlossen ist.
+

NOTE: *Achtung*: Die Verzögerung nicht außer Kraft setzen; wenn der Akku nicht geladen werden kann, kann dies zu einem Datenverlust führen.



. [[man_install3_step6]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn Ihr System... | Dann... 


| Verfügt über Festplatten und keinen Back-End-Speicher | Überspringen Sie Schritt 7 bis Schritt 12, und fahren Sie mit fort <<man_install3_step13,Schritt 13>>. 


| Ist ein V-Series System oder ein System mit FlexArray Virtualisierungssoftware, die mit Storage-Arrays verbunden ist  a| 
.. Gehen Sie zu link:set_fc_uta_uta2_config_node3.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node3 fest"] Und vervollständigen Sie die Unterabschnitte link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Konfigurieren Sie FC-Ports auf node3"] Und link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["UTA/UTA2-Ports in node3 prüfen und konfigurieren"], Je nach Ihrem System.
.. Kehren Sie zu diesem Abschnitt zurück, und führen Sie die verbleibenden Schritte aus. Beginnen Sie mit <<man_install3_step7,Schritt 7>>.



IMPORTANT: Sie müssen die integrierten FC-Ports, die integrierten CNA-Ports und CNA-Karten neu konfigurieren, bevor Sie ONTAP auf der V-Series oder dem System mit FlexArray Virtualisierungssoftware booten.

|===
. [[man_install3_step7]]Fügen Sie die FC-Initiator-Ports des neuen Knotens zu den Switch-Zonen hinzu.
+
Wenn Ihr System über ein Tape-SAN verfügt, müssen Sie das Zoning für die Initiatoren benötigen. Anweisungen finden Sie in der Dokumentation für das Storage-Array und Zoning.

. [[man_install3_step8]]Fügen Sie die FC-Initiator-Ports zum Speicher-Array als neue Hosts hinzu, und ordnen Sie die Array-LUNs den neuen Hosts zu.
+
Anweisungen finden Sie in der Dokumentation für das Storage-Array und Zoning.

. [[man_install3_step9]] Ändern Sie die WWPN-Werte (World Wide Port Name) in den Host- oder Volume-Gruppen, die mit Array LUNs auf dem Speicher-Array verknüpft sind.
+
Durch die Installation eines neuen Controller-Moduls werden die WWPN-Werte geändert, die den einzelnen integrierten FC-Ports zugeordnet sind.

. [[man_install3_step10]]Wenn Ihre Konfiguration ein Switch-basiertes Zoning verwendet, passen Sie das Zoning an die neuen WWPN-Werte an.
. [[man_install3_step11]]Überprüfen Sie, ob die Array-LUNs jetzt für node3 sichtbar sind:
+
`sysconfig -v`

+
Das System zeigt alle Array-LUNs an, die für jeden FC-Initiator-Port sichtbar sind. Wenn die Array-LUNs nicht sichtbar sind, können Sie Festplatten von node1 zu node3 später in diesem Abschnitt nicht neu zuweisen.

. [[man_install3_step12]]Drücken Sie Strg-C, um das Boot-Menü anzuzeigen und den Wartungsmodus auszuwählen.
. [[man_install3_step13]]Geben Sie in der Eingabeaufforderung für den Wartungsmodus den folgenden Befehl ein:
+
`halt`

+
Das System wird an der Eingabeaufforderung für die Boot-Umgebung angehalten.

. [[man_install3_step14]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn das System, auf das Sie aktualisieren, in einem ist... | Dann... 


| Dual-Chassis-Konfiguration (mit Controllern in anderem Chassis) | Gehen Sie zu <<man_install3_step15,Schritt 15>>. 


| Einzel-Chassis-Konfiguration (mit Controllern im selben Chassis)  a| 
.. Schalten Sie das Konsolenkabel von node3 auf node4 um.
.. Schalten Sie node4 ein, und unterbrechen Sie den Bootvorgang, indem Sie am Konsolenterminal Strg-C drücken, um auf die Eingabeaufforderung der Boot-Umgebung zuzugreifen.
+
Die Stromversorgung sollte bereits eingeschaltet sein, wenn sich beide Controller im gleichen Chassis befinden.

+

NOTE: verlassen sie node4 an der Boot-Umgebung Eingabeaufforderung; Sie kehren nach node4 in zurück link:install_boot_node4.html["installieren und booten sie node4"].

.. Wenn die Warnmeldung in angezeigt wird <<man_install3_step4,Schritt 4>>, Folgen Sie den Anweisungen in <<man_install3_step5,Schritt 5>>
.. Schalten Sie das Konsolenkabel von node4 nach node3 zurück.
.. Gehen Sie zu <<man_install3_step15,Schritt 15>>.


|===
. [[man_install3_step15]]node3 für ONTAP konfigurieren:
+
`set-defaults`


