= 
:allow-uri-read: 


Dieses Dokument wird an folgende Annahmen geschrieben:

* Die Ersatz-Controller-Hardware ist neu und wurde nicht verwendet.
+

WARNING: Da dieses Verfahren davon ausgeht, dass die Ersatz-Controller-Hardware neu und unbenutzt ist, werden die Schritte zur Vorbereitung gebrauchter Controller mit den `wipeconfig` Befehl sind in diesem Verfahren nicht enthalten.  Sie müssen sich an den technischen Support wenden, wenn die Ersatz-Controller-Hardware zuvor verwendet wurde, insbesondere wenn auf den Controllern Data ONTAP im 7-Modus ausgeführt wurde.

* Die Richtlinien zum Upgrade des Knotenpaars werden gelesen und verstanden.
+

WARNING: Versuchen Sie nicht, den NVRAM Inhalt zu löschen.  Wenn Sie den Inhalt des NVRAM löschen müssen, wenden Sie sich an den technischen Support von NetApp .

* Sie führen den entsprechenden Befehl vor und nach dem aus `modify` Und die Ausgabe von beiden vergleichen `show` Befehle, um zu überprüfen, dass das `modify` Befehl erfolgreich.
* Wenn Sie über eine SAN-Konfiguration verfügen, stehen Ihnen auf dem HA-Paar lokale LIFs und Partner-LIFs für jede Storage Virtual Machine (SVM) zur Verfügung. Wenn Sie keine lokalen LIFs für jede SVM haben und keine Partner-LIFs haben, sollten Sie vor dem Upgrade die SAN-Daten-LIF auf dem Remote- und lokalen Node für diese SVM hinzufügen.
* Wenn Sie in einer SAN-Konfiguration Port-Sets haben, müssen Sie überprüfen, dass jeder gebundene Port-Satz mindestens eine LIF von jedem Node im HA-Paar enthält.


Bei diesem Verfahren wird der Begriff „_Boot Environment prompt_“ verwendet, um die Eingabeaufforderung auf einem Node, von dem Sie bestimmte Aufgaben ausführen können, zu lesen, z. B. beim Neubooten des Knotens und beim Drucken oder Festlegen von Umgebungsvariablen. Die Eingabeaufforderung wird manchmal informell als _Boot-Loader Prompt_ bezeichnet.

Die Eingabeaufforderung der Boot-Umgebung wird im folgenden Beispiel angezeigt:

[listing]
----
LOADER>
----