= 
:allow-uri-read: 


Dieses Dokument wird an folgende Annahmen geschrieben:

* Die Ersatz-Controller-Hardware ist neu und wurde nicht verwendet.
+

WARNING: *Achtung*: Da dieses Verfahren davon ausgeht, dass die Hardware des Ersatzcontrollers neu ist und nicht verwendet wurde, werden die erforderlichen Schritte zur Vorbereitung gebrauchter Controller mit dem ausgeführt `wipeconfig` Befehl ist in dieser Prozedur nicht enthalten. Wenn bereits die Ersatz-Controller-Hardware verwendet wurde, müssen Sie sich an den technischen Support wenden, insbesondere wenn auf den Controllern Data ONTAP in 7-Mode ausgeführt wurde.

* Die Richtlinien zum Upgrade des Knotenpaars werden gelesen und verstanden.
+

WARNING: *Achtung*: Versuchen Sie nicht, den NVRAM-Inhalt zu löschen. Wenn Sie den Inhalt des NVRAM löschen müssen, wenden Sie sich an den technischen Support von NetApp.

* Sie führen den entsprechenden Befehl vor und nach dem aus `modify` Und die Ausgabe von beiden vergleichen `show` Befehle, um zu überprüfen, dass das `modify` Befehl erfolgreich.
* Wenn Sie über eine SAN-Konfiguration verfügen, stehen Ihnen auf dem HA-Paar lokale LIFs und Partner-LIFs für jede Storage Virtual Machine (SVM) zur Verfügung. Wenn Sie keine lokalen LIFs für jede SVM haben und keine Partner-LIFs haben, sollten Sie vor dem Upgrade die SAN-Daten-LIF auf dem Remote- und lokalen Node für diese SVM hinzufügen.
* Wenn Sie in einer SAN-Konfiguration Port-Sets haben, müssen Sie überprüfen, dass jeder gebundene Port-Satz mindestens eine LIF von jedem Node im HA-Paar enthält.


Bei diesem Verfahren wird der Begriff „_Boot Environment prompt_“ verwendet, um die Eingabeaufforderung auf einem Node, von dem Sie bestimmte Aufgaben ausführen können, zu lesen, z. B. beim Neubooten des Knotens und beim Drucken oder Festlegen von Umgebungsvariablen. Die Eingabeaufforderung wird manchmal informell als _Boot-Loader Prompt_ bezeichnet.

Die Eingabeaufforderung der Boot-Umgebung wird im folgenden Beispiel angezeigt:

[listing]
----
LOADER>
----