= UTA/UTA2-Ports in node3 prüfen und konfigurieren
:allow-uri-read: 




== UTA/UTA2-Ports in node3 prüfen und konfigurieren

Wenn node3 Onboard UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Konfiguration der Ports überprüfen und sie möglicherweise neu konfigurieren, je nachdem, wie Sie das aktualisierte System verwenden möchten.

.Bevor Sie beginnen
Sie müssen die richtigen SFP+ Module für die UTA/UTA2-Ports besitzen.

.Über diese Aufgabe
Wenn Sie einen Unified Target Adapter (UTA/UTA2)-Port für FC verwenden möchten, müssen Sie zuerst überprüfen, wie der Port konfiguriert ist.


NOTE: Bei NetApp Marketingmaterialien wird möglicherweise der Begriff UTA2 verwendet, um sich auf CNA-Adapter und Ports zu beziehen. Allerdings verwendet die CLI den Begriff CNA.

Sie können das verwenden `ucadmin show` Befehl zum Überprüfen der aktuellen Portkonfiguration:

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
DIE UTA2-Ports können im nativen FC-Modus oder im UTA/UTA2-Modus konfiguriert werden. FC-Modus unterstützt FC Initiator und FC Target. Der UTA-/UTA2-Modus ermöglicht gleichzeitige NIC- und FCoE-Traffic über die gleiche 10-GbE-SFP+-Schnittstelle und unterstützt FC-Ziele.

UTA/UTA2-Ports befinden sich möglicherweise auf einem Adapter oder auf dem Controller und verfügen über die folgenden Konfigurationen. Sie sollten jedoch die Konfiguration der UTA/UTA2-Ports auf der node3 überprüfen und gegebenenfalls ändern:

* UTA-/UTA2-Karten, die bestellt werden, werden vor dem Versand konfiguriert, um die von Ihnen geforderte Persönlichkeit zu erhalten.
* DIE UTA2-Karten, die separat vom Controller bestellt werden, werden mit der standardmäßigen FC-Zielgruppe ausgeliefert.
* Onboard UTA/UTA2-Ports auf neuen Controllern werden vor dem Versand konfiguriert, um die Persönlichkeit zu erhalten, die Sie anfordern.
+

NOTE: *Achtung*: Wenn Ihr System über Speicherfestplatten verfügt, müssen Sie an der Eingabeaufforderung des Clusters die Befehle in diesem Abschnitt eingeben, sofern nicht dazu aufgefordert wird, in den Wartungsmodus zu wechseln. Wenn Sie über ein VSeries-System verfügen oder über FlexArray-Virtualisierungssoftware verfügen und mit Speicherarrays verbunden sind, müssen Sie in diesem Abschnitt Befehle in der Eingabeaufforderung für den Wartungsmodus eingeben. Sie müssen sich im Wartungsmodus befinden, um UTA/UTA2-Ports zu konfigurieren.



.Schritte
. Überprüfen Sie, wie die Ports derzeit konfiguriert sind, und geben Sie auf node3 die folgenden Befehle ein:
+
[cols="35,65"]
|===
| Wenn das System... | Dann... 


| Festplatten sind vorhanden | `system node hardware unified-connect show` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `ucadmin show` 
|===
+
Das System zeigt eine Ausgabe an, die den folgenden Beispielen entspricht:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
+
[listing]
----
*> ucadmin show
         Current  Current    Pending  Pending  Admin
Adapter  Mode     Type       Mode     Type     Status
-------  -------  ---------  -------  -------  ------
0e       fc       initiator  -        -        online
0f       fc       initiator  -        -        online
0g       cna      target     -        -        online
0h       cna      target     -        -        online
0e       fc       initiator  -        -        online
0f       fc       initiator  -        -        online
0g       cna      target     -        -        online
0h       cna      target     -        -        online
*>
----
. [[Schritt2]]Wenn das aktuelle SFP+-Modul nicht mit der gewünschten Verwendung übereinstimmt, ersetzen Sie es durch das richtige SFP+-Modul.
+
Wenden Sie sich an Ihren NetApp Ansprechpartner, um das richtige SFP+ Modul zu erhalten.

. [[Schritt3]]Untersuchung der Ausgabe des `system node hardware unified-connect show` Oder `ucadmin show` Befehl zum Bestimmen, ob die UTA/UTA2-Ports die gewünschte Persönlichkeit haben.
. [[Schritt4]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn die UTA/UTA2-Ports... | Dann... 


| Haben Sie nicht die Persönlichkeit, die Sie wollen | Gehen Sie zu <<man_check_3_step5,Schritt 5>>. 


| Haben Sie die Persönlichkeit, die Sie wollen | Überspringen Sie Schritt 5 bis Schritt 12, und fahren Sie mit fort <<man_check_3_step13,Schritt 13>>. 
|===
. [[man_Check_3_step5]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn das System... | Dann... 


| Es gibt Storage-Festplatten, auf denen Clustered Data ONTAP 8.3 ausgeführt wird | Boot-Knoten3 und wechseln in den Wartungsmodus:
`boot_ontap maint` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Gehen Sie zu <<man_check_3_step6,Schritt 6>>. Sie sollten sich bereits im Wartungsmodus befinden. 
|===
. [[man_Check_3_Steppen6]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn Sie konfigurieren... | Dann... 


| Ports auf einer UTA/UTA2-Karte | Gehen Sie zu <<man_check_3_step7,Schritt 7>>. 


| Onboard UTA/UTA2-Ports | Überspringen Sie Schritt 7, und fahren Sie mit fort <<man_check_3_step8,Schritt 8>>. 
|===
. [[man_Check_3_step7]]Wenn sich der Adapter im Initiator-Modus befindet und der UTA/UTA2-Port online ist, versetzen Sie den UTA/UTA2-Port in den Offline-Modus:
+
`storage disable adapter _adapter_name_`

+
Adapter im Ziel-Modus sind im Wartungsmodus automatisch offline.

. [[man_Check_3_step8]]Wenn die aktuelle Konfiguration nicht mit der gewünschten Verwendung übereinstimmt, ändern Sie die Konfiguration nach Bedarf:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` Ist der Persönlichkeitsmodus, `fc` Oder `cna`.
** `-t` Ist der Typ FC4, `target` Oder `initiator`.
+

NOTE: Sie müssen FC Initiator für Tape-Laufwerke, FlexArray Virtualisierungssysteme und MetroCluster Konfigurationen verwenden. Sie müssen das FC-Ziel für SAN-Clients verwenden.



. Überprüfen Sie die Einstellungen:
+
`ucadmin show`

. Überprüfen Sie die Einstellungen:
+
[cols="35,65"]
|===
| Wenn das System... | Dann... 


| Festplatten sind vorhanden  a| 
.. Anhalten des Systems:
+
`halt`

+
Das System wird an der Eingabeaufforderung für die Boot-Umgebung angehalten.

.. Geben Sie den folgenden Befehl ein:
+
`boot_ontap`





| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Neubooten in den Wartungsmodus:
`boot_netapp maint` 
|===
. [[Schritt11]]Überprüfen Sie die Einstellungen:
+
[cols="35,65"]
|===
| Wenn das System... | Dann... 


| Festplatten sind vorhanden | `system node hardware unified-connect show` 


| Ist eine V-Series oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `ucadmin show` 
|===
+
Die Ausgabe in den folgenden Beispielen zeigt, dass sich der Adaptertyp „1b“ in ändert `initiator` Und dass sich der Modus der Adapter „2a“ und „2b“ in ändert `cna`:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
+
[listing]
----
*> ucadmin show
         Current  Current    Pending  Pending    Admin
Adapter  Mode     Type       Mode     Type       Status
-------  -------  ---------  -------  ---------  ------
1a       fc       initiator  -        -          online
1b       fc       target     -        initiator  online
2a       fc       target     cna      -          online
2b       fc       target     cna      -          online
*>
----
. [[step12a]]Platzieren Sie alle Zielports online, indem Sie einen der folgenden Befehle eingeben, einmal für jeden Port:
+
[cols="35,65"]
|===
| Wenn das System... | Dann... 


| Festplatten sind vorhanden | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `fcp config _adapter_name_ up` 
|===
. [[man_Check_3_steep13]]Anschluss verkabeln.
. [[steep14]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn das System... | Dann... 


| Festplatten sind vorhanden | Gehen Sie zu link:map_ports_node1_node3.html["Ports von node1 nach node3 zuordnen"]. 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Kehren Sie zu _Install and Boot node3_ zurück und fahren Sie bei fort link:install_boot_node3.html#step7["Schritt 7"]. 
|===

