= 
:allow-uri-read: 


sie müssen node4 im Rack installieren, Node2-Verbindungen zu node4 übertragen und node4 booten. Sie müssen auch node2-Spares, alle Festplatten der Root-Partition und alle nicht-Root-Aggregate neu zuweisen, die nicht zu node3 früher verschoben wurden.

.Über diese Aufgabe
Sie müssen node4 per Netzwerk neu starten, wenn die ONTAP Version auf node4 von der ONTAP Version auf node2 abweicht. Nach der Installation von node4 starten Sie es vom ONTAP 9-Image, das auf dem Webserver gespeichert ist. Anschließend können Sie die richtigen Dateien für nachfolgende Systemstarts auf das Startmedium herunterladen, indem Sie den Anweisungen in link:prepare_for_netboot.html["Vorbereitungen für den Netzboot"]

Allerdings ist ein Netboot von Node4 nicht erforderlich, wenn die ONTAP Version auf Node4 gleich oder neuer ist als die ONTAP Version auf Node2.

[IMPORTANT]
====
* Bei einem AFF A800 oder AFF C800 -Controller-Upgrade müssen Sie sicherstellen, dass alle Laufwerke im Gehäuse fest an der Mittelplatine sitzen, bevor Sie Knoten 2 entfernen. Weitere Informationen finden Sie unter link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["Ersetzen Sie die AFF A800- oder AFF C800-Controller-Module"].
* Wenn Sie ein System mit Speicherplatten aktualisieren, müssen Sie diesen Abschnitt vollständig ausfüllen und dann mit dem Abschnitt fortfahren. link:set_fc_uta_uta2_config_node4.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node4 fest"] , indem Sie Befehle an der Cluster-Eingabeaufforderung eingeben.


====
.Schritte
. [[man_install4_Step1]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn node4 wird in ... | Dann... 


| Ein von Knoten 3 getrenntes Chassis | Gehen Sie zu <<man_install4_Step2,Schritt 2>>. 


| Im gleichen Chassis mit Knoten3 | Überspringen Sie die Schritte 2 und 3 und gehen Sie zu <<man_install4_Step4,Schritt 4>>. 
|===
. [[man_install4_Step2]] stellen Sie sicher, dass node4 über ausreichend Rack-Platz verfügt.
+
Wenn node4 sich in einem separaten Chassis von node3 befindet, können sie node4 an der gleichen Stelle wie node2 platzieren. Wenn sich Node3 und node4 im selben Chassis befinden, befindet sich node4 bereits in der entsprechenden Rack-Position.

. installieren sie node4 im Rack gemäß den Anweisungen in der Anleitung _Installation and Setup Instructions_ für das Node-Modell.
. [[man_install4_Step4]]kabelnode4, die Verbindungen von node2 nach node4 verschieben.
+
Die folgenden Referenzen helfen Ihnen dabei, geeignete Kabelverbindungen zu machen. Gehen Sie zu link:other_references.html["Quellen"] Um eine Verbindung zu ihnen zu machen.

+
** _Installations- und Einrichtungsanweisungen_ für die node4-Plattform
** Das entsprechende Verfahren für das Festplatten-Shelf
** Die _HA-Paar-Management_ Dokumentation
+
Folgende Anschlüsse verkabeln:

** Konsole (Remote-Management-Port)
** Cluster-Ports
** Datenports
** Cluster- und Node-Management-Ports
** Storage
** SAN-Konfigurationen: ISCSI Ethernet und FC Switch Ports


+

NOTE: Sie müssen die Interconnect-Karte/FC_VI-Karte oder den Interconnect/FC_VI-Kabelanschluss von node2 auf node4 nicht verschieben, da die meisten Plattformmodelle über einzigartige Interconnect-Kartenmodelle verfügen.

. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn node4 in... | Dann... 


| Im gleichen Chassis wie bei Node3 | Gehen Sie zu <<man_install4_Step8,Schritt 8>>. 


| Ein von Knoten 3 getrenntes Chassis | Gehen Sie zu <<man_install4_Step6,Schritt 6>>. 
|===
. [[man_install4_Step6]]Schalten Sie die Stromversorgung zu node4 ein, und unterbrechen Sie dann den Start, indem Sie Strg-C drücken, um auf die Eingabeaufforderung der Startumgebung zuzugreifen.
+

NOTE: Wenn Sie node4 booten, wird möglicherweise die folgende Meldung angezeigt:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7]]Wenn die Warnmeldung in Schritt 6 angezeigt wird, führen Sie die folgenden Schritte aus:
+
.. Überprüfen Sie auf Meldungen der Konsole, die auf ein anderes Problem als eine schwache NVRAM-Batterie hinweisen und ergreifen Sie gegebenenfalls erforderliche Korrekturmaßnahmen.
.. Lassen Sie den Akku laden und den Bootvorgang beenden.
+

WARNING: *Überschreiben Sie die Verzögerung nicht.  Wenn der Akku nicht aufgeladen wird, kann es zu Datenverlust kommen.*



. [[man_install4_Step8]]Geben Sie an der Eingabeaufforderung für den Wartungsmodus den folgenden Befehl ein:
+
`halt`

+
Das System wird an der Eingabeaufforderung für die Boot-Umgebung angehalten.

. node4 für ONTAP konfigurieren:
+
`set-defaults`


