= 
:allow-uri-read: 


Bevor Sie node2 durch node4 ersetzen können, müssen Sie eine AutoSupport Meldung für node2 senden und dann die nicht-Root-Aggregate, die im Besitz von node2 sind, zu node3 verschieben.


CAUTION: Verschieben Sie Aggregate während dieses Verfahrens nicht von Knoten 3 zu Knoten 2. So werden Aggregate offline geschaltet und es kommt zu einem Ausfall der Daten für die verschobenen Aggregate.

[[verify-partner-sys-id]]
.Schritte
. Überprüfen Sie, ob die Partner-System-ID auf Knoten 3 korrekt eingestellt ist:
+
.. Geben Sie die erweiterte Berechtigungsebene ein:
+
`set -privilege advanced`

.. Zeigt die Partner-System-ID auf Knoten3 an:
+
`ha interconnect config show -node <node3-node1>`

+
Das System zeigt eine Ausgabe wie im folgenden Beispiel an:

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
cluster::*> ha interconnect config show -node <node>
  (system ha interconnect config show)

                       Node: node3-node1
          Interconnect Type: RoCE
            Local System ID: <node3-system-id>
          Partner System ID: <node2-system-id>
       Connection Initiator: local
                  Interface: external

Port   IP Address
----   -----------------
e4a-17   0.0.0.0
e4b-18   0.0.0.0
----
====


. Wenn „Partner System ID“ für Knoten 3 falsch ist:
+
.. Knoten 3 anhalten:
+
`halt`

.. Legen Sie an der Loader-Eingabeaufforderung den korrekten Wert „Partner-sysid“ fest.
+
Die node3 "Partner-sysid" ist die System ID von node2, die Sie in der Ausgabe in finden können `ha interconnect config show`<<verify-partner-sys-id,Schritt 1>>.

.. Einstellungen speichern:
+
`saveenv`

.. Starten Sie an der Loader-Eingabeaufforderung node3 im Boot-Menü:
+
`boot_ontap menu`

.. Melden Sie sich bei node3 an.


. Sende eine AutoSupport Nachricht an NetApp for node2:
+
`system node autosupport invoke -node <node2> -type all -message "Upgrading <node2> from <platform_old> to <platform_new>"`

. Überprüfen Sie, ob die AutoSupport Meldung gesendet wurde:
+
`system node autosupport show -node <node2> -instance`

+
Die Felder „Letzter Betreff gesendet:“ und „Letzter Zeitpunkt gesendet:“ enthalten den Nachrichtentitel der letzten gesendeten Nachricht und den Zeitpunkt, zu dem die Nachricht gesendet wurde.

. Verschieben Sie die nicht-Root-Aggregate:
+
.. Legen Sie die Berechtigungsebene auf erweitert fest:
+
`set -privilege advanced`

.. Listen Sie die Aggregate auf, die Eigentum von node2 sind:
+
`storage aggregate show -owner-name <node2>`

.. Starten Sie die Aggregatverschiebung:
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controller-upgrade true`

+

NOTE: Der Befehl sucht nur Aggregate außerhalb des Root-Bereichs.

.. Geben Sie bei der entsprechenden Aufforderung ein `y`.
+
Umzüge finden im Hintergrund statt. Für die Verschiebung eines Aggregats kann dieser Zeitraum von wenigen Sekunden bis hin zu einigen Minuten dauern. Die Zeit umfasst sowohl einen Client-Ausfall als auch Teile ohne Ausfälle. Mit dem Befehl werden keine Offline- oder eingeschränkten Aggregate verschoben.

.. Zurück zur Administratorberechtigungsebene:
+
`set -privilege admin`



. Überprüfen Sie den Versetzungsstatus von node2:
+
`storage aggregate relocation show -node <node2>`

+
Nach der Verlagerung wird für ein Aggregat „Fertig“ angezeigt.

+

NOTE: Sie müssen warten, bis alle Aggregate, die sich im Besitz von node2 befinden, in node3 verschoben wurden, bevor Sie mit dem nächsten Schritt fortfahren.

. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Bei Umzug von... | Dann... 


| Alle Aggregate waren erfolgreich | Gehen Sie zu <<man_relocate_2_3_step8,Schritt 8>>. 


| Aggregate sind ausgefallen oder sie wurden Vetos  a| 
.. Detaillierte Statusmeldung anzeigen:
+
`storage aggregate show -instance`

+
Sie können auch die EMS-Protokolle überprüfen, um die erforderlichen Korrekturmaßnahmen anzuzeigen.

+

NOTE: Der `event log show` Befehl listet alle Fehler auf, die aufgetreten sind.

.. Führen Sie die Korrekturmaßnahme durch.
.. Legen Sie die Berechtigungsebene auf erweitert fest:
+
`set -privilege advanced`

.. Verschiebung ausgefallener oder Vetos von Aggregaten:
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controllerupgrade true`

.. Geben Sie bei der entsprechenden Aufforderung ein `y`.
.. Zurück zur Administratorberechtigungsebene:
+
`set -privilege admin`



Bei Bedarf können Sie die Verschiebung mit einer der folgenden Methoden erzwingen:

** Durch Überschreiben von Veto-Prüfungen:
+
`storage aggregate relocation start -override-vetoes true -ndo-controller-upgrade`

** Durch Überschreiben von Zielprüfungen:
+
`storage aggregate relocation start -override-destination-checks true -ndocontroller-upgrade`



Weitere Informationen zu den Befehlen für die Verschiebung des Storage-Aggregats finden Sie unter link:other_references.html["Quellen"] Verbinden mit _Disk und Aggregat-Management mit den Befehlen CLI_ und _ONTAP 9: Manual Page Reference_.

|===
. [[man_relocate_2_3_step8]]Stellen Sie sicher, dass alle nicht-Root-Aggregate online sind auf node3:
+
`storage aggregate show -node <node3> -state offline -root false`

+
Wenn irgendwelche Aggregate offline gegangen sind oder fremd geworden sind, müssen Sie sie online bringen, einmal für jedes Aggregat:

+
`storage aggregate online -aggregate <aggregate_name>`

. Vergewissern Sie sich, dass alle Volumes auf node3 online sind:
+
`volume show -node <node3> -state offline`

+
Wenn Volumes auf Knoten3 offline sind, müssen Sie sie einmal für jedes Volume online bringen:

+
`volume online -vserver <Vserver-name> -volume <volume-name>`

. Überprüfen Sie, ob node2 keine Online-Aggregate ohne Root besitzt:
+
`storage aggregate show -owner-name <node2> -ha-policy sfo -state online`

+
Die Befehlsausgabe sollte nicht online nicht-Root-Aggregate anzeigen, da alle nicht-Root-Online-Aggregate bereits in node3 verschoben wurden.


