= 
:allow-uri-read: 


. Wenn die auf node4 installierte ONTAP-Version gleich oder höher als die auf node2 installierte Version von ONTAP 9 ist, geben Sie den folgenden Befehl ein:
+
`boot_ontap menu`

. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn das System, das Sie aktualisieren... | Dann... 


| Verfügt nicht über die richtige oder aktuelle ONTAP-Version unter node4 | Gehen Sie zu <<man_install4_Step20,Schritt 20>>. 


| Hat die richtige oder aktuelle Version von ONTAP auf node4 | Gehen Sie zu <<man_install4_Step25,Schritt 25>>. 
|===
. [[man_install4_Step20]]Konfigurieren Sie die Netzboot-Verbindung, indem Sie eine der folgenden Aktionen auswählen.
+

NOTE: Sie müssen den Management-Port und die IP-Adresse als Netzboot-Verbindung verwenden. Verwenden Sie keine LIF-IP-Adresse von Daten, oder es kann während des Upgrades ein Datenausfall auftreten.

+
[cols="35,75"]
|===
| Wenn DHCP (Dynamic Host Configuration Protocol) lautet... | Dann... 


| Wird Ausgeführt  a| 
Konfigurieren Sie die Verbindung automatisch, indem Sie an der Eingabeaufforderung der Boot-Umgebung den folgenden Befehl eingeben:
`ifconfig e0M -auto`



| Nicht ausgeführt  a| 
Konfigurieren Sie die Verbindung manuell, indem Sie an der Eingabeaufforderung der Boot-Umgebung den folgenden Befehl eingeben:
`ifconfig e0M -addr=_filer_addr_ mask=_netmask_ -gw=_gateway_ dns=_dns_addr_ domain=_dns_domain_`

`_filer_addr_` Ist die IP-Adresse des Speichersystems (obligatorisch).
`_netmask_` Ist die Netzwerkmaske des Storage-Systems (erforderlich).
`_gateway_` Ist das Gateway für das Speichersystem (erforderlich).
`_dns_addr_` Ist die IP-Adresse eines Namensservers in Ihrem Netzwerk (optional).
`_dns_domain_` Der Domain Name (DNS) ist der Domain-Name. Wenn Sie diesen optionalen Parameter verwenden, benötigen Sie in der Netzboot-Server-URL keinen vollqualifizierten Domänennamen. Sie benötigen nur den Host-Namen des Servers.


NOTE: Andere Parameter können für Ihre Schnittstelle erforderlich sein. Eingabe `help ifconfig` Details finden Sie in der Firmware-Eingabeaufforderung.

|===
. Ausführen eines Netzboots auf node4:
+
[cols="30,70"]
|===
| Für... | Dann... 


| Systeme der FAS/AFF8000 Serie | `netboot \http://<web_server_ip/path_to_webaccessible_directory>/netboot/kernel` 


| Alle anderen Systeme | `netboot \http://<web_server_ip/path_to_webaccessible_directory/ontap_version>_image.tgz` 
|===
+
Der `<path_to_the_web-accessible_directory>` Sollten Sie dazu führen, wo Sie das heruntergeladen haben
`<ontap_version>_image.tgz` In link:prepare_for_netboot.html#man_netboot_Step1["Schritt 1"] Im Abschnitt _Vorbereiten für Netzboot_.

+

NOTE: Unterbrechen Sie den Startvorgang nicht.

. Wählen Sie im Startmenü die Option `option (7) Install new software first`.
+
Mit dieser Menüoption wird das neue Data ONTAP-Image auf das Startgerät heruntergeladen und installiert.

+
Ignorieren Sie die folgende Meldung:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
Der Hinweis gilt für unterbrechungsfreie Upgrades der Data ONTAP und keine Upgrades von Controllern.

+

NOTE: Aktualisieren Sie den neuen Node immer als Netzboot auf das gewünschte Image. Wenn Sie eine andere Methode zur Installation des Images auf dem neuen Controller verwenden, wird möglicherweise das falsche Image installiert. Dieses Problem gilt für alle Versionen von ONTAP. Das Netzboot wird mit der Option kombiniert `(7) Install new software` Entfernt das Boot-Medium und platziert dieselbe ONTAP-Version auf beiden Image-Partitionen.

. [[man_install4_steep23] Wenn Sie aufgefordert werden, den Vorgang fortzusetzen, geben Sie y ein. Geben Sie dann die URL ein, wenn Sie nach dem Paket gefragt werden:
+
`\http://<web_server_ip/path_to_web-accessible_directory/ontap_version>_image.tgz`

. Führen Sie die folgenden Teilschritte durch:
+
.. Eingabe `n` So überspringen Sie die Backup-Recovery, wenn folgende Eingabeaufforderung angezeigt wird:
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. Starten Sie den Neustart durch Eingabe `y` Wenn die folgende Eingabeaufforderung angezeigt wird:
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
Das Controller-Modul wird neu gestartet, stoppt aber im Startmenü, da das Boot-Gerät neu formatiert wurde und die Konfigurationsdaten wiederhergestellt werden müssen.



. [[man_install4_Step25]]Wählen Sie den Wartungsmodus `5` Öffnen Sie das Startmenü, und geben Sie ein `y` Wenn Sie aufgefordert werden, den Startvorgang fortzusetzen.
. [[man_install4_Step26]]bevor Sie fortfahren, fahren Sie mit fort link:set_fc_uta_uta2_config_node4.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node4 fest"] Um alle erforderlichen Änderungen an den FC- oder UTA/UTA2-Ports auf dem Node vorzunehmen. Nehmen Sie die in diesen Abschnitten empfohlenen Änderungen vor, starten Sie den Node neu, und wechseln Sie in den Wartungsmodus.
. Geben Sie den folgenden Befehl ein und überprüfen Sie die Ausgabe, um die System-ID von node4 zu finden:
+
`disk show -a`

+
Das System zeigt die System-ID des Node sowie Informationen über seine Festplatten an, wie im folgenden Beispiel dargestellt:

+
[listing]
----
*> disk show -a
Local System ID: 536881109
DISK         OWNER                       POOL   SERIAL NUMBER   HOME
------------ -------------               -----  -------------   -------------
0b.02.23     nst-fas2520-2(536880939)    Pool0  KPG2RK6F        nst-fas2520-2(536880939)
0b.02.13     nst-fas2520-2(536880939)    Pool0  KPG3DE4F        nst-fas2520-2(536880939)
0b.01.13     nst-fas2520-2(536880939)    Pool0  PPG4KLAA        nst-fas2520-2(536880939)
......
0a.00.0                   (536881109)    Pool0  YFKSX6JG                     (536881109)
......
----
. Weisen Sie node2 Ersatzteile, Festplatten, die zur Root gehören, und alle nicht-Root-Aggregate erneut zu, die im Abschnitt früher nicht in node3 verschoben wurden link:relocate_non_root_aggr_node2_node3.html["Verschieben Sie Aggregate ohne Root-Root-Fehler von node2 auf node3"]:
+

NOTE: Wenn Sie auf Ihrem System freigegebene Festplatten, Hybrid-Aggregate oder beides haben, müssen Sie die korrekte verwenden `disk reassign` Befehl aus der folgenden Tabelle.

+
[cols="35,65"]
|===
| Festplattentyp... | Führen Sie den Befehl aus... 


| Mit gemeinsamen Festplatten | `disk reassign -s`

`_node2_sysid_ -d _node4_sysid_ -p _node3_sysid_` 


| Ohne Shared-Ressourcen | `disks disk reassign -s`

`_node2_sysid_ -d _node4_sysid_` 
|===
+
Für das `<node2_sysid>` Wert: Verwenden Sie die in erfassten Informationen link:record_node2_information.html#man_node2_info_step10["Schritt 10"] Des Abschnitts _Record node2 information_. Für `_node4_sysid_`Verwenden Sie die Informationen, die in erfasst werden <<man_install4_step23,Schritt 23>>.

+

NOTE: Der `-p` Die Option ist nur im Wartungsmodus erforderlich, wenn freigegebene Festplatten vorhanden sind.

+
Der `disk reassign` Befehl weist nur die Festplatten zu, für die es erforderlich ist `_node2_sysid_` Ist der aktuelle Eigentümer.

+
Vom System wird die folgende Meldung angezeigt:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n
----
+
Eingabe `n` Wenn Sie aufgefordert werden, die Neuzuweisung der Festplatte abzubrechen.

+
Wenn Sie aufgefordert werden, die Neuzuweisung der Festplatte abzubrechen, müssen Sie eine Reihe von Eingabeaufforderungen beantworten, wie in den folgenden Schritten dargestellt:

+
.. Vom System wird die folgende Meldung angezeigt:
+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
----
.. Eingabe `y` Um fortzufahren.
+
Vom System wird die folgende Meldung angezeigt:

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)? y
----
.. Eingabe `y` Um die Aktualisierung der Festplatteneigentümer zu ermöglichen.


. Wenn Sie ein Upgrade von einem System mit externen Festplatten auf ein System durchführen, das interne und externe Festplatten unterstützt (z. B. A800-Systeme), setzen sie node4 als root, um zu bestätigen, dass es aus dem Root-Aggregat von node2 startet.
+

WARNING: *Warnung: Sie müssen die folgenden Teilschritte in der angegebenen Reihenfolge durchführen; andernfalls kann es zu einem Ausfall oder sogar zu Datenverlust kommen.*

+
Mit dem folgenden Verfahren wird node4 vom Root-Aggregat von node2 gestartet:

+
.. Überprüfen Sie die RAID-, Plex- und Prüfsummeninformationen für das node2 Aggregat:
+
`aggr status -r`

.. Prüfen Sie den Gesamtstatus des node2-Aggregats:
+
`aggr status`

.. Bei Bedarf das node2 Aggregat online bringen:
+
`aggr_online root_aggr_from___node2__`

.. Verhindern Sie, dass das node4 aus dem ursprünglichen Root-Aggregat gebootet wird:
+
`aggr offline _root_aggr_on_node4_`

.. Legen Sie das node2-Root-Aggregat als das neue Root-Aggregat für node4 fest:
+
`aggr options aggr_from___node2__ root`



. Vergewissern Sie sich, dass Controller und Chassis als konfiguriert sind `ha` Indem Sie den folgenden Befehl eingeben und die Ausgabe beobachten:
+
`ha-config show`

+
Das folgende Beispiel zeigt die Ausgabe von `ha-config show` Befehl:

+
[listing]
----
*> ha-config show
   Chassis HA configuration: ha
   Controller HA configuration: ha
----
+
Systeme zeichnen in EINEM PROM auf, ob sie in einem HA-Paar oder einer Standalone-Konfiguration sind. Der Status muss auf allen Komponenten im Standalone-System oder im HA-Paar der gleiche sein.

+
Wenn Controller und Chassis nicht als konfiguriert wurden `ha`, Verwenden Sie die folgenden Befehle, um die Konfiguration zu korrigieren:

+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`.

+
Wenn Sie eine MetroCluster-Konfiguration haben, verwenden Sie die folgenden Befehle, um die Konfiguration zu korrigieren:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`.

. Löschen Sie die Mailboxen auf node4:
+
`mailbox destroy local`

. Beenden des Wartungsmodus:
+
`halt`

+
Das System wird an der Eingabeaufforderung für die Boot-Umgebung angehalten.

. Überprüfen Sie in Knoten 3 das Systemdatum, die Uhrzeit und die Zeitzone:
+
`date`

. Prüfen Sie am node4 das Datum an der Eingabeaufforderung für die Boot-Umgebung:
+
`show date`

. Legen Sie bei Bedarf das Datum auf node4 fest:
+
`set date _mm/dd/yyyy_`

. Prüfen Sie auf node4 die Zeit an der Eingabeaufforderung der Boot-Umgebung:
+
`show time`

. Stellen Sie bei Bedarf die Uhrzeit auf node4 ein:
+
`set time _hh:mm:ss_`

. Überprüfen Sie, ob die Partner-System-ID korrekt festgelegt ist, wie in beschrieben <<man_install4_Step26,Schritt 26>> Unter Option.
+
`printenv partner-sysid`

. Legen Sie bei Bedarf die Partner System-ID auf node4 fest:
+
`setenv partner-sysid _node3_sysid_`

+
.. Einstellungen speichern:
+
`saveenv`



. Rufen Sie das Boot-Menü an der Eingabeaufforderung der Boot-Umgebung auf:
+
`boot_ontap menu`

. Wählen Sie im Startmenü die Option *(6) Flash von Backup config* aktualisieren, indem Sie eingeben `6` An der Eingabeaufforderung.
+
Vom System wird die folgende Meldung angezeigt:

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. Eingabe `y` An der Eingabeaufforderung.
+
Der Startvorgang läuft normal weiter, und das System fordert Sie auf, die Unstimmigkeit der System-ID zu bestätigen.

+

NOTE: Das System wird möglicherweise zweimal neu gestartet, bevor die Warnmeldung zur Nichtübereinstimmung angezeigt wird.

. Bestätigen Sie die Diskrepanz. Der Node kann vor dem normalen Booten eine Runde des Neubootens abschließen.
. Melden Sie sich bei node4 an.

