= Konfigurieren Sie FC-Ports auf node4
:allow-uri-read: 




== Konfigurieren Sie FC-Ports auf node4

Wenn node4 FC-Ports hat, entweder Onboard oder auf einem FC-Adapter, müssen Sie Port-Konfigurationen auf dem Node festlegen, bevor Sie ihn in den Dienst stellen, da die Ports nicht vorkonfiguriert sind. Wenn die Ports nicht konfiguriert sind, kann es zu einer Serviceunterbrechung kommen.

.Bevor Sie beginnen
Sie müssen die Werte der FC-Port-Einstellungen von node2 haben, die Sie im Abschnitt gespeichert haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"].

.Über diese Aufgabe
Sie können diesen Abschnitt überspringen, wenn Ihr System über keine FC-Konfigurationen verfügt. Wenn Ihr System über integrierte UTA/UTA2-Ports oder einen UTA/UTA2-Adapter verfügt, konfigurieren Sie sie in <<UTA/UTA2-Ports auf node4 prüfen und konfigurieren>>.


IMPORTANT: Geben Sie die Befehle in diesem Abschnitt an der Cluster-Eingabeaufforderung ein.

.Schritte
. Zeigen Sie Informationen zu allen FC- und konvergenten Netzwerkadaptern auf dem System an:
+
`system node hardware unified-connect show`

. Vergleichen Sie die FC-Einstellungen auf den neuen Nodes mit den Einstellungen, die Sie zuvor vom ursprünglichen Node erfasst haben.
. Ändern Sie die FC-Ports auf node4 nach Bedarf:
+
** So programmieren Sie Zielanschlüsse:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** So programmieren Sie Initiator-Ports:
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
`-type` Ist der FC4-Typ, das Ziel oder der Initiator.



. Überprüfen Sie die neuen Einstellungen, indem Sie den folgenden Befehl eingeben und die Ausgabe prüfen:
+
`system node unified-connect show`

. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn die FC-Standardeinstellungen auf den neuen Nodes sind... | Dann… 


| Das gleiche wie diejenigen, die Sie auf den ursprünglichen Knoten erfasst | Gehe zu<<man_config_4_Step9,Schritt 9>> . 


| Anders als jene, die Sie auf den ursprünglichen Knoten erfasst haben | Gehe zu<<man_config_4_Step6,Step6>> . 
|===
. [[man_config_4_Step6]]Wartungsmodus beenden:
+
`halt`

. Nachdem Sie den Befehl eingegeben haben, warten Sie, bis das System an der Eingabeaufforderung der Boot-Umgebung angehalten wird.
. Booten Sie Knoten4, indem Sie an der Eingabeaufforderung der Boot-Umgebung den folgenden Befehl eingeben:
+
`boot_ontap`

. [[man_config_4_Step9]]Führen Sie eine der folgenden Aktionen aus:
+
** Gehen Sie zu <<UTA/UTA2-Ports auf node4 prüfen und konfigurieren>> Bei node4 mit einer UTA/UTA2-Karte oder Onboard-Ports UTA/UTA2:
** Überspringen Sie den Abschnitt und gehen Sie zu link:map_ports_node2_node4.html["Weisen Sie Ports von node2 nach node4 zu"] Wenn node4 keine UTA/UTA2-Karte oder UTA/UTA2 Onboard-Ports hat.



