= UTA/UTA2-Ports auf node4 prüfen und konfigurieren
:allow-uri-read: 




== UTA/UTA2-Ports auf node4 prüfen und konfigurieren

Wenn node4 Onboard UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Konfiguration der Ports überprüfen und sie je nach Nutzung des aktualisierten Systems konfigurieren.

.Bevor Sie beginnen
Sie müssen die richtigen SFP+ Module für die UTA/UTA2-Ports besitzen.

.Über diese Aufgabe
DIE UTA2-Ports können im nativen FC-Modus oder im UTA/UTA2-Modus konfiguriert werden. Der FC-Modus unterstützt FC Initiator und FC Target. Der UTA-/UTA2-Modus ermöglicht es, gleichzeitig NIC- und FCoE-Datenverkehr auf die gleiche 10-GbE-SFP+-Schnittstelle zu übertragen und das FC-Ziel zu unterstützen.


NOTE: Bei NetApp Marketingmaterialien wird möglicherweise der Begriff UTA2 verwendet, um sich auf CNA-Adapter und Ports zu beziehen. Allerdings verwendet die CLI den Begriff CNA.

UTA2-Ports können an einem Adapter oder auf dem Controller mit den folgenden Konfigurationen verwendet werden:

* UTA-/UTA2-Karten, die gleichzeitig mit dem Controller bestellt wurden, werden vor dem Versand konfiguriert, um die von Ihnen angeforderte Persönlichkeit zu erhalten.
* DIE UTA2-Karten, die separat vom Controller bestellt werden, werden mit der standardmäßigen FC-Zielgruppe ausgeliefert.
* Onboard UTA/UTA2-Ports auf neuen Controllern werden konfiguriert (vor dem Versand), um die von Ihnen angeforderte Persönlichkeit zu besitzen.


Sie können jedoch die Konfiguration der UTA/UTA2-Ports auf node4 überprüfen und sie gegebenenfalls ändern.


WARNING: Geben Sie die Befehle in diesem Abschnitt an der Cluster-Eingabeaufforderung ein, sofern Sie nicht aufgefordert werden, in den Wartungsmodus zu wechseln.  Wenn Sie über ein MetroCluster FC-System verfügen, müssen Sie sich im Wartungsmodus befinden, um UTA/UTA2-Ports zu konfigurieren.

.Schritte
. Überprüfen Sie, wie die Ports derzeit auf Knoten4 konfiguriert sind:
+
`system node hardware unified-connect show`

. Wenn das aktuelle SFP+-Modul nicht mit der gewünschten Verwendung übereinstimmt, ersetzen Sie es durch das richtige SFP+-Modul.
+
Wenden Sie sich an Ihren NetApp Ansprechpartner, um das richtige SFP+ Modul zu erhalten.

. Überprüfen Sie die Ausgabe des `system node hardware unified-connect show` Oder `ucadmin show` Führen Sie einen Befehl aus, und bestimmen Sie, ob die UTA/UTA2-Ports die gewünschte Persönlichkeit haben.
. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn die CNA-Ports... | Dann... 


| Haben Sie nicht die Persönlichkeit, die Sie wollen | Gehen Sie zu <<man_check_4_Step5,Schritt 5>>. 


| Haben Sie die Persönlichkeit, die Sie wollen | Überspringen Sie Schritt 5 bis Schritt 12, und fahren Sie mit fort <<man_check_4_Step13,Schritt 13>>. 
|===
. [[man_check_4_Step5]]Wenn das System über Speicherfestplatten verfügt und Data ONTAP 8.3 ausführt, booten Sie Knoten 4 und wechseln Sie in den Wartungsmodus:
+
`boot_ontap maint`

. Überprüfen Sie die Einstellungen, indem Sie den folgenden Befehl eingeben und seine Ausgabe überprüfen:
+
`ucadmin show`

. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn Sie konfigurieren... | Dann... 


| Ports auf einer UTA/UTA2-Karte | Gehe zu<<man_check_4_Step8,Schritt 8>> . 


| Onboard UTA/UTA2-Ports | Überspringen Sie Schritt 8 und gehen Sie zu<<man_check_4_Step9,Schritt 9>> . 
|===
. [[man_check_4_Step8]]Wenn sich der Adapter im Initiatormodus befindet und der UTA/UTA2-Port online ist, schalten Sie den UTA/UTA2-Port offline:
+
`storage disable adapter _adapter_name_`

+
Adapter im Zielmodus sind im Wartungsmodus automatisch offline.

. [[man_check_4_Step9]]Wenn die aktuelle Konfiguration nicht der gewünschten Verwendung entspricht, geben Sie den folgenden Befehl ein, um die Konfiguration nach Bedarf zu ändern:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` Ist der Personality Modus: FC oder 10GbE UTA.
** `-t` Ist der FC4-Typ: Target oder Initiator.


+

NOTE: Sie müssen den FC-Initiator für Bandlaufwerke und das FC-Ziel für SAN-Clients verwenden.

. Wenn das System über Speicherplatten verfügt, geben Sie den folgenden Befehl ein:
+
`halt`

+
Das System wird an der Eingabeaufforderung für die Boot-Umgebung angehalten.

+
.. Geben Sie den folgenden Befehl ein:
+
`boot_ontap`



. Wenn das System über Speicherplatten verfügt, geben Sie den folgenden Befehl ein:
+
`system node hardware unified-connect show`

+
Die Ausgabe in den folgenden Beispielen zeigt, dass sich der Adaptertyp „1b“ in ändert `initiator` Und dass sich der Modus der Adapter „2a“ und „2b“ in ändert `cna`.

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
. Platzieren Sie alle Ziel-Ports online, indem Sie einen der folgenden Befehle eingeben, einmal für jeden Port:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up`

. [[man_Check_4_Step13]]Anschluss verkabeln.

