= 
:allow-uri-read: 


sie müssen node4 im Rack installieren, Node2-Verbindungen zu node4 übertragen und node4 booten. Sie müssen auch node2-Spares, alle Festplatten der Root-Partition und alle nicht-Root-Aggregate neu zuweisen, die nicht zu node3 früher verschoben wurden.

.Über diese Aufgabe
Sie müssen node4 als Netzboot fahren, wenn nicht die gleiche Version von ONTAP 9 auf node2 installiert ist. Nachdem sie node4 installiert haben, starten Sie es vom ONTAP 9-Image, das auf dem Webserver gespeichert ist. Anschließend können Sie die richtigen Dateien auf das Boot-Medium für den späteren Systemstart herunterladen, indem Sie den Anweisungen unter folgen link:prepare_for_netboot.html["Vorbereitungen für den Netzboot"]

Sie sind jedoch nicht verpflichtet, Netboot node4 zu starten, wenn es die gleiche oder eine höhere Version von ONTAP 9 hat, die auf node2 installiert ist.

* Wichtige Informationen:*

* Wenn Sie ein V-Series System oder ein System mit mit mit FlexArray Virtualisierungssoftware aktualisieren, die mit Storage-Arrays verbunden ist, müssen Sie diese vollständig ausführen <<man_install4_Step1,Schritt 1>> Bis <<man_install4_Step7,Schritt 7>>, Lassen Sie diesen Abschnitt bei <<man_install4_Step8,Schritt 8>> Und befolgen Sie die Anweisungen unter link:set_fc_uta_uta2_config_node4.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node4 fest"] Geben Sie bei Bedarf die Befehle im Wartungsmodus ein. Sie müssen dann zu diesem Abschnitt zurückkehren und den Vorgang unter fortsetzen <<man_install4_Step9,Schritt 9>>.
* Wenn Sie jedoch ein System mit Speicherfestplatten aktualisieren, müssen Sie diesen gesamten Abschnitt abschließen und dann mit dem Abschnitt fortfahren link:set_fc_uta_uta2_config_node4.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node4 fest"], Eingabe von Befehlen an der Cluster-Eingabeaufforderung.


.Schritte
. [[man_install4_Step1]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn node4 wird in ... | Dann... 


| Ein von Knoten 3 getrenntes Chassis | Gehen Sie zu <<man_install4_Step2,Schritt 2>>. 


| Im gleichen Chassis mit Knoten3 | Überspringen Sie die Schritte 2 und 3 und gehen Sie zu <<man_install4_Step4,Schritt 4>>. 
|===
. [[man_install4_Step2]] stellen Sie sicher, dass node4 über ausreichend Rack-Platz verfügt.
+
Wenn node4 sich in einem separaten Chassis von node3 befindet, können sie node4 an der gleichen Stelle wie node2 platzieren. Wenn sich Node3 und node4 im selben Chassis befinden, befindet sich node4 bereits in der entsprechenden Rack-Position.

. installieren sie node4 im Rack gemäß den Anweisungen in der Anleitung _Installation and Setup Instructions_ für das Node-Modell.
. [[man_install4_Step4]]kabelnode4, die Verbindungen von node2 nach node4 verschieben.
+
Die folgenden Referenzen helfen Ihnen dabei, geeignete Kabelverbindungen zu machen. Gehen Sie zu link:other_references.html["Quellen"] Um eine Verbindung zu ihnen zu machen.

+
** _Installations- und Setup-Anleitung_ oder _Installationsanforderungen für die FlexArray-Virtualisierung und Referenz_ für die node4-Plattform
** Das entsprechende Verfahren für das Festplatten-Shelf
** Die Dokumentation _High Availability Management_
+
Folgende Anschlüsse verkabeln:

** Konsole (Remote-Management-Port)
** Cluster-Ports
** Datenports
** Cluster- und Node-Management-Ports
** Storage
** SAN-Konfigurationen: ISCSI Ethernet und FC Switch Ports


+

NOTE: Sie müssen die Interconnect-Karte/FC_VI-Karte oder den Interconnect/FC_VI-Kabelanschluss von node2 auf node4 nicht verschieben, da die meisten Plattformmodelle über einzigartige Interconnect-Kartenmodelle verfügen.

. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn node4 in... | Dann... 


| Im gleichen Chassis wie bei Node3 | Gehen Sie zu <<man_install4_Step8,Schritt 8>>. 


| Ein von Knoten 3 getrenntes Chassis | Gehen Sie zu <<man_install4_Step6,Schritt 6>>. 
|===
. [[man_install4_Step6]]Schalten Sie die Stromversorgung zu node4 ein, und unterbrechen Sie dann den Start, indem Sie Strg-C drücken, um auf die Eingabeaufforderung der Startumgebung zuzugreifen.
+

NOTE: Wenn Sie node4 booten, wird möglicherweise die folgende Meldung angezeigt:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7]]Wenn die Warnmeldung in Schritt 6 angezeigt wird, führen Sie die folgenden Schritte aus:
+
.. Überprüfen Sie auf Meldungen der Konsole, die auf ein anderes Problem als eine schwache NVRAM-Batterie hinweisen und ergreifen Sie gegebenenfalls erforderliche Korrekturmaßnahmen.
.. Lassen Sie den Akku laden und den Bootvorgang beenden.
+

WARNING: *Warnung: Die Verzögerung nicht außer Kraft setzen. Wenn der Akku nicht geladen werden kann, kann dies zu einem Datenverlust führen.*



. [[man_install4_Step8]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn Ihr System... | Dann... 


| Verfügt über Festplatten und keinen Back-End-Speicher | Überspringen Sie Schritt 9 bis Schritt 14, und fahren Sie mit fort <<man_install4_Step15,Schritt 15>>. 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden  a| 
.. Gehen Sie zum Abschnitt „ FC- oder UTA/UTA2-Konfiguration auf node4_“ und füllen Sie die Abschnitte aus link:set_fc_uta_uta2_config_node4.html#configure-fc-ports-on-node4["Konfigurieren Sie FC-Ports auf node4"] Und link:set_fc_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["UTA/UTA2-Ports auf node4 prüfen und konfigurieren"], Je nach Ihrem System.
.. Kehren Sie zu diesem Abschnitt zurück, und führen Sie die verbleibenden Schritte aus. Beginnen Sie mit <<man_install4_Step9,Schritt 9>>.



IMPORTANT: Vor dem Booten von ONTAP auf dem V-Series System müssen Sie die integrierten FC-Ports, UTA/UTA2-Ports und UTA/UTA2-Karten neu konfigurieren.

|===
. [[man_install4_Step9]]Fügen Sie die FC-Initiator-Ports des neuen Node zu den Switch-Zonen hinzu.
+
Anweisungen finden Sie in der Dokumentation für das Storage-Array und Zoning.

. Fügen Sie die FC-Initiator-Ports dem Speicher-Array als neue Hosts hinzu, und ordnen Sie die Array-LUNs den neuen Hosts zu.
+
Anweisungen finden Sie in der Dokumentation für das Storage-Array und Zoning.

. Ändern Sie die WWPN-Werte (World Wide Port Name) in den Host- oder Volume-Gruppen, die Array-LUNs auf dem Speicher-Array zugeordnet sind.
+
Durch die Installation eines neuen Controller-Moduls werden die WWPN-Werte geändert, die den einzelnen integrierten FC-Ports zugeordnet sind.

. Wenn die Konfiguration das Switch-basierte Zoning verwendet, passen Sie das Zoning an die neuen WWPN-Werte an.
. Überprüfen Sie, ob die Array-LUNs nun für node4 sichtbar sind, indem Sie den folgenden Befehl eingeben und seine Ausgabe prüfen:
+
`sysconfig -v`

+
Das System zeigt alle Array-LUNs an, die für jeden FC-Initiator-Port sichtbar sind. Wenn die Array-LUNs nicht sichtbar sind, können Sie Festplatten von node2 nicht später in diesem Abschnitt neu zuweisen.

. Drücken Sie Strg-C, um das Startmenü anzuzeigen, und wählen Sie Wartungsmodus aus.
. [[man_install4_Step15]]Geben Sie in der Eingabeaufforderung für den Wartungsmodus den folgenden Befehl ein:
+
`halt`

+
Das System wird an der Eingabeaufforderung für die Boot-Umgebung angehalten.

. node4 für ONTAP konfigurieren:
+
`set-defaults`


