---
sidebar: sidebar 
permalink: upgrade-arl-manual/aggregate_relocation_failures.html 
keywords: aggregate, relocation, failure, error, problem 
summary: Beheben Sie Fehler bei der Aggregatverschiebung, die während eines manuellen ARL Upgrades bei Controllern mit ONTAP 9.7 oder einer älteren Version auftreten können. 
---
= Fehler bei der Aggregatverschiebung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bei der Aggregatverschiebung (ARL, Aggregate Relocation) fallen während des Upgrades möglicherweise an verschiedenen Punkten aus.



== Prüfen Sie, ob Aggregate Relocation Failure vorhanden sind

Während des Verfahrens kann ARL in Phase 2, Phase 3 oder Phase 5 fehlschlagen.

.Schritte
. Geben Sie den folgenden Befehl ein und überprüfen Sie die Ausgabe:
+
`storage aggregate relocation show`

+
Der `storage aggregate relocation show` Der Befehl zeigt Ihnen, welche Aggregate erfolgreich umgezogen wurden und welche nicht, zusammen mit den Ursachen des Ausfalls.

. Überprüfen Sie die Konsole auf EMS-Nachrichten.
. Führen Sie eine der folgenden Aktionen durch:
+
** Führen Sie die entsprechenden Korrekturmaßnahmen durch, je nach der Ausgabe des `storage aggregate relocation show` Befehl und Ausgabe der EMS-Nachricht.
** Erzwingen Sie das verlagern des Aggregats oder der Aggregate mit dem `override-vetoes` Oder die Option `override-destination-checks` Option des `storage aggregate relocation start` Befehl.


+
Für detaillierte Informationen zu den  `storage aggregate relocation start`, `override-vetoes` und  `override-destination-checks` Optionen verweisen Sie auf link:other_references.html["Quellen"] zum Link zur _ONTAP 9 Command reference_.





== Aggregate, die ursprünglich auf node1 waren, gehören node4 nach Abschluss des Upgrades

Beim Abschluss des Upgrade-Verfahrens muss die Knoten3 der neue Home-Node von Aggregaten sein, die ursprünglich als Home-Node die Knoten1 hatten. Sie können sie nach dem Upgrade verschieben.

.Über diese Aufgabe
Unter den folgenden Umständen kann es nicht gelingen, Aggregate ordnungsgemäß zu verschieben und Node 1 als Home Node anstelle von Knoten3 zu verwenden:

* In Phase 3 werden Aggregate von node2 zu node3 verschoben. Einige der verschobenen Aggregate haben node1 als ihren Heimatknoten. Ein solches Aggregat könnte beispielsweise aggr_node_1 heißen. Schlägt die Verschiebung von aggr_node_1 in Phase 3 fehl und kann sie nicht erzwungen werden, verbleibt das Aggregat auf node2.
* Nach Phase 4, wenn node2 durch node4 ersetzt wird. Wenn node2 ersetzt wird, geht aggr_node_1 mit node4 als seinem Heimatknoten online, anstatt mit node3.


Sie können das falsche Eigentümerproblem nach Phase 6 beheben, wenn ein Storage-Failover aktiviert wurde, indem Sie die folgenden Schritte durchführen:

.Schritte
. [[man_aggr_fail_STep1]]Geben Sie den folgenden Befehl ein, um eine Liste der Aggregate zu erhalten:
+
`storage aggregate show -nodes _node4_ -is-home true`

+
Informationen zur Identifizierung von Aggregaten, die nicht korrekt verschoben wurden, finden Sie in der Liste der Aggregate mit dem Home-Inhaber von node1, die Sie im Abschnitt erhalten haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"] Und vergleichen Sie ihn mit der Ausgabe des obigen Befehls.

. [[Schritt2]]Vergleichen Sie die Ausgabe von <<man_aggr_fail_step1,Schritt 1>> Mit der Ausgabe, die Sie für node1 im Abschnitt aufgenommen haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"] Und beachten Sie alle Aggregate, die nicht korrekt verschoben wurden.
. [[man_aggr_fail_Step3]]Verschiebung der Aggregate links auf node4:
+
`storage aggregate relocation start -node _node4_ -aggr _aggr_node_1_ -destination _node3_`

+
Verwenden Sie das nicht `-ndo-controller-upgrade` Parameter während dieser Verschiebung.

. Geben Sie den folgenden Befehl ein, um zu überprüfen, ob node3 jetzt der Haupteigentümer der Aggregate ist:
+
`storage aggregate show -aggregate _aggr1,aggr2,aggr3..._ -fields home-name`

+
`_aggr1,aggr2,aggr3..._` Ist die Liste der Aggregate, die node1 als ursprünglichen Besitzer hatten.

+
Aggregate, die nicht über Node3 als Hausbesitzer verfügen, können mit dem gleichen Relocation-Befehl in auf node3 verschoben werden <<man_aggr_fail_Step3,Schritt 3>>.


