---
sidebar: sidebar 
permalink: upgrade-arl-manual/decide_to_use_arl_guide.html 
keywords: decision, decision, what to use, upgrade, HA pair, metrocluster, storage encryption, volume encryption, NSE, NVE 
summary: Entscheiden Sie, ob Sie das manuelle ARL-Verfahren verwenden möchten, um Speichercontroller in einem HA-Paar mit neuen Controllern mit ONTAP 9.7 oder früher zu aktualisieren. 
---
= Entscheiden Sie, ob Sie dieses Verfahren zur Aggregatverlagerung verwenden möchten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieses Verfahren beschreibt die Aktualisierung der Controller-Hardware mithilfe der manuellen Aggregatverlagerung (ARL) auf Systemen mit ONTAP 9.7 oder älter. Sie sollten dieses komplexe Verfahren nur verwenden, wenn Sie ein erfahrener ONTAP-Administrator sind.

Verwenden Sie diese Inhalte unter folgenden Umständen:

* Sie möchten die neuen Controller nicht als neues HA-Paar zum Cluster hinzufügen und die Daten mithilfe von Volume-Verschiebungen migrieren.
* Sie sind in der Verwaltung von ONTAP erfahren und sind mit den Risiken der Arbeit im Diagnose-Privilege-Modus vertraut.
* Auf Ihren Controllern läuft ONTAP 9.7 oder früher.
* Sie verfügen über ein System, bei dem Fabric MetroCluster Konfigurationen mit 4 und 8 Nodes mit ONTAP 9.5 oder einer älteren Version verwendet werden.


[NOTE]
====
* . Dieses ARL-Verfahren umfasst die Schritte, die sicherstellen, dass die internen Festplatten sicher im Gehäuse bleiben, wenn Sie während des Upgrade-Vorgangs die Controller entfernen und installieren
+
link:../upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html#supported-systems-in-chassis["Erfahren Sie mehr über die unterstützten System-Upgrade-Kombinationen mit ARL, wobei das vorhandene Systemgehäuse und die Festplatten erhalten bleiben"].

* Dabei können Sie NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) und NetApp Aggregate Encryption (NAE) verwenden.


====
Wenn Sie eine andere Methode zum Upgrade der Controller-Hardware bevorzugen und bereit sind, Volume-Verschiebungen durchzuführen, lesen Sie link:other_references.html["Quellen"] Link zu _Upgrade durch Verschieben von Volumes oder Storage_.

Siehe link:other_references.html["Quellen"] Zum Link zum Dokumentationszentrum _ONTAP 9_, wo Sie auf die Produktdokumentation zu ONTAP 9 zugreifen können.



== Wählen Sie ein anderes Verfahren zum Hardware-Upgrade

* link:../upgrade-arl/index.html["Überprüfen Sie die verfügbaren alternativen ARL-Methoden zum Aktualisieren der Controller-Hardware"].
* Wenn Sie eine andere Methode zum Upgrade der Controller-Hardware bevorzugen und bereit sind, Volume-Verschiebungen durchzuführen, lesen Sie link:other_references.html["Quellen"] Link zu _Upgrade durch Verschieben von Volumes oder Storage_.


.Verwandte Informationen
Siehe link:other_references.html["Quellen"] um auf die _ONTAP 9-Dokumentation_ zu verlinken.
