---
sidebar: sidebar 
permalink: upgrade-arl-manual/ensure_controllers_set_up_correctly.html 
keywords: set up, controllers, correctly, ha pair, lif, aggregate, node, failover 
summary: Aktivieren Sie das HA-Paar, überprüfen Sie den Node3- und node4-Storage-Zugriff und bestätigen Sie die Eigentümerschaft von Aggregaten nach einem manuellen ARL Upgrade auf Controllern mit ONTAP 9.7 oder einer älteren Version. 
---
= Vergewissern Sie sich, dass die neuen Controller ordnungsgemäß eingerichtet sind
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um die korrekte Einrichtung zu bestätigen, aktivieren Sie das HA-Paar. Außerdem überprüfen Sie, ob Node 3 und node 4 auf den Storage zugreifen können und ob keine der Daten-LIFs gehören, die zu anderen Nodes im Cluster gehören. Außerdem bestätigen Sie, dass Node 3 Eigentümer der Aggregate von Node 1 ist und node4 Eigentümer der Aggregate von Node 2 ist und die Volumes für beide Nodes online sind.

.Schritte
. Aktivieren Sie Storage Failover, indem Sie auf einem der Nodes den folgenden Befehl eingeben:
+
`storage failover modify -enabled true -node _node3_`

. Vergewissern Sie sich, dass Storage-Failover aktiviert ist:
+
`storage failover show`

+
Im folgenden Beispiel wird die Ausgabe des Befehls angezeigt, wenn ein Storage Failover aktiviert ist:

+
[listing]
----
cluster::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ------------------
node3          node4          true     Connected to node4
node4          node3          true     Connected to node3
----
. Führen Sie eine der folgenden Aktionen durch:
+
|===
| Wenn der Cluster ein... | Beschreibung 


| Cluster mit zwei Nodes | Aktivieren Sie die Hochverfügbarkeit im Cluster, indem Sie auf einem der Nodes den folgenden Befehl eingeben:
`cluster ha modify -configured true` 


| Cluster mit mehr als zwei Nodes | Gehen Sie zu <<man_ensure_setup_Step4,Schritt 4>>. 
|===
. [[man_enfy_Setup_Step4]]Überprüfen Sie, ob node3 und node4 zum selben Cluster gehören, indem Sie den folgenden Befehl eingeben und die Ausgabe überprüfen:
+
`cluster show`

. Stellen Sie sicher, dass node3 und node4 auf den Storage der jeweils anderen zugreifen können, indem Sie den folgenden Befehl eingeben und die Ausgabe überprüfen:
+
`storage failover show -fields local-missing-disks,partner-missing-disks`

. Vergewissern Sie sich, dass weder node3 noch node4 Eigentümer von Daten-LIFs sind, die im Besitz anderer Nodes im Cluster sind. Geben Sie dazu den folgenden Befehl ein und prüfen Sie die Ausgabe:
+
`network interface show`

+
Wenn Node3 oder node4 im Besitz von Daten-LIFs sind, die sich im Besitz anderer Nodes im Cluster befinden, verwenden Sie die `network interface revert` Befehl zum Zurücksetzen der Daten-LIFs auf den Home-Eigentümer.

. Überprüfen Sie, ob node3 die Aggregate von node1 besitzt und dass node4 die Aggregate von node2 besitzt:
+
`storage aggregate show -owner-name _node3_`
`storage aggregate show -owner-name _node4_`

. Legen Sie fest, ob Volumes offline sind:
+
`volume show -node _node3_ -state offline`
`volume show -node _node4_ -state offline`

. Wenn Volumes offline sind, vergleichen Sie sie mit der Liste der Offline-Volumes, die Sie in erfasst haben  link:prepare_nodes_for_upgrade.html#man_prepare_nodes_step19["Schritt 19 (d)"] In _die Nodes für Upgrade_ vorbereiten und jedes der Offline-Volumes nach Bedarf durch Eingabe des folgenden Befehls ein Mal für jedes Volume den Online-Modus versetzen:
+
`volume online -vserver _vserver_name_ -volume _volume_name_`

. Installieren Sie neue Lizenzen für die neuen Nodes, indem Sie den folgenden Befehl für jeden Node eingeben:
+
`system license add -license-code _license_code,license_code,license_code..._`

+
Der Lizenzcode-Parameter akzeptiert eine Liste von 28 alphabetischen Zeichenschlüsseln für Großbuchstaben. Sie können jeweils eine Lizenz hinzufügen, oder Sie können mehrere Lizenzen gleichzeitig hinzufügen, jeden Lizenzschlüssel durch ein Komma getrennt.

. [[unset_maxwait_manual]]Wenn in der Konfiguration selbstverschlüsselnde Laufwerke verwendet werden und Sie den eingestellt haben `kmip.init.maxwait` Variabel auf `off` (Beispiel in link:install_boot_node3.html#man_install3_step16["Schritt 16"] Von _Install and Boot node3_) müssen Sie die Variable aufheben:
+
`set diag; systemshell -node _node_name_ -command sudo kenv -u -p kmip.init.maxwait`

. Geben Sie einen der folgenden Befehle ein, um alle alten Lizenzen von den ursprünglichen Nodes zu entfernen:
+
`system license clean-up -unused -expired`
`system license delete -serial-number _node_serial_number_ -package _licensable_package_`

+
** Um alle abgelaufenen Lizenzen zu löschen, geben Sie Folgendes ein:
+
`system license clean-up -expired`

** Um alle nicht verwendeten Lizenzen zu löschen, geben Sie Folgendes ein:
+
`system license clean-up -unused`

** Geben Sie zum Löschen einer bestimmten Lizenz von einem Cluster die folgenden Befehle auf den Nodes ein:
+
`system license delete -serial-number _node1_serial_number_ -package *`
`system license delete -serial-number _node2_serial_number_ -package *`

+
Die folgende Ausgabe wird angezeigt:

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
Eingabe `y` Um alle Pakete zu entfernen.



. Überprüfen Sie die ordnungsgemäße Installation der Lizenzen, indem Sie den folgenden Befehl eingeben und seine Ausgabe überprüfen:
+
`system license show`

+
Sie können die Ausgabe mit der Ausgabe vergleichen, die Sie in erfasst haben link:prepare_nodes_for_upgrade.html#man_prepare_nodes_step30["Schritt 30"] Von _die Nodes für Upgrade vorbereiten_.

. Konfigurieren Sie die SPs, indem Sie auf beiden Knoten den folgenden Befehl ausführen:
+
`system service-processor network modify -node _node_name_`

+
Gehen Sie zu link:other_references.html["Quellen"] Link zur _Systemverwaltungsreferenz_ für Informationen über die SPs und die Befehle _ONTAP 9: Manual Page Reference_ für detaillierte Informationen zum `system service- processor network modify` Befehl.

. Wenn Sie ein Cluster ohne Switches auf den neuen Nodes einrichten möchten, fahren Sie mit fort link:other_references.html["Quellen"] Um eine Verbindung zur _Network Support Site_ herzustellen, befolgen Sie die Anweisungen unter „ Wechsel zu einem 2-Node-Cluster ohne Switch_“.


.Nachdem Sie fertig sind
Wenn die Speicherverschlüsselung auf Node3 und node4 aktiviert ist, führen Sie die Schritte in aus link:set_up_storage_encryption_new_controller.html["Richten Sie Storage Encryption auf dem neuen Controller-Modul ein"]. Führen Sie andernfalls die Schritte unter aus link:decommission_old_system.html["Ausmustern des alten Systems"].
