---
sidebar: sidebar 
permalink: upgrade-arl-manual/get_address_key_management_server_encryption.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: Konfigurieren Sie die Storage-Verschlüsselung bei einem manuellen ARL Upgrade auf Controllern mit ONTAP 9.7 oder einer älteren Version. 
---
= Holen Sie sich eine IP-Adresse eines externen Verschlüsselungsmanagement-Servers für Storage Encryption
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Nach dem Upgrade müssen Sie Storage Encryption sofort konfigurieren und einen Cluster-weiten Authentifizierungsschlüssel einrichten, um die vorherigen Authentifizierungsschlüssel auf Node-Ebene zu ersetzen.

.Schritte
. Installieren Sie die erforderlichen SSL-Zertifikate (Secure Sockets Layer) von Clients und Servern, die für die Kommunikation mit den Schlüsselverwaltungsservern erforderlich sind:
+
`security certificate install`

. Konfigurieren Sie die Storage-Verschlüsselung auf allen Nodes mithilfe des folgenden Befehls auf jedem Node:
+
`security key-manager setup`

. Fügen Sie für jeden Verschlüsselungsmanagementserver die IP-Adresse hinzu:
+
`security key-manager add`

. Vergewissern Sie sich, dass dieselben Verschlüsselungsmanagement-Server konfiguriert und auf allen Knoten im Cluster verfügbar sind:
+
`security key-manager show -status`

. Erstellen Sie einen neuen clusterweiten Authentifizierungsschlüssel:
+
`security key-manager create-key`

. Notieren Sie sich die neue Authentifizierungsschlüssel-ID.
. Rekeyfür alle Self-Encrypting Drives mit dem neuen Authentifizierungsschlüssel:
+
`storage encryption disk modify -disk * -data-key-id _authentication_key_id_`


