---
sidebar: sidebar 
permalink: upgrade-arl-manual/guidelines_upgrade_with_arl.html 
keywords: guidelines, upgrade, controllers, arl, aggregate, relocation 
summary: Wissen Sie, ob Sie das manuelle ARL-Verfahren für ein Controller-Paar mit ONTAP 9.7 oder einer älteren Version verwenden können. 
---
= Richtlinien für das Controller-Upgrade mit ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um zu verstehen, ob Sie bei einem Controller-Upgrade von ONTAP 9.0 bis 9.7 mit Aggregate Relocation (ARL) arbeiten können, hängt von der Plattform und der Konfiguration der ursprünglichen Controller sowie von den Ersatz-Controllern ab.



[[supported-upgrades-for-arl]]
== Unterstützte Upgrades für ARL

Unter den folgenden Umständen können Sie ein Upgrade eines Node-Paars mit ARL durchführen:

* Die ursprünglichen Controller und die Ersatz-Controller müssen vor dem Upgrade dieselbe Version von ONTAP 9.x ausgeführt werden.
* Die Ersatz-Controller müssen die gleiche oder eine höhere Kapazität aufweisen als die ursprünglichen Controller. Bei gleicher oder höherer Kapazität werden Attribute bezeichnet, beispielsweise die Maximalanzahl für NVRAM, Volume, LUN oder Aggregate. Er bezieht sich auch auf die maximale Volume- oder Aggregatgröße der neuen Nodes.
* Sie können die folgenden Systemtypen aktualisieren:
+
** Einem FAS System auf ein FAS System.
** Einem AFF System auf ein AFF System.





NOTE: Bevor Sie ein AFF-Systemupgrade durchführen, müssen Sie ONTAP auf Version 9.3P12, 9.4P6 oder 9.5P1 oder höher aktualisieren. Diese Versionsebenen sind für ein erfolgreiches Upgrade erforderlich.

* Bei einigen Upgrades des ARL-Controllers können Sie für das Upgrade temporäre Cluster-Ports auf dem Ersatz-Controller verwenden. Wenn Sie beispielsweise je nach Konfiguration der AFF A400 ein Upgrade von einem AFF A300 auf ein AFF A400 System durchführen, können Sie einen der beiden Mezzanine-Ports verwenden oder eine 10-GbE-Netzwerkschnittstellenkarte mit vier Ports für temporäre Cluster-Ports hinzufügen. Nachdem Sie ein Controller-Upgrade über temporäre Cluster-Ports abgeschlossen haben, können Sie Cluster unterbrechungsfrei zu 100-GbE-Ports auf dem Ersatz-Controller migrieren.
* Wenn Sie ONTAP 9.6P11, 9.7P8 oder neuere Versionen verwenden, wird empfohlen, die Aktivierung von Connectivity, Lebendigkeit und Availability Monitor (CLAM)-Übernahme zu aktivieren, um das Cluster bei bestimmten Node-Ausfällen in Quorum zurückzugeben. Der `kernel-service` Für Befehl ist der erweiterte Zugriff auf die Berechtigungsebene erforderlich. Weitere Informationen finden Sie unter: https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436["NetApp KB-Artikel SU436: DIE CLAM-Übernahme hat sich die Standardkonfiguration geändert"^].
* Das Controller-Upgrade mit ARL wird auf Systemen unterstützt, die mit SnapLock Enterprise und SnapLock Compliance Volumes konfiguriert sind.


Es ist zu überprüfen, ob der ARL auf dem Original- und dem Ersatzcontroller durchgeführt werden kann. Die Größe aller definierten Aggregate sowie die Anzahl der vom Originalsystem unterstützten Festplatten sind zu prüfen. Anschließend erfolgt ein Vergleich mit der Aggregatgröße und der Anzahl der vom neuen System unterstützten Festplatten. Für diese Informationen ist auf link:other-references.html["Quellen"] zu verweisen, um zum _Hardware Universe_ zu gelangen. Die Aggregatgröße und die Anzahl der vom neuen System unterstützten Festplatten müssen mindestens der Aggregatgröße und der Anzahl der vom Originalsystem unterstützten Festplatten entsprechen oder diese übertreffen.

In den Cluster-Mischungsregeln ist zu validieren, ob neue Knoten nach dem Austausch des ursprünglichen Controllers zusammen mit den bestehenden Knoten Teil des Clusters werden können. Weitere Informationen zu den Cluster-Mischungsregeln bietet link:other-references.html["Quellen"] der Link zum _Hardware Universe_.


NOTE: Beide Systeme sind entweder hochverfügbarkeits- (HA) oder kein HA-System. Beide Nodes müssen entweder die Persönlichkeit aktiviert oder deaktiviert sein. Sie können einen Node nicht mit der All-Flash-optimierten Persönlichkeit kombinieren, die bei einem Node aktiviert ist, der nicht im gleichen HA-Paar die Persönlichkeit aktiviert hat. Wenn sich die Persönlichkeiten unterscheiden, wenden Sie sich an den technischen Support.


NOTE: Wenn das neue System über weniger Steckplätze als das ursprüngliche System oder über weniger oder andere Ports verfügt, muss dem neuen System möglicherweise ein Adapter hinzugefügt werden. Siehe link:other-references.html["Quellen"] für einen Link zum _Hardware Universe_ auf der NetApp Support Site mit Details zu spezifischen Plattformen.



[[upgrades-not-supported-for-arl]]
== Upgrades werden für ARL nicht unterstützt

Sie können die folgenden Aktualisierungen nicht ausführen:

* Zu bzw. von Controllern, die keine ONTAP Version von ONTAP 9.0 auf ONTAP 9.7 ausführen können
+
Informationen zu Controller-Upgrades für Systeme, auf denen Data ONTAP im 7-Mode ausgeführt wird, sind unter link:other-references.html["Quellen"] im _NetApp Support Site_ verfügbar.

* Zum Austausch von Controllern, die die mit den ursprünglichen Controllern verbundenen Platten-Shelfs nicht unterstützen.
+
Informationen zur Festplattenunterstützung finden sich unter link:other-references.html["Quellen"] dem Link zum _Hardware Universe_.

* Von Controllern mit Root-Aggregaten oder Datenaggregaten auf internen Laufwerken.
+
Wenn ein Upgrade von Controllern mit Root-Aggregaten oder Datenaggregaten auf internen Festplatten durchgeführt werden soll, siehe link:other-references.html["Quellen"] den Link zu _Upgrade durch Verschieben von Volumes oder Storage_ und zur Prozedur _Upgrade eines Node-Paares mit Clustered Data ONTAP durch Verschieben von Volumes_.

+

NOTE: Informationen zur Aktualisierung von ONTAP auf Knoten in einem Cluster finden Sie unter link:other-references.html["Quellen"] dem Link _Upgrade ONTAP_.





[[assumptions-and-terminology]]
== Annahmen und Terminologie

Dieses Dokument wird an folgende Annahmen geschrieben:

* Die Ersatz-Controller-Hardware ist neu und wurde nicht verwendet.
+

WARNING: Die erforderlichen Schritte zur Vorbereitung gebrauchter Steuergeräte mit dem `wipeconfig` Befehle sind in diesem Verfahren nicht enthalten, da dieses Verfahren davon ausgeht, dass die Ersatzcontroller-Hardware neu und unbenutzt ist. Sie müssen sich an den technischen Support wenden, wenn die Ersatz-Controller-Hardware zuvor verwendet wurde, insbesondere wenn auf den Controllern Data ONTAP im 7-Modus ausgeführt wurde.

* Die Richtlinien zum Upgrade des Knotenpaars werden gelesen und verstanden.
+

WARNING: Versuchen Sie nicht, den NVRAM Inhalt zu löschen.  Wenn Sie den Inhalt des NVRAM löschen müssen, wenden Sie sich an den technischen Support von NetApp .

* Sie führen den entsprechenden Befehl vor und nach dem aus `modify` Und die Ausgabe von beiden vergleichen `show` Befehle, um zu überprüfen, dass das `modify` Befehl erfolgreich.
* Wenn Sie über eine SAN-Konfiguration verfügen, stehen Ihnen auf dem HA-Paar lokale LIFs und Partner-LIFs für jede Storage Virtual Machine (SVM) zur Verfügung. Wenn Sie keine lokalen LIFs für jede SVM haben und keine Partner-LIFs haben, sollten Sie vor dem Upgrade die SAN-Daten-LIF auf dem Remote- und lokalen Node für diese SVM hinzufügen.
* Wenn Sie in einer SAN-Konfiguration Port-Sets haben, müssen Sie überprüfen, dass jeder gebundene Port-Satz mindestens eine LIF von jedem Node im HA-Paar enthält.


Bei diesem Verfahren wird der Begriff „_Boot Environment prompt_“ verwendet, um die Eingabeaufforderung auf einem Node, von dem Sie bestimmte Aufgaben ausführen können, zu lesen, z. B. beim Neubooten des Knotens und beim Drucken oder Festlegen von Umgebungsvariablen. Die Eingabeaufforderung wird manchmal informell als _Boot-Loader Prompt_ bezeichnet.

Die Eingabeaufforderung der Boot-Umgebung wird im folgenden Beispiel angezeigt:

[listing]
----
LOADER>
----


[[licensing-in-ontap-9-7-or-earlier]]
== Lizenzierung nach ONTAP 9.7 oder früher

Einige Funktionen erfordern Lizenzen, die als _Packages_ ausgegeben werden, die eine oder mehrere Funktionen enthalten. Jeder Node im Cluster muss über seinen eigenen Schlüssel für jede Funktion im Cluster verfügen.

Wenn Sie keine neuen Lizenzschlüssel haben, sind für den neuen Controller derzeit lizenzierte Funktionen im Cluster verfügbar und funktionieren weiterhin. Durch die Verwendung nicht lizenzierter Funktionen auf dem Controller können Sie jedoch möglicherweise die Einhaltung Ihrer Lizenzvereinbarung verschließen. Sie müssen daher nach Abschluss des Upgrades den neuen Lizenzschlüssel oder die neuen Schlüssel für den neuen Controller installieren.

Alle Lizenzschlüssel bestehen aus 28 Großbuchstaben. Siehe link:other-references.html["Quellen"] für einen Link zur _NetApp Support Site_, auf der neue 28-stellige Lizenzschlüssel für ONTAP 9.7 oder ältere Versionen erhältlich sind. Die Schlüssel sind im Bereich _My Support_ unter _Software licenses_ verfügbar. Falls die benötigten Lizenzschlüssel auf der Website nicht vorhanden sind, kann der NetApp Vertriebsmitarbeiter kontaktiert werden.

Detaillierte Informationen zur Lizenzierung sind unter link:other-references.html["Quellen"] im _System Administration Reference_ verfügbar.



[[storage-encryption]]
== Storage-Verschlüsselung

Die ursprünglichen oder die neuen Nodes sind möglicherweise für die Storage-Verschlüsselung aktiviert. In diesem Fall müssen Sie in diesem Verfahren weitere Schritte durchführen, um zu überprüfen, ob die Speicherverschlüsselung ordnungsgemäß eingerichtet ist.

Falls Sie Storage Encryption verwenden möchten, müssen alle dem Node zugeordneten Festplattenlaufwerke über Self-Encrypting Drives verfügen.



[[two-node-switchless-clusters]]
== 2-Node-Cluster ohne Switches

Wenn Sie Nodes in einem 2-Node-Cluster ohne Switches aktualisieren, können Sie die Nodes im Cluster ohne Switches während des Upgrades belassen. Sie müssen sie nicht in ein Switch-Cluster konvertieren.



[[troubleshoot]]
== Fehlerbehebung

Möglicherweise ist beim Upgrade des Node-Paars ein Fehler auftritt. Der Node kann abstürzen, Aggregate werden möglicherweise nicht verschoben oder LIFs werden nicht migriert. Die Ursache des Fehlers und seiner Lösung hängt davon ab, wann der Fehler während des Aktualisierungsvorgangs aufgetreten ist.

Sollten beim Upgrade der Controller Probleme auftreten, lesen Sie bitte die link:aggregate_relocation_failures.html["Fehlerbehebung"] Abschnitt. Die Informationen zu möglichen Fehlern sind nach Phase des Verfahrens im Abschnitt link:arl_upgrade_workflow.html["ARL-Upgradesequenz"] .

Wenn Sie keine Lösung für das Problem finden, wenden Sie sich an den technischen Support.
