---
sidebar: sidebar 
permalink: upgrade-arl-manual/manage_authentication_okm.html 
keywords: manage, authentication, onboard key manager, okm, key, passphrase, fips 
summary: Verwenden Sie einen integrierten Schlüsselmanager, um Authentifizierungsschlüssel während eines manuellen ARL Upgrades bei Controllern mit ONTAP 9.7 oder einer älteren Version zu managen. 
---
= Verwalten Sie die Authentifizierung über einen integrierten Schlüsselmanager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Authentifizierungsschlüssel mit einem integrierten Schlüsselmanager verwalten. Wenn Sie ein OKM (Onboard Key Manager) verwenden möchten, müssen Sie vor Beginn des Upgrades die Passphrase und das Backup-Material aufzeichnen.

.Schritte
. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server für alle Knoten im Cluster verfügbar sind:
+
`security key-manager key show`

. Rekeyfür alle selbstverschlüsselnden Festplatten mit dem neuen Authentifizierungsschlüssel:
+
`storage encryption disk modify -disk * [-data-key-id nonMSID AK>]`

. Wenn Sie den Federal Information Processing Standard (FIPS) verwenden, müssen Sie alle selbstverschlüsselnden Festplatten mit dem neuen Authentifizierungsschlüssel neu verschlüsseln:
+
`storage encryption disk* modify -disk * [-fips-key-id nonMSID AK]`


