---
sidebar: sidebar 
permalink: upgrade-arl-manual/move_nas_lifs_node1_from_node2_node3_verify_san_lifs_node3.html 
keywords: move, nas, san, lif, ports, broadcast domain, node1, node2, node3 
summary: Verschieben Sie während eines manuellen ARL Upgrades bei Controllern mit ONTAP 9.7 oder einer älteren Version die NAS-Daten-LIFs Node1, die sich auf Knoten 2 von Knoten 2 befinden. 
---
= Verschieben Sie die NAS-Daten-LIFs von node1 auf node2 und überprüfen Sie SAN LIFs auf node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachdem Sie die Installation node3 überprüft haben und bevor Sie Aggregate von node2 auf node3 verschieben, müssen Sie die NAS-Daten-LIFs von node1 verschieben, die sich derzeit in node2 von node2 auf node3 befinden. Sie müssen außerdem die SAN-LIFs auf node3 überprüfen.

Remote-LIFs verarbeiten den Datenverkehr zu SAN-LUNs während des Upgrades. Das Verschieben von SAN-LIFs ist für den Zustand des Clusters oder des Service während des Upgrades nicht erforderlich. SAN LIFs werden nicht verschoben, es sei denn, sie müssen neuen Ports zugeordnet werden. Sie überprüfen, ob die LIFs sich in einem ordnungsgemäßen Zustand befinden und sich auf den entsprechenden Ports befinden, nachdem Sie node3 in den Online-Modus versetzt haben.

.Schritte
. [[Schritt1]]Listen Sie alle NAS-Daten-LIFs auf, die nicht im Besitz von node2 sind, indem Sie auf einem der beiden Knoten den folgenden Befehl eingeben und die Ausgabe erfassen:
+
`network interface show -role data -curr-node _node2_ -is-home false -home-node _node3_`

. [[Arbeitsblatt_Schritt2]] Wenn das Cluster für SAN-LIFs konfiguriert ist, notieren Sie die SAN-LIFs `adapter` Und `switch-port` Konfigurationsinformationen in diesem link:worksheet_information_before_moving_san_lifs_node3.html["Arbeitsblatt"] Zur späteren Verwendung im Verfahren.
+
.. Führen Sie die SAN-LIFs auf node2 auf und untersuchen Sie die Ausgabe:
+
`network interface show -data-protocol fc*`

+
Das System gibt die Ausgabe wie im folgenden Beispiel zurück:

+
[listing]
----
cluster1::> net int show -data-protocol fc*
  (network interface show)
             Logical     Status     Network            Current        Current Is
Vserver      Interface   Admin/Oper Address/Mask       Node           Port    Home
-----------  ----------  ---------- ------------------ -------------  ------- ----
svm2_cluster1
             lif_svm2_cluster1_340
                         up/up      20:02:00:50:56:b0:39:99
                                                       cluster1-01    1b      true
             lif_svm2_cluster1_398
                         up/up      20:03:00:50:56:b0:39:99
                                                       cluster1-02    1a      true
             lif_svm2_cluster1_691
                         up/up      20:01:00:50:56:b0:39:99
                                                       cluster1-01    1a      true
             lif_svm2_cluster1_925
                         up/up      20:04:00:50:56:b0:39:99
                                                       cluster1-02    1b      true
4 entries were displayed.
----
.. Führen Sie die vorhandenen Konfigurationen auf und untersuchen Sie die Ausgabe:
+
`fcp adapter show -fields switch-port,fc-wwpn`

+
Das System gibt die Ausgabe wie im folgenden Beispiel zurück:

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----


. [[Schritt3]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Falls Knoten 1... | Dann... 


| Schnittstellengruppen oder VLANs wurden konfiguriert | Gehen Sie zu ,Schritt 4. 


| Schnittstellengruppen oder VLANs waren nicht konfiguriert | Überspringen Sie Schritt 4, und fahren Sie mit fort ,Schritt 5. 
|===
. [[man_lif_verify_3_step3]]führen Sie die folgenden Teilschritte durch, um alle auf Schnittstellengruppen und VLANs gehosteten NAS-Daten-LIFs zu migrieren, die sich ursprünglich auf node1 von node2 auf node3 befanden:
+
.. [[man_lif_verify_3_subzepa]]Migrieren Sie alle auf node2 gehosteten Daten-LIFs, die zuvor zu node1 auf einer Schnittstellengruppe gehörten, zu einem Port auf node3, der in der Lage ist, LIFs auf demselben Netzwerk zu hosten, indem Sie den folgenden Befehl eingeben – einmal für jede LIF:
+
`network interface migrate -vserver _vserver_name_ -lif _LIF_name_ -destination-node _node3_ –destination-port _netport|ifgrp_`

.. Ändern Sie den Home-Port und den Home-Node der LIF in ,Unterschritt A Geben Sie zum Port und Node, der derzeit die LIFs hostet, den folgenden Befehl ein, einmal für jede LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _node3_ -home-port _netport|ifgrp_`

.. [[man_lif_verify_3_subsepc]]Migrieren Sie alle auf node2 gehosteten Daten-LIFs, die zuvor zu node1 auf einem VLAN-Port gehörten, zu einem Port auf node3, der in der Lage ist, LIFs auf demselben Netzwerk zu hosten, indem Sie den folgenden Befehl eingeben – einmal für jede LIF:
+
`network interface migrate -vserver _vserver_name_ -lif _LIF_name_ -destination-node _node3_ –destination-port _netport|ifgrp_`

.. Ändern Sie den Home-Port und den Home-Node der LIFs in ,Unterschritt C Geben Sie zum Port und Node, der derzeit die LIFs hostet, den folgenden Befehl ein, einmal für jede LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _node3_ -home-port _netport|ifgrp_`



. [[man_lif_verify_3_step4]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="25,75"]
|===
| Wenn das Cluster konfiguriert ist für... | Dann... 


| NAS | Vollständig ,Schritt 6 Und ,Schritt 7, überspringen Sie Schritt 8, und abgeschlossen ,Schritt 9 Bis ,Schritt 12. 


| San | Deaktivieren Sie alle SAN-LIFs auf dem Node, um sie für das Upgrade herunterzufahren:
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _node_to_upgrade_ -home-port _netport|ifgrp_ -status-admin down` 
|===
. [[man_lif_verify_3_step5]]Wenn Datenports auf Ihren Plattformen nicht identisch sind, fügen Sie die Ports zur Broadcast-Domäne hinzu:
+
`network port broadcast-domain add-ports -ipspace _IPspace_name_ -broadcast-domain mgmt -ports _node:port_`

+
Das folgende Beispiel fügt Port „e0a“ auf den Knoten „6280-1“ und Port „e0i“ auf Knoten „8060-1“ zum Broadcast-Domain „Management“ im IPspace „Standard“ hinzu:

+
[listing]
----
cluster::> network port broadcast-domain add-ports -ipspace Default -broadcast-domain mgmt -ports 6280-1:e0a, 8060-1:e0i
----
. [[man_lif_verify_3_step6]] Migrieren Sie jede NAS-Daten-LIF auf node3, indem Sie den folgenden Befehl eingeben, einmal für jede LIF:
+
`network interface migrate -vserver _vserver_name_ -lif _LIF_name_ -destination-node _node3_ -destination-port _netport|ifgrp_`

. [[man_lif_verify_3_step7]]stellen Sie sicher, dass die Datenmigration persistent ist:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_-home-port _netport|ifgrp_ -home-node _node3_`

. [[man_lif_verify_3_step8]]Bestätigen, dass sich die SAN-LIFs auf den richtigen Ports auf node3 befinden:
+
.. Geben Sie den folgenden Befehl ein und überprüfen Sie die Ausgabe:
+
`network interface show -data-protocol iscsi|fcp -home-node _node3_`

+
Das System gibt die Ausgabe wie im folgenden Beispiel zurück:

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3
              Logical     Status      Network             Current        Current  Is
 Vserver      Interface   Admin/Oper  Address/Mask        Node           Port     Home
 -----------  ----------  ----------  ------------------  -------------  -------  ----
 vs0
              a0a         up/down     10.63.0.53/24       node3          a0a      true
              data1       up/up       10.63.0.50/18       node3          e0c      true
              rads1       up/up       10.63.0.51/18       node3          e1a      true
              rads2       up/down     10.63.0.52/24       node3          e1b      true
 vs1
              lif1        up/up       172.17.176.120/24   node3          e0c      true
              lif2        up/up       172.17.176.121/24   node3          e1a      true
----
.. Überprüfen Sie das neue und `adapter` Und `switch-port` Die Konfigurationen sind korrekt, indem die Ausgabe von dem verglichen wird `fcp adapter show` Befehl mit den Konfigurationsinformationen, die Sie im Arbeitsblatt in aufgezeichnet haben ,Schritt 2.
+
Liste der neuen SAN LIF-Konfigurationen auf Knoten3:

+
`fcp adapter show -fields switch-port,fc-wwpn`

+
Das System gibt die Ausgabe wie im folgenden Beispiel zurück:

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node        adapter fc-wwpn                 switch-port
----------- ------- ----------------------- -------------
cluster1-01 0a      50:0a:09:82:9c:13:38:00 ACME Switch:0
cluster1-01 0b      50:0a:09:82:9c:13:38:01 ACME Switch:1
cluster1-01 0c      50:0a:09:82:9c:13:38:02 ACME Switch:2
cluster1-01 0d      50:0a:09:82:9c:13:38:03 ACME Switch:3
cluster1-01 0e      50:0a:09:82:9c:13:38:04 ACME Switch:4
cluster1-01 0f      50:0a:09:82:9c:13:38:05 ACME Switch:5
cluster1-01 1a      50:0a:09:82:9c:13:38:06 ACME Switch:6
cluster1-01 1b      50:0a:09:82:9c:13:38:07 ACME Switch:7
cluster1-02 0a      50:0a:09:82:9c:6c:36:00 ACME Switch:0
cluster1-02 0b      50:0a:09:82:9c:6c:36:01 ACME Switch:1
cluster1-02 0c      50:0a:09:82:9c:6c:36:02 ACME Switch:2
cluster1-02 0d      50:0a:09:82:9c:6c:36:03 ACME Switch:3
cluster1-02 0e      50:0a:09:82:9c:6c:36:04 ACME Switch:4
cluster1-02 0f      50:0a:09:82:9c:6c:36:05 ACME Switch:5
cluster1-02 1a      50:0a:09:82:9c:6c:36:06 ACME Switch:6
cluster1-02 1b      50:0a:09:82:9c:6c:36:07 ACME Switch:7
16 entries were displayed
----
+

NOTE: Wenn sich ein SAN LIF in der neuen Konfiguration nicht auf einem Adapter befindet, der noch an denselben angeschlossen ist `switch-port`, Es kann zu einem Systemausfall führen, wenn Sie den Node neu booten.

.. Wenn node3 irgendwelche SAN-LIFs oder Gruppen von SAN-LIFs hat, die sich auf einem Port befinden, der nicht in node1 vorhanden war oder einem anderen Port zugeordnet werden muss, verschieben Sie sie zu einem geeigneten Port auf node3, indem Sie die folgenden Teilschritte ausführen:
+
... Legen Sie den LIF-Status auf „down“ fest:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -status-admin down`

... Entfernen Sie das LIF aus dem Portsatz:
+
`portset remove -vserver _vserver_name_ -portset _portset_name_ -port-name _port_name_`

... Geben Sie einen der folgenden Befehle ein:
+
**** Verschieben eines einzelnen LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-port _new_home_port_`

**** Verschieben Sie alle LIFs auf einem einzelnen nicht vorhandenen oder falschen Port in einen neuen Port:
+
`network interface modify {-home-port _port_on_node1_ -home-node _node1_ -role data} -home-port _new_home_port_on_node3_`

**** Fügen Sie die LIFs wieder dem Portsatz hinzu:
+
`portset add -vserver _vserver_name_ -portset _portset_name_ -port-name _port_name_`

+

NOTE: Sie müssen SAN-LIFs zu einem Port verschieben, der die gleiche Verbindungsgeschwindigkeit wie der ursprüngliche Port hat.







. Ändern Sie den Status aller LIFs auf „up“, damit die LIFs den Datenverkehr auf dem Node akzeptieren und senden können:
+
`network interface modify -home-port _port_name_ -home-node _node3_ -lif data -status-admin up`

. Geben Sie an jedem Node den folgenden Befehl ein, und überprüfen Sie seine Ausgabe, um zu überprüfen, ob LIFs an die richtigen Ports verschoben wurden und ob die LIFs den Status von „up“ aufweisen. Geben Sie dazu den folgenden Befehl an einem der Nodes ein und überprüfen Sie die Ausgabe:
+
`network interface show -home-node _node3_ -role data`

. [[man_lif_verify_3_step11]] Wenn eine der LIFs nicht verfügbar ist, setzen Sie den Administrationsstatus der LIFs auf „up“, indem Sie den folgenden Befehl eingeben, einmal für jede LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -status-admin up`

. Senden Sie eine AutoSupport Nachricht nach dem Upgrade an NetApp für den Knoten1:
+
`system node autosupport invoke -node _node3_ -type all -message "node1 successfully upgraded from _platform_old_ to _platform_new_"`


