---
sidebar: sidebar 
permalink: upgrade-arl-manual/move_nas_lifs_node1_node2.html 
keywords: node1, node3, nas, lifs, cluster, san 
summary: Verschieben Sie die NAS-Daten-LIFs von node1 auf node2, wenn Sie ein Cluster mit zwei Nodes haben, oder auf einen dritten Node, wenn Ihr Cluster über mehr als zwei Nodes verfügt, während eines manuellen ARL-Upgrades auf Controllern mit ONTAP 9.7 oder einer älteren Version. 
---
= Verschieben Sie NAS-Daten-LIFs von node1 auf node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie node1 durch node3 ersetzen können, müssen Sie die NAS-Daten-LIFs, die sich im Besitz von node1 befinden, auf node2 verschieben, wenn Sie ein Cluster mit zwei Nodes haben, oder auf einen dritten Node, wenn Ihr Cluster mehr als zwei Nodes hat. Die von Ihnen verwendete Methode hängt davon ab, ob das Cluster für NAS oder SAN konfiguriert ist.

Remote-LIFs verarbeiten den Datenverkehr zu SAN-LUNs während des Upgrades. Das Verschieben von SAN-LIFs ist für den Zustand des Clusters oder des Service während des Upgrades nicht erforderlich. Sie müssen überprüfen, ob die LIFs sich in einem ordnungsgemäßen Zustand befinden und sich auf den entsprechenden Ports befinden, nachdem Sie node3 in den Online-Modus versetzt haben.

.Schritte
. Führen Sie alle auf node1 gehosteten NAS-Daten-LIFs auf, indem Sie den folgenden Befehl eingeben und die Ausgabe erfassen:
+
`network interface show -data-protocol nfs|cifs -curr-node _node1_`

+
Das System zeigt die NAS-Daten-LIFs auf node1 an, wie im folgenden Beispiel dargestellt:

+
[listing]
----
 cluster::> network interface show -data-protocol nfs|cifs -curr-node node1

          Logical     Status      Network             Current   Current Is
 Vserver  Interface   Admin/Oper  Address/Mask        Node      Port    Home
 -------- ----------  ----------  ------------------  --------- ------- ----
 vs0
          a0a         up/down     10.63.0.53/24       node1     a0a     true
          data1       up/up       10.63.0.50/18       node1     e0c     true
          rads1       up/up       10.63.0.51/18       node1     e1a     true
          rads2       up/down     10.63.0.52/24       node1     e1b     true
 vs1
          lif1        up/up       192.17.176.120/24   node1     e0c     true
          lif2        up/up       172.17.176.121/24   node1     e1a     true
----
. Führen Sie eine der folgenden Aktionen durch:
+
[cols="40,60"]
|===
| Falls Knoten 1... | Dann... 


| Sind Schnittstellengruppen mit VLANs konfiguriert | Gehen Sie zu ,Schritt 3. 


| Schnittstellengruppen oder VLANs sind nicht konfiguriert | Überspringen Sie Schritt 3, und fahren Sie mit fort ,Schritt 4. 
|===
+
Verwenden Sie die `network port vlan show` Befehl zum Anzeigen von Informationen über die mit VLANs verbundenen Netzwerk-Ports, und verwenden Sie den `network port ifgrp show` Befehl zum Anzeigen von Informationen über die Port-Schnittstellengruppen.

. [[man_move_lif_1_2_step3]]Nehmen Sie die folgenden Schritte durch, um alle auf Schnittstellengruppen und VLANs gehosteten NAS-Daten-LIFs auf node1 zu migrieren:
+
.. [[man_move_lif_1_2_substanzen]]Migrieren Sie die LIFs, die auf beliebigen Schnittstellengruppen gehostet werden, und die VLANs auf node1 zu einem Port auf node2, der in der Lage ist, LIFs auf demselben Netzwerk wie die der Schnittstellengruppen zu hosten, indem Sie den folgenden Befehl eingeben – einmal für jede LIF:
+
`network interface migrate -vserver _Vserver_name_ -lif _LIF_name_ -destination-node _node2_ –destination-port _netport|ifgrp_`

.. Ändern Sie den Home-Port und den Home-Node der LIFs und VLANs in ,Unterschritt A Geben Sie zum Port und Node, der derzeit die LIFs hostet, den folgenden Befehl ein, einmal für jede LIF:
+
`network interface modify -vserver _Vserver_name_ -lif _LIF_name_ -home-node _node2_ - home-port _netport|ifgrp_`



. [[man_move_lif_1_2_ste4]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="20,80"]
|===
| Wenn das Cluster konfiguriert ist für... | Dann... 


| NAS | Vollständig ,Schritt 5 Bis ,Schritt 8. 


| San | Deaktivieren Sie alle SAN-LIFs auf dem Node, um sie für das Upgrade herunterzufahren:
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _node_to_upgrade_ -home-port _netport|ifgrp_ -status-admin down` 
|===
. [[man_move_lif_1_2_step5]]Migrieren Sie NAS-Daten-LIFs von node1 nach node2, indem Sie den folgenden Befehl eingeben, einmal für jede Daten-LIF:
+
`network interface migrate -vserver _Vserver-name_ -lif _LIF_name_ -destination-node _node2_ -destination-port _data_port_`

. [[Schritt6]]Geben Sie den folgenden Befehl ein und überprüfen Sie seine Ausgabe, um zu überprüfen, ob LIFs an die richtigen Ports verschoben wurden und dass die LIFs den Status von „up“ aufweisen. Geben Sie dazu den folgenden Befehl an einem der beiden Nodes ein und überprüfen Sie die Ausgabe:
+
`network interface show -curr-node _node2_ -data-protocol nfs|cifs`

. [[step7]]Geben Sie den folgenden Befehl ein, um den Home-Node der migrierten LIFs zu ändern:
+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _node2_ -home-port _port_name_`

. [[man_move_lif_1_2_step8]]Überprüfen Sie, ob die LIF den Port als ihren Home- oder aktuellen Port verwendet. Wenn der Port nicht zu Hause oder der aktuelle Port ist, fahren Sie mit fort ,Schritt 9:
+
`network interface show -home-node _node2_ -home-port _port_name_`

+
`network interface show -curr-node _node_name_ -curr-port _port_name_`

. [[man_move_lif_1_2_step9]]Wenn die LIFs den Port als Home-Port oder aktuellen Port verwenden, ändern Sie die LIF und verwenden Sie einen anderen Port:
+
`network interface migrate -vserver _Vserver-name_ -lif _LIF_name_ -destination–node _node_name_ -destination-port _port_name_`

+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home–node _node_name_ -home-port _port_name_`

. [[Schritt10]]Wenn die Ports, die derzeit Daten-LIFs hosten, nicht auf der neuen Hardware vorhanden sein werden, entfernen Sie sie jetzt aus der Broadcast-Domäne:
+
`network port broadcast-domain remove-ports -ipspace Default -broadcast-domain Default -ports _node:port_`

. [[Schritt11]]Wenn eine der LIFs ausgefallen sind, setzen Sie den Administrationsstatus der LIFs auf „up“, indem Sie den folgenden Befehl eingeben, einmal für jede LIF:
+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _nodename_ -status-admin up`

+

NOTE: Bei MetroCluster Konfigurationen können Sie die Broadcast-Domäne eines Ports möglicherweise nicht ändern, da dieser einem Port zugewiesen ist, der die LIF einer Ziel-Storage Virtual Machine (SVM) hostet. Geben Sie den folgenden Befehl von der entsprechenden Quell-SVM auf dem Remote-Standort ein, um die Ziel-LIF einem entsprechenden Port zuzuweisen:
`metrocluster vserver resync -vserver _Vserver_name_`

. [[Schritt12]]Geben Sie den folgenden Befehl ein und überprüfen Sie seine Ausgabe, um zu überprüfen, ob auf node1 keine Daten-LIFs mehr vorhanden sind:
+
`network interface show -curr-node _node1_ -role data`

. [[Schritt13]]Wenn Schnittstellengruppen oder VLANs konfiguriert sind, führen Sie die folgenden Teilschritte aus:
+
.. Entfernen Sie die VLANs aus den Schnittstellengruppen, indem Sie den folgenden Befehl eingeben:
+
`network port vlan delete -node _nodename_ -port _ifgrp_name_ -vlan-id _VLAN_ID_`

.. Geben Sie den folgenden Befehl ein und überprüfen Sie seine Ausgabe, um zu sehen, ob Schnittstellengruppen auf dem Node konfiguriert sind:
+
`network port ifgrp show -node _nodename_ -ifgrp _ifgrp_name_ -instance`

+
Das System zeigt Schnittstellengruppeninformationen für den Node an, wie im folgenden Beispiel gezeigt:

+
[listing]
----
  cluster::> network port ifgrp show -node node1 -ifgrp a0a -instance
                   Node: node1
   Interface Group Name: a0a
  Distribution Function: ip
          Create Policy: multimode_lacp
            MAC Address: 02:a0:98:17:dc:d4
     Port Participation: partial
          Network Ports: e2c, e2d
               Up Ports: e2c
             Down Ports: e2d
----
.. Wenn Schnittstellengruppen auf dem Node konfiguriert sind, notieren Sie die Namen dieser Gruppen und der ihnen zugewiesenen Ports. Löschen Sie dann die Ports, indem Sie den folgenden Befehl eingeben, und zwar einmal für jeden Port:
+
`network port ifgrp remove-port -node _nodename_ -ifgrp _ifgrp_name_ -port _netport_`




