---
sidebar: sidebar 
permalink: upgrade-arl-manual/reconfig_index.html 
keywords: reconfigure, fc, switch, layout, RCF, metrocluster 
summary: Konfigurieren Sie für ONTAP 9.1 oder höher das Portlayout neu, und wenden Sie während eines manuellen ARL Upgrades die neuesten RCFs auf Controllern mit ONTAP 9.7 oder einer älteren Version an. 
---
= Konfigurieren Sie das FC-Switch-Layout für ONTAP 9.1 oder höher neu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn das vorhandene FC-Switch-Layout vor ONTAP 9.1 konfiguriert wurde, müssen Sie das Port-Layout neu konfigurieren und die neuesten RCFs (Reference Configuration Files) anwenden. Dieses Verfahren gilt nur für MetroCluster FC-Konfigurationen.

Sie müssen die in der Fabric-Domäne vorhandenen FC-Switches identifizieren.

Sie benötigen das Admin-Passwort und den Zugriff auf einen FTP- oder SCP-Server.

Sie müssen diese Aufgabe ausführen, wenn Ihr vorhandenes FC Switch-Layout vor ONTAP 9.1 konfiguriert wurde und Sie ein Upgrade auf ein in ONTAP 9.1 oder höher unterstütztes Plattformmodell durchführen. Dies ist _nicht_ erforderlich, wenn Sie ein Upgrade von einem vorhandenen Switch-Layout durchführen, das für ONTAP 9.1 oder höher konfiguriert wurde.

Dieser Vorgang läuft unterbrechungsfrei ab und dauert etwa vier Stunden (außer Rack und Stack), wenn Festplatten gelöscht werden.

.Schritte
. link:send_custom_asup_message_prior_reconfig_switches.html["Senden Sie vor der Neukonfiguration der Switches eine benutzerdefinierte AutoSupport Meldung"]
. link:verify_health_mcc_config.html["Überprüfen Sie den Systemzustand der MetroCluster-Konfiguration"]
. link:check_mcc_config_errors.html["Prüfen Sie auf MetroCluster-Konfigurationsfehler"]
. link:persist_disable_switches.html["Deaktivieren Sie die Switches dauerhaft"]
. link:determine_new_cabling_layout.html["Bestimmen Sie das neue Verkabelungslayout"]
. link:apply_RCF_files_recable_switches.html["Wenden Sie RCF-Dateien an und stellen Sie die Schalter wieder ein"]
. link:persist_enable_switches.html["Die Switches dauerhaft aktivieren"]
. link:verify_swtichover_healing_switchback.html["Überprüfung von UmschalttaFunktionen, Healing und Switchback"]

