---
sidebar: sidebar 
permalink: upgrade-arl-manual/set_fc_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, uta2 configuration, configure FC ports, uta/uta2 card, node4, target, adapter, ports 
summary: Konfiguration von node4 integrierten FC-Ports, UTA/UTA2-Ports oder UTA/UTA2-Karte während eines manuellen ARL Upgrades auf Controllern mit ONTAP 9.7 oder einer älteren Version 
---
= Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node4 fest
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn node4 über integrierte FC-Ports, integrierte Unified Target Adapter (UTA/UTA2)-Ports oder eine UTA/UTA2-Karte verfügt, müssen Sie die Einstellungen konfigurieren, bevor Sie den Rest des Verfahrens abschließen.

.Über diese Aufgabe
Möglicherweise müssen Sie den Abschluss abschließen <<Konfigurieren Sie FC-Ports auf node4>>, Das <<UTA/UTA2-Ports auf node4 prüfen und konfigurieren>>, Oder beide Abschnitte.

Wenn node4 keine integrierten FC-Ports, Onboard-UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat und Sie ein System mit Storage-Festplatten aktualisieren, können Sie weiter gehen link:map_ports_node2_node4.html["Weisen Sie Ports von node2 nach node4 zu"].

Wenn Sie jedoch ein V-Series System oder FlexArray-Virtualisierungssoftware haben und mit Storage-Arrays verbunden sind und node4 keine integrierten FC-Ports, Onboard UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat, müssen Sie zum Abschnitt _Installation and Boot node4_ zurückkehren und wieder aufnehmen link:install_boot_node4.html#Step9["Schritt 9"]. stellen Sie sicher, dass node4 über ausreichend Rack-Platz verfügt. Wenn node4 sich in einem separaten Chassis von node2 befindet, können sie node4 an der gleichen Stelle wie node3 platzieren. Wenn sich Node2 und node4 im selben Chassis befinden, befindet sich node4 bereits in der entsprechenden Rack-Position.

.Wahlmöglichkeiten
* <<Konfigurieren Sie FC-Ports auf node4>>
* <<UTA/UTA2-Ports auf node4 prüfen und konfigurieren>>




== Konfigurieren Sie FC-Ports auf node4

Wenn node4 FC-Ports hat, entweder Onboard oder auf einem FC-Adapter, müssen Sie Port-Konfigurationen auf dem Node festlegen, bevor Sie ihn in den Dienst stellen, da die Ports nicht vorkonfiguriert sind. Wenn die Ports nicht konfiguriert sind, kann es zu einer Serviceunterbrechung kommen.

.Bevor Sie beginnen
Sie müssen die Werte der FC-Port-Einstellungen von node2 haben, die Sie im Abschnitt gespeichert haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"].

.Über diese Aufgabe
Sie können diesen Abschnitt überspringen, wenn Ihr System über keine FC-Konfigurationen verfügt. Wenn Ihr System über integrierte UTA/UTA2-Ports oder einen UTA/UTA2-Adapter verfügt, konfigurieren Sie sie in <<UTA/UTA2-Ports auf node4 prüfen und konfigurieren>>.

*Wichtig*: Wenn Ihr System über Speicherfestplatten verfügt, müssen Sie die Befehle in diesem Abschnitt an der Cluster-Eingabeaufforderung eingeben. Wenn Sie ein V-Series System oder ein System mit FlexArray Virtualisierungssoftware haben, die mit Storage-Arrays verbunden sind, geben Sie in diesem Abschnitt im Wartungsmodus Befehle ein.

.Schritte
. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Festplatten sind vorhanden | Gehen Sie zu <<man_config_4_Step5,Schritt 5>>. 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Gehen Sie zu <<man_config_4_Step2,Schritt 2>>. 
|===
. [[man_config_4_Step2]]Zugriff auf den Wartungsmodus:
+
`boot_ontap maint`

. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Festplatten sind vorhanden | `system node hardware unified-connect show` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `ucadmin show` 
|===
+
Das System zeigt Informationen zu allen FC- und konvergenten Netzwerkadaptern im System an.

. Vergleichen Sie die FC-Einstellungen auf den neuen Nodes mit den Einstellungen, die Sie zuvor vom ursprünglichen Node erfasst haben.
. [[man_config_4_Step5]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Festplatten sind vorhanden  a| 
Ändern Sie die FC-Ports auf node4 nach Bedarf:

** So programmieren Sie Zielanschlüsse:


`system node hardware unified-connect modify -type | -t target -adapter _port_name_`

** So programmieren Sie Initiator-Ports:


`system node unified-connect modify type | -t initiator -adapter _port_name_`

`-type` Ist der FC4-Typ, das Ziel oder der Initiator.



| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Ändern Sie die FC-Ports auf node4 nach Bedarf:
`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` Ist der FC4-Typ, das Ziel oder der Initiator. *Hinweis*: Die FC-Ports müssen als Initiatoren programmiert werden. 
|===
. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Festplatten sind vorhanden | Überprüfen Sie die neuen Einstellungen, indem Sie den folgenden Befehl eingeben und die Ausgabe überprüfen:
`system node unified-connect show` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Überprüfen Sie die neuen Einstellungen, indem Sie den folgenden Befehl eingeben und die Ausgabe überprüfen:
`ucadmin show` 
|===
. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn die FC-Standardeinstellungen auf den neuen Nodes sind... | Dann… 


| Das gleiche wie diejenigen, die Sie auf den ursprünglichen Knoten erfasst | Gehen Sie zu <<man_config_4_Step11,Schritt 11>>. 


| Anders als jene, die Sie auf den ursprünglichen Knoten erfasst haben | Gehen Sie zu <<man_config_4_Step8,Schritt 8>>. 
|===
. [[man_config_4_Step8]]Wartungsmodus beenden:
+
`halt`

. Nachdem Sie den Befehl eingegeben haben, warten Sie, bis das System an der Eingabeaufforderung der Boot-Umgebung angehalten wird.
. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Ist ein V-Series System oder verfügt über FlexArray Virtualisierungssoftware mit Data ONTAP 8.3.0 oder höher | Greifen Sie auf den Wartungsmodus zu, indem Sie an der Eingabeaufforderung der Boot-Umgebung den folgenden Befehl eingeben:
`boot_ontap maint` 


| Ist kein V-Series System und verfügt nicht über FlexArray Virtualisierungssoftware | Boot node4 durch Eingabe des folgenden Befehls an der Eingabeaufforderung der Boot-Umgebung:
`boot_ontap` 
|===
. [[man_config_4_Step11]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Festplatten sind vorhanden  a| 
** Gehen Sie zu <<UTA/UTA2-Ports auf node4 prüfen und konfigurieren>> Bei node4 mit einer UTA/UTA2-Karte oder Onboard-Ports UTA/UTA2:
** Überspringen Sie den Abschnitt und gehen Sie zu link:map_ports_node2_node4.html["Weisen Sie Ports von node2 nach node4 zu"] Wenn node4 keine UTA/UTA2-Karte oder UTA/UTA2 Onboard-Ports hat.




| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden  a| 
** Gehen Sie zu <<UTA/UTA2-Ports auf node4 prüfen und konfigurieren>> Bei node4 mit einer UTA/UTA2-Karte oder Onboard-Ports UTA/UTA2:
** Überspringen Sie den Abschnitt _UTA/UTA2-Ports auf node4_ überprüfen und konfigurieren, wenn node4 keine UTA/UTA2-Karte oder UTA/UTA2 Onboard-Ports hat, kehren Sie zum Abschnitt _Installieren und Booten von node4_ zurück, und setzen Sie den Abschnitt unter fort link:install_boot_node4.html#Step9["Schritt 9"].


|===




== UTA/UTA2-Ports auf node4 prüfen und konfigurieren

Wenn node4 Onboard UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Konfiguration der Ports überprüfen und sie je nach Nutzung des aktualisierten Systems konfigurieren.

.Bevor Sie beginnen
Sie müssen die richtigen SFP+ Module für die UTA/UTA2-Ports besitzen.

.Über diese Aufgabe
DIE UTA2-Ports können im nativen FC-Modus oder im UTA/UTA2-Modus konfiguriert werden. Der FC-Modus unterstützt FC Initiator und FC Target. Der UTA-/UTA2-Modus ermöglicht es, gleichzeitig NIC- und FCoE-Datenverkehr auf die gleiche 10-GbE-SFP+-Schnittstelle zu übertragen und das FC-Ziel zu unterstützen.


NOTE: Bei NetApp Marketingmaterialien wird möglicherweise der Begriff UTA2 verwendet, um sich auf CNA-Adapter und Ports zu beziehen. Allerdings verwendet die CLI den Begriff CNA.

UTA2-Ports können an einem Adapter oder auf dem Controller mit den folgenden Konfigurationen verwendet werden:

* UTA-/UTA2-Karten, die gleichzeitig mit dem Controller bestellt wurden, werden vor dem Versand konfiguriert, um die von Ihnen angeforderte Persönlichkeit zu erhalten.
* DIE UTA2-Karten, die separat vom Controller bestellt werden, werden mit der standardmäßigen FC-Zielgruppe ausgeliefert.
* Onboard UTA/UTA2-Ports auf neuen Controllern werden konfiguriert (vor dem Versand), um die von Ihnen angeforderte Persönlichkeit zu besitzen.


Sie können jedoch die Konfiguration der UTA/UTA2-Ports auf node4 überprüfen und sie gegebenenfalls ändern.

*Achtung*: Wenn Ihr System über Speicherfestplatten verfügt, geben Sie die Befehle in diesem Abschnitt an der Cluster-Eingabeaufforderung ein, sofern nicht dazu aufgefordert wird, in den Wartungsmodus zu wechseln. Wenn Sie über ein MetroCluster FC-System, ein V-Series System oder ein System mit FlexArray-Virtualisierungssoftware verfügen, die mit Storage-Arrays verbunden ist, müssen Sie sich im Wartungsmodus befinden, um UTA/UTA2-Ports zu konfigurieren.

.Schritte
. Überprüfen Sie, wie die Ports derzeit mit einem der folgenden Befehle auf node4 konfiguriert werden:
+
[cols="35,65"]
|===
| Wenn das System... | Dann… 


| Festplatten sind vorhanden | `system node hardware unified-connect show` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `ucadmin show` 
|===
+
Das System zeigt eine Ausgabe wie im folgenden Beispiel an:

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Wenn das aktuelle SFP+-Modul nicht mit der gewünschten Verwendung übereinstimmt, ersetzen Sie es durch das richtige SFP+-Modul.
+
Wenden Sie sich an Ihren NetApp Ansprechpartner, um das richtige SFP+ Modul zu erhalten.

. Überprüfen Sie die Ausgabe des `system node hardware unified-connect show` Oder `ucadmin show` Führen Sie einen Befehl aus, und bestimmen Sie, ob die UTA/UTA2-Ports die gewünschte Persönlichkeit haben.
. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn die CNA-Ports... | Dann... 


| Haben Sie nicht die Persönlichkeit, die Sie wollen | Gehen Sie zu <<man_check_4_Step5,Schritt 5>>. 


| Haben Sie die Persönlichkeit, die Sie wollen | Überspringen Sie Schritt 5 bis Schritt 12, und fahren Sie mit fort <<man_check_4_Step13,Schritt 13>>. 
|===
. [[man_Check_4_Step5]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn das System... | Dann... 


| Verfügt über Speicherfestplatten und führt Data ONTAP 8.3 aus | Boot-node4 und wechseln in den Wartungsmodus:
`boot_ontap maint` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Gehen Sie zu <<man_check_4_Step6,Schritt 6>>. Sie sollten sich bereits im Wartungsmodus befinden. 
|===
. [[man_Check_4_Step6]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn Sie konfigurieren... | Dann... 


| Ports auf einer UTA/UTA2-Karte | Gehen Sie zu <<man_check_4_Step7,Schritt 7>>. 


| Onboard UTA/UTA2-Ports | Überspringen Sie Schritt 7, und fahren Sie mit fort <<man_check_4_Step8,Schritt 8>>. 
|===
. [[man_Check_4_Step7]]Wenn sich der Adapter im Initiator-Modus befindet und der UTA/UTA2-Port online ist, versetzen Sie den UTA/UTA2-Port in den Offline-Modus:
+
`storage disable adapter _adapter_name_`

+
Adapter im Zielmodus sind im Wartungsmodus automatisch offline.

. [[man_Check_4_Step8]]Wenn die aktuelle Konfiguration nicht mit der gewünschten Verwendung übereinstimmt, geben Sie den folgenden Befehl ein, um die Konfiguration nach Bedarf zu ändern:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` Ist der Personality Modus: FC oder 10GbE UTA.
** `-t` Ist der FC4-Typ: Target oder Initiator.


+

NOTE: Sie müssen FC Initiator für Tape-Laufwerke und FlexArray-Virtualisierungssysteme verwenden. Sie müssen das FC-Ziel für SAN-Clients verwenden.

. Überprüfen Sie die Einstellungen, indem Sie den folgenden Befehl eingeben und seine Ausgabe überprüfen:
+
`ucadmin show`

. Führen Sie eine der folgenden Aktionen aus:
+
[cols="35,65"]
|===
| Wenn das System... | Dann... 


| Festplatten sind vorhanden  a| 
.. Geben Sie den folgenden Befehl ein:
+
`halt`

+
Das System wird an der Eingabeaufforderung für die Boot-Umgebung angehalten.

.. Geben Sie den folgenden Befehl ein:
+
`boot_ontap`





| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden und läuft Data ONTAP 8.3 | Neustart in Wartungsmodus:
`boot_ontap maint` 
|===
. Überprüfen Sie die Einstellungen:
+
[cols="35,65"]
|===
| Wenn das System... | Dann... 


| Festplatten sind vorhanden | Geben Sie den folgenden Befehl ein:
`system node hardware unified-connect show` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Geben Sie den folgenden Befehl ein:
`ucadmin show` 
|===
+
Die Ausgabe in den folgenden Beispielen zeigt, dass sich der Adaptertyp „1b“ in ändert `initiator` Und dass sich der Modus der Adapter „2a“ und „2b“ in ändert `cna`.

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
+
[listing]
----
*> ucadmin show
               Current Current   Pending  Pending    Admin
Node  Adapter  Mode    Type      Mode     Type       Status
----  -------  ------- --------- -------  -------    -----
f-a    1a      fc      initiator -        -          online
f-a    1b      fc      target    -        initiator  online
f-a    2a      fc      target    cna      -          online
f-a    2b      fc      target    cna      -          online
4 entries were displayed.
*>
----
. Platzieren Sie alle Ziel-Ports online, indem Sie einen der folgenden Befehle eingeben, einmal für jeden Port:
+
[cols="35,65"]
|===
| Wenn das System... | Dann... 


| Festplatten sind vorhanden | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `fcp config _adapter_name_ up` 
|===
. [[man_Check_4_Step13]]Anschluss verkabeln.
. Führen Sie eine der folgenden Aktionen aus:
+
[cols="35,65"]
|===
| Wenn das System... | Dann... 


| Festplatten sind vorhanden | Gehen Sie zu link:map_ports_node2_node4.html["Weisen Sie Ports von node2 nach node4 zu"]. 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Kehren Sie zum Abschnitt _Installieren und Starten von node4_ zurück, und setzen Sie den Abschnitt unter fort link:install_boot_node4.html#Step9["Schritt 9"]. 
|===

