---
sidebar: sidebar 
permalink: upgrade-arl-manual/verify_health_mcc_config.html 
keywords: health, mcc, metrocluster, configuration, configure 
summary: Überprüfen Sie den Systemzustand der MetroCluster Konfiguration und korrigieren Sie den Betrieb während eines manuellen ARL Upgrades bei Controllern mit ONTAP 9.7 oder einer älteren Version. 
---
= Überprüfen Sie den Systemzustand der MetroCluster-Konfiguration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie sollten den Systemzustand der MetroCluster-Konfiguration überprüfen, um den korrekten Betrieb zu überprüfen.

.Schritte
. Vergewissern Sie sich, dass die MetroCluster-Komponenten ordnungsgemäß sind:
+
`metrocluster check run`

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2017 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
. Vergewissern Sie sich, dass es keine Systemzustandsmeldungen gibt:
+
`system health alert show`


