---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/manage-authentication-using-kmip-servers.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Konfiguration und Management der Storage-Verschlüsselung, Management der Authentifizierungsschlüssel und Stilllegung der SnapMirror Beziehungen, wenn Sie ein Upgrade von Controllern mit ONTAP 9.8 oder höher durchführen `system controller replace` Befehl.' 
---
= Authentifizierungsmanagement mit KMIP-Servern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Mit ONTAP 9.8 oder höher können KMIP-Server (Key Management Interoperability Protocol) Authentifizierungsschlüssel managen.

.Schritte
. Hinzufügen eines neuen Controllers:
+
`security key-manager external enable`

. Fügen Sie den Schlüsselmanager hinzu:
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server konfiguriert und für alle Nodes im Cluster verfügbar sind:
+
`security key-manager external show-status`

. Stellen Sie die Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern auf den neuen Knoten wieder her:
+
`security key-manager external restore -node _new_controller_name_`


