---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: 'Überprüfen Sie, ob die NAS-Daten-LIFs von node2, die sich auf node3 befinden, von node3 auf node4 verschoben werden, wenn Sie Controller aktualisieren, die ONTAP 9.8 oder höher mit ausführen `system controller replace` Befehle.' 
---
= Verschieben Sie Aggregate ohne Root-Root-Fehler und NAS-Daten-LIFs, die sich im Besitz von node2 befinden, von node3 auf node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die Netzwerkkonfiguration auf Knoten 4 überprüft haben, müssen Sie die NAS-Daten-LIFs, die Knoten 2 gehören, von Knoten 3 auf Knoten 4 verschieben und bestätigen, dass die SAN-LIFs auf Knoten 4 vorhanden sind.

.Über diese Aufgabe
Remote LIFs verarbeiten den Datenverkehr zu SAN LUNs während des Upgrade-Vorgangs. Das Verschieben von SAN LIFs ist für die Integrität des Clusters oder der Dienste während des Upgrades nicht erforderlich. SAN LIFs werden nur dann verschoben, wenn sie neuen Ports zugeordnet werden müssen.

Sie überprüfen, ob die LIFs intakt sind und sich an den richtigen Ports befinden, nachdem Sie Knoten 4 online geschaltet haben.


NOTE: Wenn Sie die Portgeschwindigkeit der T6-basierten Ethernet-Netzwerkkarten oder Motherboard-Ports ändern, können Sie nach der Geschwindigkeitskonvertierung fehlerhafte Pakete beobachten. Siehe https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["NetApp Bugs Online Fehler-ID 1570339"^] Und den Knowledge Base Artikel https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["CRC-Fehler auf T6-Ports nach der Konvertierung von 40GbE zu 100GbE"^] Für eine Anleitung.

.Schritte
. Wiederaufnahme des Betriebs der Versetzung:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt die folgenden Aufgaben aus:

+
** Cluster-Quorum-Prüfung
** System-ID-Prüfung
** Prüfung der Bildversion
** Überprüfung der Zielplattform
** Prüfung der Netzwerkanachabilität


+
Das System unterbricht den Vorgang an dieser Stelle während der Überprüfung der Netzwerkverfügbarkeit.

. Wiederaufnahme des Betriebs der Versetzung:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt folgende Prüfungen durch:

+
** Cluster-Zustandsprüfung
** LIF-Statusüberprüfung für Cluster


+
Nach Durchführung dieser Prüfungen werden die nicht-Root-Aggregate und NAS-Daten-LIFs, die sich im Besitz von node2 befinden, an den neuen Controller node4 verschoben. Der Controller-Ersatzvorgang hält nach Abschluss der Ressourcenverschiebung die Pause ein.

. Überprüfen Sie den Status der Aggregatverschiebung und der LIF-Verschiebung von NAS-Daten:
+
[source, cli]
----
system controller replace show-details
----
+
Wenn der Austausch des Controllers unterbrochen wird, prüfen und korrigieren Sie den Fehler, falls zutreffend, und führen Sie das Problem anschließend aus `resume` Um den Vorgang fortzusetzen.

. Falls erforderlich, stellen Sie verschobene LIFs wieder her und setzen Sie sie zurück oder migrieren und modifizieren Sie die node2 LIFs, die nicht automatisch zu node4 verschoben wurden, manuell.
+
[role="tabbed-block"]
====
.Versetzte LIFs wiederherstellen und zurücksetzen
--
.. Liste aller verschobenen LIFs:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Wenn LIFs verschoben werden, stellen Sie den Home-Node wieder in node4 wieder her:
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node4_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Manuelle Migration und Modifizierung von LIFs
--
.. Migrieren Sie die LIFs, die nicht automatisch auf Knoten 4 verschoben wurden:
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node4_nodename> -destination-port <port_on_node4>
----
.. Ändern Sie den Home-Knoten und den Home-Port für die migrierten LIFs:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node4_nodename> -home-port <home_port>
----


--
====
. Setzen Sie den Vorgang fort, um das System zur Durchführung der erforderlichen Nachprüfungen zu auffordern:
+
[source, cli]
----
system controller replace resume
----
+
Das System führt die folgenden Nachprüfungen durch:

+
** Cluster-Quorum-Prüfung
** Cluster-Zustandsprüfung
** Aggregatrekonstruktion
** Aggregatstatus-Prüfung
** Überprüfung des Festplattenstatus
** LIF-Statusüberprüfung für Cluster
** Lautstärkerprüfung



