---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/overview_of_the_arl_upgrade.html 
keywords: overview, arl, upgrade, owner, controller, hardware 
summary: 'Informieren Sie sich, wie Sie mit das Upgrade von Controllern mit ONTAP 9.8 oder höher durchführen `system controller replace` Befehle funktionieren.' 
---
= Überblick über das ARL Upgrade
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bevor Sie die Nodes mit ARL aktualisieren, sollten Sie unbedingt verstehen, wie das Verfahren funktioniert. In diesem Inhalt wird das Verfahren in mehrere Phasen unterteilt.



== Aktualisieren Sie das Node-Paar

Zum Upgrade des Node-Paars müssen Sie die ursprünglichen Nodes vorbereiten und dann für die ursprünglichen und die neuen Nodes eine Reihe von Schritten ausführen. Anschließend können Sie die ursprünglichen Knoten außer Betrieb nehmen.



== Übersicht über die ARL-Upgrade-Sequenz

Während des Verfahrens aktualisieren Sie die ursprüngliche Controller Hardware mit der Ersatz-Controller-Hardware, einem Controller gleichzeitig. Nutzen Sie die HA-Paar-Konfiguration, um das Eigentum von Aggregaten ohne Root-Berechtigungen zu verschieben. Alle Aggregate außerhalb der Root-Ebene müssen zwei Umlagerungen durchlaufen, um das endgültige Ziel zu erreichen, nämlich den korrekten aktualisierten Node.

Jedes Aggregat hat einen Hausbesitzer und aktuellen Eigentümer. Der Hausbesitzer ist der eigentliche Eigentümer des Aggregats, und der aktuelle Eigentümer ist der temporäre Eigentümer.

Die folgende Tabelle beschreibt die grundlegenden Aufgaben, die Sie in den einzelnen Phasen ausführen, und den Zustand der Aggregateigentümer am Ende der Phase. Detaillierte Schritte sind im weiteren Verlauf des Verfahrens aufgeführt:

[cols="35,65"]
|===
| Stufe | Beschreibung 


| link:stage_1_index.html["Stufe 1: Upgrade vorbereiten"]  a| 
In Phase 1 führen Sie Vorabprüfungen durch und korrigieren, falls erforderlich, die Eigentümerschaft für die Aggregate. Sie müssen bestimmte Informationen aufzeichnen, wenn Sie Storage-Verschlüsselung mithilfe des OKM managen und Sie die SnapMirror Beziehungen stilllegen möchten.

Gesamteigentum am Ende von Phase 1:

* Node1 ist der Hausbesitzer und der aktuelle Besitzer der node1 Aggregate.
* Node2 ist der Hausbesitzer und der aktuelle Besitzer der node2 Aggregate.




| link:stage_2_index.html["Stufe 2: Knoten1 verschieben und ausmustern"]  a| 
Während Phase 2 werden node1-Aggregate und NAS-Daten-LIFs in Knoten 2 verschoben. Dieser Prozess ist weitgehend automatisiert; der Vorgang hält an, damit Sie seinen Status überprüfen können. Sie müssen den Vorgang manuell fortsetzen. Bei Bedarf verschieben Sie fehlerhafte oder Vetos Aggregate. Sie erfassen Node1-Informationen für die spätere Verwendung im Verfahren vor dem Ausscheiden von node1. Sie können sich auch später beim Verfahren auf den Netzboot node3 und node4 vorbereiten.

Gesamteigentum am Ende von Phase 2:

* Node2 ist der aktuelle Besitzer von node1 Aggregaten.
* Node2 ist der Hausbesitzer und der aktuelle Besitzer von node2 Aggregaten.




| link:stage_3_index.html["Phase 3: Installieren und booten Sie node3"]  a| 
Während Phase 3 installieren und starten Sie Node 3, überprüfen Sie, ob die Cluster- und Node-Management-Ports von Node 1 auf Node 3 online sind, weisen Sie die Node 1-Festplatten Node 3 neu zu und überprüfen Sie die Node 3-Installation. Wenn Sie NetApp Volume Encryption (NVE) verwenden, stellen Sie die Konfiguration des Schlüsselmanagers wieder her. Falls erforderlich, stellen Sie die FC- oder UTA/UTA2-Konfiguration auf node3 ein. Außerdem werden die LIFs für NAS-Daten-LIFs und nicht-Root-Aggregate von node2 auf node3 verschoben und Sie überprüfen, ob die SAN-LIFs auf node3 vorhanden sind.

Gesamteigentum am Ende von Stufe 3:

* Node3 ist der Hausbesitzer und der aktuelle Besitzer von node1 Aggregaten.
* Node2 ist der Hausbesitzer und der aktuelle Besitzer von node2 Aggregaten.




| link:stage_4_index.html["Phase 4: Knoten2 verschieben und ausmustern"]  a| 
Während Phase 4 werden Aggregate und NAS-Daten-LIFs von Knoten 2 auf Knoten 3 verschoben. Sie erfassen auch node2-Informationen für die spätere Verwendung im Verfahren vor dem Ausscheiden von node2.

Gesamteigentum am Ende von Stufe 4:

* Node3 ist der Hausbesitzer und aktuelle Besitzer von Aggregaten, die ursprünglich zu node1 gehörten.
* Node2 ist der Hausbesitzer von node2 Aggregaten.
* Node3 ist der aktuelle Besitzer von node2 Aggregaten.




| link:stage_5_index.html["Phase 5: installieren und booten sie node4"]  a| 
Während Phase 5 installieren und starten Sie node4, überprüfen Sie, ob die Cluster- und Node-Management-Ports von node2 auf node4 online sind, weisen Sie die node2-Laufwerke node4 zu und überprüfen Sie die node4-Installation. Wenn Sie NVE verwenden, stellen Sie die Konfiguration für Schlüsselmanager wieder her. Falls erforderlich, stellen Sie die FC- oder UTA/UTA2-Konfiguration auf node4 ein. Außerdem werden Knoten2-NAS-Daten-LIFs und nicht-Root-Aggregate von node3 auf node4 verschoben und überprüft, ob die SAN-LIFs auf node4 vorhanden sind.

Gesamteigentum am Ende von Stufe 5:

* Node3 ist der Hausbesitzer und aktuelle Besitzer der Aggregate, die ursprünglich zu node1 gehörten.
* Node4 ist der Hausbesitzer und aktuelle Besitzer von Aggregaten, die ursprünglich zu node2 gehörten.




| link:stage_6_index.html["Phase 6: Schließen Sie das Upgrade ab"]  a| 
In Phase 6 bestätigen Sie, dass die neuen Nodes korrekt eingerichtet wurden. Und wenn die neuen Nodes verschlüsselt sind, konfigurieren und einrichten Sie Storage Encryption oder NVE. Zudem sollten die alten Nodes außer Betrieb gesetzt und der SnapMirror Betrieb fortgesetzt werden.

|===