---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/restore_key-manager_configuration_node3.html 
keywords: restoring, key-manager, configuration, node3, nve, arl, encryption, netapp, volume 
summary: 'Falls erforderlich, stellen Sie die Key-Manager-Konfiguration auf node3 wieder her, wenn Sie ein Upgrade von Controllern durchführen, die ONTAP 9.8 oder höher verwenden `system controller replace` Befehle.' 
---
= Wiederherstellung der Key-Manager-Konfiguration auf Knoten 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie NetApp Aggregate Encryption (NAE) oder NetApp Volume Encryption (NVE) zur Verschlüsselung von Volumes auf dem System verwenden, das Sie aktualisieren, muss die Verschlüsselungskonfiguration mit den neuen Nodes synchronisiert werden. Wenn Sie den Schlüsselmanager nicht wiederherstellen, werden beim Verschieben der Node1-Aggregate mit ARL von node2 auf Knoten 3 verschlüsselte Volumes offline geschaltet.

.Über diese Aufgabe
Die Verschlüsselungskonfiguration mit den neuen Nodes synchronisieren, indem Sie die folgenden Schritte durchführen:

.Schritte
. Synchronisieren Sie die Verschlüsselungskonfiguration für Onboard Key Manager (OKM) mithilfe des folgenden Befehls an der Cluster-Eingabeaufforderung:
+
`security key-manager onboard sync`

. Geben Sie die Cluster-weite Passphrase für das OKM ein.

