---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/restore_key-manager_config_node4.html 
keywords: restore key-manager, configuration, node4, nve, arl, volume, encryption 
summary: 'Stellen Sie bei Bedarf die Key-Manager-Konfiguration auf node4 wieder her, wenn Sie die Controller aktualisieren, die ONTAP 9.8 oder höher ausführen, indem Sie verwenden `system controller replace` Befehle.' 
---
= Wiederherstellen der Key-Manager-Konfiguration auf node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie mithilfe von NetApp Volume Encryption (NVE) Volumes auf dem von Ihnen aktualisieren System verschlüsseln, muss die Verschlüsselungskonfiguration mit den neuen Nodes synchronisiert werden. Wenn Sie den Schlüsselmanager nicht wiederherstellen, werden beim Verschieben der Node2-Aggregate mit ARL von node3 auf node4 verschlüsselte Volumes offline geschaltet.

.Über diese Aufgabe
Die Verschlüsselungskonfiguration mit den neuen Nodes synchronisieren, indem Sie die folgenden Schritte durchführen:

.Schritte
. Synchronisieren Sie die Verschlüsselungskonfiguration für Onboard Key Manager (OKM) mithilfe des folgenden Befehls an der Cluster-Eingabeaufforderung:
+
`security key-manager onboard sync`

. Geben Sie die Cluster-weite Passphrase für das OKM ein.

