---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'Konfigurieren Sie node3 Onboard FC-Ports, UTA/UTA2-Ports oder die UTA/UTA2-Karte, wenn Sie Controller mit ONTAP 9.8 oder höher mit aktualisieren `system controller replace` Befehle.' 
---
= Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node3 fest
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn node3 integrierte FC-Ports, Onboard Unified Target Adapter (UTA/UTA2)-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Einstellungen konfigurieren, bevor Sie den Rest des Verfahrens abschließen.

.Über diese Aufgabe
Möglicherweise müssen Sie den Abschnitt ausfüllen <<Konfigurieren Sie FC-Ports auf node3>>, Der Abschnitt <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>, Oder beide Abschnitte.


NOTE: Unter Umständen bezieht sich bei den Marketingmaterialien von NetApp der Begriff UTA2 auf Adapter und Ports des konvergierten Netzwerkadapters (CNA). Allerdings verwendet die CLI den Begriff CNA.

Wenn Knoten3 keine integrierten FC-Ports, integrierten UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat (z. B. AFF und FAS -Systeme, die ab ONTAP 9.15.1 eingeführt wurden) und Sie ein System mit Speicherplatten aktualisieren, können Sie mit fortfahren.link:reassign-node1-disks-to-node3.html["Weisen Sie node1-Festplatten Knoten 3 neu zu"] .



== Konfigurieren Sie FC-Ports auf node3

Wenn Knoten3 über FC-Ports verfügt (entweder integriert oder auf einem zusätzlichen FC-Adapter), müssen Sie die Portkonfigurationen auf dem Knoten festlegen, bevor Sie ihn in Betrieb nehmen, da die Ports bei der Auslieferung der Systeme nicht vorkonfiguriert sind.  Wenn Sie die Ports nicht konfigurieren, kann es zu einer Dienstunterbrechung kommen.

.Bevor Sie beginnen
Sie müssen die Werte der FC-Port-Einstellungen von node1 haben, die Sie im Abschnitt gespeichert haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"].

.Über diese Aufgabe
Sie können diesen Abschnitt überspringen, wenn Ihr System über keine FC-Konfigurationen verfügt. Wenn Ihr System über integrierte UTA/UTA2-Ports oder eine UTA/UTA2-Karte verfügt, konfigurieren Sie sie in <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.


IMPORTANT: Geben Sie die Befehle in diesem Abschnitt an der Shell-Eingabeaufforderung im Wartungsmodus ein.

.Schritte
. Vergleichen Sie die FC-Einstellungen auf Knoten3 mit den Einstellungen, die Sie zuvor von Knoten1 erfasst haben.
. Führen Sie eine der folgenden Aktionen aus, um die FC-Ports auf Knoten3 nach Bedarf zu ändern:
+
Im Wartungsmodus (Option 5 im Bootmenü):

+
** So programmieren Sie als Zielports:
+
`ucadmin modify -m fc -t target <adapter>`

+
Zum Beispiel: `ucadmin modify -m fc -t target 2a`

** So programmieren Sie Initiator-Ports:
+
`ucadmin modify -m fc -t initiator <adapter>`

+
Zum Beispiel: `ucadmin modify -m fc -t initator 2b`



. Überprüfen Sie die neuen Einstellungen, indem Sie den folgenden Befehl verwenden und die Ausgabe untersuchen:
+
`ucadmin show`

. Stoppen Sie den Knoten:
+
`halt`

. Booten Sie das System über die LOADER-Eingabeaufforderung:
+
`boot_ontap menu`

. Nachdem Sie den Befehl eingegeben haben, warten Sie, bis das System an der Eingabeaufforderung der Boot-Umgebung angehalten wird.
. Wählen Sie die Option `5` Wählen Sie im Bootmenü für den Wartungsmodus aus.


. [[Auto_check3_step8]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="30,70"]
|===
| Wenn Knoten 3... | Dann... 


| Verfügt über eine UTA/UTA2-Karte oder UTA/UTA2-Onboard-Ports | Gehe zu<<UTA/UTA2-Ports in node3 prüfen und konfigurieren>> 


| Verfügt nicht über eine UTA/UTA2-Karte oder UTA/UTA2-Onboard-Ports | Überspringen Sie _Überprüfen und konfigurieren Sie UTA/UTA2-Ports auf Knoten3_ und gehen Sie zulink:reassign-node1-disks-to-node3.html["Weisen Sie node1-Festplatten Knoten 3 neu zu"] . 
|===




== UTA/UTA2-Ports in node3 prüfen und konfigurieren

Wenn node3 Onboard UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Konfiguration der Ports überprüfen und sie möglicherweise neu konfigurieren, je nachdem, wie Sie das aktualisierte System verwenden möchten.

.Bevor Sie beginnen
Sie müssen die richtigen SFP+ Module für die UTA/UTA2-Ports besitzen.

.Über diese Aufgabe
Wenn Sie einen Unified Target Adapter (UTA/UTA2)-Port für FC verwenden möchten, müssen Sie zuerst überprüfen, wie der Port konfiguriert ist.


NOTE: Bei NetApp Marketingmaterialien wird möglicherweise der Begriff UTA2 verwendet, um sich auf CNA-Adapter und Ports zu beziehen. Allerdings verwendet die CLI den Begriff CNA.

Sie können die `ucadmin show` Befehl zum Anzeigen oder Überprüfen der aktuellen Portkonfiguration, wie in der folgenden Beispielausgabe gezeigt:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
DIE UTA2-Ports können im nativen FC-Modus oder im UTA/UTA2-Modus konfiguriert werden. Der FC-Modus unterstützt FC Initiator und FC Target. Der UTA-/UTA2-Modus ermöglicht gleichzeitige NIC- und FCoE-Traffic über die gleiche 10-GbE-SFP+-Schnittstelle und unterstützt FC-Ziele.

UTA/UTA2-Ports können sich auf einem Zusatzadapter oder auf der Hauptplatine des Controllers befinden und haben die folgenden Konfigurationen. Sie sollten jedoch die Konfiguration der UTA/UTA2-Ports auf dem Knoten 3 überprüfen und gegebenenfalls ändern:

* UTA-/UTA2-Karten, die bestellt werden, werden vor dem Versand konfiguriert, um die von Ihnen geforderte Persönlichkeit zu erhalten.
* DIE UTA2-Karten, die separat vom Controller bestellt werden, werden mit der standardmäßigen FC-Zielgruppe ausgeliefert.
* Onboard UTA/UTA2-Ports auf neuen Controllern werden vor dem Versand konfiguriert, um die Persönlichkeit zu erhalten, die Sie anfordern.
+

WARNING: Sie müssen sich im Wartungsmodus befinden, um UTA/UTA2-Ports zu konfigurieren.  Geben Sie die Befehle in diesem Abschnitt an der Shell-Eingabeaufforderung im Wartungsmodus ein.



.Schritte
. Wenn das aktuelle SFP+-Modul nicht mit der gewünschten Verwendung übereinstimmt, ersetzen Sie es durch das richtige SFP+-Modul.
+
Wenden Sie sich an Ihren NetApp Ansprechpartner, um das richtige SFP+ Modul zu erhalten.

. Überprüfen Sie die UTA/UTA2-Porteinstellungen:
+
`ucadmin show`

+
Untersuchen Sie die Ausgabe und stellen Sie fest, ob die UTA/UTA2-Ports die gewünschte Persönlichkeit haben.

+
Die Ausgabe im folgenden Beispiel zeigt, dass sich der Typ des Adapters „1b“ in „Initiator“ ändert und dass sich der Modus der Adapter „2a“ und „2b“ in „cna“ ändert.  Der CNA-Modus ermöglicht Ihnen, die Karte als Netzwerkadapter zu verwenden.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. Führen Sie eine der folgenden Aktionen durch:
+
[cols="30,70"]
|===
| Wenn die UTA/UTA2-Ports... | Dann… 


| Haben Sie nicht die Persönlichkeit, die Sie wollen | Gehe zu<<auto_check3_step4,Schritt 4>> . 


| Haben Sie die Persönlichkeit, die Sie wollen | Überspringen Sie Schritt 4 bis Schritt 8 und gehen Sie zu<<auto_check3_step9,Schritt 9>> . 
|===
. [[auto_check3_step4]]Führen Sie eine der folgenden Aktionen aus:
+
[cols="30,70"]
|===
| Wenn Sie konfigurieren... | Dann… 


| Ports auf einer UTA/UTA2-Karte | Gehe zu<<auto_check3_step5,Schritt 5>> 


| Onboard UTA/UTA2-Ports | Überspringen Sie Schritt 5 und gehen Sie zu<<auto_check3_step6,Schritt 6>> . 
|===
. [[auto_check3_step5]]Wenn sich der Adapter im Initiatormodus befindet und der UTA/UTA2-Port online ist, schalten Sie den UTA/UTA2-Port offline:
+
`storage disable adapter <adapter_name>`

+
Adapter im Zielmodus sind im Wartungsmodus automatisch offline.

. [[auto_check3_step6]]Wenn die aktuelle Konfiguration nicht der gewünschten Verwendung entspricht, ändern Sie die Konfiguration nach Bedarf:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` Ist der Persönlichkeitsmodus, `fc` Oder `cna`.
** `-t` Ist der Typ FC4, `target` Oder `initiator`.
+

NOTE: Sie müssen den FC-Initiator für Bandlaufwerke und MetroCluster -Konfigurationen verwenden.  Sie müssen das FC-Ziel für SAN-Clients verwenden.



. Schalten Sie alle Zielports online, indem Sie für jeden Port einmal den folgenden Befehl eingeben:
+
`storage enable adapter <adapter_name>`

. Verkabeln Sie den Port.


[[auto_check3_step9]]
. Beenden des Wartungsmodus:
+
`halt`

. [[step14]]Starten Sie den Knoten im Startmenü:
+
`boot_ontap menu`



.Was kommt als Nächstes?
* Wenn Sie auf ein AFF A800 -System upgraden, gehen Sie zulink:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["Weisen Sie node1-Festplatten Knoten 3, Schritt 9, neu zu"] .
* Für alle anderen System-Upgrades gehen Sie zulink:reassign-node1-disks-to-node3.html["Weisen Sie node1-Festplatten Knoten 3, Schritt 1, neu zu"] .

