---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'Konfigurieren Sie node3 Onboard FC-Ports, UTA/UTA2-Ports oder die UTA/UTA2-Karte, wenn Sie Controller mit ONTAP 9.8 oder höher mit aktualisieren `system controller replace` Befehle.' 
---
= Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node3 fest
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn node3 integrierte FC-Ports, Onboard Unified Target Adapter (UTA/UTA2)-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Einstellungen konfigurieren, bevor Sie den Rest des Verfahrens abschließen.

.Über diese Aufgabe
Möglicherweise müssen Sie den Abschnitt ausfüllen <<Konfigurieren Sie FC-Ports auf node3>>, Der Abschnitt <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>, Oder beide Abschnitte.


NOTE: Unter Umständen bezieht sich bei den Marketingmaterialien von NetApp der Begriff UTA2 auf Adapter und Ports des konvergierten Netzwerkadapters (CNA). Allerdings verwendet die CLI den Begriff CNA.

* Wenn node3 keine integrierten FC-Ports, Onboard-UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat und Sie ein System mit Storage-Festplatten aktualisieren, können Sie zur springen link:verify_node3_installation.html["Überprüfen Sie die Installation von node3"] Abschnitt.
* Wenn Sie jedoch ein V-Series System oder ein System mit FlexArray-Virtualisierungssoftware mit Storage-Arrays haben und node3 keine integrierten FC-Ports, Onboard UTA/UTA-Ports oder eine UTA/UTA2-Karte hat, kehren Sie zum Abschnitt _Installation und Boot-Knoten3_ zurück und setzen Sie den Abschnitt unter fort link:install_boot_node3.html#auto_install3_step23["Schritt 23"].


.Wahlmöglichkeiten
* <<Konfigurieren Sie FC-Ports auf node3>>
* <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>




== Konfigurieren Sie FC-Ports auf node3

Wenn node3 FC-Ports hat, entweder Onboard oder auf einem FC-Adapter, müssen Sie Port-Konfigurationen auf dem Node festlegen, bevor Sie ihn in Betrieb nehmen, da die Ports nicht vorkonfiguriert sind. Wenn die Ports nicht konfiguriert sind, kann es zu einer Serviceunterbrechung kommen.

.Bevor Sie beginnen
Sie müssen die Werte der FC-Port-Einstellungen von node1 haben, die Sie im Abschnitt gespeichert haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"].

.Über diese Aufgabe
Sie können diesen Abschnitt überspringen, wenn Ihr System über keine FC-Konfigurationen verfügt. Wenn Ihr System über integrierte UTA/UTA2-Ports oder eine UTA/UTA2-Karte verfügt, konfigurieren Sie sie in <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.


IMPORTANT: Wenn Ihr System über Speicherfestplatten verfügt, geben Sie an der Cluster-Eingabeaufforderung in diesem Abschnitt die Befehle ein. Wenn Sie über ein „V-Series System“ oder über FlexArray-Virtualisierungssoftware verfügen und mit Storage-Arrays verbunden sind, geben Sie in diesem Abschnitt im Wartungsmodus die entsprechenden Befehle ein.

. [[Schritt1]]Vergleichen Sie die FC-Einstellungen auf node3 mit den Einstellungen, die Sie zuvor aus node1 erfasst haben.
. [[Schritt2]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="30,70"]
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Festplatten sind vorhanden  a| 
Ändern Sie im Wartungsmodus (Option 5 im Startmenü) die FC-Ports auf node3 nach Bedarf:

** So programmieren Sie Zielanschlüsse:


`ucadmin modify -m fc -t target _adapter_`

** So programmieren Sie Initiator-Ports:


`ucadmin modify -m fc -t initiator _adapter_`

`-t` Ist der FC4-Typ: Target oder Initiator.



| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden  a| 
Ändern Sie im Wartungsmodus (Option 5 im Startmenü) die FC-Ports auf node3 nach Bedarf:

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` Ist der FC4-Typ, das Ziel oder der Initiator.


NOTE: Die FC-Ports müssen als Initiatoren programmiert werden.

|===
. [[Schritt3]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="30,70"]
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Festplatten sind vorhanden | Überprüfen Sie die neuen Einstellungen mit dem folgenden Befehl und überprüfen Sie die Ausgabe:
`ucadmin show` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Überprüfen Sie die neuen Einstellungen mit dem folgenden Befehl und überprüfen Sie die Ausgabe:
`ucadmin show` 
|===
. [[Schritt4]]Wartungsmodus beenden:
+
`halt`

. Booten des Systems von der Loader-Eingabeaufforderung:
+
`boot_ontap menu`

. [[Schritt6]] nach Eingabe des Befehls warten Sie, bis das System an der Eingabeaufforderung der Boot-Umgebung angehalten wird.
. Wählen Sie die Option `5` Wählen Sie im Bootmenü für den Wartungsmodus aus.


. [[Auto_check3_step8]]Nehmen Sie eine der folgenden Aktionen:
+
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Festplatten sind vorhanden  a| 
** Wenn node3 eine UTA/UTA2-Karte oder Onboard-Ports zu UTA/UTA2 hat, fahren Sie mit dem Abschnitt fort <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.
** Wenn node3 keine UTA/UTA2-Karte oder Onboard-Ports UTA/UTA2 hat, überspringen Sie den Abschnitt <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>> Und gehen Sie zum Abschnitt link:verify_node3_installation.html["Überprüfen Sie die Installation von node3"].




| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden  a| 
** Wenn node3 eine UTA/UTA2-Karte oder Onboard-Ports zu UTA/UTA2 hat, fahren Sie mit dem Abschnitt fort <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.
** Wenn node3 keine UTA/UTA2-Karte oder Onboard-Ports UTA/UTA2 hat, überspringen Sie den Abschnitt <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>> Und kehren Sie zum Abschnitt _Installieren und Booten node3_ zurück und fahren Sie bei fort link:install_boot_node3.html#auto_install3_step23["Schritt 23"].


|===




== UTA/UTA2-Ports in node3 prüfen und konfigurieren

Wenn node3 Onboard UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Konfiguration der Ports überprüfen und sie möglicherweise neu konfigurieren, je nachdem, wie Sie das aktualisierte System verwenden möchten.

.Bevor Sie beginnen
Sie müssen die richtigen SFP+ Module für die UTA/UTA2-Ports besitzen.

.Über diese Aufgabe
Wenn Sie einen Unified Target Adapter (UTA/UTA2)-Port für FC verwenden möchten, müssen Sie zuerst überprüfen, wie der Port konfiguriert ist.


NOTE: Bei NetApp Marketingmaterialien wird möglicherweise der Begriff UTA2 verwendet, um sich auf CNA-Adapter und Ports zu beziehen. Allerdings verwendet die CLI den Begriff CNA.

Sie können das verwenden `ucadmin show` Befehl zum Überprüfen der aktuellen Portkonfiguration:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
DIE UTA2-Ports können im nativen FC-Modus oder im UTA/UTA2-Modus konfiguriert werden. Der FC-Modus unterstützt FC Initiator und FC Target. Der UTA-/UTA2-Modus ermöglicht gleichzeitige NIC- und FCoE-Traffic über die gleiche 10-GbE-SFP+-Schnittstelle und unterstützt FC-Ziele.

UTA/UTA2-Ports befinden sich möglicherweise auf einem Adapter oder auf dem Controller und verfügen über die folgenden Konfigurationen. Sie sollten jedoch die Konfiguration der UTA/UTA2-Ports auf der node3 überprüfen und gegebenenfalls ändern:

* UTA-/UTA2-Karten, die bestellt werden, werden vor dem Versand konfiguriert, um die von Ihnen geforderte Persönlichkeit zu erhalten.
* DIE UTA2-Karten, die separat vom Controller bestellt werden, werden mit der standardmäßigen FC-Zielgruppe ausgeliefert.
* Onboard UTA/UTA2-Ports auf neuen Controllern werden vor dem Versand konfiguriert, um die Persönlichkeit zu erhalten, die Sie anfordern.
+

WARNING: *Achtung*: Wenn Ihr System über Speicherfestplatten verfügt, geben Sie die Befehle in diesem Abschnitt an der Cluster-Eingabeaufforderung ein, sofern nicht dazu aufgefordert wird, in den Wartungsmodus zu wechseln. Wenn Sie über ein V-Series System verfügen oder über FlexArray-Virtualisierungssoftware verfügen und mit Storage-Arrays verbunden sind, geben Sie in diesem Abschnitt an der Eingabeaufforderung im Wartungsmodus Befehle ein. Sie müssen sich im Wartungsmodus befinden, um UTA/UTA2-Ports zu konfigurieren.



.Schritte
. [[Schritt1]]Überprüfen Sie, wie die Ports derzeit konfiguriert sind, indem Sie auf node3 den folgenden Befehl eingeben:
+
[cols="30,70"]
|===
| Wenn das System... | Dann… 


| Festplatten sind vorhanden | Keine Aktion erforderlich. 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `ucadmin show` 
|===
+
Das System zeigt eine Ausgabe wie im folgenden Beispiel an:

+
....
*> ucadmin show
         Current  Current     Pending   Pending    Admin
Adapter  Mode     Type        Mode      Type       Status
-------  -------  ---------   -------   --------   ---------
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
*>
....
. [[Schritt2]]Wenn das aktuelle SFP+-Modul nicht mit der gewünschten Verwendung übereinstimmt, ersetzen Sie es durch das richtige SFP+-Modul.
+
Wenden Sie sich an Ihren NetApp Ansprechpartner, um das richtige SFP+ Modul zu erhalten.

. [[Schritt3]]Untersuchung der Ausgabe des `ucadmin show` Führen Sie einen Befehl aus, und bestimmen Sie, ob die UTA/UTA2-Ports die gewünschte Persönlichkeit haben.
. [[Schritt4]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="30,70"]
|===
| Wenn die UTA/UTA2-Ports... | Dann… 


| Haben Sie nicht die Persönlichkeit, die Sie wollen | Gehen Sie zu <<auto_check3_step5,Schritt 5>>. 


| Haben Sie die Persönlichkeit, die Sie wollen | Überspringen Sie Schritt 5 bis Schritt 12, und fahren Sie mit fort <<auto_check3_step13,Schritt 13>>. 
|===
. [[Auto_check3_schritt 5]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="30,70"]
|===
| Wenn Sie konfigurieren... | Dann… 


| Ports auf einer UTA/UTA2-Karte | Gehen Sie zu <<auto_check3_step7,Schritt 7>> 


| Onboard UTA/UTA2-Ports | Überspringen Sie Schritt 7, und fahren Sie mit fort <<auto_check3_step8,Schritt 8>>. 
|===
. [[Schritt6]]Wenn sich der Adapter im Initiator-Modus befindet und der UTA/UTA2-Port online ist, versetzen Sie den UTA/UTA2-Port in den Offline-Modus:
+
`storage disable adapter _adapter_name_`

+
Adapter im Zielmodus sind im Wartungsmodus automatisch offline.

. [[Auto_Check3_step7]]Wenn die aktuelle Konfiguration nicht mit der gewünschten Verwendung übereinstimmt, ändern Sie die Konfiguration nach Bedarf:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` Ist der Persönlichkeitsmodus, `fc` Oder `cna`.
** `-t` Ist der Typ FC4, `target` Oder `initiator`.
+

NOTE: Sie müssen FC Initiator für Tape-Laufwerke, FlexArray Virtualisierungssysteme und MetroCluster Konfigurationen verwenden. Sie müssen das FC-Ziel für SAN-Clients verwenden.



. [[Auto_check3_steep8]]Überprüfen Sie die Einstellungen:
+
`ucadmin show`

. [[steep9]]Überprüfen Sie die Einstellungen:
+
[cols="30,70"]
|===
| Wenn das System... | Dann… 


| Festplatten sind vorhanden | `ucadmin show` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `ucadmin show` 
|===
+
Die Ausgabe in den folgenden Beispielen zeigt, dass sich der Adaptertyp „1b“ in ändert `initiator` Und dass sich der Modus der Adapter „2a“ und „2b“ in ändert `cna`:

+
....
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
....
. [[ste10]]Platzieren Sie alle Zielports online, indem Sie einen der folgenden Befehle eingeben, einmal für jeden Port:
+
[cols="30,70"]
|===
| Wenn das System... | Dann… 


| Festplatten sind vorhanden | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `fcp config _adapter_name_ up` 
|===
. [[Schritt11]]Anschluss verkabeln.


. [[Auto_check3_step12]]Nehmen Sie eine der folgenden Aktionen:
+
|===
| Wenn das System... | Dann… 


| Festplatten sind vorhanden | Gehen Sie zu link:verify_node3_installation.html["Überprüfen Sie die Installation von node3"]. 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Kehren Sie zum Abschnitt _Installieren und Starten von node3_ zurück, und fahren Sie bei fort link:install_boot_node3.html#auto_install3_step23["Schritt 23"]. 
|===
. [[Auto_check3_steep13]]Wartungsmodus beenden:
+
`halt`

. [[Schritt14]]Boot-Knoten in Boot-Menü durch Ausführen `boot_ontap menu`. Wenn Sie ein Upgrade auf eine A800 durchführen, gehen Sie zu <<auto_check3_step23,Schritt 23>>.


. [[auto9597_Check_node3_step15]]in node3 wechseln Sie zum Startmenü und wählen Sie mit 22/7 die verborgene Option aus `boot_after_controller_replacement`. Geben Sie an der Eingabeaufforderung node1 ein, um die Festplatten von node1 zu node3 wie im folgenden Beispiel neu zuzuweisen.
+
.Erweitern Sie das Ausgabebeispiel der Konsole
[%collapsible]
====
....
LOADER-A> boot_ontap menu
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7) Print this secret List
(25/6) Force boot with multiple filesystem disks missing.
(25/7) Boot w/ disk labels forced to clean.
(29/7) Bypass media errors.
(44/4a) Zero disks if needed and create new flexible root volume.
(44/7) Assign all disks, Initialize all disks as SPARE, write DDR labels
.
<output truncated>
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
<output truncated>
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
<output truncated>
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
<output truncated>
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
Login:
....
====
+

NOTE: Im obigen Beispiel der Konsolenausgabe werden Sie von ONTAP aufgefordert, den Namen des Partner-Node anzugeben, wenn das System ADP-Festplatten (Advanced Disk Partitioning) verwendet.

. Wenn das System in eine Reboot-Schleife mit der Meldung geht `no disks found`, Es zeigt an, dass das System die FC- oder UTA/UTA2-Ports wieder in den Ziel-Modus zurückgesetzt hat und somit keine Disketten sehen kann. Um dies zu beheben, fahren Sie mit fort <<auto_check3_step17,Schritt 17>> Bis <<auto_check3_step22,Schritt 22>>Oder gehen Sie zu Abschnitt link:verify_node3_installation.html["Überprüfen Sie die Installation von node3"].
. [[Auto_check3_step17]]Drücken Sie `Ctrl-C` Während des automatischen Bootens, um den Node auf dem zu beenden `LOADER>` Eingabeaufforderung:
. [[Schritt18]]wechseln Sie an der Loader-Eingabeaufforderung in den Wartungsmodus:
+
`boot_ontap maint`

. [[ste19]]] im Wartungsmodus werden alle zuvor festgelegten Initiator-Ports angezeigt, die sich jetzt im Zielmodus befinden:
+
`ucadmin show`

+
Ändern Sie die Ports zurück in den Initiatormodus:

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. [[steep20]]Überprüfen Sie, ob die Ports in den Initiatormodus geändert wurden:
+
`ucadmin show`

. [[step21]]Wartungsmodus beenden:
+
`halt`

+
[NOTE]
====
Wenn Sie ein Upgrade von einem System durchführen, das externe Festplatten unterstützt, auf ein System, das auch externe Festplatten unterstützt, gehen Sie zu <<auto_check3_step22,Schritt 22>>.

Wenn Sie ein Upgrade von einem System durchführen, das externe Festplatten unterstützt, auf ein System, das sowohl interne als auch externe Festplatten, wie z. B. ein AFF A800 System, unterstützt, finden Sie unter <<auto_check3_step23,Schritt 23>>.

====
. [[Auto_check3_step22]]an der Loader-Eingabeaufforderung booten:
+
`boot_ontap menu`

+
Beim Booten erkennt der Node jetzt alle Festplatten, die zuvor ihm zugewiesen waren, und kann wie erwartet gebootet werden.

+
Wenn die Cluster-Knoten, die Sie ersetzen, die Root-Volume-Verschlüsselung verwenden, kann die ONTAP-Software die Volume-Informationen nicht von den Festplatten lesen. Stellen Sie die Schlüssel für das Root-Volume wieder her:

+
.. Zurück zum speziellen Startmenü:
`LOADER> boot_ontap menu`
+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Wählen Sie *(10) Set Onboard Key Manager Recovery Secrets*
.. Eingabe `y` An der folgenden Eingabeaufforderung:
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. Geben Sie an der Eingabeaufforderung die Passphrase für das Schlüsselmanagement ein.
.. Geben Sie bei Aufforderung die Backup-Daten ein.
+

NOTE: Sie müssen die Passphrase und Sicherungsdaten im erhalten haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"] Abschnitt dieses Verfahrens.

.. Nachdem das System wieder zum speziellen Startmenü gestartet wurde, führen Sie die Option *(1) Normal Boot* aus
+

NOTE: In dieser Phase ist möglicherweise ein Fehler aufgetreten. Wenn ein Fehler auftritt, wiederholen Sie die Teilschritte in <<auto_check3_step22,Schritt 22>> Bis das System ordnungsgemäß gebootet wird.



. [[Auto_check3_step23]]Wenn Sie ein Upgrade von einem System mit externen Festplatten auf ein System durchführen, das interne und externe Festplatten unterstützt (z. B. AFF A800 Systeme), setzen Sie das node1-Aggregat als Root-Aggregat ein, um zu bestätigen, dass node3 aus dem Root-Aggregat von node1 bootet. Zum Festlegen des Root-Aggregats rufen Sie das Boot-Menü auf und wählen dann Option `5` Um in den Wartungsmodus zu wechseln.
+

CAUTION: *Die folgenden Teilschritte müssen in der angegebenen Reihenfolge ausgeführt werden; andernfalls kann es zu einem Ausfall oder sogar zu Datenverlust kommen.*

+
Im folgenden Verfahren wird node3 vom Root-Aggregat von node1 gestartet:

+
.. Wechseln in den Wartungsmodus:
+
`boot_ontap maint`

.. Überprüfen Sie die RAID-, Plex- und Prüfsummeninformationen für das node1 Aggregat:
+
`aggr status -r`

.. Überprüfen Sie den Status des node1-Aggregats:
+
`aggr status`

.. Bei Bedarf das node1 Aggregat online bringen:
+
`aggr_online root_aggr_from___node1__`

.. Verhindern Sie, dass das node3 vom ursprünglichen Root-Aggregat gebootet wird:
+
`aggr offline _root_aggr_on_node3_`

.. Legen Sie das node1-Root-Aggregat als das neue Root-Aggregat für node3 fest:
+
`aggr options aggr_from___node1__ root`

.. Überprüfen Sie, ob das Root-Aggregat von node3 offline ist und das Root-Aggregat für die von node1 hergebrachten Festplatten online ist und in den Root-Status eingestellt ist:
+
`aggr status`

+

NOTE: Wenn der vorherige Unterschritt nicht ausgeführt wird, kann node3 vom internen Root-Aggregat booten, oder es kann dazu führen, dass das System eine neue Cluster-Konfiguration übernimmt oder Sie aufgefordert werden, eine zu identifizieren.

+
Im Folgenden wird ein Beispiel für die Befehlsausgabe angezeigt:

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



