---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'Konfigurieren Sie node3 Onboard FC-Ports, UTA/UTA2-Ports oder die UTA/UTA2-Karte, wenn Sie Controller mit ONTAP 9.8 oder höher mit aktualisieren `system controller replace` Befehle.' 
---
= Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node3 fest
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn node3 integrierte FC-Ports, Onboard Unified Target Adapter (UTA/UTA2)-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Einstellungen konfigurieren, bevor Sie den Rest des Verfahrens abschließen.

.Über diese Aufgabe
Möglicherweise müssen Sie den Abschnitt ausfüllen <<Konfigurieren Sie FC-Ports auf node3>>, Der Abschnitt <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>, Oder beide Abschnitte.


NOTE: Unter Umständen bezieht sich bei den Marketingmaterialien von NetApp der Begriff UTA2 auf Adapter und Ports des konvergierten Netzwerkadapters (CNA). Allerdings verwendet die CLI den Begriff CNA.

* Wenn Node3 nicht über Onboard FC-Ports, Onboard UTA/UTA2-Ports oder eine UTA/UTA2-Karte verfügt und Sie ein System mit Storage-Festplatten aktualisieren, können Sie zu überspringenlink:reassign-node1-disks-to-node3.html["Weisen Sie node1-Festplatten Knoten 3 neu zu"].
* Wenn Sie jedoch ein V-Series System oder ein System mit FlexArray Virtualisierungssoftware mit Storage-Arrays haben und node3 keine integrierten FC-Ports, Onboard UTA/UTA-Ports oder eine UTA/UTA2-Karte hat, kehren Sie zu _Install und Boot node3_ zurück und fahren Sie unter fortlink:install_boot_node3.html#auto_install3_step23["Schritt 23"].




== Konfigurieren Sie FC-Ports auf node3

Wenn node3 FC-Ports hat, entweder Onboard oder auf einem FC-Adapter, müssen Sie Port-Konfigurationen auf dem Node festlegen, bevor Sie ihn in Betrieb nehmen, da die Ports nicht vorkonfiguriert sind. Wenn die Ports nicht konfiguriert sind, kann es zu einer Serviceunterbrechung kommen.

.Bevor Sie beginnen
Sie müssen die Werte der FC-Port-Einstellungen von node1 haben, die Sie im Abschnitt gespeichert haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"].

.Über diese Aufgabe
Sie können diesen Abschnitt überspringen, wenn Ihr System über keine FC-Konfigurationen verfügt. Wenn Ihr System über integrierte UTA/UTA2-Ports oder eine UTA/UTA2-Karte verfügt, konfigurieren Sie sie in <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.


IMPORTANT: Wenn Ihr System über Speicherfestplatten verfügt, geben Sie an der Cluster-Eingabeaufforderung in diesem Abschnitt die Befehle ein. Wenn Sie über ein „V-Series System“ oder über FlexArray-Virtualisierungssoftware verfügen und mit Storage-Arrays verbunden sind, geben Sie in diesem Abschnitt im Wartungsmodus die entsprechenden Befehle ein.

. [[Schritt1]]Vergleichen Sie die FC-Einstellungen auf node3 mit den Einstellungen, die Sie zuvor aus node1 erfasst haben.
. [[Schritt2]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="30,70"]
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Festplatten sind vorhanden  a| 
Ändern Sie im Wartungsmodus (Option 5 im Startmenü) die FC-Ports auf node3 nach Bedarf:

** So programmieren Sie Zielanschlüsse:


`ucadmin modify -m fc -t target _adapter_`

** So programmieren Sie Initiator-Ports:


`ucadmin modify -m fc -t initiator _adapter_`

`-t` Ist der FC4-Typ: Target oder Initiator.



| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden  a| 
Ändern Sie im Wartungsmodus (Option 5 im Startmenü) die FC-Ports auf node3 nach Bedarf:

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` Ist der FC4-Typ, das Ziel oder der Initiator.


NOTE: Die FC-Ports müssen als Initiatoren programmiert werden.

|===
. [[Schritt3]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="30,70"]
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Festplatten sind vorhanden | Überprüfen Sie die neuen Einstellungen mit dem folgenden Befehl und überprüfen Sie die Ausgabe:
`ucadmin show` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Überprüfen Sie die neuen Einstellungen mit dem folgenden Befehl und überprüfen Sie die Ausgabe:
`ucadmin show` 
|===
. [[Schritt4]]Wartungsmodus beenden:
+
`halt`

. Booten Sie das System über die LOADER-Eingabeaufforderung:
+
`boot_ontap menu`

. [[Schritt6]] nach Eingabe des Befehls warten Sie, bis das System an der Eingabeaufforderung der Boot-Umgebung angehalten wird.
. Wählen Sie die Option `5` Wählen Sie im Bootmenü für den Wartungsmodus aus.


. [[Auto_check3_step8]]Nehmen Sie eine der folgenden Aktionen:
+
|===
| Wenn das System, das Sie aktualisieren... | Dann… 


| Festplatten sind vorhanden  a| 
** Wenn node3 eine UTA/UTA2-Karte oder Onboard-Ports zu UTA/UTA2 hat, gehen Sie zu <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.
** Wenn node3 keine UTA/UTA2-Karte oder UTA/UTA2-Onboard-Ports hat, überspringen sie _Check und konfigurieren Sie UTA/UTA2-Ports auf node3_ und gehen Sie zu link:reassign-node1-disks-to-node3.html["Weisen Sie node1-Festplatten Knoten 3 neu zu"].




| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden  a| 
** Wenn node3 eine UTA/UTA2-Karte oder Onboard-Ports zu UTA/UTA2 hat, gehen Sie zu <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.
** Wenn node3 keine UTA/UTA2-Karte oder UTA/UTA2-Onboard-Ports hat, überspringen sie _Check und konfigurieren Sie UTA/UTA2-Ports auf node3_ und kehren Sie zu _Install und Boot node3_ zurück und fahren Sie mit link:install_boot_node3.html#auto_install3_step23["Schritt 23"]dem Verfahren unter fort.


|===




== UTA/UTA2-Ports in node3 prüfen und konfigurieren

Wenn node3 Onboard UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Konfiguration der Ports überprüfen und sie möglicherweise neu konfigurieren, je nachdem, wie Sie das aktualisierte System verwenden möchten.

.Bevor Sie beginnen
Sie müssen die richtigen SFP+ Module für die UTA/UTA2-Ports besitzen.

.Über diese Aufgabe
Wenn Sie einen Unified Target Adapter (UTA/UTA2)-Port für FC verwenden möchten, müssen Sie zuerst überprüfen, wie der Port konfiguriert ist.


NOTE: Bei NetApp Marketingmaterialien wird möglicherweise der Begriff UTA2 verwendet, um sich auf CNA-Adapter und Ports zu beziehen. Allerdings verwendet die CLI den Begriff CNA.

Sie können das verwenden `ucadmin show` Befehl zum Überprüfen der aktuellen Portkonfiguration:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
DIE UTA2-Ports können im nativen FC-Modus oder im UTA/UTA2-Modus konfiguriert werden. Der FC-Modus unterstützt FC Initiator und FC Target. Der UTA-/UTA2-Modus ermöglicht gleichzeitige NIC- und FCoE-Traffic über die gleiche 10-GbE-SFP+-Schnittstelle und unterstützt FC-Ziele.

UTA/UTA2-Ports befinden sich möglicherweise auf einem Adapter oder auf dem Controller und verfügen über die folgenden Konfigurationen. Sie sollten jedoch die Konfiguration der UTA/UTA2-Ports auf der node3 überprüfen und gegebenenfalls ändern:

* UTA-/UTA2-Karten, die bestellt werden, werden vor dem Versand konfiguriert, um die von Ihnen geforderte Persönlichkeit zu erhalten.
* DIE UTA2-Karten, die separat vom Controller bestellt werden, werden mit der standardmäßigen FC-Zielgruppe ausgeliefert.
* Onboard UTA/UTA2-Ports auf neuen Controllern werden vor dem Versand konfiguriert, um die Persönlichkeit zu erhalten, die Sie anfordern.
+

WARNING: *Achtung*: Wenn Ihr System über Speicherfestplatten verfügt, geben Sie die Befehle in diesem Abschnitt an der Cluster-Eingabeaufforderung ein, sofern nicht dazu aufgefordert wird, in den Wartungsmodus zu wechseln. Wenn Sie über ein V-Series System verfügen oder über FlexArray-Virtualisierungssoftware verfügen und mit Storage-Arrays verbunden sind, geben Sie in diesem Abschnitt an der Eingabeaufforderung im Wartungsmodus Befehle ein. Sie müssen sich im Wartungsmodus befinden, um UTA/UTA2-Ports zu konfigurieren.



.Schritte
. [[Schritt1]]Überprüfen Sie, wie die Ports derzeit konfiguriert sind, indem Sie auf node3 den folgenden Befehl eingeben:
+
[cols="30,70"]
|===
| Wenn das System... | Dann… 


| Festplatten sind vorhanden | Keine Aktion erforderlich. 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `ucadmin show` 
|===
+
Das System zeigt eine Ausgabe wie im folgenden Beispiel an:

+
....
*> ucadmin show
         Current  Current     Pending   Pending    Admin
Adapter  Mode     Type        Mode      Type       Status
-------  -------  ---------   -------   --------   ---------
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
*>
....
. [[Schritt2]]Wenn das aktuelle SFP+-Modul nicht mit der gewünschten Verwendung übereinstimmt, ersetzen Sie es durch das richtige SFP+-Modul.
+
Wenden Sie sich an Ihren NetApp Ansprechpartner, um das richtige SFP+ Modul zu erhalten.

. [[Schritt3]]Untersuchung der Ausgabe des `ucadmin show` Führen Sie einen Befehl aus, und bestimmen Sie, ob die UTA/UTA2-Ports die gewünschte Persönlichkeit haben.
. [[Schritt4]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="30,70"]
|===
| Wenn die UTA/UTA2-Ports... | Dann… 


| Haben Sie nicht die Persönlichkeit, die Sie wollen | Gehen Sie zu <<auto_check3_step5,Schritt 5>>. 


| Haben Sie die Persönlichkeit, die Sie wollen | Überspringen Sie Schritt 5 bis Schritt 12, und fahren Sie mit fort <<auto_check3_step13,Schritt 13>>. 
|===
. [[Auto_check3_schritt 5]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="30,70"]
|===
| Wenn Sie konfigurieren... | Dann… 


| Ports auf einer UTA/UTA2-Karte | Gehen Sie zu <<auto_check3_step7,Schritt 7>> 


| Onboard UTA/UTA2-Ports | Überspringen Sie Schritt 7, und fahren Sie mit fort <<auto_check3_step8,Schritt 8>>. 
|===
. [[Schritt6]]Wenn sich der Adapter im Initiator-Modus befindet und der UTA/UTA2-Port online ist, versetzen Sie den UTA/UTA2-Port in den Offline-Modus:
+
`storage disable adapter _adapter_name_`

+
Adapter im Zielmodus sind im Wartungsmodus automatisch offline.

. [[Auto_Check3_step7]]Wenn die aktuelle Konfiguration nicht mit der gewünschten Verwendung übereinstimmt, ändern Sie die Konfiguration nach Bedarf:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` Ist der Persönlichkeitsmodus, `fc` Oder `cna`.
** `-t` Ist der Typ FC4, `target` Oder `initiator`.
+

NOTE: Sie müssen FC Initiator für Tape-Laufwerke, FlexArray Virtualisierungssysteme und MetroCluster Konfigurationen verwenden. Sie müssen das FC-Ziel für SAN-Clients verwenden.



. [[Auto_check3_steep8]]Überprüfen Sie die Einstellungen:
+
`ucadmin show`

. [[steep9]]Überprüfen Sie die Einstellungen:
+
[cols="30,70"]
|===
| Wenn das System... | Dann… 


| Festplatten sind vorhanden | `ucadmin show` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `ucadmin show` 
|===
+
Die Ausgabe in den folgenden Beispielen zeigt, dass sich der Adaptertyp „1b“ in ändert `initiator` Und dass sich der Modus der Adapter „2a“ und „2b“ in ändert `cna`:

+
....
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
....
. [[ste10]]Platzieren Sie alle Zielports online, indem Sie einen der folgenden Befehle eingeben, einmal für jeden Port:
+
[cols="30,70"]
|===
| Wenn das System... | Dann… 


| Festplatten sind vorhanden | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | `fcp config _adapter_name_ up` 
|===
. [[Schritt11]]Anschluss verkabeln.


. [[Auto_check3_step12]]Nehmen Sie eine der folgenden Aktionen:
+
|===
| Wenn das System... | Dann… 


| Festplatten sind vorhanden | Gehen Sie zu link:reassign-node1-disks-to-node3.html["Weisen Sie node1-Festplatten Knoten 3 neu zu"]. 


| Ist ein V-Series System oder hat FlexArray-Virtualisierungssoftware und ist mit Storage-Arrays verbunden | Kehren Sie zu _Install und Boot node3_ zurück, und setzen Sie den Vorgang fortlink:install_boot_node3.html#auto_install3_step23["Schritt 23"]. 
|===
. [[Auto_check3_steep13]]Wartungsmodus beenden:
+
`halt`

. [[step14]]Starten Sie den Knoten in das Startmenü, indem Sie ausführen `boot_ontap menu`. Wenn Sie ein Upgrade auf eine A800 durchführen, gehen Sie zu link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["Weisen Sie node1-Festplatten Knoten 3, Schritt 9, neu zu"].

