---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/stage_3_index.html 
keywords: installing, booting, node3, install, cluster, stage 3 
summary: 'Phase 3-Prozessreihenfolge für ein ARL-Upgrade mit `system controller replace` Befehle auf Controllern mit ONTAP 9.8 oder höher.' 
---
= Phase 3: Installieren und booten Sie node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Während Phase 3 installieren und booten Sie node3, überprüfen, ob die Cluster- und Node-Management-Ports von node1 auf node3 online geschaltet sind und überprüfen Sie die Installation node3. Daten-LIFs außerhalb von SAN und Aggregate außerhalb des Root-Bereichs, die zu node1 gehören, werden von node2 in node3 verschoben.

.Schritte
. link:install_boot_node3.html["Installieren und booten Sie node3"]
. link:set_fc_or_uta_uta2_config_on_node3.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node3 fest"]
. link:verify_node3_installation.html["Überprüfen Sie die Installation von node3"]
. link:restore_key-manager_configuration_node3.html["Wiederherstellung der Key-Manager-Konfiguration auf Knoten 3"]
. link:move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html["Verschieben Sie Aggregate ohne Root-Root-Fehler und NAS-Daten-LIFs, die sich im Besitz von node1 befinden, von node2 auf node3"]

