---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/verify_health_of_metrocluster_config.html 
keywords: verifying, health, metrocluster, configuration, fabric, mcc 
summary: 'Überprüfen Sie den Systemzustand der MetroCluster Konfiguration und den korrekten Betrieb, wenn Sie Controller mit ONTAP 9.8 oder höher mithilfe von aktualisieren `system controller replace` Befehle.' 
---
= Überprüfen Sie den Systemzustand der MetroCluster-Konfiguration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie ein Upgrade auf einer Fabric-MetroCluster-Konfiguration starten, müssen Sie den Zustand der MetroCluster-Konfiguration überprüfen, um den korrekten Betrieb zu überprüfen.

.Schritte
. Vergewissern Sie sich, dass die MetroCluster-Komponenten ordnungsgemäß sind:
+
`metrocluster check run`

+
....
metrocluster_siteA::*> metrocluster check run
....
+
Der Vorgang wird im Hintergrund ausgeführt.

. Nach dem `metrocluster check run` Vorgang abgeschlossen, Ergebnisse anzeigen:
+
`metrocluster check show`

+
Nach etwa fünf Minuten werden die folgenden Ergebnisse angezeigt:

+
[listing]
----
metrocluster_siteA::*> metrocluster check show
Last Checked On: 4/7/2019 21:15:05
Component            Result
---------------      -------
nodes                ok
lifs                 ok
config-replication   ok
aggregates           warning
clusters             ok
connections          not-applicable
volumes              ok
7 entries were displayed.
----
. Überprüfen Sie den Status des laufenden MetroCluster-Prüfvorgangs:
+
`metrocluster operation history show -job-id 38`

. Vergewissern Sie sich, dass es keine Systemzustandsmeldungen gibt:
+
`system health alert show`


