---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/aggregate_relocation_failures.html 
keywords: aggregate, relocation, failures, arl, stage 2, stage 3, stage 5 
summary: Beheben Sie Fehler bei Aggregatverschiebung, die während eines Upgrades von AFF A700 auf AFF A900 auftreten können. 
---
= Fehler bei der Aggregatverschiebung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bei der Aggregatverschiebung (ARL, Aggregate Relocation) fallen während des Upgrades möglicherweise an verschiedenen Punkten aus.



== Prüfen Sie, ob Aggregate Relocation Failure vorhanden sind

Während des Verfahrens kann ARL in Phase 2, Phase 3 oder Phase 5 fehlschlagen.

.Schritte
. Geben Sie den folgenden Befehl ein und überprüfen Sie die Ausgabe:
+
`storage aggregate relocation show`

+
Der `storage aggregate relocation show` Der Befehl zeigt Ihnen, welche Aggregate erfolgreich umgezogen wurden und welche nicht, zusammen mit den Ursachen des Ausfalls.

. Überprüfen Sie die Konsole auf EMS-Nachrichten.
. Führen Sie eine der folgenden Aktionen durch:
+
** Führen Sie die entsprechenden Korrekturmaßnahmen durch, je nach der Ausgabe des `storage aggregate relocation show` Befehl und Ausgabe der EMS-Nachricht.
** Erzwingen Sie das verlagern des Aggregats oder der Aggregate mit dem `override-vetoes` Oder die Option `override-destination-checks` Option des `storage aggregate relocation start` Befehl.


+
Ausführliche Informationen zum `storage aggregate relocation start`, `override-vetoes`, und `override-destination-checks` Optionen finden Sie unter link:other_references.html["Quellen"] Link zu den Befehlen _ONTAP 9: Manual Page Reference_.





== Aggregate, die ursprünglich auf node1 verwendet wurden, sind nach Abschluss des Upgrades Eigentum von node2

Beim Ende des Upgrade-Verfahrens sollte die Knoten1 der neue Home-Node von Aggregaten sein, die ursprünglich als Home-Node node1 verwendet wurden. Sie können sie nach dem Upgrade verschieben.

Falls Aggregate nicht korrekt verschoben werden können, d. h. Node 2 statt Knoten 1, wird unter den folgenden Umständen als Home Node verwendet:

* In Phase 3, wenn Aggregate von node2 auf node1 verschoben werden.
+
Einige der verlagerten Aggregate haben die Nr. 1 als Home-Node. Ein solches Aggregat könnte zum Beispiel „aggr_Node_1“ heißen. Wenn die Verlagerung von aggr_Node_1 während Phase 3 fehlschlägt und eine Verlagerung nicht erzwungen werden kann, dann bleibt das Aggregat auf node2 zurück.

* Wenn nach Phase 4 node2 durch den AFF A900 oder den FAS9500 Controller und NVRAM-Module ersetzt wird.
+
Wenn node2 ersetzt wird, kommt aggr_Node_1 mit node1 als Home-Node statt node2 online.



Nach Phase 6 können Sie das falsche Eigentümerproblem beheben, nachdem Sie das Storage-Failover aktiviert haben, indem Sie die folgenden Schritte durchführen:

.Schritte
. Erhalten Sie eine Liste von Aggregaten:
+
`storage aggregate show -nodes _node2_ -is-home true`

+
Informationen zur Identifizierung von Aggregaten, die nicht korrekt verschoben wurden, finden Sie in der Liste der Aggregate mit dem Home-Inhaber von node1, die Sie im Abschnitt erhalten haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"] Und vergleichen Sie ihn mit der Ausgabe des obigen Befehls.

. Vergleichen Sie die Ausgabe von Schritt 1 mit der Ausgabe, die Sie für Knoten 1 im Abschnitt aufgenommen haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"] Und beachten Sie alle Aggregate, die nicht korrekt verschoben wurden.
. Verschiebung der Aggregate links hinter Knoten2:
+
`storage aggregate relocation start -node _node2_ -aggr _aggr_node_1_ -destination _node1_`

+
Verwenden Sie während dieser Verschiebung keinen Parameter für -ndo-Controller-Upgrade.

. Vergewissern Sie sich, dass node1 jetzt der Haupteigentümer der Aggregate ist:
+
`storage aggregate show -aggregate _aggr1,aggr2,aggr3..._ -fields home-name`

+
`_aggr1,aggr2,aggr3..._` Ist die Liste der Aggregate, die node1 als ursprünglichen Besitzer hatten.

+
Aggregate, die nicht den Knoten1 als Hausbesitzer haben, können mit dem gleichen Relocation-Befehl in Schritt 3 auf node1 umgezogen werden.


