---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: Entscheiden Sie, ob Sie das ARL-Verfahren zum Upgrade von Controller-Modellen im selben Chassis anwenden. 
---
= Entscheiden Sie, ob Sie das Verfahren zur Aggregatverschiebung verwenden
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieser Inhalt beschreibt, wie Sie ein Upgrade von Storage Controllern in einem HA-Paar durchführen, ohne dabei alle vorhandenen Daten und Festplatten zu beeinträchtigen. Dies ist ein komplexes Verfahren, das nur von erfahrenen Administratoren verwendet werden sollte.

Sie können dieses Verfahren unter folgenden Umständen verwenden:

* Sie führen eines der folgenden Controller-Upgrades aus:
+
[cols="50,50"]
|===
| Alter Controller | Ersatz-Controller 


| AFF A800 | AFF A70 und AFF A90 


| AFF A220 als ASA konfiguriert | ASA A150 


| AFF A220, AFF A200 oder AFF C190 | AFF A150 


| FAS2720 oder FAS2720 | FAS2820 


| AFF A700 – als ASA konfiguriert | ASA A900 


| AFF A700 | AFF A900 


| FAS9000 | FAS9500 
|===
* Sie haben mit Ihrem NetApp Vertriebsmitarbeiter verifiziert, dass Sie die Hardware für das Controller-Upgrade erhalten haben:
+
** Zwei AFF A90 oder zwei AFF A70-Controller und alle für das Upgrade erforderlichen I/O-Module. Die erforderliche Länge von 100-GbE-Kabeln.
** ASA Controller A150, AFF A150 oder FAS2820
** ASA Controller- und NVRAM-Module A900, AFF A900 oder FAS9500 sowie die für das Upgrade erforderlichen Teile


* Sie verwenden die minimale ONTAP-Version für Ihr Upgrade. Weitere Informationen finden Sie unter link:index.html["Überblick"].
* Sie möchten die neuen Controller nicht als neues HA-Paar zum Cluster hinzufügen und die Daten mithilfe von Volume-Verschiebungen migrieren.
* Sie sind erfahren in der Verwaltung von ONTAP und sind mit den Risiken der Arbeit im Diagnose-Privilege-Modus vertraut.


Sie können dieses Verfahren unter folgenden Umständen nicht verwenden:

* Sie verwenden die FlexArray Virtualisierungssoftware auf den Systemen AFF A800, AFF A700 oder FAS9000.
* Sie verwenden einen gemeinsamen Switch für Cluster-Interconnect und Ethernet Attached Storage.


Informationen zum Upgrade von MetroCluster IP-Konfigurationen auf AFF A800, AFF A700 oder FAS9000 Systemen finden Sie unter link:other_references.html["Quellen"] Link zum Inhalt _MetroCluster Upgrade and Expansion_.


NOTE: Dabei können Sie NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) und NetApp Aggregate Encryption (NAE) verwenden.

Wenn Sie eine andere Methode zum Upgrade der Controller-Hardware bevorzugen und bereit sind, Volume-Verschiebungen durchzuführen, lesen Sie link:other_references.html["Quellen"] Link zu _Upgrade durch Verschieben von Volumes oder Storage_.

Siehe link:other_references.html["Quellen"] Zum Link zum Dokumentationszentrum _ONTAP 9_, wo Sie auf die Produktdokumentation zu ONTAP 9 zugreifen können.
