---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: Entscheiden Sie, ob Sie das ARL-Verfahren zum Upgrade von Controller-Modellen im selben Chassis anwenden. 
---
= Entscheiden Sie, ob Sie das Verfahren zur Aggregatverschiebung verwenden
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieser Inhalt beschreibt, wie Sie ein Upgrade von Storage Controllern in einem HA-Paar durchführen, ohne dabei alle vorhandenen Daten und Festplatten zu beeinträchtigen. Dies ist ein komplexes Verfahren, das nur von erfahrenen Administratoren verwendet werden sollte.



== Unterstützt für ARL-Upgrades

Sie können dieses Verfahren unter folgenden Umständen verwenden:

* Die Aktualisierung Ihres Controllers wird in der Liste aufgeführtlink:index.html#supported-systems,["Unterstützte Systeme Matrix"].
* Sie haben mit Ihrem NetApp Vertriebsmitarbeiter verifiziert, dass Sie die Hardware erhalten haben, die Sie für das Controller-Upgrade benötigen:
+
** Zwei AFF A90-, AFF A70- oder AFF C80-Controller und alle I/O-Module. Die erforderliche Länge von 100-GbE-Kabeln.
** Zwei AFF A50-, AFF A30-, AFF C30- oder AFF C60-Controller und E/A-Module. Die erforderlichen Kabel.
** ASA Controller A150, AFF A150 oder FAS2820
** ASA A900-, AFF A900- oder FAS9500-Controller und NVRAM-Module und die Teile


* Sie verwenden die minimale ONTAP-Version für Ihr Upgrade. Weitere Informationen finden Sie unter link:index.html["Überblick"].
* Sie möchten die neuen Controller nicht als neues HA-Paar zum Cluster hinzufügen und die Daten mithilfe von Volume-Verschiebungen migrieren.
* Sie sind erfahren in der Verwaltung von ONTAP und sind mit den Risiken der Arbeit im Diagnose-Privilege-Modus vertraut.
* Auf Ihren Systemen wird ONTAP 9.15.1 oder höher ausgeführt, und sie verwenden Ethernet-Switches für die Verbindung mit Ethernet-Attached Storage.




== Nicht unterstützt bei ARL-Upgrades

Sie können dieses Verfahren unter folgenden Umständen nicht verwenden:

* Sie verwenden die FlexArray Virtualisierungssoftware auf dem zu aktualisierenden System.
* Sie aktualisieren eine MetroCluster IP-Konfiguration.
+
Informationen zum Upgrade einer MetroCluster-IP-Konfiguration finden Sie unter link:other_references.html["Quellen"] zum Link zum _MetroCluster-Upgrade und -Erweiterung_-Inhalt.




NOTE: Dabei können Sie NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) und NetApp Aggregate Encryption (NAE) verwenden.

Wenn Sie eine andere Methode zum Upgrade der Controller-Hardware bevorzugen und bereit sind, Volume-Verschiebungen durchzuführen, lesen Sie link:other_references.html["Quellen"] Link zu _Upgrade durch Verschieben von Volumes oder Storage_.

Siehe link:other_references.html["Quellen"] Zum Link zum Dokumentationszentrum _ONTAP 9_, wo Sie auf die Produktdokumentation zu ONTAP 9 zugreifen können.
