---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability, aff, a700, a900 
summary: Entscheiden Sie, ob Sie das ARL-Verfahren verwenden, um eine AFF A700 auf einen AFF A900 zu aktualisieren. 
---
= Entscheiden Sie, ob Sie das Verfahren zur Aggregatverschiebung verwenden
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In diesem Inhalt wird beschrieben, wie Storage Controller in einem AFF A700 HA-Paar mit den neuen AFF A900 Controllern in einem FAS9000 HA-Paar mit den neuen FAS9500 Controllern aktualisiert werden. Dabei werden alle Daten und Festplatten gespeichert. Dies ist ein komplexes Verfahren, das nur von erfahrenen Administratoren verwendet werden sollte.

Verwenden Sie dieses Verfahren unter den folgenden Umständen:

* Sie haben gemeinsam mit Ihrem NetApp Ansprechpartner überprüft, ob Sie den AFF A900 oder FAS9500 Controller, NVRAM-Module sowie die für das Upgrade erforderlichen Teile erhalten haben.
* Sie führen derzeit ONTAP 9.11.1P6 oder 9.10.1P10 aus (für Februar 2023 geplant).
* Sie möchten die neuen Controller nicht als neues HA-Paar zum Cluster hinzufügen und die Daten mithilfe von Volume-Verschiebungen migrieren.
* Sie sind erfahren in der Verwaltung von ONTAP und sind mit den Risiken der Arbeit im Diagnose-Privilege-Modus vertraut.


Verwenden Sie dieses Verfahren unter folgenden Umständen:

* Sie verwenden die FlexArray Virtualisierungssoftware auf den AFF A700 oder FAS9000 Systemen.
* Sie verwenden einen gemeinsamen Switch für Cluster-Interconnect und Ethernet Attached Storage.


Informationen zum Aktualisieren von Fabric-MetroCluster- oder MetroCluster IP-Konfigurationen finden Sie unter link:other_references.html["Quellen"] Zum Verlinken auf den Inhalt _MetroCluster Upgrade und Expansion_.


NOTE: Dabei können Sie NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) und NetApp Aggregate Encryption (NAE) verwenden.

Wenn Sie eine andere Methode zum Upgrade der Controller-Hardware bevorzugen und bereit sind, Volume-Verschiebungen durchzuführen, lesen Sie link:other_references.html["Quellen"] Link zu _Upgrade durch Verschieben von Volumes oder Storage_.

Siehe link:other_references.html["Quellen"] Zum Link zum Dokumentationszentrum _ONTAP 9_, wo Sie auf die Produktdokumentation zu ONTAP 9 zugreifen können.
