---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, aff, a900, a700, ontap, controllers 
summary: Stellen Sie sich vor, ob Sie mit ARL ein Upgrade einer AFF A700 auf einen AFF A900 durchführen können. 
---
= Richtlinien für Controller Upgrades
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden von ARL, um ein Controller-Paar mit ONTAP 9.10.1P10, 9.11.1P6 oder eine neuere Version in den folgenden Systemkonfigurationen zu aktualisieren:

* AFF A700 Controller zu einem AFF A900 System
* FAS9000 Controller zu einem FAS9500 System




== Unterstützte Upgrades für ARL

Controller Upgrade von einer AFF A700 auf einen AFF A900 oder von einer FAS9000 mithilfe von ARL auf ein FAS9500 System. Dabei wird das NVRAM-Modul von einer unterstützten Kombination unterstützt. Wenn Sie ein neues AFF A900 oder FAS9500 System als komplettes System mit neuem Gehäuse erhalten haben, finden Sie unter link:other_references.html["Quellen"] Um eine Verbindung zu den Befehlen „System Controller Replace“ zu herstellen, um die Controller Hardware mit ONTAP 9.8 oder höher zu aktualisieren_.


WARNING: Dieses Verfahren gilt ausschließlich für eine AFF A700 auf AFF A900 oder für ein FAS9000 auf FAS9500 Upgrade mit ONTAP 9.10.1P10, 9.11.1P6 oder einer neueren Version. Verwenden Sie dieses Verfahren NICHT, um ein Upgrade zwischen anderen Systemkombinationen durchzuführen.

Das Controller-Upgrade mit ARL wird auf Systemen unterstützt, die mit SnapLock Enterprise und SnapLock Compliance Volumes konfiguriert sind.



== 2-Node-Cluster ohne Switches

Wenn Sie Nodes in einem 2-Node-Cluster ohne Switches aktualisieren, können Sie die Nodes im Cluster ohne Switches während des Upgrades belassen. Sie müssen sie nicht in ein Switch-Cluster konvertieren.



== Fehlerbehebung

Falls beim Upgrade der Controller Probleme auftreten, lesen Sie den link:troubleshoot_index.html["Fehlerbehebung"] Abschnitt am Ende des Verfahrens für weitere Informationen und mögliche Lösungen.

Wenn Sie keine Lösung für das Problem finden, wenden Sie sich an den technischen Support.
