---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, old, system, chassis, disk, disks 
summary: Sie können Controller-Hardware aufrüsten, indem Sie ein altes System in ein Ersatzsystem konvertieren und dabei das alte Systemgehäuse und die alten Festplatten beibehalten. 
---
= Erfahren Sie mehr über dieses ARL-Upgradeverfahren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es gibt verschiedene Methoden zur Aggregatverlagerung (ARL) für die Aktualisierung der Controller-Hardware. Dieses Verfahren beschreibt die Aktualisierung der Speichercontroller in einem HA-Paar durch Konvertierung des vorhandenen Systems in das Ersatzsystem unter Beibehaltung des vorhandenen Systemgehäuses und der vorhandenen Festplatten.

ARL nutzt die HA-Konfiguration und die Cluster Interconnect-Kommunikation. So können Sie Eigentum von nicht-Root-Aggregaten von einem Node zu einem anderen verschieben, wenn sie Storage innerhalb desselben Clusters gemeinsam nutzen.

Während des Verfahrens führen Sie ein Upgrade der ursprünglichen Controller Hardware mit der Ersatz-Controller-Hardware durch. Hierbei werden die Eigentumsrechte an Aggregaten verschoben, die nicht mit Root-Berechtigungen verbunden sind. Sie migrieren die nicht-Root-Aggregate zwischen den alten Controller-Nodes. Nach der Installation der Ersatz-Nodes migrieren Sie die nicht-Root-Aggregate von den alten Controller-Nodes auf die Ersatz-Controller-Nodes. Auf die Daten, die auf den Nodes gehostet werden, die Sie aktualisieren, kann während des Upgrades zugegriffen werden. Sie migrieren beim Fortfahren Daten-LIFs zwischen Nodes im Cluster.

Die Controller-Hardware, die Sie ersetzen, hängt vom vorhandenen Systemmodelltyp ab:

[cols="30,70"]
|===
| Wenn Ihr bestehendes System... | Dann... 


| AFF A250, AFF C250 | Tauschen Sie die beiden AFF A250 oder AFF C250 Controller durch die neuen Controller und I/O-Module aus. 


| AFF A800, AFF C800 | Tauschen Sie die beiden AFF A800 oder AFF C800 Controller durch die neuen Controller und I/O-Module aus. 


| AFF A220, AFF A200, AFF C190, FAS2720 oder FAS2720 | Tauschen Sie das Controller-Modul an jedem Knoten des alten Controllers gegen das neue Modul aus. 


| AFF A700 ODER FAS9000 | Tauschen Sie den Controller und die NVRAM-Module auf jedem Node des alten Controllers gegen die neuen Module aus. *Hinweis*: Sie müssen die I/O-Karten, Datenkabel, Platten-Shelfs und Festplatten nicht verschieben, trennen oder wieder anschließen. 
|===

NOTE: Die Begriffe *node1* und *node2* werden nur als Hinweis auf Knotennamen in diesem Dokument verwendet. Wenn Sie das Verfahren befolgen, müssen Sie die tatsächlichen Namen Ihrer Knoten ersetzen.



== Anforderungen und Einschränkungen zu erfüllen

Sie müssen wichtige Faktoren berücksichtigen, bevor Sie mit dem Upgrade-Vorgang beginnen.


NOTE: Sie müssen alle folgenden wichtigen Informationen überprüfen, bevor Sie mit dem Upgrade-Vorgang beginnen.

* Diese Vorgehensweise ist komplex und setzt voraus, dass Sie über erweiterte ONTAP-Administrationsfähigkeiten verfügen. Sie sollten auch die link:guidelines_for_upgrading_controllers_with_arl.html["Richtlinien zum Upgraden von Controllern"] Und link:overview_of_the_arl_upgrade.html["ARL-Upgradesequenz"] bevor Sie mit dem Upgrade beginnen.
* Bei diesem Verfahren wird vorausgesetzt, dass die Ersatz-Controller-Hardware neu ist und nicht in einem anderen System verwendet wurde. Die erforderlichen Schritte zur Vorbereitung gebrauter Controller mit dem `wipeconfig` Befehl ist in dieser Prozedur nicht enthalten. Sie müssen sich an den technischen Support wenden, wenn die Ersatz-Controller-Hardware zuvor als Teil eines anderen ONTAP Clusters oder als Standalone-System mit einem einzelnen Node verwendet wurde.
* Sie können dieses Verfahren zum Upgrade der Controller Hardware in Clustern mit mehr als zwei Nodes verwenden. Sie müssen jedoch die Verfahren für jedes HA-Paar im Cluster separat durchführen.
* Wenn Sie über einen Switch verfügen, der von der ONTAP-Version und dem Ersatzsystem, auf das Sie aktualisieren, nicht unterstützt wird, finden Sie weitere Informationen unter link:other_references.html["Quellen"] Zum Verknüpfen mit der _Hardware Universe_.
* Die Systeme AFF A250 und AFF C250 nutzen integrierte 10/25-GbE-Ports für die Cluster-Verbindung. Um Switchless-Cluster mit zwei Knoten eines AFF A250- oder AFF C250-Systems auf ein AFF A50-, AFF A30-, AFF C60- oder AFF C30-System aufzurüsten, benötigen Sie eine X60132A, 4-Port 10/25-GbE-Karte in Steckplatz 1 auf beiden Knoten. Dadurch wird die Cluster-Verbindung für Cluster-LIFs zu einem temporären Port auf der Zielplattform hergestellt.
* Die Systeme AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60, AFF C80, FAS70 und FAS90 verwenden 100-GbE-Netzwerk-Ports sowohl für Cluster- als auch für HA-Verbindungen. Diese Systeme können 10-GbE- oder 25-GbE-Clusterverbindungen zu älteren Cluster-Switches unterstützen. NetApp empfiehlt jedoch ein Upgrade auf eine Clustergeschwindigkeit von 100 GbE, wenn die 10-GbE- und 25-GbE-Switches nicht mehr benötigt werden. Weitere Informationen finden Sie in den folgenden Knowledge Base-Artikeln:
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["Konfigurieren von 10G- oder 25G-Cluster-Ports bei einem neuen Cluster-Setup"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["Wie konvertiert man bestehende 10G- oder 25G-Cluster-Ports in 40G- oder 100G-Cluster-Ports"^]


--
+
Wenn Sie auf dem vorhandenen Node keine e0a oder e0b Cluster-Ports mit den Cluster-Ports auf dem neuen Node verknüpfen können, finden Sie weitere Informationen unter:

+
** link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp Bugs Online Fehler-ID CONTAP-166978"^]
** https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1127315["NetApp Bugs Online Fehler-ID 1127315"^]


* Die ASA Systeme A900, AFF A900 und FAS9500 unterstützen nur eine hohe Netzspannung (200 V bis 240 V). Wenn Ihr AFF A700 oder FAS9000 System mit niedriger Netzspannung (100 V bis 120 V) ausgeführt wird, müssen Sie vor diesem Verfahren die Eingangsspannung der AFF A700 oder FAS9000 konvertieren.
* Wenn Sie ein Upgrade eines vorhandenen Systems mit einer Ausfallzeit <<supported-systems-in-chassis,Unterstützte Systeme Matrix>>durchführen, die in enthalten ist, können Sie die Controller-Hardware durch Verschieben des Storage-Systems aktualisieren oder sich an den technischen Support wenden. Siehe link:other_references.html["Quellen"] Link zu _Upgrade by moving Volumes or Storage_.




== Automatisierung des Controller-Upgrades

Dieses Verfahren enthält die Schritte für das automatisierte Verfahren. Hierbei werden die automatische Festplattenzuordnung und die Überprüfung der Erreichbarkeit von Netzwerk-Ports verwendet, um das Upgrade des Controllers zu vereinfachen.
