---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install-aff-a30-a50-c30-c50-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: Installieren Sie die Ersatz-Systemmodule auf Node 2 während eines ARL-Upgrades von Controller-Modellen im selben Chassis. 
---
= Installieren Sie das AFF A30-, AFF A50-, AFF C30- oder AFF C60-Modul auf Knoten 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Installieren Sie das Ersatz-Controller-Modul, das Sie für das Upgrade auf Knoten2 erhalten haben. Knoten2 ist Controller B, der sich in der unteren Hälfte des Gehäuses befindet, wenn man von der Rückseite des Systems auf die Controller schaut.

.Schritte
. Positionieren Sie das Speichersystem auf den Schienen in der Mitte des Schranks oder des Telco-Racks, und stützen Sie das Speichersystem von unten ab, und schieben Sie es hinein.
+

NOTE: Setzen Sie das Controller-Modul erst dann vollständig in das Gehäuse ein, wenn Sie dazu später im Verfahren aufgefordert werden.

. Verkabeln Sie die Management- und Konsolen-Ports mit dem node2-Controller-Modul.
+

NOTE: Da das Gehäuse bereits eingeschaltet ist, startet Knoten 2 die BIOS-Initialisierung und anschließend den AUTOBOOT, sobald es vollständig eingesetzt ist.  Um den Bootvorgang von Node2 zu unterbrechen, wird empfohlen, vor dem vollständigen Einsetzen des Controllermoduls in den Steckplatz die seriellen Konsolen- und Verwaltungskabel an das Controllermodul von Node2 anzuschließen.

. Schieben Sie das Steuermodul bei geöffnetem Nockengriff fest hinein, bis es auf die Mittelplatine trifft und vollständig eingesetzt ist. Die Verriegelung steigt, wenn das Controller-Modul voll eingesetzt ist. Schließen Sie den Nockengriff in die verriegelte Position.
+

NOTE: Um eine Beschädigung der Anschlüsse zu vermeiden, sollten Sie beim Einschieben des Controller-Moduls in das Gehäuse keine übermäßige Kraft anwenden.

. Schließen Sie die serielle Konsole an, sobald das Modul sitzt, und seien Sie bereit, den AUTOBOOT von Knoten2 zu unterbrechen.
. Nachdem Sie DEN AUTOBOOT unterbrochen haben, wird node2 an der LOADER-Eingabeaufforderung angehalten. Wenn Sie das AUTOBOOT nicht rechtzeitig unterbrechen und node2 startet den Boot-Vorgang, warten Sie auf die Eingabeaufforderung und drücken Sie Strg-C, um zum Boot-Menü zu gelangen. Nachdem der Node im Boot-Menü angehalten wurde, verwenden Sie Option `8` , um den Node neu zu booten und DAS AUTOBOOT während des Neubootens zu unterbrechen.
. Legen Sie an der Eingabeaufforderung LOADER> von node2 die Standardumgebungsvariablen fest:
+
`set-defaults`

. Speichern Sie die Standardeinstellungen für Umgebungsvariablen:
+
`saveenv`

. Stellen Sie bei Switchless-Konfigurationen mit zwei Knoten sicher, dass Sie eine X60132A-Karte (4-Port 10/25 GbE) in Steckplatz 1 auf Knoten 2 installiert haben. Die X60132A-Karte wird während des Upgrades für die Clusterverbindung benötigt.

