---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install-asaa150-affa150-fas2820-on-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: Installieren Sie die Ersatz-Systemmodule auf Node 2 während eines ARL-Upgrades von Controller-Modellen im selben Chassis. 
---
= Installieren Sie das ASA A150, AFF A150 oder FAS2820 Controller-Modul auf Knoten2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Installieren Sie das ASA A150, AFF A150 oder FAS2820 Controller-Modul, das Sie für das Upgrade auf Knoten2 erhalten haben. Node2 ist Controller B auf der rechten Seite des Chassis, wenn man sich die Controller von der Rückseite des Systems ansieht.

.Bevor Sie beginnen
* Wenn du nicht bereits geerdet bist, beground dich richtig.
* Trennen Sie alle Kabel, einschließlich Konsole, Management, SAS Storage und Datennetzwerkkabel, vom entfernten Controller.


.Schritte
. Richten Sie das Ende des Controller-Moduls an Schacht B im Chassis aus, und drücken Sie dann vorsichtig das Controller-Modul zur Hälfte in das System.
+

TIP: Bay B befindet sich auf dem Chassis unten.

+

WARNING: Setzen Sie das Controller-Modul erst dann vollständig in das Chassis ein, wenn Sie dazu später beim Verfahren aufgefordert werden.

. Verkabeln Sie die Management- und Konsolen-Ports mit dem node2-Controller-Modul.
+

NOTE: Da das Chassis bereits eingeschaltet ist, startet node2, sobald es vollständig eingesetzt ist. Um das Booten von node2 zu vermeiden, empfiehlt NetApp, die Konsole und die Managementkabel an das node2-Controller-Modul anzuschließen, bevor Sie das Controller-Modul vollständig in den Steckplatz einsetzen.

. Drücken Sie das Controller-Modul fest in das Gehäuse, bis es auf die Mittelebene trifft und vollständig sitzt.
+
Die Verriegelung steigt, wenn das Controller-Modul voll eingesetzt ist.

+

NOTE: Um Schäden an den Anschlüssen zu vermeiden, sollten Sie beim Einschieben des Controller-Moduls in das Gehäuse keine übermäßige Kraft verwenden.

. Schließen Sie die serielle Konsole an, sobald das Modul eingesetzt ist und bereit ist, DEN AUTOSTART von node1 zu unterbrechen.
. Nachdem Sie DEN AUTOBOOT unterbrochen haben, wird node2 an der LOADER-Eingabeaufforderung angehalten. Wenn Sie das AUTOBOOT nicht rechtzeitig unterbrechen und node2 startet den Boot-Vorgang, warten Sie auf die Eingabeaufforderung und drücken Sie Strg-C, um zum Boot-Menü zu gelangen. Nachdem der Node im Boot-Menü angehalten wurde, verwenden Sie Option `8` , um den Node neu zu booten und DAS AUTOBOOT während des Neubootens zu unterbrechen.

