---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/manage_storage_encryption_using_okm.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: Storage Encryption konfigurieren und managen, Authentifizierungsschlüssel managen und die SnapMirror Beziehungen stilllegen, wenn Sie mit ARL ein Upgrade von Controller-Modellen im selben Chassis durchführen. 
---
= Management der Storage-Verschlüsselung mit dem Onboard Key Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können den Onboard Key Manager (OKM) zur Verwaltung der Schlüssel verwenden. Wenn Sie das OKM eingerichtet haben, müssen Sie die Passphrase und das Sicherungsmaterial aufzeichnen, bevor Sie mit dem Upgrade beginnen.

.Schritte
. Notieren Sie die Cluster-weite Passphrase.
+
Dies ist die Passphrase, die eingegeben wurde, als das OKM mit der CLI oder REST-API konfiguriert oder aktualisiert wurde.

. Sichern Sie die Key-Manager-Informationen, indem Sie den ausführen `security key-manager onboard show-backup` Befehl.




== Stilllegen der SnapMirror Beziehungen (optional)

Bevor Sie mit dem Verfahren fortfahren, müssen Sie bestätigen, dass alle SnapMirror Beziehungen stillgelegt werden. Wenn eine SnapMirror Beziehung stillgelegt wird, bleibt es bei einem Neustart und einem Failover stillgelegt.

.Schritte
. Überprüfen Sie den SnapMirror Beziehungsstatus auf dem Ziel-Cluster:
+
`snapmirror show`

+
[NOTE]
====
Wenn der Status „Übertragen“ lautet, müssen Sie diese Transfers abbrechen:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
Der Abbruch schlägt fehl, wenn sich die SnapMirror-Beziehung nicht im Zustand „Übertragen“ befindet.

. Alle Beziehungen zwischen dem Cluster stilllegen:
+
`snapmirror quiesce -destination-vserver *`


