---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/manage-authentication-using-kmip-servers.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: Storage Encryption konfigurieren und managen, Authentifizierungsschlüssel managen und die SnapMirror Beziehungen stilllegen, wenn Sie mit ARL ein Upgrade von Controller-Modellen im selben Chassis durchführen. 
---
= Authentifizierungsmanagement mit KMIP-Servern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ab ONTAP 9.10.1 können Sie KMIP-Server (Key Management Interoperability Protocol) verwenden, um Authentifizierungsschlüssel zu managen.

.Schritte
. Hinzufügen eines neuen Controllers:
+
`security key-manager external enable`

. Fügen Sie den Schlüsselmanager hinzu:
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server konfiguriert und für alle Nodes im Cluster verfügbar sind:
+
`security key-manager external show-status`

. Stellen Sie die Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern auf den neuen Knoten wieder her:
+
`security key-manager external restore -node _new_controller_name_`


