---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/move_non_root_aggr_and_nas_data_lifs_back_to_node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Vergewissern Sie sich, dass die NAS-Daten-LIFs auf Node 1 von Node 1 auf Node 2 verschoben werden, wenn Sie zum Upgrade von Controller-Modellen im selben Chassis ARL verwenden. 
---
= Verschieben Sie Aggregate und NAS-Daten-LIFs zurück auf node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachdem Sie die Netzwerkkonfiguration auf Node2 überprüft und bevor Sie Aggregate von Node1 zu Node2 verschieben, überprüfen Sie, ob die NAS-Daten-LIFs, die zu Node2 gehören, die sich derzeit auf Node1 befinden, von Node1 zu Node2 verschoben werden. Sie müssen außerdem überprüfen, ob die SAN LIFs auf Knoten2 vorhanden sind.

.Über diese Aufgabe
Remote-LIFs verarbeiten den Datenverkehr zu SAN-LUNs während des Upgrades. Das Verschieben von SAN-LIFs ist für den Zustand des Clusters oder des Service während des Upgrades nicht erforderlich. SAN LIFs werden nicht verschoben, es sei denn, sie müssen neuen Ports zugeordnet werden. Nachdem Sie node2 in den Online-Modus versetzt haben, müssen Sie überprüfen, ob sich die LIFs in einem ordnungsgemäßen Zustand und auf den entsprechenden Ports befinden.

.Schritte
. Wiederaufnahme des Betriebs der Versetzung:
+
`system controller replace resume`

+
Das System führt die folgenden Aufgaben aus:

+
--
** Cluster-Quorum-Prüfung
** System-ID-Prüfung
** Prüfung der Bildversion
** Überprüfung der Zielplattform
** Prüfung der Netzwerkanachabilität


--
+
Der Vorgang unterbricht in dieser Phase in der Überprüfung der Netzwerknachprüfbarkeit.

. Wiederaufnahme des Betriebs der Versetzung:
+
`system controller replace resume`

+
Das System führt folgende Prüfungen durch:

+
--
** Cluster-Zustandsprüfung
** LIF-Statusüberprüfung für Cluster


--
+
Nach Durchführung dieser Überprüfungen verlagert das System die nicht-Root-Aggregate und NAS-Daten-LIFs zurück auf node2, das jetzt auf dem Ersatz-Controller ausgeführt wird.

+
Der Controller-Ersatzvorgang hält nach Abschluss der Ressourcenverschiebung die Pause ein.

. Überprüfen Sie den Status der Aggregatverschiebung und der LIF-Verschiebung von NAS-Daten:
+
`system controller replace show-details`

+
Wenn der Austausch des Controllers unterbrochen wird, prüfen und korrigieren Sie den Fehler, falls zutreffend, und führen Sie das Problem anschließend aus `resume` Um den Vorgang fortzusetzen.

. Falls erforderlich, stellen Sie alle vertriebenen LIFs wieder her. Liste aller vertriebenen LIFs:
+
`cluster controller-replacement network displaced-interface show`

+
Wenn LIFs verschoben werden, stellen Sie den Home-Node wieder in node2 wieder her:

+
`cluster controller-replacement network displaced-interface restore-home-node`

. Setzen Sie den Vorgang fort, um das System zur Durchführung der erforderlichen Nachprüfungen zu auffordern:
+
`system controller replace resume`

+
Das System führt die folgenden Nachprüfungen durch:

+
** Cluster-Quorum-Prüfung
** Cluster-Zustandsprüfung
** Aggregatrekonstruktion
** Aggregatstatus-Prüfung
** Überprüfung des Festplattenstatus
** LIF-Statusüberprüfung für Cluster
** Lautstärkerprüfung



