---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/overview_of_the_arl_upgrade.html 
keywords: overview, arl, upgrade, owner, controller, hardware 
summary: Erfahren Sie, wie das Upgrade-Verfahren für den ARL-Controller von AFF A700 auf AFF A900 funktioniert. 
---
= Überblick über das ARL Upgrade
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie die Nodes mit ARL aktualisieren, sollten Sie unbedingt verstehen, wie das Verfahren funktioniert. In diesem Inhalt wird das Verfahren in mehrere Phasen unterteilt.



== Aktualisieren Sie das Node-Paar

Zum Upgrade des Node-Paars müssen Sie die ursprünglichen Nodes vorbereiten und dann für die ursprünglichen und die neuen Nodes eine Reihe von Schritten ausführen. Anschließend können Sie die ursprünglichen Knoten außer Betrieb nehmen.



== Übersicht über die ARL-Upgrade-Sequenz

Während des Verfahrens aktualisieren Sie die ursprüngliche Controller Hardware mit der Ersatz-Controller-Hardware, einem Controller gleichzeitig. Nutzen Sie die HA-Paar-Konfiguration, um das Eigentum von Aggregaten ohne Root-Berechtigungen zu verschieben. Alle Aggregate außerhalb der Root-Ebene müssen zwei Umlagerungen durchlaufen, um das endgültige Ziel zu erreichen, nämlich den korrekten aktualisierten Node.

Jedes Aggregat hat einen Hausbesitzer und aktuellen Eigentümer. Der Hausbesitzer ist der eigentliche Eigentümer des Aggregats, und der aktuelle Eigentümer ist der temporäre Eigentümer.

Die folgende Tabelle beschreibt die grundlegenden Aufgaben, die Sie in den einzelnen Phasen ausführen, und den Zustand der Aggregateigentümer am Ende der Phase. Detaillierte Schritte sind im weiteren Verlauf des Verfahrens aufgeführt:

[cols="35,65"]
|===
| Stufe | Schritte 


| link:stage_1_index.html["Phase 1: Upgrade vorbereiten"]  a| 
Während Phase 2 werden node1-Aggregate und NAS-Daten-LIFs in Knoten 2 verschoben. Dieser Prozess ist weitgehend automatisiert; der Vorgang hält an, damit Sie seinen Status überprüfen können. Sie müssen den Vorgang manuell fortsetzen. Bei Bedarf verschieben Sie fehlerhafte oder Vetos Aggregate. Sie müssen die erforderlichen Node1-Informationen zur Verwendung später im Verfahren aufzeichnen und anschließend die entsprechenden node1-Controller und NVRAM-Module austauschen, node1 ausmustern und den aktualisierten node1-Netzboot ausführen.

Gesamteigentum am Ende von Phase 1:

* Node1 ist der Hausbesitzer und der aktuelle Besitzer der node1 Aggregate
* Node2 ist der Hausbesitzer und der aktuelle Besitzer der node2 Aggregate




| link:stage_2_index.html["Phase 2: Verschieben von Ressourcen von Knoten1 und Ausmustern von AFF A700 oder FAS9000 Node1"]  a| 
Während Phase 2 werden node1-Aggregate und NAS-Daten-LIFs in Knoten 2 verschoben. Dieser Prozess ist weitgehend automatisiert; der Vorgang hält an, damit Sie seinen Status überprüfen können. Sie müssen den Vorgang manuell fortsetzen. Bei Bedarf verschieben Sie fehlerhafte oder Vetos Aggregate. Sie erfassen Node1-Informationen für die spätere Verwendung im Verfahren vor dem Ausscheiden von node1. Sie können sich auch später beim Verfahren auf den Netzboot node1 vorbereiten.

Gesamteigentum am Ende von Phase 2:

* Node2 ist der aktuelle Besitzer von node1 Aggregaten
* Node2 ist der Hausbesitzer und der aktuelle Besitzer von node2 Aggregaten




| link:stage_3_index.html["Phase 3: Boot-Node1 mit dem AFF A900 oder FAS9500 Controller und NVRAM-Modulen"]  a| 
In Phase 3 booten Sie Node1 mit aktualisierten Controller- und NVRAM-Modulen und überprüfen die aktualisierte Node1-Installation. Wenn Sie NetApp Volume Encryption (NVE) verwenden, stellen Sie die Konfiguration des Schlüsselmanagers wieder her. Außerdem werden node1 Aggregate und NAS-Daten-LIFs von node2 auf die aktualisierte Node1 verschoben und Sie überprüfen, ob die SAN-LIFs auf node1 vorhanden sind.

Gesamteigentum am Ende von Stufe 3:

* Aktualisiertes AFF A900 oder FAS9500 Node1 ist der Eigentümer und aktueller Besitzer von Node1 Aggregaten
* Node2 ist der Hausbesitzer und der aktuelle Besitzer von node2 Aggregaten




| link:stage_4_index.html["Phase 4: Verlagerung von Ressourcen von node2 und Ausmustern node2"]  a| 
Während Phase 4 verschieben Sie Aggregate und NAS-Daten-LIFs von Knoten 2 auf die aktualisierte Knoten 1 und Mustern Knoten 2 aus.

Gesamteigentum am Ende von Stufe 4:

* Der aktualisierte Knoten 1 ist der Hausbesitzer und der aktuelle Besitzer von Aggregaten, die ursprünglich zu node1 gehörten
* Der aktualisierte Knoten 1 ist der aktuelle Besitzer von node2 Aggregaten




| link:stage_5_index.html["Phase 5: Installieren Sie die NVRAM- und Controller-Module AFF A900 oder FAS9500 auf node2"]  a| 
In Phase 5 installieren Sie die neuen NVRAM- und Controller-Module, die Sie für den aktualisierten Node2 erhalten haben, und anschließend als Netzboot node2.

Gesamteigentum am Ende von Stufe 5:

* Der aktualisierte Node1 ist der Hausbesitzer und der aktuelle Besitzer der Aggregate, die ursprünglich zu node1 gehörten.
* Upgrade node2 ist der Hausbesitzer und der aktuelle Besitzer von Aggregaten, die ursprünglich zu node2 gehörten.




| link:stage_6_index.html["Phase 6: Boot-Node2 mit dem AFF A900 oder FAS9500 Controller und NVRAM-Modulen"]  a| 
In Phase 6 booten Sie Node2 mit aktualisierten Controller- und NVRAM-Modulen und überprüfen die Upgrade-Installation node2. Wenn Sie NVE verwenden, stellen Sie die Konfiguration für Schlüsselmanager wieder her. Außerdem werden node1-Aggregate und NAS-Daten-LIFs von node1 auf die aktualisierte Node2 verschoben und Sie überprüfen, ob die SAN-LIFs auf node2 vorhanden sind.



| link:stage_7_index.html["Phase 7: Das Upgrade abschließen"]  a| 
In Phase 7 bestätigen Sie, dass die neuen Nodes korrekt eingerichtet wurden. Und wenn die neuen Nodes verschlüsselt sind, konfigurieren und einrichten Sie Storage Encryption oder NVE. Zudem sollten die alten Nodes außer Betrieb gesetzt und der SnapMirror Betrieb fortgesetzt werden.

|===