---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/relocate_non_root_aggr_nas_lifs_from_node2_to_node1.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node1, NVRAM, controller, module, modules 
summary: Verschieben Sie die nicht-Root-Aggregate von Node 2 in Node 1, wenn Sie Controller-Modelle im selben Chassis mit ARL aktualisieren. 
---
= Verschieben von Aggregaten ohne Root-Wurzeln und NAS-Daten-LIFs von Knoten 2 auf Knoten 1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie Knoten 2 durch das Ersatz-Systemmodul ersetzen können, müssen Sie zunächst die nicht-Root-Aggregate, die im Besitz von Knoten 2 sind, in Knoten 1 verschieben.

.Bevor Sie beginnen
Nach den Nachprüfungen aus der vorherigen Phase wird automatisch die Ressourcenfreigabe für node2 gestartet. Die Aggregate außerhalb des Root-Bereichs und LIFs für nicht-SAN-Daten werden von node2 in die neue Knoten1 migriert.

.Über diese Aufgabe
Nach der Migration der Aggregate und LIFs wird der Vorgang zu Verifizierungszwecken angehalten. An dieser Phase müssen Sie überprüfen, ob alle Aggregate ohne Root-Root-Daten und LIFs außerhalb des SAN in die neue Knoten1 migriert werden.

Der Home-Inhaber für die Aggregate und LIFs werden nicht geändert, nur der aktuelle Besitzer wird geändert.

.Schritte
. Vergewissern Sie sich, dass alle nicht-Root-Aggregate online sind und ihren Status auf node1:
+
`storage aggregate show -node node1 -state online -root false`

+
Das folgende Beispiel zeigt, dass die nicht-Root-Aggregate auf node1 online sind:

+
[listing]
----
cluster::> storage aggregate show -node node1 state online -root false

Aggregate     Size        Available   Used%   State	  #Vols	 Nodes	 RAID	  Status
----------    ---------   ---------   ------  -----   -----  ------  -------  ------
aggr_1	      744.9GB     744.8GB	  0%	  online	  5	 node1   raid_dp  normal
aggr_2	      825.0GB	  825.0GB	  0%	  online	  1	 node1   raid_dp  normal
2 entries were displayed.
----
+
Wenn die Aggregate offline gegangen sind oder in node1 fremd geworden sind, stellen Sie sie mit dem folgenden Befehl auf der neuen node1, einmal für jedes Aggregat online:

+
`storage aggregate online -aggregate _aggr_name_`

. Überprüfen Sie, ob alle Volumes auf node1 online sind, indem Sie den folgenden Befehl auf node1 verwenden und seine Ausgabe überprüfen:
+
`volume show -node node1 -state offline`

+
Wenn ein Volume auf node1 offline ist, stellen Sie sie mit dem folgenden Befehl auf node1 für jedes Volume online:

+
`volume online -vserver _vserver-name_ -volume _volume-name_`

+
Der `_vserver-name_` Die Verwendung mit diesem Befehl ist in der Ausgabe des vorherigen gefunden `volume show` Befehl.

. Überprüfen Sie, ob die LIFs zu den richtigen Ports verschoben wurden und über den Status von verfügen `up`. Wenn irgendwelche LIFs ausgefallen sind, setzen Sie den Administratorstatus der LIFs auf `up` Geben Sie den folgenden Befehl ein, einmal für jede LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _nodename_ - status-admin up`

. Überprüfen Sie, ob auf node2 keine Daten-LIFs mehr vorhanden sind, indem Sie den folgenden Befehl verwenden und die Ausgabe überprüfen:
+
`network interface show -curr-node _node2_ -role data`


