---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/restore_key_manager_config_upgraded_node1.html 
keywords: restore key-manager, configuration, node1, nve, arl, volume, encryption 
summary: Falls erforderlich, stellen Sie die Key-Manager-Konfiguration auf dem aktualisierten Node1 während eines AFF A700 auf ein AFF A900-Upgrade wieder her. 
---
= Stellen Sie die Key-Manager-Konfiguration auf dem aktualisierten Node1 wieder her
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie NetApp Aggregate Encryption (NAE) oder NetApp Volume Encryption (NVE) zur Verschlüsselung von Volumes auf dem System verwenden, das Sie aktualisieren, muss die Verschlüsselungskonfiguration mit den neuen Nodes synchronisiert werden. Wenn Sie den Schlüsselmanager nicht neu synchronisieren, wenn Sie die node1-Aggregate mithilfe von ARL von node2 zur aktualisierten node1 verschieben, können Ausfälle auftreten, da node1 nicht über die erforderlichen Schlüssel zum Online-Zugriff verschlüsselter Volumes und Aggregate verfügt.

.Über diese Aufgabe
Die Verschlüsselungskonfiguration mit den neuen Nodes synchronisieren, indem Sie die folgenden Schritte durchführen:

.Schritte
. Führen Sie den folgenden Befehl aus node1:
+
`security key-manager onboard sync`

. Überprüfen Sie, ob der SVM-KEK-Schlüssel auf „true“ in node1 wiederhergestellt wird, bevor Sie die Datenaggregate verschieben:
+
[listing]
----
::> security key-manager key query -node node1 -fields restored -key-type SVM-KEK
----
+
.Beispiel
[listing]
----
::> security key-manager key query -node node1 -fields restored -key-type SVM-KEK

node     vserver   key-server   key-id                                  restored
-------- --------- -----------  --------------------------------------- --------
node1    svm1      ""           00000000000000000200000000000a008a81976 true
                                2190178f9350e071fbb90f00000000000000000
----

