---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/set_up_netapp_volume_encryption_new_module.html 
keywords: set up, netapp volume encryption, controller, module, nve, node 
summary: Konfigurieren Sie bei Bedarf das neue Controller-Modul für NVE oder NAE bei einem Upgrade von Controller-Modellen im selben Chassis durch ARL.“ 
---
= Einrichtung von NetApp Volume oder Aggregate Encryption auf dem neuen Controller-Modul
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn der ersetzte Controller oder der HA-Partner (High Availability, Hochverfügbarkeit) des neuen Controllers NetApp Volume Encryption (NVE) oder NetApp Aggregate Encryption (NAE) verwendet, muss das neue Controller-Modul für NVE oder NAE konfiguriert werden.

.Über diese Aufgabe
Dieses Verfahren umfasst Schritte, die auf dem neuen Controller-Modul ausgeführt werden. Sie müssen den Befehl auf dem richtigen Node eingeben.

[role="tabbed-block"]
====
.Onboard Key Manager
--
Konfigurieren Sie NVE oder NAE mit dem Onboard Key Manager.

.Schritte
. Stellen Sie Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern mit dem neuen Knoten wieder her:
+
`security key-manager onboard sync`



--
.Externes Verschlüsselungsmanagement
--
Konfigurieren Sie NVE oder NAE mit externem Verschlüsselungsmanagement.

.Schritte
. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server weiterhin verfügbar sind, deren Status und ihre Authentifizierungsdaten folgendermaßen sind:
+
`security key-manager key query -node node`

. Fügen Sie die im vorherigen Schritt aufgeführten Verschlüsselungsmanagement-Server der Liste des zentralen Management-Servers des neuen Controllers hinzu:
+
.. Fügen Sie den Schlüsselverwaltungsserver hinzu:
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

.. Wiederholen Sie den vorherigen Schritt für jeden aufgeführten Key Management Server. Sie können bis zu vier Verschlüsselungsmanagement-Server verknüpfen.
.. Überprüfen Sie, ob die Verschlüsselungsmanagementserver erfolgreich hinzugefügt wurden:
+
`security key-manager external show`



. Führen Sie auf dem neuen Controller-Modul den Setup-Assistenten für das Verschlüsselungsmanagement aus, um die wichtigsten Management-Server einzurichten und zu installieren.
+
Sie müssen dieselben Key Management-Server installieren, die auf dem vorhandenen Controller-Modul installiert sind.

+
.. Starten Sie den Setup-Assistenten für den Schlüsselmanagementserver auf dem neuen Knoten:
+
`security key-manager external enable`

.. Führen Sie die Schritte im Assistenten zum Konfigurieren von Verschlüsselungsmanagementservern durch.


. Stellen Sie Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern mit dem neuen Knoten wieder her:
+
`security key-manager external restore`

+
Für diesen Befehl ist die OKM-Passphrase erforderlich

+
Weitere Informationen finden Sie im Knowledge Base-Artikel https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["So stellen Sie die Konfiguration des externen Schlüsselmanager-Servers aus dem ONTAP-Startmenü wieder her"^].



--
====
.Nachdem Sie fertig sind
Überprüfen Sie, ob Volumes offline geschaltet wurden, da Authentifizierungsschlüssel nicht verfügbar waren oder EKM-Server nicht erreicht werden konnten. Stellen Sie diese Volumes mithilfe der wieder online `volume online` Befehl.

.Nachdem Sie fertig sind
Überprüfen Sie, ob Volumes offline geschaltet wurden, da Authentifizierungsschlüssel nicht verfügbar waren oder externe Schlüsselverwaltungsserver nicht erreicht werden konnten. Bringen Sie diese Volumes wieder online, indem Sie die  `volume online` Befehl.
