---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_3_index.html 
keywords: upgrade, boot, node1, verify, restore, overview, stage 3 
summary: 'Phase 3 Prozessablauf für ein ARL-Upgrade mit `system controller replace` Befehle zum Upgrade von Controller-Modellen in demselben Chassis.' 
---
= Phase-3-Übersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Phase 3 verbinden Sie die gemeinsam genutzten Cluster-HA- und Speicherverbindungen für die externen Shelfs, falls vorhanden, starten Sie Knoten 1 mit den aktualisierten Systemmodulen und überprüfen Sie die aktualisierte Installation von Knoten 1. Wenn Sie NetApp Volume Encryption (NVE) verwenden, stellen Sie die Konfiguration des Schlüsselmanagers wieder her. Außerdem werden node1 Aggregate und NAS-Daten-LIFs von node2 auf die aktualisierte Node1 verschoben und Sie überprüfen, ob die SAN-LIFs auf node1 vorhanden sind.

.Schritte
. link:cable-node1-for-shared-cluster-HA-storage.html["Kabelnode1 für Shared Cluster-HA-Storage (nur AFF A800 Upgrade)"]
. link:boot_node1_with_a900_controller_and_nvs.html["Starten Sie Knoten 1 mit den Ersatz-Systemmodulen"]
. link:verify_node1_installation.html["Überprüfen Sie die Installation node1"]
. link:restore_key_manager_config_upgraded_node1.html["Stellen Sie die Key-Manager-Konfiguration auf dem aktualisierten Node1 wieder her"]
. link:move_non_root_aggr_nas_lifs_node1_from_node2_to_upgraded_node1.html["Verschieben Sie Aggregate und NAS-Daten-LIFs, die sich im Besitz von Knoten1 befinden, von Knoten 2 auf die aktualisierte Knoten 1"]

