---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_3_index.html 
keywords: upgrade, preparing, preparation, prepare, overview, stage 1 
summary: 'Phase 1-Prozessreihenfolge für ein ARL-Upgrade mit `system controller replace` Befehle auf Controllern mit ONTAP 9.8 oder höher.' 
---
= Phase 3: Boot-Node1 mit dem AFF A900 oder FAS9500 Controller und NVRAM-Modulen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Phase 3 booten Sie Node1 mit aktualisierten Controller- und NVRAM-Modulen und überprüfen die aktualisierte Node1-Installation. Wenn Sie NetApp Volume Encryption (NVE) verwenden, stellen Sie die Konfiguration des Schlüsselmanagers wieder her. Außerdem werden node1 Aggregate und NAS-Daten-LIFs von node2 auf die aktualisierte Node1 verschoben und Sie überprüfen, ob die SAN-LIFs auf node1 vorhanden sind.

.Schritte
. link:boot_node1_with_a900_controller_and_nvs.html["Boot-Node1 mit dem AFF A900 oder FAS9500 Controller und NVRAM-Modulen"]
. link:verify_node1_installation.html["Überprüfen Sie die Installation node1"]
. link:restore_key_manager_config_upgraded_node1.html["Stellen Sie die Key-Manager-Konfiguration auf dem aktualisierten Node1 wieder her"]
. link:move_non_root_aggr_nas_lifs_node1_from_node2_to_upgraded_node1.html["Verschieben Sie Aggregate und NAS-Daten-LIFs, die sich im Besitz von Knoten1 befinden, von Knoten 2 auf die aktualisierte Knoten 1"]

