---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_node1_installation.html 
keywords: verifying, verify, node1, install, installation, NVRAM, controller, module, modules 
summary: Überprüfen Sie die Node-1-Installation zusammen mit den Ersatzmodulen, wenn Sie mit ARL Controller-Modelle im gleichen Chassis aktualisieren. 
---
= Überprüfen Sie die Installation node1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachdem Sie node1 mit dem Ersatz-Controller-Modul gestartet haben, überprüfen Sie, ob es richtig installiert ist.

Nur bei AFF A800-Upgrades weisen Sie die physischen Ports des vorhandenen Knoten1 dem Ersatznode1 zu, da sich die physischen Ports zwischen der AFF A800 und dem AFF A90- oder AFF A70-Controller ändern.

Bei allen anderen Upgrades werden die physischen Ports nicht geändert, sodass Sie die physischen Ports des alten Knoten1 nicht dem Ersatznode1 zuordnen müssen.

.Über diese Aufgabe
Sie müssen warten, bis Knoten 1 dem Quorum beitreten und dann den Controller-Austauschvorgang fortsetzen.

An diesem Punkt in der Prozedur sollte der Upgrade-Vorgang des Controllers angehalten sein, da node1 versucht hat, Quorum automatisch beizutreten.

.Schritte
. Vergewissern Sie sich, dass node1 dem Quorum beigetreten ist:
+
`cluster show -node node1 -fields health`

+
Die Ausgabe des `health` Feld muss sein `true`.

. Vergewissern Sie sich, dass node1 Teil desselben Clusters wie node2 ist und dass er sich in einem ordnungsgemäßen Zustand befindet:
+
`cluster show`

+
[NOTE]
====
Wenn node1 nach dem Booten noch nicht dem Quorum beigetreten ist, warten Sie fünf Minuten, und überprüfen Sie es erneut. Je nach Cluster-Verbindung kann es einige Zeit dauern, bis der Scan der Erreichbarkeit von Ports abgeschlossen und LIFs an die jeweiligen Home Ports verschoben werden.

Wenn node1 nach fünf Minuten immer noch nicht im Quorum ist, können Sie den Cluster-Port des neuen Knotens ändern, indem Sie ihn mit dem Diagnoseberechtigungsbefehl in „Cluster ipspace“ platzieren `network port modify <port_name> -ipspace Cluster`.

====
. Wechseln in den erweiterten Berechtigungsmodus:
+
`set advanced`

. Überprüfen Sie den Status des Controller-Austauschvorgangs und vergewissern Sie sich, dass er sich in einem Pause-Zustand befindet und sich im gleichen Zustand wie zuvor in node1 befand, um die physischen Aufgaben beim Installieren neuer Controller und Verschieben von Kabeln auszuführen:
+
`system controller replace show`

+
`system controller replace show-details`

. Setzen Sie den Austausch des Controllers wieder ein:
+
`system controller replace resume`

. Der Controller-Ersatzvorgang hält für Eingriffe mit der folgenden Meldung an:
+
[listing]
----
Cluster::*> system controller replace show
Node          Status                       Error-Action
------------  ------------------------     ------------------------------------
Node1         Paused-for-intervention      Follow the instructions given in
                                           Step Details
Node2         None

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes:


1. Re-create the interface group, if needed, before restoring VLANs. For detailed commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast domains" section of the upgrade controller hardware guide for the ONTAP version running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show" to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
----
+

NOTE: In diesem Verfahren wurde Abschnitt _Neuerstellen von VLANs, ifgrps und Broadcast-Domänen_ unter node1_ umbenannt.

. Wenn sich der Controller-Austausch im Status „Pause“ befindet, fahren Sie mit fort <<Stellen Sie die Netzwerkkonfiguration auf node1 wieder her>>.




== Stellen Sie die Netzwerkkonfiguration auf node1 wieder her

Nachdem Sie bestätigt haben, dass node1 sich im Quorum befindet und mit node2 kommunizieren kann, überprüfen Sie, dass node1 VLANs, Interface Groups und Broadcast-Domains auf node1 gesehen werden. Überprüfen Sie außerdem, ob alle node1-Netzwerk-Ports in ihren richtigen Broadcast-Domänen konfiguriert sind.

.Über diese Aufgabe
Weitere Informationen zum Erstellen und Neuerstellen von VLANs, Schnittstellengruppen und Broadcast-Domänen finden Sie unter link:other_references.html["Quellen"] Zum Verknüpfen mit dem Inhalt _Network Management_.

.Schritte
. Listen Sie alle physischen Ports auf, die auf Upgrade-Knoten1 stehen:
+
`network port show -node node1`

+
Alle physischen Netzwerk-Ports, VLAN-Ports und Schnittstellen-Gruppen-Ports auf dem Node werden angezeigt. In dieser Ausgabe sehen Sie alle physischen Ports, die in verschoben wurden `Cluster` Broadcast-Domäne von ONTAP Sie können diese Ausgabe verwenden, um die Entscheidung zu erleichtern, welche Ports als Ports für Schnittstellengruppen, als VLAN-Basis-Ports oder als eigenständige physische Ports zum Hosten von LIFs verwendet werden sollten.

. Liste der Broadcast-Domänen auf dem Cluster:
+
`network port broadcast-domain show`

. Die Erreichbarkeit des Netzwerkports aller Ports auf node1 auflisten:
+
`network port reachability show -node node1`

+
Die Ausgabe sollte wie im folgenden Beispiel angezeigt werden:

+
[listing]
----
Cluster::> reachability show -node node1
  (network port reachability show)
Node      Port     Expected Reachability                Reachability Status
--------- -------- ------------------------------------ ---------------------
Node1
          a0a      Default:Default                      ok
          a0a-822  Default:822                          ok
          a0a-823  Default:823                          ok
          e0M      Default:Mgmt                         ok
          e1a      Cluster:Cluster                      ok
          e1b      -                                    no-reachability
          e2a      -                                    no-reachability
          e2b      -                                    no-reachability
          e3a      -                                    no-reachability
          e3b      -                                    no-reachability
          e7a      Cluster:Cluster                      ok
          e7b      -                                    no-reachability
          e9a      Default:Default                      ok
          e9a-822  Default:822                          ok
          e9a-823  Default:823                          ok
          e9b      Default:Default                      ok
          e9b-822  Default:822                          ok
          e9b-823  Default:823                          ok
          e9c      Default:Default                      ok
          e9d      Default:Default                      ok
20 entries were displayed.
----
+
In den vorhergehenden Beispielen wurde node1 nach dem Austausch des Controllers gestartet. Die Ports, die „nicht-Erreichbarkeit“ anzeigen, verfügen über keine physische Verbindung. Sie müssen alle Ports mit einem anderen Status als reparieren `ok`.

+

NOTE: Während des Upgrades sollten sich die Netzwerkports und ihre Konnektivität nicht ändern. Alle Ports sollten sich in den richtigen Broadcast-Domänen befinden, und die Erreichbarkeit des Netzwerkports sollte sich nicht ändern. Bevor Sie jedoch LIFs von node2 zurück auf node1 verschieben, müssen Sie die Erreichbarkeit und den Integritätsstatus der Netzwerk-Ports überprüfen.

. [[restore_node1_stee4]]Reparieren Sie die Erreichbarkeit für jeden Port auf node1 mit einem anderen Status als der Erreichbarkeit `ok` Mit dem folgenden Befehl in der folgenden Reihenfolge:
+
`network port reachability repair -node _node_name_  -port _port_name_`

+
--
.. Physische Ports
.. VLAN-Ports


--
+
Die Ausgabe sollte wie im folgenden Beispiel angezeigt werden:

+
[listing]
----
Cluster ::> reachability repair -node node1 -port e1b
----
+
[listing]
----
Warning: Repairing port "node1:e1b" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
+
Eine Warnmeldung, wie im vorhergehenden Beispiel dargestellt, wird für Ports mit einem Wiederanmeldungs-Status erwartet, die sich vom Status der Erreichbarkeit der Broadcast-Domäne unterscheiden können, in der sie sich derzeit befindet. Überprüfen Sie die Verbindung des Ports und die Antwort `y` Oder `n` Je nach Bedarf.

+
Überprüfen Sie, ob alle physischen Ports die erwartete Erreichbarkeit haben:

+
`network port reachability show`

+
Während die Reparatur der Erreichbarkeit durchgeführt wird, versucht ONTAP, die Ports in die richtigen Broadcast-Domänen zu platzieren. Wenn jedoch die Erreichbarkeit eines Ports nicht ermittelt werden kann und keiner der bestehenden Broadcast-Domänen angehört, wird ONTAP neue Broadcast-Domains für diese Ports erstellen.

. Überprüfen der Port-Erreichbarkeit:
+
`network port reachability show`

+
Wenn alle Ports korrekt konfiguriert und den richtigen Broadcast-Domänen hinzugefügt wurden, wird das angezeigt `network port reachability show` Der Befehl sollte den Status der Erreichbarkeit als melden `ok` Für alle verbundenen Ports und den Status als `no-reachability` Für Ports ohne physische Konnektivität. Wenn ein Port einen anderen Status als diese beiden meldet, führen Sie die Reparatur der Nachweisbarkeit durch und fügen Sie Ports aus ihren Broadcast-Domänen hinzu oder entfernen Sie sie gemäß Anweisungen in <<restore_node1_step4,Schritt 4>>.

. Vergewissern Sie sich, dass alle Ports in Broadcast-Domänen platziert wurden:
+
`network port show`

. Vergewissern Sie sich, dass alle Ports in den Broadcast-Domänen die richtige MTU (Maximum Transmission Unit) konfiguriert haben:
+
`network port broadcast-domain show`

. Stellen Sie die LIF-Home-Ports wieder her und geben Sie ggf. den Vserver und die LIF-Home-Ports an, die Sie mit folgenden Schritten wiederherstellen müssen:
+
.. Führen Sie alle vertriebenen LIFs auf:
+
`displaced-interface show`

.. LIF-Home-Knoten und Home-Ports wiederherstellen:
+
`displaced-interface restore-home-node -node _node_name_ -vserver _vserver_name_ -lif-name _LIF_name_`



. Überprüfen Sie, ob alle LIFs einen Home Port haben und administrativ höher sind:
+
`network interface show -fields home-port,status-admin`


