---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_upgrade_hardware.html 
keywords: nodes, upgrade, verify, hardware 
summary: Vergewissern Sie sich vor Beginn des Upgrades, dass Sie über die richtige Hardware verfügen, um Controller-Modelle in demselben Chassis zu aktualisieren. 
---
= Überprüfen Sie die Upgrade-Hardware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vergewissern Sie sich vor dem Upgrade, dass Sie die richtige Hardware für das Upgrade haben. Je nach Upgrade müssen Sie für jedes upgradeende HA-Paar zwei Controller-Module oder zwei Controller-Module und zwei NVRAM-Module für das Ersatzsystem besitzen. Sollten Teile fehlen, wenden Sie sich an den technischen Support oder an Ihren NetApp Ansprechpartner.

[cols="50,50"]
|===
| Wenn Sie ein Upgrade ... | Ersatzsystem muss ... 


| AFF A800 | Zwei Controller-Module, zwei NVRAMs und neue I/O-Module 


| AFF A220 als ASA auf ASA A150 konfiguriert | Zwei Controller-Module 


| AFF A220, AFF A200 oder AFF C190 auf AFF A150 | Zwei Controller-Module 


| FAS2720 oder FAS2720 zu FAS2720 | Zwei Controller-Module 


| AFF A700 als ASA zu ASA A900 konfiguriert | Zwei Controller und zwei NVRAM-Module 


| AFF A700 AUF AFF A900 | Zwei Controller und zwei NVRAM-Module 


| FAS9000 auf FAS9500 Systeme | Zwei Controller und zwei NVRAM-Module 
|===