---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_upgrade_hardware.html 
keywords: nodes, upgrade, verify, hardware 
summary: Vergewissern Sie sich vor Beginn des Upgrades, dass Sie über die richtige Hardware verfügen, um Controller-Modelle in demselben Chassis zu aktualisieren. 
---
= Überprüfen Sie die Upgrade-Hardware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vergewissern Sie sich vor dem Upgrade, dass Sie über die richtigen Module für das Ersatzsystem verfügen. Sollten Teile fehlen, wenden Sie sich an den technischen Support oder an Ihren NetApp Ansprechpartner.

[cols="50,50"]
|===
| Wenn Sie ein Upgrade von ... | Ersatzsystem muss ... 


| AFF A250, AFF C250 | Zwei Controller-Module und neue I/O-Module 


| AFF A800, AFF C800 | Zwei Controller-Module, zwei NVRAMs und neue I/O-Module 


 a| 
* AFF A220 als ASA konfiguriert
* AFF A220, AFF A200, AFF C190
* FAS2620, FAS2720

 a| 
Zwei Controller-Module

Wenn Sie das bestehende System in ein Storage Shelf konvertieren, sodass Sie es an ein anderes System anschließen können, muss das Ersatzsystem auch über zwei I/O-Module verfügen.



 a| 
* AFF A700 – als ASA konfiguriert
* AFF A700
* FAS9000

| Zwei Controller und zwei NVRAM-Module 
|===