---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/index.html 
keywords: controller, aggregate, relocation, manual, upgrade, metrocluster 
summary: Mithilfe des manuellen ARL-Upgrade-Verfahrens für ein Upgrade der Controller-Hardware mit ONTAP 9.8 oder höher; die Eigentümerschaft von Aggregaten außerhalb der Root-Ebene wird verschoben. 
---
= Erfahren Sie mehr über dieses ARL-Upgradeverfahren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Dieses Verfahren beschreibt, wie Sie die Controller-Hardware mithilfe der manuellen Aggregatverlagerung (ARL) auf Systemen mit ONTAP 9.8 oder höher aktualisieren.

Sie können dieses ARL-Verfahren verwenden, wenn Sie eines der folgenden Upgrades durchführen:

* FAS System zu FAS System
* AFF System zu AFF System
+
Sie können nur ein Upgrade auf ein Ersatzsystem derselben Serie durchführen:

+
** System der AFF A-Series auf einem System der AFF A-Series
** System der AFF C-Serie auf ein System der AFF C-Serie übertragen


* ASA System zu ASA System
+
ASA-Upgrades auf ein ASA r2-Ersatzsystem werden nicht unterstützt. Informationen zur Migration von Daten von ASA auf ASA r2 finden Sie unter link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html["Aktivieren Sie den Datenzugriff von SAN-Hosts auf Ihr ASA r2 Storage-System"^].

+
Sie können nur ein Upgrade auf ein Ersatzsystem derselben Serie durchführen:

+
** System der ASA A-Series auf einem System der ASA A-Series
** System der ASA C-Serie auf ein System der ASA C-Serie übertragen




Während des Verfahrens führen Sie ein Upgrade der ursprünglichen Controller Hardware mit der Ersatz-Controller-Hardware durch. Hierbei werden die Eigentumsrechte an Aggregaten verschoben, die nicht mit Root-Berechtigungen verbunden sind. Sie migrieren Aggregate mehrmals von Node zu Node, um zu bestätigen, dass mindestens ein Node während des Upgrades Daten von den Aggregaten bereitstellt. Außerdem migrieren Sie Daten-logische Schnittstellen (LIFs) und weisen Sie die Netzwerk-Ports auf dem neuen Controller den Schnittstellengruppen zu, während Sie fortfahren.


NOTE: In diesem Dokument werden die ursprünglichen Knoten als _node1_ und _node2_ und die neuen Knoten als _node3_ und _node4_ bezeichnet.  Während des beschriebenen Vorgangs wird Knoten1 durch Knoten3 und Knoten2 durch Knoten4 ersetzt.  Die Begriffe _Knoten1_, _Knoten2_, _Knoten3_ und _Knoten4_ werden nur verwendet, um zwischen den ursprünglichen und neuen Knoten zu unterscheiden.  Wenn Sie das Verfahren befolgen, müssen Sie die tatsächlichen Namen Ihrer ursprünglichen und neuen Knoten ersetzen.  In Wirklichkeit ändern sich die Namen der Knoten jedoch nicht: Knoten3 hat den Namen Knoten1 und Knoten4 den Namen Knoten2, nachdem die Controller-Hardware aktualisiert wurde.

.Wichtige Informationen:
* Diese Vorgehensweise ist komplex und setzt voraus, dass Sie über erweiterte ONTAP-Administrationsfähigkeiten verfügen. Sie müssen außerdem die link:guidelines_upgrade_with_arl.html["Richtlinien zum Upgraden von Controllern mit ARL"] und die link:arl_upgrade_workflow.html["ARL Upgrade-Workflow"] bevor Sie mit dem Upgrade beginnen.
* Bei dieser Vorgehensweise wird vorausgesetzt, dass die Ersatz-Controller-Hardware neu ist und nicht verwendet wurde. Die erforderlichen Schritte zur Vorbereitung gebrauter Controller mit dem `wipeconfig` Befehl ist in dieser Prozedur nicht enthalten. Wenn bereits die Ersatz-Controller-Hardware verwendet wurde, müssen Sie sich an den technischen Support wenden, insbesondere wenn auf den Controllern Data ONTAP in 7-Mode ausgeführt wurde.
* Mit diesem Verfahren können Sie die Controller-Hardware in Clustern mit mehr als zwei Nodes aktualisieren. Sie müssen jedoch für jedes Hochverfügbarkeitspaar (HA) im Cluster separat vorgehen.


* Neben Konfigurationen, die nicht von MetroCluster stammen, gilt dieses Verfahren für Fabric MetroCluster Konfigurationen mit vier und acht Nodes mit ONTAP 9.8 und höher.
+
** Weitere Informationen zu MetroCluster Konfigurationen mit ONTAP 9.7 und früher finden Sie unter link:other_references.html["Quellen"] Verbinden mit _Aggregat-Verlagerung verwenden, um manuell ein Upgrade der Controller-Hardware mit ONTAP 9.7 oder früher_ durchzuführen.
** Weitere Upgrade-Optionen für MetroCluster IP-Konfigurationen und zusätzliche Upgrade-Optionen für Fabric-MetroCluster-Konfigurationen finden Sie unter link:other_references.html["Quellen"] Zum Verlinken auf den Inhalt _MetroCluster Upgrade und Expansion_.



