---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/install_boot_node4.html 
keywords: node4, install ONTAP, boot, node4, relocate, non-root aggregates, disks 
summary: installieren und booten sie node4 und installieren Sie die ONTAP Software während eines manuellen ARL Upgrades auf Controllern mit ONTAP 9.8 oder höher. 
---
= installieren und booten sie node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
sie müssen node4 im Rack installieren, Node2-Verbindungen zu node4 übertragen und node4 booten. Sie müssen auch node2-Spares, alle Festplatten der Root-Partition und alle nicht-Root-Aggregate neu zuweisen, die nicht zu node3 früher verschoben wurden.

.Über diese Aufgabe
Sie müssen node4 per Netzwerk neu starten, wenn die ONTAP Version auf node4 von der ONTAP Version auf node2 abweicht. Nach der Installation von node4 starten Sie es vom ONTAP 9-Image, das auf dem Webserver gespeichert ist. Anschließend können Sie die richtigen Dateien für nachfolgende Systemstarts auf das Startmedium herunterladen, indem Sie den Anweisungen in link:prepare_for_netboot.html["Vorbereitungen für den Netzboot"]

Allerdings ist ein Netboot von Node4 nicht erforderlich, wenn die ONTAP Version auf Node4 gleich oder neuer ist als die ONTAP Version auf Node2.

[IMPORTANT]
====
* Bei einem AFF A800 oder AFF C800 -Controller-Upgrade müssen Sie sicherstellen, dass alle Laufwerke im Gehäuse fest an der Mittelplatine sitzen, bevor Sie Knoten 2 entfernen. Weitere Informationen finden Sie unter link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["Ersetzen Sie die AFF A800- oder AFF C800-Controller-Module"].
* Wenn Sie ein System mit Speicherplatten aktualisieren, müssen Sie diesen Abschnitt vollständig ausfüllen und dann mit dem Abschnitt fortfahren. link:set_fc_uta_uta2_config_node4.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node4 fest"] , indem Sie Befehle an der Cluster-Eingabeaufforderung eingeben.


====
.Schritte
. [[man_install4_Step1]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn node4 wird in ... | Dann... 


| Ein von Knoten 3 getrenntes Chassis | Gehen Sie zu <<man_install4_Step2,Schritt 2>>. 


| Im gleichen Chassis mit Knoten3 | Überspringen Sie die Schritte 2 und 3 und gehen Sie zu <<man_install4_Step4,Schritt 4>>. 
|===
. [[man_install4_Step2]] stellen Sie sicher, dass node4 über ausreichend Rack-Platz verfügt.
+
Wenn node4 sich in einem separaten Chassis von node3 befindet, können sie node4 an der gleichen Stelle wie node2 platzieren. Wenn sich Node3 und node4 im selben Chassis befinden, befindet sich node4 bereits in der entsprechenden Rack-Position.

. installieren sie node4 im Rack gemäß den Anweisungen in der Anleitung _Installation and Setup Instructions_ für das Node-Modell.
. [[man_install4_Step4]]kabelnode4, die Verbindungen von node2 nach node4 verschieben.
+
Die folgenden Referenzen helfen Ihnen dabei, geeignete Kabelverbindungen zu machen. Gehen Sie zu link:other_references.html["Quellen"] Um eine Verbindung zu ihnen zu machen.

+
** _Installations- und Einrichtungsanweisungen_ für die node4-Plattform
** Das entsprechende Verfahren für das Festplatten-Shelf
** Die _HA-Paar-Management_ Dokumentation
+
Folgende Anschlüsse verkabeln:

** Konsole (Remote-Management-Port)
** Cluster-Ports
** Datenports
** Cluster- und Node-Management-Ports
** Storage
** SAN-Konfigurationen: ISCSI Ethernet und FC Switch Ports


+

NOTE: Sie müssen die Interconnect-Karte/FC_VI-Karte oder den Interconnect/FC_VI-Kabelanschluss von node2 auf node4 nicht verschieben, da die meisten Plattformmodelle über einzigartige Interconnect-Kartenmodelle verfügen.

. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn node4 in... | Dann... 


| Im gleichen Chassis wie bei Node3 | Gehen Sie zu <<man_install4_Step8,Schritt 8>>. 


| Ein von Knoten 3 getrenntes Chassis | Gehen Sie zu <<man_install4_Step6,Schritt 6>>. 
|===
. [[man_install4_Step6]]Schalten Sie die Stromversorgung zu node4 ein, und unterbrechen Sie dann den Start, indem Sie Strg-C drücken, um auf die Eingabeaufforderung der Startumgebung zuzugreifen.
+

NOTE: Wenn Sie node4 booten, wird möglicherweise die folgende Meldung angezeigt:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7]]Wenn die Warnmeldung in Schritt 6 angezeigt wird, führen Sie die folgenden Schritte aus:
+
.. Überprüfen Sie auf Meldungen der Konsole, die auf ein anderes Problem als eine schwache NVRAM-Batterie hinweisen und ergreifen Sie gegebenenfalls erforderliche Korrekturmaßnahmen.
.. Lassen Sie den Akku laden und den Bootvorgang beenden.
+

WARNING: *Überschreiben Sie die Verzögerung nicht.  Wenn der Akku nicht aufgeladen wird, kann es zu Datenverlust kommen.*



. [[man_install4_Step8]]Geben Sie an der Eingabeaufforderung für den Wartungsmodus den folgenden Befehl ein:
+
`halt`

+
Das System wird an der Eingabeaufforderung für die Boot-Umgebung angehalten.

. node4 für ONTAP konfigurieren:
+
`set-defaults`

. Wenn Sie NetApp Storage Encryption (NSE)-Laufwerke installiert haben, führen Sie die folgenden Schritte aus:
+

NOTE: Falls Sie dies noch nicht bereits in der Prozedur getan haben, lesen Sie den Artikel in der Knowledge Base https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Wie erkennen Sie, ob ein Laufwerk FIPS-zertifiziert ist"^] Ermitteln der Art der verwendeten Self-Encrypting Drives.

+
.. Einstellen `bootarg.storageencryption.support` Bis `true` Oder `false`:
+
[cols="35,65"]
|===
| Wenn die folgenden Laufwerke verwendet werden… | Dann… 


| NSE-Laufwerke, die den Self-Encryption-Anforderungen von FIPS 140-2 Level 2 entsprechen | `setenv bootarg.storageencryption.support *true*` 


| NetApp ohne FIPS SEDs | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
FIPS-Laufwerke können nicht mit anderen Laufwerkstypen auf demselben Node oder HA-Paar kombiniert werden.

SEDs können mit Laufwerken ohne Verschlüsselung auf demselben Node oder HA-Paar kombiniert werden.

====
.. Gehen Sie zum speziellen Startmenü und wählen Sie Option `(10) Set Onboard Key Manager recovery secrets`.
+
Geben Sie die Passphrase und die Backup-Informationen ein, die Sie zuvor aufgezeichnet haben. Siehe link:manage_authentication_okm.html["Verwaltung von Authentifizierungsschlüssel mit dem Onboard Key Manager"].



. Wenn die auf node4 installierte ONTAP-Version gleich oder höher als die auf node2 installierte Version von ONTAP 9 ist, geben Sie den folgenden Befehl ein:
+
`boot_ontap menu`

. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn das System, das Sie aktualisieren... | Dann... 


| Verfügt nicht über die richtige oder aktuelle ONTAP-Version unter node4 | Gehe zu<<man_install4_Step13,Schritt 13>> . 


| Hat die richtige oder aktuelle Version von ONTAP auf node4 | Gehe zu<<man_install4_Step18,Schritt 18>> . 
|===
. [[man_install4_Step13]]Konfigurieren Sie die Netboot-Verbindung, indem Sie eine der folgenden Aktionen auswählen.
+

NOTE: Sie müssen den Management-Port und die IP-Adresse als Netzboot-Verbindung verwenden. Verwenden Sie keine LIF-IP-Adresse von Daten, oder es kann während des Upgrades ein Datenausfall auftreten.

+
[cols="35,75"]
|===
| Wenn DHCP (Dynamic Host Configuration Protocol) lautet... | Dann... 


| Wird Ausgeführt  a| 
Konfigurieren Sie die Verbindung automatisch, indem Sie an der Eingabeaufforderung der Boot-Umgebung den folgenden Befehl eingeben:
`ifconfig e0M -auto`



| Nicht ausgeführt  a| 
Konfigurieren Sie die Verbindung manuell, indem Sie an der Eingabeaufforderung der Boot-Umgebung den folgenden Befehl eingeben:
`ifconfig e0M -addr=_filer_addr_ mask=_netmask_ -gw=_gateway_ dns=_dns_addr_ domain=_dns_domain_`

`_filer_addr_` Ist die IP-Adresse des Speichersystems (obligatorisch).
`_netmask_` Ist die Netzwerkmaske des Storage-Systems (erforderlich).
`_gateway_` Ist das Gateway für das Speichersystem (erforderlich).
`_dns_addr_` Ist die IP-Adresse eines Namensservers in Ihrem Netzwerk (optional).
`_dns_domain_` Der Domain Name (DNS) ist der Domain-Name. Wenn Sie diesen optionalen Parameter verwenden, benötigen Sie in der Netzboot-Server-URL keinen vollqualifizierten Domänennamen. Sie benötigen nur den Host-Namen des Servers.


NOTE: Andere Parameter können für Ihre Schnittstelle erforderlich sein. Eingabe `help ifconfig` Details finden Sie in der Firmware-Eingabeaufforderung.

|===
. Ausführen eines Netzboots auf node4:
+
[cols="30,70"]
|===
| Für... | Dann... 


| Systeme der FAS/AFF8000 Serie | `netboot \http://<web_server_ip/path_to_webaccessible_directory>/netboot/kernel` 


| Alle anderen Systeme | `netboot \http://<web_server_ip/path_to_webaccessible_directory/ontap_version>_image.tgz` 
|===
+
Der `<path_to_the_web-accessible_directory>` Sollten Sie dazu führen, wo Sie das heruntergeladen haben
`<ontap_version>_image.tgz` In link:prepare_for_netboot.html#man_netboot_Step1["Schritt 1"] Im Abschnitt _Vorbereiten für Netzboot_.

+

NOTE: Unterbrechen Sie den Startvorgang nicht.

. Wählen Sie im Startmenü die Option `option (7) Install new software first`.
+
Mit dieser Menüoption wird das neue Data ONTAP-Image auf das Startgerät heruntergeladen und installiert.

+
Ignorieren Sie die folgende Meldung:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
Der Hinweis gilt für unterbrechungsfreie Upgrades der Data ONTAP und keine Upgrades von Controllern.

+

NOTE: Aktualisieren Sie den neuen Node immer als Netzboot auf das gewünschte Image. Wenn Sie eine andere Methode zur Installation des Images auf dem neuen Controller verwenden, wird möglicherweise das falsche Image installiert. Dieses Problem gilt für alle Versionen von ONTAP. Das Netzboot wird mit der Option kombiniert `(7) Install new software` Entfernt das Boot-Medium und platziert dieselbe ONTAP-Version auf beiden Image-Partitionen.

. [[man_install4_steep23] Wenn Sie aufgefordert werden, den Vorgang fortzusetzen, geben Sie y ein. Geben Sie dann die URL ein, wenn Sie nach dem Paket gefragt werden:
+
`\http://<web_server_ip/path_to_web-accessible_directory/ontap_version>_image.tgz`

. Führen Sie die folgenden Teilschritte durch:
+
.. Eingabe `n` So überspringen Sie die Backup-Recovery, wenn folgende Eingabeaufforderung angezeigt wird:
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. Starten Sie den Neustart durch Eingabe `y` Wenn die folgende Eingabeaufforderung angezeigt wird:
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
Das Controller-Modul wird neu gestartet, stoppt aber im Startmenü, da das Boot-Gerät neu formatiert wurde und die Konfigurationsdaten wiederhergestellt werden müssen.



. [[man_install4_Step18]]Wartungsmodus auswählen `5` aus dem Boot-Menü und geben Sie `y` wenn Sie aufgefordert werden, mit dem Booten fortzufahren.
. [[man_install4_Step19]]Bevor Sie fortfahren, gehen Sie zulink:set_fc_uta_uta2_config_node4.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node4 fest"] um alle notwendigen Änderungen an den FC- oder UTA/UTA2-Ports auf dem Knoten vorzunehmen.  Nehmen Sie die in diesen Abschnitten empfohlenen Änderungen vor, starten Sie den Knoten neu und wechseln Sie in den Wartungsmodus.
. Geben Sie den folgenden Befehl ein und überprüfen Sie die Ausgabe, um die System-ID von node4 zu finden:
+
`disk show -a`

+
Das System zeigt die System-ID des Node sowie Informationen über seine Festplatten an, wie im folgenden Beispiel dargestellt:

+
[listing]
----
*> disk show -a
Local System ID: 536881109
DISK         OWNER                       POOL   SERIAL NUMBER   HOME
------------ -------------               -----  -------------   -------------
0b.02.23     nst-fas2520-2(536880939)    Pool0  KPG2RK6F        nst-fas2520-2(536880939)
0b.02.13     nst-fas2520-2(536880939)    Pool0  KPG3DE4F        nst-fas2520-2(536880939)
0b.01.13     nst-fas2520-2(536880939)    Pool0  PPG4KLAA        nst-fas2520-2(536880939)
......
0a.00.0                   (536881109)    Pool0  YFKSX6JG                     (536881109)
......
----
. Weisen Sie node2 Ersatzteile, Festplatten, die zur Root gehören, und alle nicht-Root-Aggregate erneut zu, die im Abschnitt früher nicht in node3 verschoben wurden link:relocate_non_root_aggr_node2_node3.html["Verschieben Sie Aggregate ohne Root-Root-Fehler von node2 auf node3"]:
+

NOTE: Wenn Sie auf Ihrem System freigegebene Festplatten, Hybrid-Aggregate oder beides haben, müssen Sie die korrekte verwenden `disk reassign` Befehl aus der folgenden Tabelle.

+
[cols="35,65"]
|===
| Festplattentyp... | Führen Sie den Befehl aus... 


| Mit gemeinsamen Festplatten | `disk reassign -s`

`_node2_sysid_ -d _node4_sysid_ -p _node3_sysid_` 


| Ohne Shared-Ressourcen | `disks disk reassign -s`

`_node2_sysid_ -d _node4_sysid_` 
|===
+
Für das `<node2_sysid>` Wert: Verwenden Sie die in erfassten Informationen link:record_node2_information.html#man_record_2_step10["Schritt 10"] Des Abschnitts _Record node2 information_. Für `_node4_sysid_`Verwenden Sie die Informationen, die in erfasst werden <<man_install4_step23,Schritt 23>>.

+

NOTE: Der `-p` Die Option ist nur im Wartungsmodus erforderlich, wenn freigegebene Festplatten vorhanden sind.

+
Der `disk reassign` Befehl weist nur die Festplatten zu, für die es erforderlich ist `_node2_sysid_` Ist der aktuelle Eigentümer.

+
Vom System wird die folgende Meldung angezeigt:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n
----
+
Eingabe `n` Wenn Sie aufgefordert werden, die Neuzuweisung der Festplatte abzubrechen.

+
Wenn Sie aufgefordert werden, die Neuzuweisung der Festplatte abzubrechen, müssen Sie eine Reihe von Eingabeaufforderungen beantworten, wie in den folgenden Schritten dargestellt:

+
.. Vom System wird die folgende Meldung angezeigt:
+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
----
.. Eingabe `y` Um fortzufahren.
+
Vom System wird die folgende Meldung angezeigt:

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)? y
----
.. Eingabe `y` Um die Aktualisierung der Festplatteneigentümer zu ermöglichen.


. Wenn Sie ein Upgrade von einem System mit externen Festplatten auf ein System durchführen, das interne und externe Festplatten unterstützt (z. B. A800-Systeme), setzen sie node4 als root, um zu bestätigen, dass es aus dem Root-Aggregat von node2 startet.
+

WARNING: *Warnung: Sie müssen die folgenden Teilschritte in der angegebenen Reihenfolge durchführen; andernfalls kann es zu einem Ausfall oder sogar zu Datenverlust kommen.*

+
Mit dem folgenden Verfahren wird node4 vom Root-Aggregat von node2 gestartet:

+
.. Überprüfen Sie die RAID-, Plex- und Prüfsummeninformationen für das node2 Aggregat:
+
`aggr status -r`

.. Prüfen Sie den Gesamtstatus des node2-Aggregats:
+
`aggr status`

.. Bei Bedarf das node2 Aggregat online bringen:
+
`aggr_online root_aggr_from___node2__`

.. Verhindern Sie, dass das node4 aus dem ursprünglichen Root-Aggregat gebootet wird:
+
`aggr offline _root_aggr_on_node4_`

.. Legen Sie das node2-Root-Aggregat als das neue Root-Aggregat für node4 fest:
+
`aggr options aggr_from___node2__ root`



. Vergewissern Sie sich, dass Controller und Chassis als konfiguriert sind `ha` Indem Sie den folgenden Befehl eingeben und die Ausgabe beobachten:
+
`ha-config show`

+
Das folgende Beispiel zeigt die Ausgabe von `ha-config show` Befehl:

+
[listing]
----
*> ha-config show
   Chassis HA configuration: ha
   Controller HA configuration: ha
----
+
Systeme zeichnen in EINEM PROM auf, ob sie in einem HA-Paar oder einer Standalone-Konfiguration sind. Der Status muss auf allen Komponenten im Standalone-System oder im HA-Paar der gleiche sein.

+
Wenn Controller und Chassis nicht als konfiguriert wurden `ha`, Verwenden Sie die folgenden Befehle, um die Konfiguration zu korrigieren:

+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`.

+
Wenn Sie eine MetroCluster-Konfiguration haben, verwenden Sie die folgenden Befehle, um die Konfiguration zu korrigieren:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`.

. Löschen Sie die Mailboxen auf node4:
+
`mailbox destroy local`

. Beenden des Wartungsmodus:
+
`halt`

+
Das System wird an der Eingabeaufforderung für die Boot-Umgebung angehalten.

. Überprüfen Sie in Knoten 3 das Systemdatum, die Uhrzeit und die Zeitzone:
+
`date`

. Prüfen Sie am node4 das Datum an der Eingabeaufforderung für die Boot-Umgebung:
+
`show date`

. Legen Sie bei Bedarf das Datum auf node4 fest:
+
`set date _mm/dd/yyyy_`

. Prüfen Sie auf node4 die Zeit an der Eingabeaufforderung der Boot-Umgebung:
+
`show time`

. Stellen Sie bei Bedarf die Uhrzeit auf node4 ein:
+
`set time _hh:mm:ss_`

. Überprüfen Sie, ob die Partnersystem-ID korrekt eingestellt ist, wie in<<man_install4_Step19,Schritt 19>> unter Option.
+
`printenv partner-sysid`

. Legen Sie bei Bedarf die Partner System-ID auf node4 fest:
+
`setenv partner-sysid _node3_sysid_`

+
.. Einstellungen speichern:
+
`saveenv`



. Rufen Sie das Boot-Menü an der Eingabeaufforderung der Boot-Umgebung auf:
+
`boot_ontap menu`

. Wählen Sie im Startmenü die Option *(6) Flash von Backup config* aktualisieren, indem Sie eingeben `6` An der Eingabeaufforderung.
+
Vom System wird die folgende Meldung angezeigt:

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. Eingabe `y` An der Eingabeaufforderung.
+
Der Startvorgang läuft normal weiter, und das System fordert Sie auf, die Unstimmigkeit der System-ID zu bestätigen.

+

NOTE: Das System wird möglicherweise zweimal neu gestartet, bevor die Warnmeldung zur Nichtübereinstimmung angezeigt wird.

. Bestätigen Sie die Diskrepanz. Der Node kann vor dem normalen Booten eine Runde des Neubootens abschließen.
. Melden Sie sich bei node4 an.

