---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/manage_authentication_kmip.html 
keywords: kmip, authentication, keys, fips 
summary: Nutzen Sie KMIP-Server, um Authentifizierungsschlüssel während eines manuellen ARL-Upgrades auf Controllern mit ONTAP 9.8 oder höher zu managen. 
---
= Authentifizierungsmanagement mit KMIP-Servern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit ONTAP 9.5 und höher können KMIP-Server (Key Management Interoperability Protocol) Authentifizierungsschlüssel managen.

.Schritte
. Hinzufügen eines neuen Controllers:
+
`security key-manager setup -node _new_controller_name_`

. Fügen Sie den Schlüsselmanager hinzu:
+
`security key-manager -add _key_management_server_ip_address_`

. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server konfiguriert und für alle Nodes im Cluster verfügbar sind:
+
`security key-manager show -status`

. Stellen Sie die Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern auf den neuen Knoten wieder her:
+
`security key-manager restore -node _new_controller_name_`


