---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/manage_authentication_okm.html 
keywords: manage, authentication, onboard key manager, okm, key, passphrase, fips 
summary: Managen Sie Authentifizierungsschlüssel mit dem integrierten Schlüsselmanager bei einem manuellen ARL-Upgrade auf Controllern, auf denen ONTAP 9.8 oder höher ausgeführt wird. 
---
= Verwaltung von Authentifizierungsschlüssel mit dem Onboard Key Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können den Onboard Key Manager (OKM) zur Verwaltung von Authentifizierungsschlüsseln verwenden. Wenn Sie das OKM eingerichtet haben, müssen Sie die Passphrase und das Sicherungsmaterial aufzeichnen, bevor Sie mit dem Upgrade beginnen.

.Schritte
. Notieren Sie die Cluster-weite Passphrase.
+
Dies ist die Passphrase, die eingegeben wurde, als das OKM mit der CLI oder REST-API konfiguriert oder aktualisiert wurde.

. Überprüfen Sie die Passphrase und den Schlüsselmanager-Vorgang:
+
`security key-manager onboard sync`

+
Geben Sie bei Aufforderung die clusterweite OKM-Passphrase ein, die Sie im vorherigen Schritt aufgezeichnet haben.

. Vergewissern Sie sich, dass cc-mode aktiviert ist, indem Sie die Ausgabe des folgenden Befehls überprüfen:
+
`security key-manager config show`

. Sichern Sie die Key-Manager-Informationen:
+
`security key-manager onboard show-backup`


