---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/move_nas_lifs_node1_node2.html 
keywords: nas, node1, node2, lifs, cluster, san 
summary: Verschieben Sie die Daten-LIFs von node1 auf node2, wenn Sie ein Cluster mit zwei Nodes haben, oder auf einen dritten Node, wenn Ihr Cluster über mehr als zwei Nodes verfügt, während eines manuellen ARL-Upgrades auf Controllern mit ONTAP 9.8 oder höher. 
---
= Verschieben Sie NAS-Daten-LIFs von node1 auf node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie node1 durch node3 ersetzen können, müssen Sie die NAS-Daten-LIFs, die sich im Besitz von node1 befinden, auf node2 verschieben, wenn Sie ein Cluster mit zwei Nodes haben, oder auf einen dritten Node, wenn Ihr Cluster mehr als zwei Nodes hat. Die von Ihnen verwendete Methode hängt davon ab, ob das Cluster für NAS oder SAN konfiguriert ist.

.Über diese Aufgabe
Remote-LIFs verarbeiten den Datenverkehr zu SAN-LUNs während des Upgrades. Das Verschieben von SAN-LIFs ist für den Zustand des Clusters oder des Service während des Upgrades nicht erforderlich. Sie müssen überprüfen, ob die LIFs sich in einem ordnungsgemäßen Zustand befinden und sich auf den entsprechenden Ports befinden, nachdem Sie node3 in den Online-Modus versetzt haben.

.Schritte
. Führen Sie alle auf node1 gehosteten NAS-Daten-LIFs auf, indem Sie den folgenden Befehl eingeben und die Ausgabe erfassen:
+
`network interface show -data-protocol nfs|cifs -curr-node _node1_`

+
[listing]
----
 cluster::> network interface show -data-protocol nfs|cifs -curr-node node1

          Logical     Status      Network             Current   Current Is
 Vserver  Interface   Admin/Oper  Address/Mask        Node      Port    Home
 -------- ----------  ----------  ------------------  --------- ------- ----
 vs0
          a0a         up/down     10.63.0.53/24       node1     a0a     true
          data1       up/up       10.63.0.50/18       node1     e0c     true
          rads1       up/up       10.63.0.51/18       node1     e1a     true
          rads2       up/down     10.63.0.52/24       node1     e1b     true
 vs1
          lif1        up/up       192.17.176.120/24   node1     e0c     true
          lif2        up/up       172.17.176.121/24   node1     e1a     true
----
. [[Schritt2]]Ändern Sie die Einstellungen zur automatischen Zurücksetzen aller LIFs auf node1 und node2:
+
`network interface modify -vserver _Vserver_name_ -lif _LIF_name_ -auto-revert false`

. [[Schritt3]]Nehmen Sie die folgenden Schritte auf, um alle NAS-Daten-LIFs zu migrieren, die auf Schnittstellengruppen und VLANs auf node1 gehostet werden:
+
.. [[subepa] Migrieren Sie die LIFs, die auf einer beliebigen Interface Groups gehostet werden, und die VLANs auf node1 zu einem Port auf node2, der in der Lage ist, LIFs auf demselben Netzwerk wie die der Interface Groups zu hosten, indem Sie den folgenden Befehl eingeben, einmal für jede LIF:
+
`network interface migrate -vserver _Vserver_name_ -lif _LIF_name_ -destination-node _node2_ –destination-port _netport|ifgrp_`

.. Ändern Sie den Home-Port und den Home-Node der LIFs und VLANs in <<substepa,Unterschritt A>> Geben Sie zum Port und Node, der derzeit die LIFs hostet, den folgenden Befehl ein, einmal für jede LIF:
+
`network interface modify -vserver _Vserver_name_ -lif _LIF_name_ -home-node _node2_ - home-port _netport|ifgrp_`



. [[Schritt4]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="20,80"]
|===
| Wenn das Cluster konfiguriert ist für... | Dann... 


| NAS | Vollständig <<man_lif_1_2_step5,Schritt 5>> Bis <<man_lif_1_2_step8,Schritt 8>>. 


| San | Deaktivieren Sie alle SAN-LIFs auf dem Node, um sie für das Upgrade herunterzufahren:
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _node_to_upgrade_ -home-port _netport|ifgrp_ -status-admin down` 
|===
. [[man_lif_1_2_step5]]NAS-Daten-LIFs von node1 nach node2 migrieren, indem Sie den folgenden Befehl eingeben, einmal für jede Daten-LIF:
+
`network interface migrate -vserver _Vserver-name_ -lif _LIF_name_ -destination-node _node2_ -destination-port _data_port_`

. [[Schritt6]]Geben Sie den folgenden Befehl ein und überprüfen Sie seine Ausgabe, um zu überprüfen, ob LIFs an die richtigen Ports verschoben wurden und dass die LIFs den Status von „up“ aufweisen. Geben Sie dazu den folgenden Befehl an einem der beiden Nodes ein und überprüfen Sie die Ausgabe:
+
`network interface show -curr-node _node2_ -data-protocol nfs|cifs`

. [[step7]]Ändern Sie den Home-Node der migrierten LIFs:
+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _node2_ -home-port _port_name_`

. [[man_lif_1_2_step8]]Überprüfen Sie, ob die LIF den Port als ihren Home- oder aktuellen Port verwendet. Wenn der Port nicht zu Hause oder der aktuelle Port ist, fahren Sie mit fort <<man_lif_1_2_step9,Schritt 9>>:
+
`network interface show -home-node _node2_ -home-port _port_name_`

+
`network interface show -curr-node _node_name_ -curr-port _port_name_`

. [[man_lif_1_2_step9]]Wenn die LIFs den Port als Home-Port oder aktuellen Port verwenden, ändern Sie die LIF und verwenden Sie einen anderen Port:
+
`network interface migrate -vserver _Vserver-name_ -lif _LIF_name_ -destination–node _node_name_ -destination-port _port_name_`

+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home–node _node_name_ -home-port _port_name_`

. [[Schritt10]]Wenn eine der LIFs ausgefallen sind, setzen Sie den Administrationsstatus der LIFs auf „up“, indem Sie den folgenden Befehl eingeben, einmal für jede LIF:
+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _nodename_ -status-admin up`

+

NOTE: Bei MetroCluster Konfigurationen können Sie die Broadcast-Domäne eines Ports möglicherweise nicht ändern, da dieser einem Port zugewiesen ist, der die LIF einer Ziel-Storage Virtual Machine (SVM) hostet. Geben Sie den folgenden Befehl von der entsprechenden Quell-SVM auf dem Remote-Standort ein, um die Ziel-LIF einem entsprechenden Port zuzuweisen:
`metrocluster vserver resync -vserver _Vserver_name_`

. [[Schritt11]]Geben Sie den folgenden Befehl ein und überprüfen Sie seine Ausgabe, um zu überprüfen, ob auf node1 keine Daten-LIFs mehr vorhanden sind:
+
`network interface show -curr-node _node1_ -role data`


