---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/move_nas_lifs_node2_node3.html 
keywords: move, nas, lif, node2, node3, san, nfs, cifs, ifgrp 
summary: Verschieben Sie während eines manuellen ARL Upgrades auf Controllern mit ONTAP 9.8 oder höher die NAS-Daten-LIFs von node2 auf Knoten 3. 
---
= Verschieben Sie die NAS-Daten-LIFs von node2 auf node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die Aggregate von node2 auf node3 verschoben haben, müssen Sie die NAS-Daten-LIFs von node2 auf node3 verschieben.

.Über diese Aufgabe
Remote-LIFs verarbeiten den Datenverkehr zu SAN-LUNs während des Upgrades. Das Verschieben von SAN-LIFs ist für den Zustand des Clusters oder des Service während des Upgrades nicht erforderlich. SAN LIFs werden nicht verschoben, es sei denn, sie müssen neuen Ports zugeordnet werden. Sie müssen überprüfen, ob die LIFs sich in den entsprechenden Ports befinden, nachdem Sie die LIFs von node3 nach node4 verschoben und node4 in den Online-Modus versetzt haben.

.Schritte
. [[Schritt1]]Listen Sie alle NAS-Daten-LIFs auf, die sich im Besitz von node2 befinden, indem Sie auf einem der beiden Knoten den folgenden Befehl eingeben und die Ausgabe erfassen:
+
`network interface show -data-protocol nfs|cifs -home-node _node2_`

+
Im folgenden Beispiel wird die Befehlsausgabe für „node2“ gezeigt:

+
[listing]
----
cluster::> network interface show -data-protocol nfs|cifs -home-node node2
              Logical     Status      Network             Current  Current  Is
 Vserver      Interface   Admin/Oper  Address/Mask        Node     Port     Home
 -----------  ----------  ----------  ------------------  -------  -------  ----
 vs0
              a0a         up/down     10.63.0.53/24       node2    a0a      true
              data1       up/up       10.63.0.50/18       node2    e0c      true
              rads1       up/up       10.63.0.51/18       node2    e1a      true
              rads2       up/down     10.63.0.52/24       node2    e1b      true
 vs1
              lif1        up/up       172.17.176.120/24   node2    e0c      true
              lif2        up/up       172.17.176.121/24   node2    e1a      true
----
. [[Schritt2]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Falls Knoten 2... | Dann... 


| Schnittstellengruppen oder VLANs sind konfiguriert | Gehen Sie zu <<man_move_lif_2_3_step3,Schritt 3>>. 


| Schnittstellengruppen oder VLANs sind nicht konfiguriert | Überspringen Sie Schritt 3, und fahren Sie mit fort <<man_move_lif_2_3_step4,Schritt 4>>. 
|===
. [[man_move_lif_2_3_step3]]Nehmen Sie die folgenden Schritte durch, um die auf Schnittstellengruppen und VLANs auf node2 gehosteten NAS-Daten-LIFs zu migrieren:
+
.. [[man_move_lif_2_3_substanzen]]Migrieren Sie alle Daten-LIFs, die auf einer Schnittstellengruppe auf node2 gehostet werden, zu einem Port auf node3, der in der Lage ist, LIFs auf demselben Netzwerk zu hosten, indem Sie den folgenden Befehl eingeben, einmal für jede LIF:
+
`network interface migrate -vserver _Vserver_name_ -lif _LIF_name_ -destination-node _node3_ –destination-port _netport|ifgrp_`

.. Ändern Sie den Home-Port und den Home-Node der LIFs in <<man_move_lif_2_3_substepa,Unterschritt A>> Um den Port und Node, der derzeit die LIFs hostet, geben Sie einmal für jeden Node den folgenden Befehl ein:
+
`network interface modify -vserver _Vserver_name_ -lif _LIF_name_ -home-node _node3_ -homeport _netport|ifgrp_`

.. [[man_move_lif_2_3_subrepc]]Migrieren Sie alle auf VLANs gehosteten LIFs auf node2 zu einem Port auf node3, der in der Lage ist, LIFs auf demselben Netzwerk wie die des VLANs zu hosten, indem Sie den folgenden Befehl eingeben – einmal für jede LIF:
+
`network interface migrate -vserver _Vserver_name_ -lif _LIF_name_ -destination-node _node3_ –destination-port _netport|ifgrp_`

.. Ändern Sie den Home-Port und den Home-Node der LIFs in <<man_move_lif_2_3_substepc,Unterschritt C>> Geben Sie zum Port und Node, der derzeit die LIFs hostet, den folgenden Befehl ein, einmal für jede LIF:
+
`network interface modify -vserver _Vserver_name_ -lif _LIF_name_ -home-node _node3_ -homeport _netport|ifgrp_`



. [[man_move_lif_2_3_step4]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn das Cluster konfiguriert ist für... | Dann... 


| NAS | Vollständig <<man_move_lif_2_3_step5,Schritt 5>> Bis <<man_move_lif_2_3_step8,Schritt 8>>. 


| San | Überspringen Sie Schritt 5 bis Schritt 8 und schließen Sie dann ab <<man_move_lif_2_3_step9,Schritt 9>>. 


| Sowohl NAS als auch SAN | Vollständig <<man_move_lif_2_3_step5,Schritt 5>> Bis <<man_move_lif_2_3_step9,Schritt 9>>. 
|===
. [[man_move_lif_2_3_step5]]Wenn auf Ihren Plattformen nicht dieselben Daten-Ports vorhanden sind, fügen Sie die Ports der Broadcast-Domäne hinzu:
+
`network port broadcast-domain add-ports -ipspace _IPspace_name_ -broadcast-domain mgmt -ports _node:port_`

+
Das folgende Beispiel fügt Port „e0a“ auf den Knoten „6280-1“ und Port „e0i“ auf Knoten „8060-1“ zum Broadcast-Domain „Management“ im IPspace „Standard“ hinzu:

+
[listing]
----
cluster::> network port broadcast-domain add-ports -ipspace Default
           -broadcast-domain mgmt -ports 6280-1:e0a, 8060-1:e0i
----
. [[Schritt6]]Migrieren Sie jede NAS-Daten-LIF auf node3 durch Eingabe des folgenden Befehls, einmal für jede LIF:
+
`network interface migrate -vserver _Vserver_name_ -lif _LIF_name_ -destination-node _node3_ -destination-port _netport|ifgrp_`

. [[step7]]Überprüfen Sie, ob NAS-LIFs zu den richtigen Ports verschoben wurden und ob die LIFs den Status von „up“ haben, indem Sie auf einem der beiden Knoten den folgenden Befehl eingeben und die Ausgabe überprüfen:
+
`network interface show -curr-node _node3_ -data-protocol cifs|nfs`

. [[man_move_lif_2_3_step8]]Wenn eine der LIFs nicht verfügbar ist, setzen Sie den administrativen Status der LIFs auf „up“, indem Sie den folgenden Befehl eingeben, einmal für jede LIF:
+
`network interface modify -vserver _Vserver_name_ -lif _LIF_name_ -status-admin up`

. [[man_move_lif_2_3_step9]]Wenn Schnittstellengruppen oder VLANs konfiguriert sind, führen Sie die folgenden Teilschritte aus:
+
.. Entfernen Sie die VLANs aus den Schnittstellengruppen:
+
`network port vlan delete -node _node_name_ -port _ifgrp_ -vlan-id _VLAN_ID_`

.. Geben Sie den folgenden Befehl ein und überprüfen Sie seine Ausgabe, um zu ermitteln, ob Schnittstellengruppen auf dem Node konfiguriert sind:
+
`network port ifgrp show -node _node_name_ -ifgrp _ifgrp_name_ -instance`

+
Das System zeigt Schnittstellengruppeninformationen für den Node an, wie im folgenden Beispiel gezeigt:

+
[listing]
----
cluster::> network port ifgrp show -node node2 -ifgrp a0a -instance
                 Node: node2
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode_lacp
          MAC Address: MAC_address
    ort Participation: partial
        Network Ports: e2c, e2d
             Up Ports: e2c
           Down Ports: e2d
----
.. Wenn auf dem Node Schnittstellengruppen konfiguriert sind, notieren Sie die Namen der Interface Groups und der ihnen zugewiesenen Ports. Löschen Sie dann die Ports, indem Sie den folgenden Befehl eingeben, jeweils ein für jeden Port:
+
`network port ifgrp remove-port -node _node_name_ -ifgrp _ifgrp_name_ -port _port_name_`




