---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/overview.html 
keywords: upgrade, controller, hardware, replacement, aggregates, migrate, lifs, network, ports 
summary: Erfahren Sie, wie das manuelle ARL-Upgrade bei Controllern mit ONTAP 9.8 oder höher funktioniert. 
---
= Überblick
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Während des Verfahrens führen Sie ein Upgrade der ursprünglichen Controller Hardware mit der Ersatz-Controller-Hardware durch. Hierbei werden die Eigentumsrechte an Aggregaten verschoben, die nicht mit Root-Berechtigungen verbunden sind. Sie migrieren Aggregate mehrmals von Node zu Node, um zu bestätigen, dass mindestens ein Node während des Upgrades Daten von den Aggregaten bereitstellt. Außerdem migrieren Sie Daten-logische Schnittstellen (LIFs) und weisen Sie die Netzwerk-Ports auf dem neuen Controller den Schnittstellengruppen zu, während Sie fortfahren.


NOTE: In diesem Dokument werden die ursprünglichen Knoten _node1_ und _node2_ genannt, und die neuen Knoten werden _node3_ und _node4_ genannt. Während des beschriebenen Verfahrens wird node1 durch node3 ersetzt und node2 durch node4 ersetzt. Die Begriffe _node1_, _node2_, _node3_ und _node4_ werden nur verwendet, um zwischen den ursprünglichen und neuen Knoten zu unterscheiden. Wenn Sie das Verfahren befolgen, müssen Sie die richtigen Namen Ihrer ursprünglichen und neuen Knoten ersetzen. In der Realität ändern sich jedoch die Namen der Nodes nicht: node3 hat den Namen node1 und node4 hat nach dem Upgrade der Controller-Hardware den Namen node2. In diesem Dokument wird der Begriff „ Systems with FlexArray Virtualization Software_“ verwendet, um sich auf Systeme zu beziehen, die zu diesen neuen Plattformen gehören. Dabei wird der Begriff _V-Series System_ verwendet, um sich auf die separaten Hardware-Systeme zu beziehen, die an Storage-Arrays angeschlossen werden können

.Wichtige Informationen:
* Diese Vorgehensweise ist komplex und setzt voraus, dass Sie über erweiterte ONTAP-Administrationsfähigkeiten verfügen. Sie müssen auch lesen und verstehen, die link:guidelines_upgrade_with_arl.html["Richtlinien für das Controller-Upgrade mit ARL"] Und das link:arl_upgrade_workflow.html["ARL Upgrade-Workflow"] Abschnitte vor Beginn der Aktualisierung.
* Bei dieser Vorgehensweise wird vorausgesetzt, dass die Ersatz-Controller-Hardware neu ist und nicht verwendet wurde. Die erforderlichen Schritte zur Vorbereitung gebrauter Controller mit dem `wipeconfig` Befehl ist in dieser Prozedur nicht enthalten. Wenn bereits die Ersatz-Controller-Hardware verwendet wurde, müssen Sie sich an den technischen Support wenden, insbesondere wenn auf den Controllern Data ONTAP in 7-Mode ausgeführt wurde.
* Mit diesem Verfahren können Sie die Controller-Hardware in Clustern mit mehr als zwei Nodes aktualisieren. Sie müssen jedoch für jedes Hochverfügbarkeitspaar (HA) im Cluster separat vorgehen.
* Dieses Verfahren gilt für FAS Systeme, V-Series Systeme, AFF Systeme und Systeme mit FlexArray Virtualisierungssoftware. FAS Systeme, die nach ONTAP 9 freigegeben wurden, können an Speicher-Arrays angebunden werden, wenn die erforderliche Lizenz installiert ist. Die vorhandenen Systeme der V-Serie werden von ONTAP 9 unterstützt. Informationen zu den Modellen Storage Array und V-Series finden Sie unter link:other_references.html["Quellen"] Um zu _Hardware Universe_ zu verlinken und eine Support-Matrix zur _V-Serie_ zu erhalten.

