---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/restore_key-manager_config_node4.html 
keywords: restore key-manager, configuration, node4, nve, arl, volume, encryption 
summary: Bei Bedarf kann die Key-Manager-Konfiguration auf Node4 während eines manuellen ARL Upgrades auf Controllern mit ONTAP 9.8 oder höher wiederhergestellt werden. 
---
= Wiederherstellen der Key-Manager-Konfiguration auf node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn Sie mithilfe von NetApp Volume Encryption (NVE) und NetApp Aggregate Encryption (NAE) Volumes auf dem System verschlüsseln, muss die Verschlüsselungskonfiguration mit den neuen Nodes synchronisiert werden. Wenn Sie den Schlüsselmanager nicht synchronisieren, können beim Verschieben der Node2-Aggregate mit ARL Fehler auftreten, da node4 nicht über die erforderlichen Schlüssel verfügt, um verschlüsselte Volumes und Aggregate online zu bringen.

.Über diese Aufgabe
Die Verschlüsselungskonfiguration mit den neuen Nodes synchronisieren, indem Sie die folgenden Schritte durchführen:

.Schritte
. Führen Sie folgenden Befehl aus node4 aus:
+
`security key-manager onboard sync`

. Vergewissern Sie sich, dass der SVM-KEK-Schlüssel auf node4 als „true“ wiederhergestellt wurde, bevor Sie die Datenaggregate verschieben:
+
[listing]
----
::> security key-manager key query -node node4 -fields restored -key-type SVM-KEK
----
+
.Beispiel
[listing]
----
::> security key-manager key query -node node4 -fields restored -key-type SVM-KEK

node     vserver   key-server   key-id                                  restored
-------- --------- -----------  --------------------------------------- --------
node4    svm1      ""           00000000000000000200000000000a008a81976 true
                                2190178f9350e071fbb90f00000000000000000
----

