---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_up_netapp_encryption_on_new_controller.html 
keywords: set up, netapp volume encryption, encryption, controller, module 
summary: Konfigurieren Sie, falls erforderlich, das neue Controller-Modul für NVE oder NAE während eines manuellen ARL Upgrades bei Controllern mit ONTAP 9.8 oder höher. 
---
= Einrichten von NetApp Volume oder Aggregte Verschlüsselung auf dem neuen Controller-Modul
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn der ersetzte Controller oder der HA-Partner (High Availability, Hochverfügbarkeit) des neuen Controllers NetApp Volume Encryption (NVE) oder NetApp Aggregate Encryption (NAE) verwendet, muss das neue Controller-Modul für NVE oder NAE konfiguriert werden.

.Über diese Aufgabe
Dieses Verfahren umfasst Schritte, die auf dem neuen Controller-Modul ausgeführt werden. Sie müssen den Befehl auf dem richtigen Node eingeben.

.Schritte
. Vergewissern Sie sich, dass die Verschlüsselungsmanagement-Server weiterhin verfügbar sind, deren Status und ihre Authentifizierungsdaten folgendermaßen sind:
+
`security key-manager key query -node node`

. Fügen Sie die im vorherigen Schritt aufgeführten Verschlüsselungsmanagement-Server der Liste des zentralen Management-Servers des neuen Controllers hinzu:
+
.. Fügen Sie den Verschlüsselungsmanagementserver mit dem folgenden Befehl hinzu:
+
`security key-manager -add _key_management_server_ip_address_`

.. Wiederholen Sie den vorherigen Schritt für jeden aufgeführten Key Management Server. Sie können bis zu vier Verschlüsselungsmanagement-Server verknüpfen.
.. Überprüfen Sie, ob die Verschlüsselungsmanagement-Server erfolgreich hinzugefügt wurden. Verwenden Sie dazu den folgenden Befehl:
+
`security key-manager show`



. Führen Sie auf dem neuen Controller-Modul den Setup-Assistenten für das Verschlüsselungsmanagement aus, um die wichtigsten Management-Server einzurichten und zu installieren.
+
Sie müssen dieselben Key Management-Server installieren, die auf dem vorhandenen Controller-Modul installiert sind.

+
.. Starten Sie den Setup-Assistenten für den Verschlüsselungsmanagement-Server auf dem neuen Knoten, indem Sie den folgenden Befehl verwenden:
+
`security key-manager setup -node _new_controller_name_`

.. Führen Sie die Schritte im Assistenten zum Konfigurieren von Verschlüsselungsmanagementservern durch.


. Stellen Sie Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern mit dem neuen Knoten wieder her:
+
[cols="35,65"]
|===
| Für... | Befehl 


| Externer Schlüsselmanager | `security key-manager external restore`Für diesen Befehl ist die OKM-Passphrase erforderlich 


| Onboard Key Manager (OKM) | `security key-manager onboard sync` 
|===
+
Weitere Informationen finden Sie im Knowledge Base-Artikel https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["So stellen Sie die Konfiguration des externen Schlüsselmanager-Servers aus dem ONTAP-Startmenü wieder her"^].



.Nachdem Sie fertig sind
Überprüfen Sie, ob Volumes offline geschaltet wurden, da Authentifizierungsschlüssel nicht verfügbar waren oder externe Verschlüsselungsmanagementserver nicht erreicht werden konnten. Stellen Sie diese Volumes mithilfe der wieder online `volume online` Befehl.
