---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_fc_uta_uta2_config_node3.html 
keywords: configure, configuration, fc, uta, uta2, settings 
summary: Konfiguration von node3 integrierten FC-Ports, UTA/UTA2-Ports oder UTA/UTA2-Karte während eines manuellen ARL Upgrades auf Controllern mit ONTAP 9.8 oder höher 
---
= Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node3 fest
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn node3 integrierte FC-Ports, Onboard Unified Target Adapter (UTA/UTA2)-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Einstellungen konfigurieren, bevor Sie den Rest des Verfahrens abschließen.

.Über diese Aufgabe
Möglicherweise müssen Sie Folgendes ausfüllen:<<Konfigurieren Sie FC-Ports auf node3>> oder<<UTA/UTA2-Ports in node3 prüfen und konfigurieren>> oder beide Abschnitte.


NOTE: Für das NetApp Marketingmaterial wird möglicherweise der Begriff „UTA2“ verwendet, um CNA-Adapter und Ports zu beziehen. Die CLI verwendet jedoch den Begriff „CNA“.

* Wenn Knoten3 keine integrierten FC-Ports, integrierten UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat (z. B. AFF und FAS -Systeme, die ab ONTAP 9.15.1 eingeführt wurden) und Sie ein System mit Speicherplatten aktualisieren, können Sie mit dem nächsten Schritt fortfahren.link:map_ports_node1_node3.html["Ports von node1 nach node3 zuordnen"] .
* Wenn Sie jedoch ein V-Series System oder ein System mit FlexArray-Virtualisierungssoftware mit Storage-Arrays haben und node3 keine integrierten FC-Ports, Onboard UTA/UTA-Ports oder eine UTA/UTA2-Karte haben, kehren Sie zurück zu _Install and Boot node3_ und fahren Sie fort link:install_boot_node3.html#man_install3_step22["Schritt 22"].




== Konfigurieren Sie FC-Ports auf node3

Wenn Knoten3 über FC-Ports verfügt (entweder integriert oder auf einem zusätzlichen FC-Adapter), müssen Sie die Portkonfigurationen auf dem Knoten festlegen, bevor Sie ihn in Betrieb nehmen, da die Ports bei der Auslieferung der Systeme nicht vorkonfiguriert sind.  Wenn Sie die Ports nicht konfigurieren, kann es zu einer Dienstunterbrechung kommen.

.Bevor Sie beginnen
Sie müssen die Werte der FC-Port-Einstellungen von node1 haben, die Sie in gespeichert haben link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"].

.Über diese Aufgabe
Sie können diesen Abschnitt überspringen, wenn Ihr System über keine FC-Konfigurationen verfügt. Wenn Ihr System über integrierte UTA/UTA2-Ports oder eine UTA/UTA2-Karte verfügt, konfigurieren Sie sie in <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.


IMPORTANT: Geben Sie die Befehle in diesem Abschnitt an der Cluster-Eingabeaufforderung ein.

.Schritte
. Zeigt Informationen zu allen FC- und konvergenten Netzwerkadaptern im System an.
+
`system node hardware unified-connect show`

. Vergleichen Sie die FC-Einstellungen von Knoten3 mit den Einstellungen, die Sie zuvor von Knoten1 erfasst haben.
. [[man_config_3_step3]]Führen Sie eine der folgenden Aktionen aus:
+
[cols="35,65"]
|===
| Wenn die FC-Standardeinstellungen auf den neuen Nodes sind... | Dann... 


| Das gleiche wie jene, die ihr auf Node1 gefangen habt | Gehe zu<<man_config_3_step9,Schritt 9>> . 


| Anders als jene, die du auf Node1 gefangen hast | Gehe zu<<man_config_3_step4,Schritt 4>> . 
|===
. [[man_config_3_step4]]Ändern Sie die FC-Ports auf Knoten3 nach Bedarf, indem Sie einen der folgenden Befehle eingeben:
+
** So programmieren Sie Zielanschlüsse:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** So programmieren Sie Initiator-Ports:
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` Ist der FC4-Typ: Target oder Initiator.



. Überprüfen Sie die neuen Einstellungen, indem Sie den folgenden Befehl eingeben und die Ausgabe prüfen:
+
`system node hardware unified-connect show`

. Beenden des Wartungsmodus:
+
`halt`

. Nachdem Sie den Befehl eingegeben haben, warten Sie, bis das System an der Eingabeaufforderung der Boot-Umgebung angehalten wird.
. Booten Sie Knoten3 an der Eingabeaufforderung der Boot-Umgebung:
+
`boot_ontap`

. [[man_config_3_step9]]Führen Sie eine der folgenden Aktionen aus:
+
** Wenn node3 eine UTA/UTA2-Karte oder Onboard-Ports zu UTA/UTA2 hat, gehen Sie zu <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>>.
** Wenn node3 keine UTA/UTA2-Karte oder Onboard-Ports UTA/UTA2 hat, überspringen <<UTA/UTA2-Ports in node3 prüfen und konfigurieren>> Und gehen Sie zu link:map_ports_node1_node3.html["Ports von node1 nach node3 zuordnen"].






== UTA/UTA2-Ports in node3 prüfen und konfigurieren

Wenn node3 Onboard UTA/UTA2-Ports oder eine UTA/UTA2-Karte hat, müssen Sie die Konfiguration der Ports überprüfen und sie möglicherweise neu konfigurieren, je nachdem, wie Sie das aktualisierte System verwenden möchten.

.Bevor Sie beginnen
Sie müssen die richtigen SFP+ Module für die UTA/UTA2-Ports besitzen.

.Über diese Aufgabe
Wenn Sie einen Unified Target Adapter (UTA/UTA2)-Port für FC verwenden möchten, müssen Sie zuerst überprüfen, wie der Port konfiguriert ist.


NOTE: Bei NetApp Marketingmaterialien wird möglicherweise der Begriff UTA2 verwendet, um sich auf CNA-Adapter und Ports zu beziehen. Allerdings verwendet die CLI den Begriff CNA.

Sie können das verwenden `ucadmin show` Befehl zum Überprüfen der aktuellen Portkonfiguration:

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
DIE UTA2-Ports können im nativen FC-Modus oder im UTA/UTA2-Modus konfiguriert werden. FC-Modus unterstützt FC Initiator und FC Target. Der UTA-/UTA2-Modus ermöglicht gleichzeitige NIC- und FCoE-Traffic über die gleiche 10-GbE-SFP+-Schnittstelle und unterstützt FC-Ziele.

UTA/UTA2-Ports befinden sich möglicherweise auf einem Adapter oder auf dem Controller und verfügen über die folgenden Konfigurationen. Sie sollten jedoch die Konfiguration der UTA/UTA2-Ports auf der node3 überprüfen und gegebenenfalls ändern:

* UTA-/UTA2-Karten, die bestellt werden, werden vor dem Versand konfiguriert, um die von Ihnen geforderte Persönlichkeit zu erhalten.
* DIE UTA2-Karten, die separat vom Controller bestellt werden, werden mit der standardmäßigen FC-Zielgruppe ausgeliefert.
* Onboard UTA/UTA2-Ports auf neuen Controllern werden vor dem Versand konfiguriert, um die Persönlichkeit zu erhalten, die Sie anfordern.
+

NOTE: Geben Sie die Befehle in diesem Abschnitt an der Cluster-Eingabeaufforderung ein, sofern Sie nicht aufgefordert werden, in den Wartungsmodus zu wechseln.



.Schritte
. Überprüfen Sie die aktuelle Portkonfiguration, indem Sie auf Knoten3 den folgenden Befehl eingeben:
+
`system node hardware unified-connect show`

+
Das System zeigt eine Ausgabe wie im folgenden Beispiel an:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
. [[Schritt2]]Wenn das aktuelle SFP+-Modul nicht mit der gewünschten Verwendung übereinstimmt, ersetzen Sie es durch das richtige SFP+-Modul.
+
Wenden Sie sich an Ihren NetApp Ansprechpartner, um das richtige SFP+ Modul zu erhalten.

. [[Schritt3]]Untersuchung der Ausgabe des `system node hardware unified-connect show` Oder `ucadmin show` Befehl zum Bestimmen, ob die UTA/UTA2-Ports die gewünschte Persönlichkeit haben.
. [[Schritt4]]Nehmen Sie eine der folgenden Aktionen:
+
[cols="35,65"]
|===
| Wenn die UTA/UTA2-Ports... | Dann... 


| Haben Sie nicht die Persönlichkeit, die Sie wollen | Gehen Sie zu <<man_check_3_step5,Schritt 5>>. 


| Haben Sie die Persönlichkeit, die Sie wollen | Überspringen Sie Schritt 5 bis Schritt 13 und gehen Sie zu<<man_check_3_step14,Schritt 14>> . 
|===
. [[man_check_3_step5]]Wenn das System über Speicherfestplatten verfügt und Clustered Data ONTAP 8.3 ausführt, booten Sie Knoten 3 und wechseln Sie in den Wartungsmodus:
+
`boot_ontap maint`

. Überprüfen Sie die Einstellungen:
+
`ucadmin show`

. Führen Sie eine der folgenden Aktionen durch:
+
[cols="35,65"]
|===
| Wenn Sie konfigurieren... | Dann... 


| Ports auf einer UTA/UTA2-Karte | Gehe zu<<man_check_3_step8,Schritt 8>> . 


| Onboard UTA/UTA2-Ports | Überspringen Sie Schritt 8 und gehen Sie zu<<man_check_3_step9,Schritt 9>> . 
|===
. [[man_check_3_step8]]Wenn sich der Adapter im Initiatormodus befindet und der UTA/UTA2-Port online ist, schalten Sie den UTA/UTA2-Port offline:
+
`storage disable adapter _adapter_name_`

+
Adapter im Ziel-Modus sind im Wartungsmodus automatisch offline.

. [[man_check_3_step9]]Wenn die aktuelle Konfiguration nicht der gewünschten Verwendung entspricht, ändern Sie die Konfiguration nach Bedarf:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` Ist der Persönlichkeitsmodus, `fc` Oder `cna`.
** `-t` Ist der Typ FC4, `target` Oder `initiator`.
+

NOTE: Sie müssen den FC-Initiator für Bandlaufwerke und MetroCluster -Konfigurationen verwenden.  Sie müssen das FC-Ziel für SAN-Clients verwenden.



. Anhalten des Systems:
+
`halt`

+
Das System wird an der Eingabeaufforderung für die Boot-Umgebung angehalten.

. Geben Sie den folgenden Befehl ein:
+
`boot_ontap`

. [[Schritt11]]Überprüfen Sie die Einstellungen:
+
`system node hardware unified-connect show`

+
Die Ausgabe in den folgenden Beispielen zeigt, dass sich der Adaptertyp „1b“ in ändert `initiator` Und dass sich der Modus der Adapter „2a“ und „2b“ in ändert `cna`:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
. [[step12a]]Setzen Sie alle Zielports online, indem Sie den folgenden Befehl einmal für jeden Port eingeben:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up`

. [[man_check_3_step14]]Verkabeln Sie den Port.

