---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/stage_6_index.html 
keywords: stage 6, complete, upgrade, set up, setup, controller, storage encryption, netapp encryption, decommission, resume snapmirror 
summary: Phase 6 Prozessreihenfolge für ein manuelles ARL Upgrade bei Controllern mit ONTAP 9.8 oder höher. 
---
= Phase-6-Übersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Phase 6 bestätigen Sie, dass die neuen Nodes ordnungsgemäß eingerichtet wurden. Bei aktivierter Verschlüsselung konfigurieren und einrichten Sie Storage Encryption bzw. NetApp Volume Encryption. Zudem sollten die alten Nodes außer Betrieb gesetzt und der SnapMirror Betrieb fortgesetzt werden.

. link:manage_authentication_kmip.html["Authentifizierungsmanagement mit KMIP-Servern"]
. link:ensure_controllers_set_up_correctly.html["Vergewissern Sie sich, dass die neuen Controller ordnungsgemäß eingerichtet sind"]
. link:set_up_storage_encryption_new_controller.html["Richten Sie Storage Encryption auf dem neuen Controller-Modul ein"]
. link:set_up_netapp_encryption_on_new_controller.html["Einrichtung von NetApp Volume oder Aggregate Encryption auf dem neuen Controller-Modul"]
. link:decommission_old_system.html["Ausmustern des alten Systems"]
. link:resume_snapmirror_ops.html["Setzen Sie den SnapMirror Betrieb fort"]

