---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/stage_3_index.html 
keywords: relocate, retire, node1, steps, stage 3 
summary: Phase 3 Prozessreihenfolge für ein manuelles ARL Upgrade bei Controllern mit ONTAP 9.8 oder höher. 
---
= Phase 3: Installieren und booten Sie node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Phase 3 installieren und booten Sie Knoten3, ordnen Sie die Cluster- und Node-Management-Ports von node1 zu node3 zu und verschieben Daten-LIFs und SAN-LIFs, die zu node1 gehören, von node2 auf node3. Außerdem werden alle Aggregate von node2 auf node3 verschoben und die Daten-LIFs und SAN-LIFs von node2 auf node3 verschoben.

.Schritte
. link:install_boot_node3.html["Installieren und booten Sie node3"]
. link:set_fc_uta_uta2_config_node3.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node3 fest"]
. link:map_ports_node1_node3.html["Ports von node1 nach node3 zuordnen"]
. link:move_nas_lifs_node1_from_node2_node3_verify_san_lifs_node3.html["Verschieben Sie die NAS-Daten-LIFs von node1 auf node2 und überprüfen Sie SAN LIFs auf node3"]
. link:relocate_non_root_aggr_node2_node3.html["Verschieben Sie Aggregate ohne Root-Root-Fehler von node2 auf node3"]
. link:move_nas_lifs_node2_node3.html["Verschieben Sie die NAS-Daten-LIFs von node2 auf node3"]

