---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/stage_1_index.html 
keywords: stage 1, prepare, upgrade, steps 
summary: Phase 1-Prozessreihenfolge für ein manuelles ARL Upgrade bei Controllern mit ONTAP 9.8 oder höher. 
---
= Überblick
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Phase 1 bestätigen Sie, dass interne Festplatten keine Root-Aggregate oder Datenaggregate enthalten, die Nodes für das Upgrade vorbereiten und mehrere Vorabprüfungen durchführen. Unter Umständen müssen Sie auch Festplatten für die Storage-Verschlüsselung rekeysen und die neuen Controller als Netzboot vorbereiten.

.Schritte
. link:determine_aggregates_on_internal_drives.html["Ermitteln Sie, ob der Controller über Aggregate auf internen Festplatten verfügt"]
. link:prepare_nodes_for_upgrade.html["Bereiten Sie die Knoten für ein Upgrade vor"]
. link:manage_authentication_okm.html["Verwaltung von Authentifizierungsschlüssel mit dem Onboard Key Manager"]
. link:quiesce_snapmirror_relationships.html["SnapMirror Beziehungen stilllegen"]
. link:prepare_for_netboot.html["Vorbereitungen für den Netzboot"]

