---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/stage_5_index.html 
keywords: stage 5, install, boot, node3, node4, relocate, aggregates 
summary: Phase 5 Prozessreihenfolge für ein manuelles ARL Upgrade bei Controllern mit ONTAP 9.8 oder höher. 
---
= Stage5. installieren und booten sie node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Phase 5 installieren und booten Sie node4 und ordnen den Cluster und Node-Management-Ports von node2 nach node4 zu. Außerdem verschieben Sie die Daten-LIFs und SAN-LIFs, die sich im Besitz von node2 befinden, von Knoten 3 auf node4 und verschieben die Aggregate von Knoten 2 von Knoten 3 auf node4.

.Schritte
. link:install_boot_node4.html["installieren und booten sie node4"]
. link:set_fc_uta_uta2_config_node4.html["Legen Sie die FC- oder UTA/UTA2-Konfiguration auf node4 fest"]
. link:map_ports_node2_node4.html["Weisen Sie Ports von node2 nach node4 zu"]
. link:move_nas_lifs_node2_from_node3_node4_verify_san_lifs_node4.html["Verschieben Sie die NAS-Daten-LIFs von node2 von node3 auf node4 und überprüfen Sie SAN LIFs auf node4"]
. link:relocate_node2_non_root_aggr_node3_node4.html["Verschiebung von nicht-Root-Aggregaten node2 von Node3 auf node4"]

