---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/stage_2_index.html 
keywords: relocate, retire, node1, steps, stage 2 
summary: Phase 2-Prozessreihenfolge für ein manuelles ARL Upgrade bei Controllern mit ONTAP 9.8 oder höher. 
---
= Phase-2-Übersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Während Phase 2 verschieben Sie Aggregate ohne Root-Root-Fehler von Knoten1 auf Knoten2 und verschieben Daten-LIFs, die nicht-SAN-Daten-LIFs gehören, die sich im Besitz von node1 befinden, auf Knoten 2, einschließlich fehlgeschlagener oder Vetos. Sie notieren auch die notwendigen Node1-Informationen, die Sie später im Verfahren verwenden können, und setzen dann node1 aus.

.Schritte
. link:relocate_non_root_aggr_node1_node2.html["Verlagerung von Aggregaten außerhalb der Root-Ebene und NAS-Daten-LIFs, die sich im Besitz von node1 auf node2 befinden"]
. link:move_nas_lifs_node1_node2.html["Das Verschieben von NAS-Daten-LIFs von node1 auf node2"]
. link:record_node1_information.html["Node1-Informationen werden aufgezeichnet"]
. link:retire_node1.html["Node1 ausmustern"]

